var myArr = 
[
    ["Abadi", "Fana, konkret"],
    ["Abolisi", "Pemberatan"],
    ["Absurd", "Masuk Akal"],
    ["Abstrak", "Konkret"],
    ["Acuh", "Tidak mau tahu"],

    ["Adik", "Kakak"],
    ["Adiluhung", "Hina"],
    ["Ahli", "Awam, Amatir"],
    ["Aktual", "Kedaluwarsa"],
    ["Akuisisi", "Pengeluaran"],
    ["Alam Fana", "Alam Kubur"],
    ["Amal", "Perbuatan"],
    ["Amar", "Larangan"],
    ["Amatir", "Kampiun, Ahli"],
    ["Anak", "Ibu"],
    ["Anggara", "Sengsara"],
    ["Angkara", "Gembira"],
    ["Anomali", "Normal"],
    ["Antagonis", "Protagonis"],
    ["Antipati", "Simpati"],
    ["Antonim", "Sinonim"],
    ["Apatis", "Antusiasme, acuh"],
    ["Apriori", "Aposteriori, menyelidiki"],
    ["Aristokrat", "Jelata"],
    ["Asli", "Duplikat"],
    ["Atrofi", "Pembesaran"],
    ["Autentik", "Palsu"],
    ["Awam", "Ahli, Pakar"],

    ["Badung", "Penurut"],
    ["Bahadun", "Pengecut"],
    ["Baka", "Fana"],
    ["Berdikari", "Bergantung"],
    ["Berhasil", "Gagal"],
    ["Berpihak", "Bertentangan"],
    ["Bersih", "Kotor"],
    ["Bersimbah", "Kering"],

    ["Besar", "Kecil"],
    ["Bongsor", "Kerdil"],
    ["Bulat", "Bola"],
    ["Bukit", "Lembah, ngarai"],

    ["Canggih", "Sederhana"],
    ["Cerewet", "Pendiam"],
    ["Chaos", "Normal"],
    ["Cucu", "Kakek"],
    ["Curam", "Landai"],
    ["Curang", "Sportif"],

    ["Daif", "Kuat"],
    ["Debit", "Kredit (pengeluaran)"],
    ["Deduksi", "Induksi"],
    ["Degenerasi", "Kemajuan"],
    ["Delusi (khayal)", "Nyata"],
    ["Demosi", "Promosi"],
    ["Dependen", "Independen, mandiri"],
    ["Deskriptif", "Fiktif"],
    ["Destruktif", "Konstruktif"],
    ["Deteriorasi", "Kemajuan"],
    ["Diam", "Mobilitas"],
    ["Dinamis", "Statis"],
    ["Diskrepansi", "Kecocokan"],

    ["Eklektik", "Tidak pilih-pilih"],
    ["Eksekutif", "Legislatif"],
    ["Eksentrik", "Internal"],
    ["Eksplisit", "Implisit"],

    ["Ekspresi", "Impresi"],
    ["Elastis", "Kaku"],
    ["Elusif", "Mudah dipahami"],
    ["Enmity", "Amity"],
    ["Emigrasi", "Imigrasi"],
    ["Empati", "Tidak peduli"],
    ["Epilog", "Prolog"],
    ["Eternal", "Fana"],
    
    ["Fakir", "Berada"],
    ["Fana", "Abadi"],
    ["Fiksi", "Realita"],
    ["Fisik", "Mental"],
    ["Fonem", "Morfem"],

    ["Gagal", "Berhasil"],
    ["Galib", "Khusus"],
    ["Gasal (ganjil)", "Genap"],
    ["Gawat", "Tenteram"],
    ["Gegai", "Kuat,kokoh"],
    ["Gelap", "Terang"],
    ["Generik", "Khusus"],
    ["Gentar", "Berani"],
    ["Gembira", "Gelisah"],
    ["Gersang", "Subur"],
    ["Gulita", "Benderang"],

    ["Hadir", "Absen"],
    ["Hampa", "Berisi"],
    ["Heterogen", "Homogen"],
    ["Hidup", "Mati"],
    ["Higienis", "Kotor"],
    ["Hina", "Mulia"],

    ["Hirau", "Lalai"],
    ["Homogen", "Heterogen"],
    ["Horizontal", "Vertikal"],
    
    ["Ibu", "Anak"],
    ["Imigrasi", "Emigrasi"],
    ["Independen", "Dependen"],
    ["Induksi", "Deduksi"],
    ["Inferior", "Superior"],
    ["Inflasi", "Deflasi"],
    ["Inklusif", "Kecuali"],
    ["Input (Masukan)", "Ouput (Keluaran)"],
    ["Insidental", "Rutin"],
    ["Insinuasi", "Terang-terangan"],
    ["Internal", "Eksternal"],
    ["Intro", "Penutup"],
    ["Isolator (Penghambat)", "Konduktor (penghantar)"],

    ["Jaga", "Tidur"],
    ["Jahat", "Baik"],
    ["Jauh", "Dekat"],
    ["Jawab", "Tanya"],

    ["Kaku", "Elastis"],
    ["Kaleidoskop", "Seragam"],
    ["Kapabel", "Bodoh"],
    ["Kebal", "Lemah"],
    ["Kebijakan", "Kecerobohan"],

    ["Kedaluwarsa", "Aktual"],
    ["Kendala", "Pendukung"],

    ["Kerdil", "Bongsor"],
    ["Kesempatan", "Hambatan"],
    ["Khas", "Umum"],
    ["Kohesi", "Adhesi"],
    ["Kolektif", "Personal"],
    ["Konduktor", "Isolator"],
    ["Konkaf", "Konveks"],
    ["Konklusi", "Uraian"],
    ["Konklusif", "Proposisi"],
    ["Konkret", "Abstrak"],
    ["Konservasi", "Eksploitasi"],
    ["Konsonan", "Vokal"],
    ["Konstruktif", "Destruktif"],
    ["Konsumen", "Penghasil"],
    ["Kontinu", "Terputus-putus"],
    ["Konveks", "Konkaf"],
    ["Konvergen", "Bercabang"],
    ["Krusial", "Sepele"],

    ["Laba", "Rugi"],
    ["Labil", "Tetap"],
    ["Lancung", "Asli"],
    ["Landai", "Curam"],
    ["Laten", "Tampak"],
    ["Legal", "Ilegal"],
    ["Legislatif", "Eksekutif"],
    ["Longgar", "Tegas"],

    ["Makar", "Jujur"],
    
    ["Mandiri", "Bergantung"],
    ["Maya", "Nyata"],
    ["Mayor", "Minor"],
    ["Mobilitas", "Diam"],
    ["Modern", "Tradisional"],
    ["Monoton", "Berubah-ubah"],
    ["Muda", "Tua"],
    ["Muskil", "Mungkin"],

    ["Nahas", "Untung"],
    ["Negasi", "Konfirmasi"],
    ["Netral", "Berpihak"],
    ["Nisbi", "Mutlak"],
    ["Niskala", "Berwujud"],
    ["Nomaden, nomadik", "Menetap"],
    ["Normal", "Anomali, abnormal"],
    ["Nyalang", "Terpejam"],

    ["Objektif", "Subjektif"],
    ["Obsolet", "Baru"],
    ["Ofensif", "Defensif"],
    ["Oponen", "Kawan"],
    ["Optimis", "Pesimis"],
    ["Ortodoks", "Modern"],
    ["Otokrasi", "Demokrasi"],
    ["Output", "Input"],
    
    ["Pancarona", "Sewarna"],
    
    ["Pandir", "Pintar"],
    ["Panjang", "Pendek"],
    ["Pasti", "Spekulasi"],
    ["Pejal", "Berongga"],
    ["Penting", "Remeh"],
    ["Pertemuan", "Perpisahan"],
    ["Pewaris", "Perintis"],
    ["Plural", "Tunggal"],
    ["Poligami", "Monogami"],
    ["Pra", "Pasca"],
    ["Praktis", "Teoritis"],
    ["Prefiks", "Sufiks"],
    ["Presensi", "Absen, mangkir"],
    ["Progresif", "Regresif"],
    ["Proletar", "Regresif"],
    ["Prolog", "Epilog"],
    ["Prominem", "Biasa"],
    ["Proposisi", "Reaksi"],
    ["Protagonis", "Antagonis"],
    ["Putus", "Sambung"],

    ["Quasi", "Nyata"],

    ["Rabun", "Jelas"],
    ["Rawan", "Aman"],
    ["Remisi", "Penambahan"],
    ["Retro", "Progress"],
    ["Revolusi", "Evolusi"],
    ["Rongga", "Rapat"],
    ["Sederhana", "Canggih"],
    ["Sekarang", "Esok"],
    ["Sekuler", "Keagamaan"],
    ["Semacam", "Beraneka"],
    ["Senang", "Merana"],
    ["Separasi", "Penyatuan"],
    ["Simpati", "Antipati"],
    ["Sinkron", "Sumbang"],
    ["Skeptis", "Yakin"],
    ["Sporadis", "Sering"],
    ["Sportif", "Curang"],
    ["Stabil", "Labil"],
    ["Stagnan", "Berubah"],
    ["Sumbang", "Benar, selaras, sesuai"],
    ["Surai", "Berhimpun"],

    ["Takeoff", "Landing"],
    ["Takzim", "Acuh"],
    ["Tanya", "Jawab"],
    ["Teks", "Konteks"],
    ["Tentatif", "Pasti"],
    ["Terbit", "Tenggelam"],
    ["Terkatung", "Terbenam"],
    ["Tertib", "Kacau"],
    ["Tesis", "Antitesis"],
    ["Tetiran", "Asli"],
    ["Tinggi", "Rendah"],
    ["Tua", "Muda"],

    ["Ultima", "Awal"],
    ["Umum", "Khusus, Khas"],
    ["Universal", "Parsial"],
    ["Utopis", "Nyata"],

    ["Vademekum", "Kamus besar"],
    ["Verbal", "Tulisan"],
    ["Virulen", "Baik"],
    ["Vokal", "Konsonan"],
    ["Waruga", "Jiwa"],
    ["Wreda", "Muda"],
]