var myArr = 
[
    ["Abadi", "Fana, konkret"],
    ["Abolisi", "Pemberatan"],
    ["Absurd", "Masuk Akal"],
    ["Abstrak", "Konkret"],
    ["Acuh", "Tidak mau tahu"],

    ["Adik", "Kakak"],
    ["Adiluhung", "Hina"],
    ["Ahli", "Awam, Amatir"],
    ["Aktual", "Kedaluwarsa"],
    ["Akuisisi", "Pengeluaran"],
    ["Alam Fana", "Alam Kubur"],
    ["Amal", "Perbuatan"],
    ["Amar", "Larangan"],
    ["Amatir", "Kampiun, Ahli"],
    ["Anak", "Ibu"],
    ["Anggara", "Sengsara"],
    ["Angkara", "Gembira"],
    ["Anomali", "Normal"],
    ["Antagonis", "Protagonis"],
    ["Antipati", "Simpati"],
    ["Antonim", "Sinonim"],
    ["Apatis", "Antusiasme, acuh"],
    ["Apriori", "Aposteriori, menyelidiki"],
    ["Aristokrat", "Jelata"],
    ["Asli", "Duplikat"],
    ["Atrofi", "Pembesaran"],
    ["Autentik", "Palsu"],
    ["Awam", "Ahli, Pakar"],

    ["Badung", "Penurut"],
    ["Bahadun", "Pengecut"],
    ["Baka", "Fana"],
    ["Berdikari", "Bergantung"],
    ["Berhasil", "Gagal"],
    ["Berpihak", "Bertentangan"],
    ["Bersih", "Kotor"],
    ["Bersimbah", "Kering"],

    ["Besar", "Kecil"],
    ["Bongsor", "Kerdil"],
    ["Bulat", "Bola"],
    ["Bukit", "Lembah, ngarai"],

    ["Canggih", "Sederhana"],
    ["Cerewet", "Pendiam"],
    ["Chaos", "Normal"],
    ["Cucu", "Kakek"],
    ["Curam", "Landai"],
    ["Curang", "Sportif"],

    ["Daif", "Kuat"],
    ["Debit", "Kredit (pengeluaran)"],
    ["Deduksi", "Induksi"],
    ["Degenerasi", "Kemajuan"],
    ["Delusi (khayal)", "Nyata"],
    ["Demosi", "Promosi"],
    ["Dependen", "Independen, mandiri"],
    ["Deskriptif", "Fiktif"],
    ["Destruktif", "Konstruktif"],
    ["Deteriorasi", "Kemajuan"],
    ["Diam", "Mobilitas"],
    ["Dinamis", "Statis"],
    ["Diskrepansi", "Kecocokan"],

    ["Eklektik", "Tidak pilih-pilih"],
    ["Eksekutif", "Legislatif"],
    ["Eksentrik", "Internal"],
    ["Eksplisit", "Implisit"],

    ["Ekspresi", "Impresi"],
    ["Elastis", "Kaku"],
    ["Elusif", "Mudah dipahami"],
    ["Enmity", "Amity"],
    ["Emigrasi", "Imigrasi"],
    ["Empati", "Tidak peduli"],
    ["Epilog", "Prolog"],
    ["Eternal", "Fana"],
    
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],

    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],

    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],

    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],

    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],

    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
    ["", ""],
]