var myArr = [
    ["Abolisi", "Penghapusan"],
    ["Abonemen", "Berlangganan"],
    ["Abrasi", "Kikis, pengikisan"],
    ["Absah","Sah"],
    ["Absen","Bolos"],
    ["Absolut","Mutlak"],
    ["Absorpsi","Penyerapan"],
    ["Acuan","Rujukan"],
    ["Adagium","Pepatah, peribahasa"],
    ["Adaptasi","Penyesuaian"],

    ["Adiktif","Bersifat Candu"],
    ["Ad Interim","Sementara"],
    ["Afeksi","Kasih Sayang"],
    ["Afinitas","Empati"],
    ["Afirmasi","Penegasan, peneguhan"],
    ["Agitasi","Persuasi, ajakan"],
    ["Agraria","Pertahanan"],
    ["Agresi","Serangan, penyerangan"],
    ["Agunan","Jaminan"],
    ["Ajun","Ajudan, asisten"],
    ["Akreditasi","Pengakuan"],
    ["Akselerasi","Percepatan"],
    ["Akseptor","Penerima"],
    ["Aktual","Nyata, anyar"],
    ["Akurasi","Ketelitian"],
    ["Akurat","Benar, jitu, seksama"],
    ["Alegori","Kias"],
    ["Algoritma","Prosedur"],
    ["Aliansi","Afiliasi, asosiasi"],
    ["Alternatif","Cara lain"],
    ["Amatir","Pemula"],
    ["Ambigu","Enigmatis, enigma"],
    ["Ambiguitas","Makna ganda, ketidakjelasan"],
    ["Ambisi","Keinginan"],
    ["Analogi","Perbandingan"],
    ["Andal","Kredibel"],
    ["Anemia","Kurand Darah"],
    ["Anggaran","Catatan"],
    ["Angkara","Kejahatan"],
    ["Anjung","Panggung"],
    ["Anomali","Tidak Normal, menyimpang"],
    ["Anonim","Tanpa nama"],
    ["Anulir","Abolisi, penghapusan, pembatalan"],
    ["Apatis","Dingin, acuh tak acuh, masa bodoh"],
    ["Api","Bara"],
    ["Aporisma","Maksimal"],
    ["Arbitrer","Acak"],
    ["Aristokrasi","Feodal"],
    ["Aristokrat","Bangsawan, Ningrat"],
    ["Arketipe","Model"],
    ["Arogan","Congkak"],
    ["Artifisial","Buatan"],
    ["Asa","Harapan"],
    ["Autentik","Asli, sah, tulen, orisinil"],

    ["Bab","Perkara"],
    ["Bagak","Pemberani, berani, bangga"],
    ["Bahana","Gema, Dengung"],
    ["Baku","Standar, pokok, utama"],
    ["Bala","Bencana"],
    ["Bara","Api"],
    ["Benchmark","Patokan, tolok ukur"],
    ["Bergeming","Diam"],
    
    ["Bibliografi","Daftar pustaka"],
    ["Biduk","Bahtera"],
    ["Blangko","Abstain"],
    ["Boga","Makanan nikmat"],
    ["Bonafide","Dapat dipercaya"],
    ["Bonanza","Sumber kesenangan, kebahagiaan, kemakmuran"],
    ["Bonus","Hadiah"],
    ["Botani","Nabati"],
    ["Bramacorah","Residivis"],
    ["Bubut","Cabut"],
    ["Bulat","Bola"],

    ["Cagar","Panjar"],
    ["Candu","Adiktif"],
    ["Canggih","Kompleks"],
    ["Celepuk","Burung hantu"],
    ["Centeng","Penjaga, bodyguard"],
    ["Ciri","Karakteristik"],
    ["Citra","Gambaran"],
    ["Class","Tingkatan"],
    ["Collapse","Bangkrut"],
    ["Congkak","Sombong, arogan"],

    ["Daur","Siklus"],
    ["Dedikasi","Pengabdian"],
    ["Deduksi","Konklusi"],
    ["Defacto","secara nyata, menurut kenyataan"],
    ["Defleksi","Penyimpangan"],
    ["Defisit","kekurangan"],
    ["Degradasi","Kemerosotan, reduksi"],

    ["Dehidrasi","Kehilangan cairan tubuh, penyusutan air"],
    ["Dekade","Dasawarsa, sepuluh tahun"],
    ["Dekadensi","Kemerosotan (moral, akhlak)"],
    ["Dekrit","Keputusan"],
    ["Delik","Tindak pidana, pelanggran hukum"],
    ["Delusi","Khayal, khayalan, ilusi"],
    ["Delusif","Fiktif, palsu"],
    ["Densitas","Kepadatan penduduk"],
    ["Dependen","Tergantung"],
    ["Depedensi","Ketergantungan"],
    ["Deportasi","Pengusiran"],
    ["Depresi","Stagnasi"],
    ["Deputi","Wakil"],
    ["Derivasi","Afiksasi"],
    ["Desalinasi","Penyulingan"],
    ["Deksripsi","Pemaparan"],
    ["Deskriptif","Gambaran"],
    ["Destruktif","Subversif"],
    ["Detensi","Penahanan"],
    ["Detente","Rekonsiliasi"],
    ["Dikotomi","Dua kekuatan, dibagi dua"],
    ["Dinamis","Bergerak (terus)"],
    ["Dispensasi","Pengecualian"],
    ["Distorsi","Penyimpangan"],
    ["Divestasi","Pelepasan"],

    ["Doktrin","Ajaran, dogma"],
    ["Donasi","Bantuan"],
    ["Duplikat","Replika"],
    ["Durjana","Jahat"],

    ["Efisien","Efektif"],
    ["Egaliter","Sama, sederajat"],
    ["Egois","Individualis"],
    ["Ekamatra","Fisika"],
    ["Eklips","Gerhana"],
    ["Eksekusi","Pelaksanaan, hukuman"],
    ["Eksemplar","Lembar"],
    ["Eksentrik","Aneh"],
    ["Eksepsi","Pengecualian"],
    ["Ekskavasi","Penggalian"],
    ["Eksodus","Hijrah, mengungsi, pindah"],
    ["Ekspansi","Perluasan"],
    ["Ekspedisi","Pengiriman"],
    ["Eksploitasi","Pemanfaatan"],
    ["Eksplorasi","Pendalaman, penggalian, pengkajian"],
    ["Ekpresi","Ungkapan, roman muka"],
    ["Ekstensi","Perluasan"],
    ["Ekstra","Bonus, tambahan"],
    ["Ekuator","Khatulistiwa"],
    ["Ekuilibrium","Keseimbangan, setimbang, sepadan"],
    ["Ekuivalen","Sama, sedarajat, sebanding"],
    ["Elaborasi","Penjelasan, terperinci"],
    ["Elusif","Canggih, kompleks, misterius"],
    ["Embargo","Inhibisi, larangan"],
    ["Embarkasi","Keberangkatan"],
    ["Endemi","Wabah, pagebluk"],
    ["Enigmatis","Ambigu"],
    ["Entitas","Materi, zat"],
    ["Enumerasi","Pencacahan, perhitungan"],
    ["Epilog","Penutup"],
    ["Epidemi","Wabah"],
    ["Era","Zaman, masa"],
    ["Esensi","Hakikat"],
    ["Eskalasi","Peningkatan"],
    ["Estetis","Elok, indah"],
    ["Estimasi","Pediksi, anggapan"],
    ["Estuari","Muara, hilir"],
    ["Etika","Akhlak"],
    ["Etnis","Kesukuan, rasial"],
    ["Eufemisme","Penghalusan (bahasa)"],
    ["Evakuasi","Pemindahan"],
    ["Evaluasi","Penilaian"],
    ["Evaporasi","Penguapan"],
    ["Evokasi","Provokasi, sugesti, penggugah rasa"],
    ["Evolusi","Perubahan"],

    ["Faksi","Golongan, kelompok"],
    ["Faktor","Penyebab, unsur"],
    ["Faktual","Konkret, objektif"],
    ["Fakulatif","Tidak wajib"],
    ["Fana","Sementara"],
    ["Fatamorgana","Halusinasi"],
    ["Fantastis","Luar biasa"],
    ["Fauna","Dunia hewan"],
    ["Fenomena","Gejala"],
    ["Feodal","Aristokrasi"],
    ["Fermentasi","Pembusukan"],
    ["Fertil","Subur"],
    ["Fertilitas","Kesuburan"],
    ["Fiksi","Khayalan, delusi"],
    ["Fiktif","Palsu, delusif"],
    ["Fiskal","Perpajakan"],
    ["Fiegmatis","Serba lamban"],
    ["Flora","Dunia tumbuhan"],
    ["Fluktuatif","Labil"],
    ["Friksi","Perselisihan,perpecahan, bentrokan, desakan"],
    ["Frontal","Depan"],
    ["Fungi","Cendawan, jamur"],
    ["Fusi","Penggabungan, gabungan"],
    ["Futuristis","Menuju masa depan"],

    ["Gaji","honor"],
    ["Galat","Keliru, eror"],
    ["Galib","Umum"],
    ["Gambaran","Deskriptif, imajinasi"],
    ["Gasal","Ganjil"],
    ["Gema","Bahana, dengung"],
    ["Generik","Umum, lazim"],
    ["Genjah","Cepat, berbuah"],
    ["Glosarium","Kamus singkat/ringkas"],
    ["Grasi","Pengampunan"],

    ["Harmoni","Proporsi, simetri"],
    ["Hayati","Hidup"],
    ["Heksagonal","Segi enam"],
    ["Herbivora","Pemakan tumbuhan"],
    ["Hibrida","Bibit Unggul"],
    ["Hibridasi","Penyilangan"],
    ["Hijrah","Mengungsi, eksodus"],
    ["Hipokrit","Munafik"],
    ["Hipotenusa","Sisi miring"],
    ["Hipotesis","Dugaan awal, anggapan dasar"],
    ["Hukuman","Denda"],
    ["Homogen","Sejenis"],

    ["Identitas","Ciri-ciri"],
    ["Ideologi","Pemikiran"],
    ["Ikebana","Seni merangkai bunga"],
    ["Ikhtiar","Usaha"],
    ["Ikhtisar","Sinopsis, ringkasan"],
    ["Ilusi","Khayalan"],
    ["Imajinasi","Gambaran"],
    ["Imbas","Efek, dampak"],

    ["Imitasi","Sintesis, tiruan"],
    ["Implikasi","Keterkaitan"],
    ["Implisit","Tersirat"],
    ["Impuls","Dorongan"],
    ["Imun","Kebal"],
    ["Individualis","Egois"],
    ["Indraloka","Surga"],
    ["Inferensi","Deduksi, konklusi, kesimpulan, simpulan"],
    ["Infiks","Sisipan"],
    ["Informal","Santai"],
    ["Inhibisi","Larangan, embargo"],
    ["Inisiasi","Pembaiatan"],
    ["Injeksi","Suntik, suntikan"],
    ["Inklusif","Global, termasuk, terhitung"],
    ["Inovasi","Kebaruan, penemuan"],
    ["Insentif","Bonus"],
    ["Inses","Sedarah"],
    ["Insedental","Tertentu, sewaktu-waktu"],
    ["Insinuasi","Sindiran"],
    ["Insomnia","Sulit / tidak bisa tidur"],
    ["Inspeksi","Peninjauan"],
    ["Inpirasi","Gagasan, ide, ilham"],
    ["Instruksi","Aba-aba, perintah, komando"],
    ["Integrasi","Pembauran"],
    ["Intelektual","Cendekiawan"],

    ["Interogasi","Pemeriksaan"],
    ["Interupsi","Penyelaan, pemotongan"],
    ["Interval","Sela"],
    ["Intervensi","Campur tangan"],
    ["Intimidasi","Menakut-nakuti"],
    ["Intuisi","Naluri, insting"],
    ["Iterasi","Perulangan"],
    ["Izin","Wenang"],

    ["Jati diri","Bukti diri"],
    ["Jurnal","Buletin, bacaan"],

    ["Kaidah","Ajaran"],
    ["Kaldera","Kawah"],
    ["Kalkulasi","Perhitungan"],
    ["Kampiun","Juara"],
    ["Kapital","Modal"],
    ["Kapitalisasi","Invetasi"],
    ["Karakteristik","Ciri"],
    ["Karnivora","Pemakan Daging"],
    ["Kartel","Badan Usaha Besar"],
    ["Kawan","Mitra"],
    ["Kedap","Rapat"],
    ["Kelas","Tingkatan"],
    ["Kelenger","Pingsan"],
    ["Kisi-kisi","Terali"],
    ["Kitab","Buku"],
    ["Klan","Suku"],
    ["Klasifikasi","Pengelompokan"],
    ["Kleptofobia","Takut kecurian"],
    ["Klimaks","Puncak"],
    ["Kognisi","Pemahaman"],

    ["Koleteral","Paralel"],
    ["Kolega","Rekan"],
    ["Koloni","Jajahan"],
    ["Kolusi","Kongkalikong"],
    ["Komoditas","Produk"],
    ["Kompleksitas","Kerumitan"],
    ["Komplemen","Pelengkap"],
    ["Komposit","Campuran, gabungan"],
    ["Komprehensif","Luas, lengkap"],
    ["Kondusif","Aman"],
    ["Konfrontasi","Pertikaian"],
    ["Konjungsi","Penghubung"],
    ["Konkaf","Cekung"],
    ["Konklusi","Kesimpulan, deduksi"],
    ["Konkret","Nyata, faktual, objektif"],
    ["Konsesi","Kelonggaran"],
    ["Konstan","Kontinu"],
    ["Konstitusi","Undang-undang"],
    ["Kontemporer","Mutakhir, pada masa kini"],
    ["Kontras","Perbedaan nyata"],
    ["Kontribusi","Bantuan, Jasa"],
    ["Konveks","Cembung"],
    ["Konvensi","Kesepakatan"],
    ["Konvensional","Konservatif, kolot"],
    ["Konvergen","Memusat"],
    ["Koordinator","Manajer"],
    ["Korelasi","Hubungan"],
    ["Kredibel","Andal"],
    ["Kronologi","Urutan Peristiwa"],
    ["Krusial","Penting"],

    ["Kulminasi","Tingkatan yang tertinggi"],
    ["Kuota","Jatah"],

    ["Laba","Untung, profit"],
    ["Labil","Fluktuatif"],
    ["Laten","Tersembunyi"],
    ["Laik","Layak, pantas"],
    ["Laten","Tersembunyi"],
    ["Latif","Indah"],
    ["Legalitas","Keabsahan"],
    ["Leksikon","Kamus, kosakata"],
    ["Loka","Tempat, dunia"],

    ["Majemuk","Plural, heterogen"],
    ["Makar","Akal bulus, tipu muslihat"],
    ["Manuskrip","Dokumen, naskah"],
    ["Masa","Waktu"],
    ["Massif","Padat, pejal"],
    ["Materialistis","Kebendaan"],
    ["Mawas diri","Introspeksi diri"],
    ["Mayapada","Bumi, dunia"],
    ["Memangkas","Memotong"],
    ["Membal","Berbalik"],
    ["Membran","Selaput"],
    ["Metodis","Teratur"],
    ["Militan","Agresif"],
    ["Mistifikasi","Pengecohan"],
    ["Mitra","Kawan"],
    ["Mobilitas","Gerak"],
    ["Moderat","Lunak, konservatif, rasional"],

    ["Monarki","Kerajaan"],
    ["Morbiditas","Angka penduduk yang sakit dan sehat"],
    ["Mortalitas","Angka Kematian"],
    ["Mukjizat","Karamah"],
    ["Mutakhir","Modern, terbaru"],
    ["Mutilasi","Pemotongan"],
    ["Mutlak","Absolut"],

    ["Nabati","Botani"],
    ["Naluri","Insting, Intuisi"],
    ["Nahar","Bingung"],
    ["Narasi","Deskripsi"],
    ["Naratif","Deskriptif"],
    ["Natalitas","Angka kelahiran"],
    ["Navigasi","Pelayaran, penerbangan"],
    ["Negosiasi","Perundingan"],
    ["Nisbi","Relatif"],
    ["Nomaden","Berpindah-pindah"],
    ["Nomenklatur","Tata nama"],
    ["Notulen","Catatan, risalah"],
    ["Nuansa","Perbedaan makna"],

    ["Objektif","Ilmiah"],
    ["Oktagon","Segi delapan"],
    ["Omnivora","Pemakan segala (tumbuhan dan daging)"],
    ["Origami","Seni melipat kertas"],
    ["Orisinil","Asli, autentik"],
    ["Otodidak","Belajar sendiri"],

    ["Otoritas","Dominasi"],
    ["Out of date","Kadaluwarsa"],

    ["Pagu","Plafon"],
    ["Pandir","Bodoh, dungu, bebal"],
    ["Panorama","Pemandangan"],
    ["Paradigma","Model, pola, kerangka berpikir"],
    ["Paradoks","Bertentangan"],
    ["Paradoksal","Kontras"],
    ["Paralel","Sejajar"],
    ["Parameter","Standar Ukuran"],
    ["Paripurna","Sempurna, lengkap"],
    ["Partikelir","Swasta"],
    ["Pasca","Sesudah"],
    ["Patologi","Ilmu tentang penyakit"],
    ["Pedagogi","Pengajaran, pendidikan"],
    ["Pejal","Padat"],
    ["Pentagon","Segi Lima"],
    ["Parlente","Gagah"],
    ["Permisif","Liberal, terbuka"],
    ["Persuasi","Agitasi, ajakan"],
    ["Petisi","Gugatan"],
    ["Pionir","Pelopor, perintis"],
    ["Polemik","Kontroversi"],
    ["Porto","Biaya"],
    ["Pra","Sebelum"],
    ["Prefiks","Awalan"],
    ["Premi","Uang hadiah"],
    ["Preposisi","Kata depan"],

    ["Presensi","Keberadaan"],
    ["Preventif","Defensif"],
    ["Primer","Utama, pokok"],
    ["Profit","Keuntungan"],
    ["Prohibisi","Larangan"],
    ["Proletar","Rakyat Jelata"],
    ["Prolog","Pembuka"],
    ["Prominem","Terkenal, terkemuka"],
    ["Promosi","Pemasaran"],
    ["Promovendus","Calon doktor"],
    ["Propaganda","Ajakan, kampanye"],
    ["Proporsi","Nisbah, perbandingan"],
    ["Proteksi","Perlindungan"],
    ["Provokasi","Gangguan, sugesti, evokasi, pancingan"],
    ["Prudensial","Bijaksana"],

    ["Rabat","Potongan Harga, diskon"],
    ["Rancu","Kacau"],
    ["Random","Acak"],
    ["Reboisasi","Penghijauan"],
    ["Referensi","Rujukan"],
    ["Refleksi","Pencerminan / pemantulan"],
    ["Registrasi","Pendaftaran"],
    ["Rehabilitasi","Perbaikan"],
    ["Reklamasi","Penimbunan"],
    ["Rekonsiliasi","Perdamaian"],
    ["Relatif","Nisbi"],

    ["Remisi","Pengampunan, pengurangan hukuman"],
    ["Rendezvous","Pertemuan"],
    ["Replika","Duplikat, tiruan"],
    ["Reportase","Peliputan, pemberitaan"],
    ["Resesi","stagnasi, masa sulit"],
    ["Residu","Sisa"],
    ["Resistan","Kuat, tangguh"],
    ["Restriksi","Pembatasan"],
    ["Revolusi","Perubahan"],
    ["Rigid","Kaku"],
    ["Ringkih","Rapu"],

    ["Sais","Kusir"],
    ["Seksama","Cermat"],
    ["Sangkur","Bayonet"],
    ["Sedimentasi","Pengendapan"],
    ["Sekte","Aliran, mazhab"],
    ["Selebrasi","Perayaan"],
    ["Semenjana","Sedang"],
    ["Serebrum","Otak besar"],
    ["Seremoni","Upacara"],
    ["Siklus","Daur"],
    ["Sine qua non","Harus ada"],
    ["Singular","Tunggal"],
    ["Sinopsis","Ikhtisar, Intisari"],
    ["Sintesis","Imitasi, buatan"],
    ["Sinyalemen","Petunjuk"],
    ["Skeptis","Ragu-ragu"],
    ["Spesifik","Istimewa"],
    ["Spiritual","Kerohanian, psikis"],

    ["Sporadis","Kadang-kadang, jarang"],
    ["Depresi","macet"],
    ["Statis","Diam"],
    ["Stigma","Ciri negatif"],
    ["Suar","Nyala api"],
    ["Substansi","Intisari"],
    ["Subversif","Destruktif"],
    ["Sufiks","Akhiran"],
    ["Suksesi","Pergantian, pemimpin"],
    ["Sumbang","Tidak selaras"],
    ["Supervisi","Pengawasan"],
    ["Supremasi","Kekuasaan tertinggi"],
    ["Swasembada","Mandiri, independen, otonom"],
    ["Swatantra","Otonomi"],

    ["Tag","Label"],
    ["Tanggalkan","Lepaskan"],
    ["Tangkal","Cegah"],
    ["Tangsi","Barak"],
    ["Tanur","Perapian"],
    ["Tautologi","Repetisi"],
    ["Tendensi","Cenderung, kecenderungan"],
    ["Tentatif","Belum pasti"],
    ["Tera","Stempel"],
    ["Terali","Kisi-kisi"],
    ["Teritori","Zona"],
    ["Termaktub","Tercatat"],
    ["Tolan","Sahabat"],
    
    ["Transedental","Abstrak, sulit dipahami"],
    ["Transisi","Peralihan"],
    ["Tunaaksara","Buta huruf"],
    ["Tunadaksa","Cacat tubuh"],
    ["Tunagrahita","Cacat mental / pikiran"],
    ["Tunanetra","Buta"],
    ["Tunarungu","Tuli"],
    ["Tunasusila","Pelacur"],
    ["Tunawicara","Bisu"],
    ["Tunawisma","Gelandangan"],
    ["Tuslah","Tambah"],

    ["Ugahari","Sedang, pertengahan, sederhana"],
    ["Up to date","Baru"],
    ["Utopis","Bersifat khayal"],

    ["Vademekum","Kamus kecil"],
    ["Vakansi","Liburan"],
    ["Validitas","Kebenaran"],
    ["Vandalisme","Destruksi, perusakan"],
    ["Vegetasi","Tumbuh-tumbuhan"],
    ["Versus","Lawan"],
    ["Virtual","Impian"],
    ["Virulen","Jahat, busuk, keji"],
    ["Visual","Optis"],
    ["Vital","Esensial, fundamental"],

    ["Volunter","Sukarelawan"],

    ["Warisan","Harta benda"],
    ["Warkat","Surat"],
    ["Wenang","Izin"],

    ["Yurisdiksi","Kekuasaan"],
    ["Zenit","Puncah, titik puncak"],
];