// var id_post = PostList[i][0];
// var url_post = url_root + PostList[i][1];
// var name_post = PostList[i][2];
// var date_post = PostList[i][3];
// var description_post = PostList[i][4];
// var post_category = PostList[i][5];
// var post_preview_src = PostList[i][6];

var footerArray = [
  //June2020
  [
    "Jan21_Jwb_01",
    "/excel/001-cara-menjumlah-di-excel",
    "Cara Melakukan Penjumlahan di Microsoft Excel ?",
    "",
    "Cara menjumlahkan nilai di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_02",
    "/excel/002-cara-mengurang-di-excel",
    "Cara Melakukan Pengurangan di Microsoft Excel ?",
    "",
    "Cara melakukan pengurangan di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_03",
    "/excel/003-cara-perkalian-di-excel",
    "Cara Melakukan Perkalian di Microsoft Excel ?",
    "",
    "Cara melakukan perkalian di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_04",
    "/excel/004-cara-pembagian-di-excel",
    "Cara Melakukan Pembagian di Microsoft Excel ?",
    "",
    "Cara melakukan pembagian di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_05",
    "/excel/005-cara-membuat-operasi-modulo-di-excel",
    "Cara Melakukan Modulo di Microsoft Excel ?",
    "",
    "Cara melakukan operasi modulo di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_06",
    "/excel/006-cara-membuat-penjumlahan-total-di-excel",
    "Cara Membuat Penjumlahan Total (SUM) di Microsoft Excel ?",
    "",
    "Cara melakukan penjumlahan total (SUM) di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_07",
    "/excel/007-cara-membuat-rumus-di-excel",
    "Cara Membuat Rumus di Microsoft Excel ?",
    "",
    "Cara Membuat Rumus di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_08",
    "/excel/008-cara-membuat-rumus-rata-rata-di-excel",
    "Cara Membuat Rumus Rata-Rata di Microsoft Excel ?",
    "",
    "Cara Membuat Rumus rata-rata di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_09",
    "/excel/009-cara-membuat-tabel-di-excel",
    "Cara Membuat Tabel di Microsoft Excel ?",
    "",
    "Cara Membuat Tabel di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_10",
    "/excel/010-cara-membuat-grafik-di-excel",
    "Cara Membuat Grafik di Microsoft Excel ?",
    "",
    "Cara Membuat Grafik di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_11",
    "/excel/011-cara-mengakses-data-di-sheet-lain-di-excel",
    "Cara Mengakses Data dari Sheet Lain di Microsoft Excel ?",
    "",
    "Cara Mengakses data sheet lain di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_12",
    "/excel/012-cara-mengubah-nilai-desimal-menjadi-bentuk-persen-di-excel",
    "Cara Mengubah Nilai Desimal menjadi bentuk Persen di Microsoft Excel ?",
    "",
    "Cara mengubah nilai desimal menjadi bentuk persen di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_13",
    "/excel/013-cara-mengatur-jumlah-angka-dibelakang-koma-di-excel",
    "Cara Mengatur Jumlah Angka Dibelakang Koma di Microsoft Excel ?",
    "",
    "Cara mengatur jumlah angka dibelakang koma di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_14",
    "/excel/014-cara-menentukan-nilai-minimum-di-excel",
    "Cara Menentukan Nilai Minimum di Microsoft Excel ?",
    "",
    "Cara menetukan nilai minimum dari sejumlah angka di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_15",
    "/excel/015-cara-menentukan-nilai-maksimum-di-excel",
    "Cara Menentukan Nilai Maksimum di Microsoft Excel ?",
    "",
    "Cara menetukan nilai maksimum dari sejumlah angka di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_16",
    "/excel/016-cara-membuat-nilai-absolut-di-excel",
    "Cara Membuat Nilai Absolut di Microsoft Excel ?",
    "",
    "Cara membuat nilai absolut di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_17",
    "/excel/017-cara-membangkitkan-nilai-random-0-hingga-1-di-excel",
    "Cara Membangkitkan Nilai Random 0-1 di Microsoft Excel ?",
    "",
    "Cara membangkitkan nilai random 0 hingga 1 di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_18",
    "/excel/018-cara-membangkitkan-nilai-random-bilangan-bulat-di-excel",
    "Cara Membangkitkan Nilai Random Bilangan Bulat di Microsoft Excel ?",
    "",
    "Cara membangkitkan nilai random bilangan bulat di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_19",
    "/excel/019-cara-menjumlah-nilai-tanpa-tulis-rumus-di-excel",
    "Cara Menjumlah Nilai Tanpa Tulis Rumus di Microsoft Excel ?",
    "",
    "Cara menjumlah nilai tanpa tulis rumus di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_20",
    "/excel/020-cara-menghitung-rata-rata-nilai-tanpa-tulis-rumus-di-excel",
    "Cara Menghitung Rata-Rata Nilai Tanpa Tulis Rumus di Microsoft Excel ?",
    "",
    "Cara menghitung rata-rata nilai tanpa tulis rumus di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_21",
    "/excel/021-cara-menghitung-banyaknya-jumlah-data-yang-dipilih-di-excel",
    "Cara Menghitung Banyaknya Jumlah Data yang Dipilih di Microsoft Excel ?",
    "",
    "Cara menghitung banyaknya jumlah data yang dipilih di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_22",
    "/excel/022-cara-menentukan-nilai-maksimum-tanpa-tulis-rumus-di-excel",
    "Cara Menentukan Nilai Maksimum Tanpa Tulis Rumus di Microsoft Excel ?",
    "",
    "Cara menentukan nilai maksimum tanpa harus menulis rumus di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_23",
    "/excel/023-cara-menentukan-nilai-minimum-tanpa-tulis-rumus-di-excel",
    "Cara Menentukan Nilai Minimum Tanpa Tulis Rumus di Microsoft Excel ?",
    "",
    "Cara menentukan nilai minimum tanpa harus menulis rumus di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_24",
    "/excel/024-cara-membuat-nilai-berpangkat-di-excel",
    "Cara Membuat Nilai Berpangkat di Microsoft Excel ?",
    "",
    "Cara membuat nilai berpangkat di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_25",
    "/excel/025-cara-mencari-akar-pangkat-dua-di-excel",
    "Cara Mencari Akar Pangkat Dua di Microsoft Excel ?",
    "",
    "Cara mencari akar pangkat dua di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_26",
    "/excel/026-cara-membuat-sel-absolut-di-excel",
    "Cara Membuat Sel Abslout di Microsoft Excel ?",
    "",
    "Cara membuat sel absolut di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_27",
    "/excel/027-cara-membuat-fungsi-if-di-excel",
    "Cara Membuat Fungsi IF di Microsoft Excel ?",
    "",
    "Cara membuat fungsi IF di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_28",
    "/excel/028-cara-membuat-fungsi-and-di-excel",
    "Cara Membuat Fungsi AND di Microsoft Excel ?",
    "",
    "Cara membuat fungsi AND di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_29",
    "/excel/029-cara-membuat-fungsi-or-di-excel",
    "Cara Membuat Fungsi OR di Microsoft Excel ?",
    "",
    "Cara membuat fungsi OR di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_30",
    "/excel/030-cara-membuat-sel-pada-excel-berubah-warna-berdasarkan-isinya",
    "Cara Membuat Sel pada Microsoft Excel Berubah Warna Berdasarkan Isinya ?",
    "",
    "Cara membuat sel pada Excel berubah warna berdasarkan isinya",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_31",
    "/excel/031-cara-mengubah-nilai-bentuk-persen-menjadi-bentuk-desimal-di-excel",
    "Cara Mengubah Nilai Bentuk Persen menjadi Bentuk Desimal di Microsoft Excel ?",
    "",
    "Cara mengubah nilai ke persen ke desimal di Excel",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_32",
    "/excel/032-cara-membuat-pembulatan-di-excel",
    "Cara Membuat Pembulatan di Microsoft Excel ?",
    "",
    "Cara membuat pembulatan di Excel. Baik berupa pembulatan menjadi bilangan bulat, atau menjadi beberapa angka dibelakang koma",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_33",
    "/excel/033-cara-mencari-akar-pangkat-berapapun-di-excel",
    "Cara Mencari Akar Pangkat Berapapun di Microsoft Excel ?",
    "",
    "Cara mencari akar pangkat berapapun di excel. Anda bisa mencari akar pangkat 2, 3, 4, 5 dan berapapun dari sebuah nilai",
    ["Excel"],
    "",
  ],
  [
    "Jan21_Jwb_34",
    "/excel/034-wrap-text-di-excel",
    "Cara Membuat Baris Baru pada Sebuah Sel di Microsoft Excel ?",
    "",
    "Pada saat membuat baris baru pada text editor misalnya Microsoft Word, biasanya ditekan ENTER. Tapi, pada saat anda tekan ENTER di Excel, anda malah berpindah ke baris berikutnya. Lalu bagaimana cara melakukannya di Excel ?",
    ["Excel"],
    "",
  ],
  
];
