// var id_post = PostList[i][0];
// var url_post = url_root + PostList[i][1];
// var name_post = PostList[i][2];
// var date_post = PostList[i][3];
// var description_post = PostList[i][4];
// var post_category = PostList[i][5];
// var post_preview_src = PostList[i][6];
var class_category_calc = [
  ["Pangkat", "/pangkat", ""],
  ["Waktu", "/waktu", ""],
  ["Suhu", "/suhu", ""],
  ["Pecahan", "/pecahan", ""],
];
var url_root = "https://nasrianas.website/jawab/math";
var footerArray = [
  //June2020
  [
    "Math_001",
    "/waktu/001-300-detik-berapa-menit",
    "300 Detik Berapa Menit ?",
    "",
    "300 detik berapa menit",
    ["Waktu"],
    "",
  ],
  [
    "Math_002",
    "/pangkat/002-akar-mines-1-berapa",
    "Akar -1 Berapa ?",
    "",
    "Akar mines 1 berapa",
    ["Pangkat"],
    "",
  ],
  [
    "Math_003",
    "/pangkat/003-mines-1-pangkat-4",
    "-1 pangkat 4 ?",
    "",
    "mines 1 pangkat 4",
    ["Pangkat"],
    "",
  ],
  [
    "Math_004",
    "/waktu/004-500-detik-berapa-menit",
    "500 Detik Berapa Menit ?",
    "",
    "500 detik berapa menit",
    ["Waktu"],
    "",
  ],
  [
    "Math_005",
    "/suhu/005-30-derajat-celcius-berapa-fahrenheit",
    "30 Derajat Celcius Berapa Fahrenheit ?",
    "",
    "30 derajat celcius berapa fahrenheit",
    ["Suhu"],
    "",
  ],
  [
    "Math_006",
    "/suhu/006-30-derajat-celcius-berapa-reamur",
    "30 Derajat Celcius Berapa Reamur ?",
    "",
    "30 derajat celcius berapa Reamur",
    ["Suhu"],
    "",
  ],
  [
    "Math_007",
    "/waktu/007-300-menit-berapa-jam",
    "300 Menit Berapa Jam ?",
    "",
    "300 menit berapa jam",
    ["Waktu"],
    "",
  ],
  [
    "Math_008",
    "/pangkat/008-2-pangkat-9",
    "2 Pangkat 9?",
    "",
    "2 pangkat 9",
    ["Pangkat"],
    "",
  ],
  [
    "Math_009",
    "/suhu/009-30-derajat-celcius-berapa-kelvin",
    "30 Derajat Celcius Berapa Kelvin ?",
    "",
    "30 derajat celcius berapa Kelvin",
    ["Suhu"],
    "",
  ],
  [
    "Math_010",
    "/suhu/010-300-kelvin-berapa-celcius",
    "300 Kelvin Berapa Celcius ?",
    "",
    "300 kelvin berapa celcius",
    ["Suhu"],
    "",
  ],
  [
    "Math_011",
    "/waktu/011-300-detik-berapa-jam",
    "300 Detik Berapa Jam",
    "",
    "300 detik berapa jam",
    ["Waktu"],
    "",
  ],
  [
    "Math_012",
    "/pangkat/012-mines-1-pangkat-5",
    "-1 pangkat 5 ?",
    "",
    "mines 1 pangkat 5",
    ["Pangkat"],
    "",
  ],
  [
    "Math_013",
    "/pecahan/013-0,75-diubah-menjadi-pecahan-biasa",
    "0.75 Diubah Menjadi Pecahan Biasa",
    "",
    "0.75 diubah menjadi pecahan biasa",
    ["Pecahan"],
    "",
  ],
  [
    "Math_014",
    "/pangkat/014-3-pangkat-4",
    "3 pangkat 4 ?",
    "",
    "3 pangkat 4",
    ["Pangkat"],
    "",
  ],
  [
    "Math_015",
    "/waktu/015-300-jam-berapa-hari",
    "300 Jam Berapa Hari",
    "",
    "300 jam berapa hari",
    ["Waktu"],
    "",
  ],
  [
    "Math_016",
    "/pangkat/016-akar-pangkat-3-dari-3375",
    "Akar Pangkat 3 dari 3375 ?",
    "",
    "akar pangkat 3 dari 3375",
    ["Pangkat"],
    "",
  ],
  [
    "Math_017",
    "/pangkat/017-akar-pangkat-3-dari-1728",
    "Akar Pangkat 3 dari 1728 ?",
    "",
    "akar pangkat 3 dari 1728",
    ["Pangkat"],
    "",
  ],
  [
    "Math_018",
    "/pangkat/018-akar-pangkat-3-dari-729",
    "Akar Pangkat 3 dari 729 ?",
    "",
    "akar pangkat 3 dari 729",
    ["Pangkat"],
    "",
  ],
  [
    "Math_019",
    "/pangkat/019-akar-pangkat-3-dari-1331",
    "Akar Pangkat 3 dari 1331 ?",
    "",
    "akar pangkat 3 dari 1331",
    ["Pangkat"],
    "",
  ],
  [
    "Math_020",
    "/pangkat/020-akar-pangkat-3-dari-4096",
    "Akar Pangkat 3 dari 4096 ?",
    "",
    "akar pangkat 3 dari 4096",
    ["Pangkat"],
    "",
  ],
  [
    "Math_021",
    "/pangkat/021-akar-pangkat-3-dari-343",
    "Akar Pangkat 3 dari 343 ?",
    "",
    "akar pangkat 3 dari 343",
    ["Pangkat"],
    "",
  ],
  [
    "Math_022",
    "/pangkat/022-akar-pangkat-3-dari-9261",
    "Akar Pangkat 3 dari 9261 ?",
    "",
    "akar pangkat 3 dari 9261",
    ["Pangkat"],
    "",
  ],
  [
    "Math_023",
    "/pangkat/023-akar-pangkat-3-dari-2744",
    "Akar Pangkat 3 dari 2744 ?",
    "",
    "akar pangkat 3 dari 2744",
    ["Pangkat"],
    "",
  ],

  [
    "Math_024",
    "/pangkat/024-akar-pangkat-3-dari-27",
    "Akar Pangkat 3 dari 27 ?",
    "",
    "akar pangkat 3 dari 27",
    ["Pangkat"],
    "",
  ],
  [
    "Math_025",
    "/pangkat/025-akar-pangkat-3-dari-17576",
    "Akar Pangkat 3 dari 17576 ?",
    "",
    "akar pangkat 3 dari 17576",
    ["Pangkat"],
    "",
  ],
  [
    "Math_026",
    "/pangkat/026-akar-pangkat-3-dari-512",
    "Akar Pangkat 3 dari 512 ?",
    "",
    "akar pangkat 3 dari 512",
    ["Pangkat"],
    "",
  ],
  [
    "Math_027",
    "/pangkat/027-akar-pangkat-3-dari-125",
    "Akar Pangkat 3 dari 125 ?",
    "",
    "akar pangkat 3 dari 125",
    ["Pangkat"],
    "",
  ],
  [
    "Math_028",
    "/pangkat/028-akar-pangkat-3-dari-4913",
    "Akar Pangkat 3 dari 4913 ?",
    "",
    "akar pangkat 3 dari 4913",
    ["Pangkat"],
    "",
  ],
  
];
