var class_category = [
  ["HTML & CSS", "/html-css", "teal"],
  ["Javascript", "/javascript", "orange"],
];

var Post_List = [
  [
    "Coding2020_01",
    "/html-css/opacity",
    "Apa itu Opacity pada CSS",
    "Feb 8, 2020",
    "Pecahan adalah bentuk lain dari bilangan desimal. misalnya 1/4 adalah bentuk lain dari 0.25. Operasi tambah dan kurang pecahan berbeda dengan kali dan bagi. Operasi tambah dan kurang pecahan membutuhkan sedikit perhatian untuk diselesaikan. Berikut ini beberapa cara yang bisa anda gunakan dalam menjumlahkan dan mengurangkan pecahan.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_02",
    "/html-css/Membuat-Animasi",
    "Membuat Animasi dengan CSS",
    "Feb 12, 2020",
    "Bagaimana cara membuat animasi dengan hanya menggunakan HTML dan CSS. Membuat Animasi dengan rule keyframes pada CSS dengan mengatur tingkat kecerahan atau tingkat transparan objek atau element HTML.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_03",
    "/html-css/Membuat-Animasi-part2",
    "Membuat Animasi dengan CSS bg. 2",
    "Feb 16, 2020",
    "Bagaimana cara mengubah posisi atau penempatan objek dengan animasi pada HTML dan CSS. Pembuatan animasi dengan menggunakan rule keyframes pada CSS untuk mengatur posisi objek atau element HTML. Bagaimana cara menerapkan animasi yang telah dibuat pada objek atau element HTML. Bagaimana cara membuat Animasi Fade In dengan menerapkan opacity dan posisi objek pada CSS",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_04",
    "/html-css/animation-timing-function",
    "Apa itu Animation Timing Function",
    "Feb 20, 2020",
    "Membuat animasi dengan HTML dan CSS dengan mempertimbangkan animation timing function. Penerapan animation timing function pada beberapa objek dan melihat perbedaan dari animation timing function tersebut. ",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_05",
    "/javascript/cara-membangkitkan-nilai-random-dengan-javascript",
    "Cara Membangkitkan Nilai Random dengan Javascript",
    "Oct 15, 2020",
    "",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_06",
    "/javascript/cara-membangkitkan-nilai-random-bilangan-bulat-dengan-javascript",
    "Cara Membangkitkan Nilai Random Bilangan Bulat dengan Javascript",
    "Oct 17, 2020",
    "",
    ["Javascript"],
    "",
  ],
]