var class_category = [
  ["HTML & CSS", "/html-css", "teal"],
  ["Javascript", "/javascript", "grey"],
  ["Structured Text", "/structured-text", "grey"],
];
var url_root = "https://nasrianas.website/coding";
var footerArray = [
  [
    "CodingST21_01",
    "/ST/001-percabangan-if-pada-structured-text",
    "Percabangan IF pada Structured Text",
    "Feb 26, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_02",
    "/ST/002-perbandingan-pada-structured-text",
    "Perbandingan pada Structured Text",
    "Feb 26, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_03",
    "/ST/003-perbandingan-untuk-tipe-data-boolean-pada-structured-text",
    "Perbandingan untuk Tipe Data Boolean pada Structured Text",
    "Feb 26, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_04",
    "/ST/004-operator-logika-pada-structured-text",
    "Operator Logika pada Structured Text",
    "Feb 26, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_05",
    "/ST/005-assignment-pada-structured-text",
    "Assignment pada Structured Text",
    "Feb 26, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_06",
    "/ST/006-perulangan-for-pada-structured-text",
    "Perulangan FOR pada Structured Text",
    "Feb 27, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_07",
    "/ST/007-contoh-program-timer-dengan-structured-text-pada-rslogix5000",
    "Contoh Program Timer dengan Structured Text pada RSLOGIX 5000",
    "Mar 4, 2021",
    "",
    ["Structured Text"],
    "",
  ], 
  [
    "CodingST21_08",
    "/ST/008-contoh-program-one-shoot-dengan-structured-text-pada-rslogix5000",
    "Contoh Program One Shoot dengan Structured Text pada RSLOGIX 5000",
    "Mar 6, 2021",
    "",
    ["Structured Text"],
    "",
  ],

]