var class_category = [
  ["HTML & CSS", "/html-css", "teal"],
  ["Javascript", "/javascript", "grey"],
  ["Structured Text", "/structured-text", "grey"],
];

var footerArray = [
  [
    "Coding2020_05",
    "/javascript/005-cara-membangkitkan-nilai-random-dengan-javascript",
    "Cara Membangkitkan Nilai Random dengan Javascript",
    "Oct 15, 2020",
    "Bilangan acak dan bahasa pemrograman adalah hal yang tidak mungkin terpisahkan. Setiap bahasa pemrograman memiliki caranya sendiri dalam membuat nilai random. Berikut ini bagaimana cara membangkitkan nilai random dengan javascript",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_06",
    "/javascript/006-cara-membangkitkan-nilai-random-bilangan-bulat-dengan-javascript",
    "Cara Membangkitkan Nilai Random Bilangan Bulat dengan Javascript",
    "Oct 17, 2020",
    "Pembulatan pada javascript dapat dilakukan dengan beberapa cara tergantung pada jenis pembulatan yang digunakan. Math.floor() adalah jenis pembulatan kebawah, atau menjadi bilangan bulat yang tepat berada di bawah bilangan asal pembulatan. Misalnya ketika anda membulatkan 14.56 dengan Math.floor() maka hasil yang akan anda peroleh adalah 14.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_07",
    "/javascript/007-cara-membuat-pembulatan-biasa-dengan-javascript",
    "Cara Membuat Pembulatan Biasa dengan Javascript",
    "Oct 19, 2020",
    "Metode Pembulatan adalah metode matematika yang mana menggeser nilai suatu bilangan ke bilangan bulat tertentu. Salah satu jenis pembulatan adalah pembulatan biasa atau pembulatan ke nilai terdekat. Pembulatan ini menggeser bilangan ke bilangan bulat terdekat. Misalnya 1.2 digeser menjadi 1, atau 3.6 digeser menjadi 4.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_08",
    "/javascript/008-cara-membuat-pembulatan-ke-bawah-dengan-javascript",
    "Cara Membuat Pembulatan ke Bawah dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa, pembulatan ke bawah juga bisa dilakukan di javascript. Pembulatan ke bawah adalah pembulatan dimana menggeser nilai suatu bilangan menjadi bilangan bulat dibawah nilai tersebut. Pembulatan ke bawah juga bisa dijelaskan dengan menghilangkan nilai desimal pada bilangan sehingga hanya menyisakan bilangan bulatnya saja",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_09",
    "/javascript/009-cara-membuat-pembulatan-ke-atas-dengan-javascript",
    "Cara Membuat Pembulatan ke Atas dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa dan pembulatan kebawah seperti yang sudah di bahas sebelumnya. Pembulatan ke atas juga bisa dilakukan dengan javascript. Pembulatan ke atas adalah pembulatan dimana nilai desimal dibulatkan menjadi 1 atau menjadi bilangan bulat berikutnya. Misalnya 4.3 menjadi 5, atau 4.8 menjadi 5.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_10",
    "/javascript/010-cara-memperoleh-waktu-setempat-dengan-javascript",
    "Cara Memperoleh Waktu Setempat dengan Javascript",
    "Oct 19, 2020",
    "Saat anda membuat program terkadang anda membutuhkan waktu setempat/lokal pengguna. Waktu lokal bisa berarti kapan pengguna membuka aplikasi tersebut. Mungkin anda membutuhkan informasi jam, menit atau detik, atau bahkan nama hari.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_11",
    "/javascript/011-cara-menampilkan-property-dari-object-di-javascript",
    "Cara Menampilkan Property dari Object di Javascript",
    "Oct 21, 2020",
    "Menampilkan method dan property mungkin tidak begitu diperlukan. Tapi untuk sekadar memahami isi dari object pada javascript, berikut cara yang bisa anda lakukan.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_12",
    "/javascript/012-cara-memperoleh-nilai-absolut-dari-suatu-nilai-dengan-javascript",
    "Cara Memperoleh Nilai Absolut dari Suatu Nilai dengan javascript",
    "Oct 21, 2020",
    "Metode absolute adalah metode yang digunakan untuk membuat nilai negatif menjadi positif dan membuat nilai positif tetap positif. Salah satu contoh penerapannya adalah perhitungan selisih dari dua nilai.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_13",
    "/javascript/013-cara-memperoleh-nilai-hasil-pangkat-dengan-javascript",
    "Cara Memperoleh Nilai Hasil Pangkat dengan Javasript",
    "Oct 21, 2020",
    "Metode pangkat adalah metode yang digunakan untuk mengalikan sebuah nilai yang sama beberapa nilai. Misalnya 3x3x3x3 sama dengan 3 pangkat 4, dimana angka 3 dikalikan sebanyak 4 kali. Berikut ini cara membuat perhitungan pangkat pada javascript.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_14",
    "/javascript/014-hubungan-radian-dan-derajat-pada-trigonometri",
    "Hubungan Radian dan Derajat pada Trigonometri",
    "Oct 25, 2020",
    "Pada saat kita menggunakan fungsi sinus trigonometri untuk 90 derajat, maka nilai yang kita harap akan muncul adalah 1. Hasilnya akan berbeda jika kita menggunakan fungsi sinus di javascript, jika penulisannya seperti dibawah ini.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_15",
    "/javascript/015-bagaimana-cara-membuat-fungsi-sinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Sinus Trigonometri pada javascript",
    "Oct 25, 2020",
    "Fungsi sinus adalah salah satu fungsi trigonometri yang sering digunakan. Fungsi sinus pada javascript dapat dituliskan sebagai berikut.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_16",
    "/javascript/016-bagaimana-cara-membuat-fungsi-cosinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Cosinus Trigonometri pada javascript",
    "Oct 25, 2020",
    "Selain fungsi sinus, fungsi trigonometri lain yang sering digunakan adalah fungsi cosinus. Berikut ini cara penulisan fungsi cosinus pada javascript.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_17",
    "/javascript/017-bagaimana-cara-membuat-fungsi-tangen-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Tangen Trigonometri pada javascript",
    "Oct 25, 2020",
    "Selain fungsi sinus dan cosinus, salah satu fungsi trigonometri yang juga cukup populer adalah fungsi tangen. Berikut ini contoh penulisan fungsi tangen pada javascript. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_18",
    "/javascript/018-bagaimana-cara-mencari-nilai-minimum-pada-javascript",
    "Bagaimana Cara Mencari Nilai Minimum pada Javascript",
    "Oct 31, 2020",
    "Nilai minimum adalah satu nilai paling rendah dari serangkaian nilai yang diberikan. Misalnya jika diberikan serangkaian nilai dari 30, 45, 33, 21, 20 maka nilai paling rendah adalah 20. ",
    ["Javascript"],
    "",
  ],  
  [
    "Coding2020_19",
    "/javascript/019-bagaimana-cara-mencari-nilai-maksimum-pada-javascript",
    "Bagaimana Cara Mencari Nilai Maksimum pada Javascript",
    "Oct 31, 2020",
    "Nilai maksimum adalah satu nilai paling tinggi dari serangkaian atau sekumpulan nilai yang diberikan. Misalnya jika diberikan serangkaian nilai dari 30, 45, 33, 21, 20 maka nilai paling tinggi adalah 45. ",
    ["Javascript"],
    "",
  ],  
  [
    "Coding2020_20",
    "/javascript/020-bagaimana-cara-membuat-fungsi-invers-sinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Sinus Trigonometri pada javascript",
    "Oct 31, 2020",
    "Arcsin atau Asin merupakan fungsi kebalikan dari fungsi trigonometri sinus atau biasa juga disebut sebagai invers sinus. Sinus digunakan untuk mencari nilai tertentu dengan derajat, sementara arcsin atau asin digunakan untuk mencari derajat dengan nilai tertentu",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_21",
    "/javascript/021-bagaimana-cara-membuat-fungsi-invers-cosinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Cosinus Trigonometri pada javascript",
    "Nov 1, 2020",
    "Selain fungsi invers sinus, fungsi cosinus juga memiliki fungsi invers di javascript. Fungsi tersebut adalah Arccos atau Acos. Fungsi invers cosinus digunakan untuk mencari besar sudut berdasarkan pada sebuah nilai. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_22",
    "/javascript/022-bagaimana-cara-membuat-fungsi-invers-tangen-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Tangen Trigonometri pada javascript",
    "Nov 1, 2020",
    "Selain fungsi invers sinus dan fungsi invers cosinus, fungsi tangen juga memiliki fungsi invers di javascript. Fungsi tersebut adalah Arctan atau Atan. Fungsi invers tangen digunakan untuk mencari besar sudut berdasarkan pada sebuah nilai.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_23",
    "/javascript/023-bagaimana-cara-menghubungkan-html-dan-javascript",
    "Bagaimana Cara Menghubungkan HTML dan javascript",
    "Nov 2, 2020",
    "Selain fungsi invers sinus dan fungsi invers cosinus, fungsi tangen juga memiliki fungsi invers di javascript. Fungsi tersebut adalah Arctan atau Atan. Fungsi invers tangen digunakan untuk mencari besar sudut berdasarkan pada sebuah nilai.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_24",
    "/javascript/024-bagaimana-cara-membuat-fungsi-secan-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Secan Trigonometri pada javascript",
    "Nov 2, 2020",
    "Selain 3 fungsi trigonometri yang cukup populer yaitu sinus, kosinus dan tangen, terdapat 3 fungsi trigonometri lain yang biasa digunakan. Salah satu diantaranya adalah fungsi trigonometri secan. Sayangnya, tidak terdapat fungsi yang langsung dapat digunakan pada javascript. Dan Untungnya, fungsi ini masih memiliki kaitan dengan 3 fungsi populer trigonometri. Berikut penjelasannya. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_25",
    "/javascript/025-bagaimana-cara-membuat-fungsi-cosecan-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Cosecan Trigonometri pada javascript",
    "Nov 4, 2020",
    "Selain 3 fungsi trigonometri yang cukup populer yaitu sinus, kosinus dan tangen, terdapat 3 fungsi trigonometri lain yang biasa digunakan. Salah satu diantara fungsi tersebut adalah fungsi cosecan. Sayangnya fungsi ini tidak memiliki fungsi langsung pada javascript. Meskipun demikian masih memiliki kaitan dengan 3 fungsi populer trigonometri.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_26",
    "/javascript/026-bagaimana-cara-membuat-fungsi-cotangen-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Cotangen Trigonometri pada javascript",
    "Nov 4, 2020",
    "Sama halnya dengan fungsi trigonometri secan dan cosecan, fungsi trigonometri cotangen juga tidak tersedia di javascript. Berita baiknya adalah, fungsi trigonometri cotangen masih ada hubungannya dengan salah satu fungsi populer trigonometri yaitu fungsi trigonometri tangen yang mana fungsi tersebut bisa dibuat langsung dengan javascript. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_27",
    "/javascript/027-bagaimana-cara-membuat-fungsi-invers-cosecan-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Cosecan Trigonometri pada javascript",
    "Nov 5, 2020",
    "Karena fungsi trigonometri cosecan tidak tersedia di javascript, yang mana harus dibuat sendiri, begitu pula dengan fungsi inversnya. Maka dari itu, yang harus kita lakukan adalah menggunakan fungsi invers dari fungsi trigonometri yang sudah ada. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_28",
    "/javascript/028-bagaimana-cara-membuat-fungsi-invers-secan-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Secan Trigonometri pada javascript",
    "Nov 5, 2020",
    "Karena fungsi trigonometri Secan tidak tersedia di javascript, yang mana harus dibuat sendiri, begitu pula dengan fungsi inversnya seperti halnya fungsi cosecan dan cotangen. Maka dari itu, yang harus kita lakukan adalah menggunakan fungsi invers dari fungsi trigonometri yang sudah ada. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_29",
    "/javascript/029-bagaimana-cara-membuat-fungsi-invers-cotangen-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Invers Cotangen Trigonometri pada javascript",
    "Nov 5, 2020",
    "Karena fungsi trigonometri Cotangen tidak tersedia di javascript, yang mana harus dibuat sendiri, begitu pula dengan fungsi inversnya seperti halnya fungsi cosecan dan cotangen. Maka dari itu, yang harus kita lakukan adalah menggunakan fungsi invers dari fungsi trigonometri yang sudah ada. ",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_30",
    "/javascript/030-cara-membuat-dan-mengakses-array-pada-javascript",
    "Tutorial Javascript: Cara Membuat dan Mengakses Array",
    "Feb 28, 2021",
    "",
    ["Javascript"],
    "",
  ],

]