var class_category = [
  ["HTML & CSS", "/html-css", "teal"],
  ["Javascript", "/javascript", "orange"],
];

var Post_List = [
  [
    "Coding2020_01",
    "/html-css/opacity",
    "Apa itu Opacity pada CSS",
    "Feb 8, 2020",
    "Pecahan adalah bentuk lain dari bilangan desimal. misalnya 1/4 adalah bentuk lain dari 0.25. Operasi tambah dan kurang pecahan berbeda dengan kali dan bagi. Operasi tambah dan kurang pecahan membutuhkan sedikit perhatian untuk diselesaikan. Berikut ini beberapa cara yang bisa anda gunakan dalam menjumlahkan dan mengurangkan pecahan.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_02",
    "/html-css/Membuat-Animasi",
    "Membuat Animasi dengan CSS",
    "Feb 12, 2020",
    "Bagaimana cara membuat animasi dengan hanya menggunakan HTML dan CSS. Membuat Animasi dengan rule keyframes pada CSS dengan mengatur tingkat kecerahan atau tingkat transparan objek atau element HTML.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_03",
    "/html-css/Membuat-Animasi-part2",
    "Membuat Animasi dengan CSS bg. 2",
    "Feb 16, 2020",
    "Bagaimana cara mengubah posisi atau penempatan objek dengan animasi pada HTML dan CSS. Pembuatan animasi dengan menggunakan rule keyframes pada CSS untuk mengatur posisi objek atau element HTML. Bagaimana cara menerapkan animasi yang telah dibuat pada objek atau element HTML. Bagaimana cara membuat Animasi Fade In dengan menerapkan opacity dan posisi objek pada CSS",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_04",
    "/html-css/animation-timing-function",
    "Apa itu Animation Timing Function",
    "Feb 20, 2020",
    "Membuat animasi dengan HTML dan CSS dengan mempertimbangkan animation timing function. Penerapan animation timing function pada beberapa objek dan melihat perbedaan dari animation timing function tersebut. ",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_05",
    "/javascript/005-cara-membangkitkan-nilai-random-dengan-javascript",
    "Cara Membangkitkan Nilai Random dengan Javascript",
    "Oct 15, 2020",
    "Bilangan acak dan bahasa pemrograman adalah hal yang tidak mungkin terpisahkan. Setiap bahasa pemrograman memiliki caranya sendiri dalam membuat nilai random. Berikut ini bagaimana cara membangkitkan nilai random dengan javascript",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_06",
    "/javascript/006-cara-membangkitkan-nilai-random-bilangan-bulat-dengan-javascript",
    "Cara Membangkitkan Nilai Random Bilangan Bulat dengan Javascript",
    "Oct 17, 2020",
    "Pembulatan pada javascript dapat dilakukan dengan beberapa cara tergantung pada jenis pembulatan yang digunakan. Math.floor() adalah jenis pembulatan kebawah, atau menjadi bilangan bulat yang tepat berada di bawah bilangan asal pembulatan. Misalnya ketika anda membulatkan 14.56 dengan Math.floor() maka hasil yang akan anda peroleh adalah 14.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_07",
    "/javascript/007-cara-membuat-pembulatan-biasa-dengan-javascript",
    "Cara Membuat Pembulatan Biasa dengan Javascript",
    "Oct 19, 2020",
    "Metode Pembulatan adalah metode matematika yang mana menggeser nilai suatu bilangan ke bilangan bulat tertentu. Salah satu jenis pembulatan adalah pembulatan biasa atau pembulatan ke nilai terdekat. Pembulatan ini menggeser bilangan ke bilangan bulat terdekat. Misalnya 1.2 digeser menjadi 1, atau 3.6 digeser menjadi 4.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_08",
    "/javascript/008-cara-membuat-pembulatan-ke-bawah-dengan-javascript",
    "Cara Membuat Pembulatan ke Bawah dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa, pembulatan ke bawah juga bisa dilakukan di javascript. Pembulatan ke bawah adalah pembulatan dimana menggeser nilai suatu bilangan menjadi bilangan bulat dibawah nilai tersebut. Pembulatan ke bawah juga bisa dijelaskan dengan menghilangkan nilai desimal pada bilangan sehingga hanya menyisakan bilangan bulatnya saja",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_09",
    "/javascript/009-cara-membuat-pembulatan-ke-atas-dengan-javascript",
    "Cara Membuat Pembulatan ke Atas dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa dan pembulatan kebawah seperti yang sudah di bahas sebelumnya. Pembulatan ke atas juga bisa dilakukan dengan javascript. Pembulatan ke atas adalah pembulatan dimana nilai desimal dibulatkan menjadi 1 atau menjadi bilangan bulat berikutnya. Misalnya 4.3 menjadi 5, atau 4.8 menjadi 5.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_10",
    "/javascript/010-cara-memperoleh-waktu-setempat-dengan-javascript",
    "Cara Memperoleh Waktu Setempat dengan Javascript",
    "Oct 19, 2020",
    "Saat anda membuat program terkadang anda membutuhkan waktu setempat/lokal pengguna. Waktu lokal bisa berarti kapan pengguna membuka aplikasi tersebut. Mungkin anda membutuhkan informasi jam, menit atau detik, atau bahkan nama hari.",
    ["Javascript"],
    "",
  ],
]