var class_category = [
  ["HTML & CSS", "/html-css", "teal"],
  ["Javascript", "/javascript", "orange"],
];

var Post_List = [
  [
    "Coding2020_01",
    "/html-css/opacity",
    "Apa itu Opacity pada CSS",
    "Feb 8, 2020",
    "Pecahan adalah bentuk lain dari bilangan desimal. misalnya 1/4 adalah bentuk lain dari 0.25. Operasi tambah dan kurang pecahan berbeda dengan kali dan bagi. Operasi tambah dan kurang pecahan membutuhkan sedikit perhatian untuk diselesaikan. Berikut ini beberapa cara yang bisa anda gunakan dalam menjumlahkan dan mengurangkan pecahan.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_02",
    "/html-css/Membuat-Animasi",
    "Membuat Animasi dengan CSS",
    "Feb 12, 2020",
    "Bagaimana cara membuat animasi dengan hanya menggunakan HTML dan CSS. Membuat Animasi dengan rule keyframes pada CSS dengan mengatur tingkat kecerahan atau tingkat transparan objek atau element HTML.",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_03",
    "/html-css/Membuat-Animasi-part2",
    "Membuat Animasi dengan CSS bg. 2",
    "Feb 16, 2020",
    "Bagaimana cara mengubah posisi atau penempatan objek dengan animasi pada HTML dan CSS. Pembuatan animasi dengan menggunakan rule keyframes pada CSS untuk mengatur posisi objek atau element HTML. Bagaimana cara menerapkan animasi yang telah dibuat pada objek atau element HTML. Bagaimana cara membuat Animasi Fade In dengan menerapkan opacity dan posisi objek pada CSS",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_04",
    "/html-css/animation-timing-function",
    "Apa itu Animation Timing Function",
    "Feb 20, 2020",
    "Membuat animasi dengan HTML dan CSS dengan mempertimbangkan animation timing function. Penerapan animation timing function pada beberapa objek dan melihat perbedaan dari animation timing function tersebut. ",
    ["HTML & CSS"],
    "",
  ],
  [
    "Coding2020_05",
    "/javascript/cara-membangkitkan-nilai-random-dengan-javascript",
    "Cara Membangkitkan Nilai Random dengan Javascript",
    "Oct 15, 2020",
    "Bilangan acak dan bahasa pemrograman adalah hal yang tidak mungkin terpisahkan. Setiap bahasa pemrograman memiliki caranya sendiri dalam membuat nilai random. Berikut ini bagaimana cara membangkitkan nilai random dengan javascript",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_06",
    "/javascript/006-cara-membangkitkan-nilai-random-bilangan-bulat-dengan-javascript",
    "Cara Membangkitkan Nilai Random Bilangan Bulat dengan Javascript",
    "Oct 17, 2020",
    "Pembulatan pada javascript dapat dilakukan dengan beberapa cara tergantung pada jenis pembulatan yang digunakan. Math.floor() adalah jenis pembulatan kebawah, atau menjadi bilangan bulat yang tepat berada di bawah bilangan asal pembulatan. Misalnya ketika anda membulatkan 14.56 dengan Math.floor() maka hasil yang akan anda peroleh adalah 14.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_07",
    "/javascript/007-cara-membuat-pembulatan-biasa-dengan-javascript",
    "Cara Membuat Pembulatan Biasa dengan Javascript",
    "Oct 19, 2020",
    "Metode Pembulatan adalah metode matematika yang mana menggeser nilai suatu bilangan ke bilangan bulat tertentu. Salah satu jenis pembulatan adalah pembulatan biasa atau pembulatan ke nilai terdekat. Pembulatan ini menggeser bilangan ke bilangan bulat terdekat. Misalnya 1.2 digeser menjadi 1, atau 3.6 digeser menjadi 4.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_08",
    "/javascript/008-cara-membuat-pembulatan-ke-bawah-dengan-javascript",
    "Cara Membuat Pembulatan ke Bawah dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa, pembulatan ke bawah juga bisa dilakukan di javascript. Pembulatan ke bawah adalah pembulatan dimana menggeser nilai suatu bilangan menjadi bilangan bulat dibawah nilai tersebut. Pembulatan ke bawah juga bisa dijelaskan dengan menghilangkan nilai desimal pada bilangan sehingga hanya menyisakan bilangan bulatnya saja",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_09",
    "/javascript/009-cara-membuat-pembulatan-ke-atas-dengan-javascript",
    "Cara Membuat Pembulatan ke Atas dengan Javascript",
    "Oct 19, 2020",
    "Selain pembulatan biasa dan pembulatan kebawah seperti yang sudah di bahas sebelumnya. Pembulatan ke atas juga bisa dilakukan dengan javascript. Pembulatan ke atas adalah pembulatan dimana nilai desimal dibulatkan menjadi 1 atau menjadi bilangan bulat berikutnya. Misalnya 4.3 menjadi 5, atau 4.8 menjadi 5.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_10",
    "/javascript/010-cara-memperoleh-waktu-setempat-dengan-javascript",
    "Cara Memperoleh Waktu Setempat dengan Javascript",
    "Oct 19, 2020",
    "Saat anda membuat program terkadang anda membutuhkan waktu setempat/lokal pengguna. Waktu lokal bisa berarti kapan pengguna membuka aplikasi tersebut. Mungkin anda membutuhkan informasi jam, menit atau detik, atau bahkan nama hari.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_11",
    "/javascript/011-cara-menampilkan-property-dari-object-di-javascript",
    "Cara Menampilkan Property dari Object di Javascript",
    "Oct 21, 2020",
    "Menampilkan method dan property mungkin tidak begitu diperlukan. Tapi untuk sekadar memahami isi dari object pada javascript, berikut cara yang bisa anda lakukan.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_12",
    "/javascript/012-cara-memperoleh-nilai-absolut-dari-suatu-nilai-dengan-javascript",
    "Cara Memperoleh Nilai Absolut dari Suatu Nilai dengan javascript",
    "Oct 21, 2020",
    "Metode absolute adalah metode yang digunakan untuk membuat nilai negatif menjadi positif dan membuat nilai positif tetap positif. Salah satu contoh penerapannya adalah perhitungan selisih dari dua nilai.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_13",
    "/javascript/013-cara-memperoleh-nilai-hasil-pangkat-dengan-javascript",
    "Cara Memperoleh Nilai Hasil Pangkat dengan Javasript",
    "Oct 21, 2020",
    "Metode pangkat adalah metode yang digunakan untuk mengalikan sebuah nilai yang sama beberapa nilai. Misalnya 3x3x3x3 sama dengan 3 pangkat 4, dimana angka 3 dikalikan sebanyak 4 kali. Berikut ini cara membuat perhitungan pangkat pada javascript.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_14",
    "/javascript/014-hubungan-radian-dan-derajat-pada-trigonometri",
    "Hubungan Radian dan Derajat pada Trigonometri",
    "Oct 25, 2020",
    "Pada saat kita menggunakan fungsi sinus trigonometri untuk 90 derajat, maka nilai yang kita harap akan muncul adalah 1. Hasilnya akan berbeda jika kita menggunakan fungsi sinus di javascript, jika penulisannya seperti dibawah ini.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_15",
    "/javascript/015-bagaimana-cara-membuat-fungsi-sinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Sinus Trigonometri pada javascript",
    "Oct 25, 2020",
    "Fungsi sinus adalah salah satu fungsi trigonometri yang sering digunakan. Fungsi sinus pada javascript dapat dituliskan sebagai berikut.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_16",
    "/javascript/015-bagaimana-cara-membuat-fungsi-cosinus-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Cosinus Trigonometri pada javascript",
    "Oct 25, 2020",
    "Selain fungsi sinus, fungsi trigonometri lain yang sering digunakan adalah fungsi cosinus. Berikut ini cara penulisan fungsi cosinus pada javascript.",
    ["Javascript"],
    "",
  ],
  [
    "Coding2020_17",
    "/javascript/015-bagaimana-cara-membuat-fungsi-tangen-trigonometri-pada-javascript",
    "Bagaimana Cara Membuat Fungsi Tangen Trigonometri pada javascript",
    "Oct 25, 2020",
    "Selain fungsi sinus dan cosinus, salah satu fungsi trigonometri yang juga cukup populer adalah fungsi tangen. Berikut ini contoh penulisan fungsi tangen pada javascript. ",
    ["Javascript"],
    "",
  ],
]