var titleCat_1 = "Persen";
var url_root = "https://nasrianas.website/jawab/math/persen";
var footerArray = [
    
["potongan_1", "/potongan-harga/potongan-1-persen", "Cara Menghitung Potongan 1 Persen", "", "potongan 1 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_2", "/potongan-harga/potongan-2-persen", "Cara Menghitung Potongan 2 Persen", "", "potongan 2 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_3", "/potongan-harga/potongan-3-persen", "Cara Menghitung Potongan 3 Persen", "", "potongan 3 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_4", "/potongan-harga/potongan-4-persen", "Cara Menghitung Potongan 4 Persen", "", "potongan 4 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_5", "/potongan-harga/potongan-5-persen", "Cara Menghitung Potongan 5 Persen", "", "potongan 5 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_6", "/potongan-harga/potongan-6-persen", "Cara Menghitung Potongan 6 Persen", "", "potongan 6 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_7", "/potongan-harga/potongan-7-persen", "Cara Menghitung Potongan 7 Persen", "", "potongan 7 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_8", "/potongan-harga/potongan-8-persen", "Cara Menghitung Potongan 8 Persen", "", "potongan 8 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_9", "/potongan-harga/potongan-9-persen", "Cara Menghitung Potongan 9 Persen", "", "potongan 9 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_10", "/potongan-harga/potongan-10-persen", "Cara Menghitung Potongan 10 Persen", "", "potongan 10 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_11", "/potongan-harga/potongan-11-persen", "Cara Menghitung Potongan 11 Persen", "", "potongan 11 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_12", "/potongan-harga/potongan-12-persen", "Cara Menghitung Potongan 12 Persen", "", "potongan 12 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_13", "/potongan-harga/potongan-13-persen", "Cara Menghitung Potongan 13 Persen", "", "potongan 13 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_14", "/potongan-harga/potongan-14-persen", "Cara Menghitung Potongan 14 Persen", "", "potongan 14 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_15", "/potongan-harga/potongan-15-persen", "Cara Menghitung Potongan 15 Persen", "", "potongan 15 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_16", "/potongan-harga/potongan-16-persen", "Cara Menghitung Potongan 16 Persen", "", "potongan 16 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_17", "/potongan-harga/potongan-17-persen", "Cara Menghitung Potongan 17 Persen", "", "potongan 17 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_18", "/potongan-harga/potongan-18-persen", "Cara Menghitung Potongan 18 Persen", "", "potongan 18 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_19", "/potongan-harga/potongan-19-persen", "Cara Menghitung Potongan 19 Persen", "", "potongan 19 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_20", "/potongan-harga/potongan-20-persen", "Cara Menghitung Potongan 20 Persen", "", "potongan 20 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_21", "/potongan-harga/potongan-21-persen", "Cara Menghitung Potongan 21 Persen", "", "potongan 21 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_22", "/potongan-harga/potongan-22-persen", "Cara Menghitung Potongan 22 Persen", "", "potongan 22 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_23", "/potongan-harga/potongan-23-persen", "Cara Menghitung Potongan 23 Persen", "", "potongan 23 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_24", "/potongan-harga/potongan-24-persen", "Cara Menghitung Potongan 24 Persen", "", "potongan 24 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_25", "/potongan-harga/potongan-25-persen", "Cara Menghitung Potongan 25 Persen", "", "potongan 25 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_26", "/potongan-harga/potongan-26-persen", "Cara Menghitung Potongan 26 Persen", "", "potongan 26 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_27", "/potongan-harga/potongan-27-persen", "Cara Menghitung Potongan 27 Persen", "", "potongan 27 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_28", "/potongan-harga/potongan-28-persen", "Cara Menghitung Potongan 28 Persen", "", "potongan 28 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_29", "/potongan-harga/potongan-29-persen", "Cara Menghitung Potongan 29 Persen", "", "potongan 29 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_30", "/potongan-harga/potongan-30-persen", "Cara Menghitung Potongan 30 Persen", "", "potongan 30 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_31", "/potongan-harga/potongan-31-persen", "Cara Menghitung Potongan 31 Persen", "", "potongan 31 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_32", "/potongan-harga/potongan-32-persen", "Cara Menghitung Potongan 32 Persen", "", "potongan 32 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_33", "/potongan-harga/potongan-33-persen", "Cara Menghitung Potongan 33 Persen", "", "potongan 33 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_34", "/potongan-harga/potongan-34-persen", "Cara Menghitung Potongan 34 Persen", "", "potongan 34 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_35", "/potongan-harga/potongan-35-persen", "Cara Menghitung Potongan 35 Persen", "", "potongan 35 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_36", "/potongan-harga/potongan-36-persen", "Cara Menghitung Potongan 36 Persen", "", "potongan 36 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_37", "/potongan-harga/potongan-37-persen", "Cara Menghitung Potongan 37 Persen", "", "potongan 37 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_38", "/potongan-harga/potongan-38-persen", "Cara Menghitung Potongan 38 Persen", "", "potongan 38 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_39", "/potongan-harga/potongan-39-persen", "Cara Menghitung Potongan 39 Persen", "", "potongan 39 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_40", "/potongan-harga/potongan-40-persen", "Cara Menghitung Potongan 40 Persen", "", "potongan 40 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_41", "/potongan-harga/potongan-41-persen", "Cara Menghitung Potongan 41 Persen", "", "potongan 41 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_42", "/potongan-harga/potongan-42-persen", "Cara Menghitung Potongan 42 Persen", "", "potongan 42 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_43", "/potongan-harga/potongan-43-persen", "Cara Menghitung Potongan 43 Persen", "", "potongan 43 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_44", "/potongan-harga/potongan-44-persen", "Cara Menghitung Potongan 44 Persen", "", "potongan 44 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_45", "/potongan-harga/potongan-45-persen", "Cara Menghitung Potongan 45 Persen", "", "potongan 45 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_46", "/potongan-harga/potongan-46-persen", "Cara Menghitung Potongan 46 Persen", "", "potongan 46 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_47", "/potongan-harga/potongan-47-persen", "Cara Menghitung Potongan 47 Persen", "", "potongan 47 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_48", "/potongan-harga/potongan-48-persen", "Cara Menghitung Potongan 48 Persen", "", "potongan 48 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_49", "/potongan-harga/potongan-49-persen", "Cara Menghitung Potongan 49 Persen", "", "potongan 49 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_50", "/potongan-harga/potongan-50-persen", "Cara Menghitung Potongan 50 Persen", "", "potongan 50 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_51", "/potongan-harga/potongan-51-persen", "Cara Menghitung Potongan 51 Persen", "", "potongan 51 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_52", "/potongan-harga/potongan-52-persen", "Cara Menghitung Potongan 52 Persen", "", "potongan 52 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_53", "/potongan-harga/potongan-53-persen", "Cara Menghitung Potongan 53 Persen", "", "potongan 53 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_54", "/potongan-harga/potongan-54-persen", "Cara Menghitung Potongan 54 Persen", "", "potongan 54 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_55", "/potongan-harga/potongan-55-persen", "Cara Menghitung Potongan 55 Persen", "", "potongan 55 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_56", "/potongan-harga/potongan-56-persen", "Cara Menghitung Potongan 56 Persen", "", "potongan 56 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_57", "/potongan-harga/potongan-57-persen", "Cara Menghitung Potongan 57 Persen", "", "potongan 57 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_58", "/potongan-harga/potongan-58-persen", "Cara Menghitung Potongan 58 Persen", "", "potongan 58 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_59", "/potongan-harga/potongan-59-persen", "Cara Menghitung Potongan 59 Persen", "", "potongan 59 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_60", "/potongan-harga/potongan-60-persen", "Cara Menghitung Potongan 60 Persen", "", "potongan 60 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_61", "/potongan-harga/potongan-61-persen", "Cara Menghitung Potongan 61 Persen", "", "potongan 61 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_62", "/potongan-harga/potongan-62-persen", "Cara Menghitung Potongan 62 Persen", "", "potongan 62 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_63", "/potongan-harga/potongan-63-persen", "Cara Menghitung Potongan 63 Persen", "", "potongan 63 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_64", "/potongan-harga/potongan-64-persen", "Cara Menghitung Potongan 64 Persen", "", "potongan 64 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_65", "/potongan-harga/potongan-65-persen", "Cara Menghitung Potongan 65 Persen", "", "potongan 65 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_66", "/potongan-harga/potongan-66-persen", "Cara Menghitung Potongan 66 Persen", "", "potongan 66 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_67", "/potongan-harga/potongan-67-persen", "Cara Menghitung Potongan 67 Persen", "", "potongan 67 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_68", "/potongan-harga/potongan-68-persen", "Cara Menghitung Potongan 68 Persen", "", "potongan 68 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_69", "/potongan-harga/potongan-69-persen", "Cara Menghitung Potongan 69 Persen", "", "potongan 69 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_70", "/potongan-harga/potongan-70-persen", "Cara Menghitung Potongan 70 Persen", "", "potongan 70 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_71", "/potongan-harga/potongan-71-persen", "Cara Menghitung Potongan 71 Persen", "", "potongan 71 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_72", "/potongan-harga/potongan-72-persen", "Cara Menghitung Potongan 72 Persen", "", "potongan 72 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_73", "/potongan-harga/potongan-73-persen", "Cara Menghitung Potongan 73 Persen", "", "potongan 73 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_74", "/potongan-harga/potongan-74-persen", "Cara Menghitung Potongan 74 Persen", "", "potongan 74 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_75", "/potongan-harga/potongan-75-persen", "Cara Menghitung Potongan 75 Persen", "", "potongan 75 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_76", "/potongan-harga/potongan-76-persen", "Cara Menghitung Potongan 76 Persen", "", "potongan 76 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_77", "/potongan-harga/potongan-77-persen", "Cara Menghitung Potongan 77 Persen", "", "potongan 77 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_78", "/potongan-harga/potongan-78-persen", "Cara Menghitung Potongan 78 Persen", "", "potongan 78 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_79", "/potongan-harga/potongan-79-persen", "Cara Menghitung Potongan 79 Persen", "", "potongan 79 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_80", "/potongan-harga/potongan-80-persen", "Cara Menghitung Potongan 80 Persen", "", "potongan 80 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_81", "/potongan-harga/potongan-81-persen", "Cara Menghitung Potongan 81 Persen", "", "potongan 81 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_82", "/potongan-harga/potongan-82-persen", "Cara Menghitung Potongan 82 Persen", "", "potongan 82 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_83", "/potongan-harga/potongan-83-persen", "Cara Menghitung Potongan 83 Persen", "", "potongan 83 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_84", "/potongan-harga/potongan-84-persen", "Cara Menghitung Potongan 84 Persen", "", "potongan 84 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_85", "/potongan-harga/potongan-85-persen", "Cara Menghitung Potongan 85 Persen", "", "potongan 85 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_86", "/potongan-harga/potongan-86-persen", "Cara Menghitung Potongan 86 Persen", "", "potongan 86 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_87", "/potongan-harga/potongan-87-persen", "Cara Menghitung Potongan 87 Persen", "", "potongan 87 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_88", "/potongan-harga/potongan-88-persen", "Cara Menghitung Potongan 88 Persen", "", "potongan 88 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_89", "/potongan-harga/potongan-89-persen", "Cara Menghitung Potongan 89 Persen", "", "potongan 89 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_90", "/potongan-harga/potongan-90-persen", "Cara Menghitung Potongan 90 Persen", "", "potongan 90 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

["potongan_91", "/potongan-harga/potongan-91-persen", "Cara Menghitung Potongan 91 Persen", "", "potongan 91 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_92", "/potongan-harga/potongan-92-persen", "Cara Menghitung Potongan 92 Persen", "", "potongan 92 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_93", "/potongan-harga/potongan-93-persen", "Cara Menghitung Potongan 93 Persen", "", "potongan 93 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_94", "/potongan-harga/potongan-94-persen", "Cara Menghitung Potongan 94 Persen", "", "potongan 94 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_95", "/potongan-harga/potongan-95-persen", "Cara Menghitung Potongan 95 Persen", "", "potongan 95 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_96", "/potongan-harga/potongan-96-persen", "Cara Menghitung Potongan 96 Persen", "", "potongan 96 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_97", "/potongan-harga/potongan-97-persen", "Cara Menghitung Potongan 97 Persen", "", "potongan 97 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_98", "/potongan-harga/potongan-98-persen", "Cara Menghitung Potongan 98 Persen", "", "potongan 98 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_99", "/potongan-harga/potongan-99-persen", "Cara Menghitung Potongan 99 Persen", "", "potongan 99 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],
["potongan_100", "/potongan-harga/potongan-100-persen", "Cara Menghitung Potongan 100 Persen", "", "potongan 100 persen itu berapa = ... ? Berikut hasil dan penjelasannya", ["Potongan Harga"], "", ],

];
