var mme_category = [["Process Control", "#", "teal"]];

var Post_List = [
  [
    "mme_2020_9_01",
    "/process-control/common-isa-symbols",
    "ISA Common Symbols",
    "12 September 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_02",
    "/process-control/process-control",
    "Process Control",
    "14 September 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_03",
    "/process-control/isa-symbology",
    "ISA Symbology",
    "14 September 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_04",
    "/process-control/automation-engineer-interview-questions",
    "Automation Engineer Interview Questions",
    "14 September 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_05",
    "/process-control/isa-symbology-(symbols)",
    "ISA Symbology (Symbols)",
    "19 September 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_06",
    "/process-control/isa-symbology-(letter)",
    "ISA Symbology (Letter)",
    "7 Oktober 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_07",
    "/process-control/Ethernet",
    "Ethernet",
    "7 Oktober 2020",
    "",
    ["Process Control"],
    "#",
  ],
  [
    "mme_2020_9_08",
    "/process-control/rs232-rs485",
    "RS232 - RS485",
    "7 Oktober 2020",
    "",
    ["Process Control"],
    "#",
  ],
];
