var titleCat_1 = "Panjang";
var url_root = "https://nasrianas.website/jawab/math/panjang";
var footerArray = [
    //June2020

    ["panjang_4690", "/mm-dm/4690-1-mm-berapa-dm", "1 mm berapa dm ?", "", "1 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4691", "/mm-dm/4691-2-mm-berapa-dm", "2 mm berapa dm ?", "", "2 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4692", "/mm-dm/4692-3-mm-berapa-dm", "3 mm berapa dm ?", "", "3 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4693", "/mm-dm/4693-4-mm-berapa-dm", "4 mm berapa dm ?", "", "4 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4694", "/mm-dm/4694-5-mm-berapa-dm", "5 mm berapa dm ?", "", "5 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4695", "/mm-dm/4695-6-mm-berapa-dm", "6 mm berapa dm ?", "", "6 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4696", "/mm-dm/4696-7-mm-berapa-dm", "7 mm berapa dm ?", "", "7 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4697", "/mm-dm/4697-8-mm-berapa-dm", "8 mm berapa dm ?", "", "8 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4698", "/mm-dm/4698-9-mm-berapa-dm", "9 mm berapa dm ?", "", "9 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4699", "/mm-dm/4699-10-mm-berapa-dm", "10 mm berapa dm ?", "", "10 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4700", "/mm-dm/4700-11-mm-berapa-dm", "11 mm berapa dm ?", "", "11 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4701", "/mm-dm/4701-12-mm-berapa-dm", "12 mm berapa dm ?", "", "12 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4702", "/mm-dm/4702-13-mm-berapa-dm", "13 mm berapa dm ?", "", "13 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4703", "/mm-dm/4703-14-mm-berapa-dm", "14 mm berapa dm ?", "", "14 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4704", "/mm-dm/4704-15-mm-berapa-dm", "15 mm berapa dm ?", "", "15 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4705", "/mm-dm/4705-16-mm-berapa-dm", "16 mm berapa dm ?", "", "16 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4706", "/mm-dm/4706-17-mm-berapa-dm", "17 mm berapa dm ?", "", "17 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4707", "/mm-dm/4707-18-mm-berapa-dm", "18 mm berapa dm ?", "", "18 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4708", "/mm-dm/4708-19-mm-berapa-dm", "19 mm berapa dm ?", "", "19 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4709", "/mm-dm/4709-20-mm-berapa-dm", "20 mm berapa dm ?", "", "20 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4710", "/mm-dm/4710-21-mm-berapa-dm", "21 mm berapa dm ?", "", "21 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4711", "/mm-dm/4711-22-mm-berapa-dm", "22 mm berapa dm ?", "", "22 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4712", "/mm-dm/4712-23-mm-berapa-dm", "23 mm berapa dm ?", "", "23 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4713", "/mm-dm/4713-24-mm-berapa-dm", "24 mm berapa dm ?", "", "24 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4714", "/mm-dm/4714-25-mm-berapa-dm", "25 mm berapa dm ?", "", "25 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4715", "/mm-dm/4715-26-mm-berapa-dm", "26 mm berapa dm ?", "", "26 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4716", "/mm-dm/4716-27-mm-berapa-dm", "27 mm berapa dm ?", "", "27 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4717", "/mm-dm/4717-28-mm-berapa-dm", "28 mm berapa dm ?", "", "28 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4718", "/mm-dm/4718-29-mm-berapa-dm", "29 mm berapa dm ?", "", "29 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4719", "/mm-dm/4719-30-mm-berapa-dm", "30 mm berapa dm ?", "", "30 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4720", "/mm-dm/4720-31-mm-berapa-dm", "31 mm berapa dm ?", "", "31 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4721", "/mm-dm/4721-32-mm-berapa-dm", "32 mm berapa dm ?", "", "32 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4722", "/mm-dm/4722-33-mm-berapa-dm", "33 mm berapa dm ?", "", "33 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4723", "/mm-dm/4723-34-mm-berapa-dm", "34 mm berapa dm ?", "", "34 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4724", "/mm-dm/4724-35-mm-berapa-dm", "35 mm berapa dm ?", "", "35 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4725", "/mm-dm/4725-36-mm-berapa-dm", "36 mm berapa dm ?", "", "36 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4726", "/mm-dm/4726-37-mm-berapa-dm", "37 mm berapa dm ?", "", "37 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4727", "/mm-dm/4727-38-mm-berapa-dm", "38 mm berapa dm ?", "", "38 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4728", "/mm-dm/4728-39-mm-berapa-dm", "39 mm berapa dm ?", "", "39 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4729", "/mm-dm/4729-40-mm-berapa-dm", "40 mm berapa dm ?", "", "40 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4730", "/mm-dm/4730-41-mm-berapa-dm", "41 mm berapa dm ?", "", "41 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4731", "/mm-dm/4731-42-mm-berapa-dm", "42 mm berapa dm ?", "", "42 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4732", "/mm-dm/4732-43-mm-berapa-dm", "43 mm berapa dm ?", "", "43 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4733", "/mm-dm/4733-44-mm-berapa-dm", "44 mm berapa dm ?", "", "44 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4734", "/mm-dm/4734-45-mm-berapa-dm", "45 mm berapa dm ?", "", "45 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4735", "/mm-dm/4735-46-mm-berapa-dm", "46 mm berapa dm ?", "", "46 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4736", "/mm-dm/4736-47-mm-berapa-dm", "47 mm berapa dm ?", "", "47 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4737", "/mm-dm/4737-48-mm-berapa-dm", "48 mm berapa dm ?", "", "48 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4738", "/mm-dm/4738-49-mm-berapa-dm", "49 mm berapa dm ?", "", "49 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4739", "/mm-dm/4739-50-mm-berapa-dm", "50 mm berapa dm ?", "", "50 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4740", "/mm-dm/4740-51-mm-berapa-dm", "51 mm berapa dm ?", "", "51 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4741", "/mm-dm/4741-52-mm-berapa-dm", "52 mm berapa dm ?", "", "52 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4742", "/mm-dm/4742-53-mm-berapa-dm", "53 mm berapa dm ?", "", "53 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4743", "/mm-dm/4743-54-mm-berapa-dm", "54 mm berapa dm ?", "", "54 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4744", "/mm-dm/4744-55-mm-berapa-dm", "55 mm berapa dm ?", "", "55 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4745", "/mm-dm/4745-56-mm-berapa-dm", "56 mm berapa dm ?", "", "56 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4746", "/mm-dm/4746-57-mm-berapa-dm", "57 mm berapa dm ?", "", "57 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4747", "/mm-dm/4747-58-mm-berapa-dm", "58 mm berapa dm ?", "", "58 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4748", "/mm-dm/4748-59-mm-berapa-dm", "59 mm berapa dm ?", "", "59 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4749", "/mm-dm/4749-60-mm-berapa-dm", "60 mm berapa dm ?", "", "60 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4750", "/mm-dm/4750-61-mm-berapa-dm", "61 mm berapa dm ?", "", "61 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4751", "/mm-dm/4751-62-mm-berapa-dm", "62 mm berapa dm ?", "", "62 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4752", "/mm-dm/4752-63-mm-berapa-dm", "63 mm berapa dm ?", "", "63 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4753", "/mm-dm/4753-64-mm-berapa-dm", "64 mm berapa dm ?", "", "64 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4754", "/mm-dm/4754-65-mm-berapa-dm", "65 mm berapa dm ?", "", "65 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4755", "/mm-dm/4755-66-mm-berapa-dm", "66 mm berapa dm ?", "", "66 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4756", "/mm-dm/4756-67-mm-berapa-dm", "67 mm berapa dm ?", "", "67 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4757", "/mm-dm/4757-68-mm-berapa-dm", "68 mm berapa dm ?", "", "68 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4758", "/mm-dm/4758-69-mm-berapa-dm", "69 mm berapa dm ?", "", "69 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4759", "/mm-dm/4759-70-mm-berapa-dm", "70 mm berapa dm ?", "", "70 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4760", "/mm-dm/4760-71-mm-berapa-dm", "71 mm berapa dm ?", "", "71 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4761", "/mm-dm/4761-72-mm-berapa-dm", "72 mm berapa dm ?", "", "72 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4762", "/mm-dm/4762-73-mm-berapa-dm", "73 mm berapa dm ?", "", "73 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4763", "/mm-dm/4763-74-mm-berapa-dm", "74 mm berapa dm ?", "", "74 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4764", "/mm-dm/4764-75-mm-berapa-dm", "75 mm berapa dm ?", "", "75 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4765", "/mm-dm/4765-76-mm-berapa-dm", "76 mm berapa dm ?", "", "76 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4766", "/mm-dm/4766-77-mm-berapa-dm", "77 mm berapa dm ?", "", "77 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4767", "/mm-dm/4767-78-mm-berapa-dm", "78 mm berapa dm ?", "", "78 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4768", "/mm-dm/4768-79-mm-berapa-dm", "79 mm berapa dm ?", "", "79 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4769", "/mm-dm/4769-80-mm-berapa-dm", "80 mm berapa dm ?", "", "80 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4770", "/mm-dm/4770-81-mm-berapa-dm", "81 mm berapa dm ?", "", "81 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4771", "/mm-dm/4771-82-mm-berapa-dm", "82 mm berapa dm ?", "", "82 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4772", "/mm-dm/4772-83-mm-berapa-dm", "83 mm berapa dm ?", "", "83 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4773", "/mm-dm/4773-84-mm-berapa-dm", "84 mm berapa dm ?", "", "84 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4774", "/mm-dm/4774-85-mm-berapa-dm", "85 mm berapa dm ?", "", "85 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4775", "/mm-dm/4775-86-mm-berapa-dm", "86 mm berapa dm ?", "", "86 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4776", "/mm-dm/4776-87-mm-berapa-dm", "87 mm berapa dm ?", "", "87 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4777", "/mm-dm/4777-88-mm-berapa-dm", "88 mm berapa dm ?", "", "88 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4778", "/mm-dm/4778-89-mm-berapa-dm", "89 mm berapa dm ?", "", "89 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4779", "/mm-dm/4779-90-mm-berapa-dm", "90 mm berapa dm ?", "", "90 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4780", "/mm-dm/4780-91-mm-berapa-dm", "91 mm berapa dm ?", "", "91 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4781", "/mm-dm/4781-92-mm-berapa-dm", "92 mm berapa dm ?", "", "92 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4782", "/mm-dm/4782-93-mm-berapa-dm", "93 mm berapa dm ?", "", "93 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4783", "/mm-dm/4783-94-mm-berapa-dm", "94 mm berapa dm ?", "", "94 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4784", "/mm-dm/4784-95-mm-berapa-dm", "95 mm berapa dm ?", "", "95 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4785", "/mm-dm/4785-96-mm-berapa-dm", "96 mm berapa dm ?", "", "96 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4786", "/mm-dm/4786-97-mm-berapa-dm", "97 mm berapa dm ?", "", "97 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4787", "/mm-dm/4787-98-mm-berapa-dm", "98 mm berapa dm ?", "", "98 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4788", "/mm-dm/4788-99-mm-berapa-dm", "99 mm berapa dm ?", "", "99 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    ["panjang_4789", "/mm-dm/4789-100-mm-berapa-dm", "100 mm berapa dm ?", "", "100 mm berapa dm beserta penjelasannya", ["mm - dm"], "", ],
    

];

//km berapa mm
//cc berapa ml
//mm berapa cm