var titleCat_1 = "Suhu";
var cat_1 = [
  ["Celcius-Fahrenheit", "/celcius-fahrenheit/001-30-derajat-celcius-berapa-fahrenheit", ""],
  ["Celcius-Reamur", "/celcus-reamur/002-30-derajat-celcius-berapa-reamur", ""],
  ["Celcius-Kelvin", "/celcius-kelvin/003-30-derajat-celcius-berapa-kelvin", ""],
  ["Reamur-Celcius", "/reamur-celcius/043-60-derajat-reamur-berapa-celcius", ""],
  ["Reamur-Fahrenheit", "/reamur-fahrenheit/056-1-derajat-reamur-berapa-fahrenheit", ""],
  ["Reamur-Kelvin", "/reamur-kelvin/069-20-derajat-reamur-berapa-kelvin", ""],
  ["Fehrenheit-Celcius", "/fahrenheit-celcius/079-77-derajat-fahrenheit-berapa-celcius", ""],
  ["Fehrenheit-Reamur", "/fahrenheit-reamur/090-122-derajat-fahrenheit-berapa-reamur", ""],
  ["Fehrenheit-Kelvin", "/fahrenheit-kelvin/099-212-derajat-fahrenheit-berapa-kelvin", ""],
  ["Kelvin-Celcius", "/kelvin-celcius/004-300-kelvin-berapa-celcius", ""],
  ["Kelvin-Reamur", "/kelvin-reamur/120-300-derajat-kelvin-berapa-reamur", ""], 
  ["Kelvin-Fahrenheit", "/kelvin-fahrenheit/131-1-derajat-kelvin-berapa-fahrenheit", ""],  
];
var url_root = "https://nasrianas.website/jawab/math/suhu";
var footerArray = [
    //June2020
    [
      "suhu_001",
      "/celcius-fahrenheit/001-30-derajat-celcius-berapa-fahrenheit",
      "30 Derajat Celcius Berapa Fahrenheit ?",
      "",
      "30 derajat celcius berapa fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_002",
      "/celcus-reamur/002-30-derajat-celcius-berapa-reamur",
      "30 Derajat Celcius Berapa Reamur ?",
      "",
      "30 derajat celcius berapa Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_003",
      "/celcius-kelvin/003-30-derajat-celcius-berapa-kelvin",
      "30 Derajat Celcius Berapa Kelvin ?",
      "",
      "30 derajat celcius berapa Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_004",
      "/kelvin-celcius/004-300-kelvin-berapa-celcius",
      "300 Kelvin Berapa Celcius ?",
      "",
      "300 kelvin berapa celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_005",
      "/celcus-reamur/005-25-derajat-celcius-berapa-reamur",
      "25 Celcius Berapa Reamur ?",
      "",
      "25 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_006",
      "/celcus-reamur/006-50-derajat-celcius-berapa-reamur",
      "50 Celcius Berapa Reamur ?",
      "",
      "50 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_007",
      "/celcus-reamur/007-20-derajat-celcius-berapa-reamur",
      "20 Celcius Berapa Reamur ?",
      "",
      "20 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_008",
      "/celcus-reamur/008-90-derajat-celcius-berapa-reamur",
      "90 Celcius Berapa Reamur ?",
      "",
      "90 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_009",
      "/celcus-reamur/009-40-derajat-celcius-berapa-reamur",
      "40 Celcius Berapa Reamur ?",
      "",
      "40 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_010",
      "/celcus-reamur/010-30-derajat-celcius-berapa-reamur",
      "30 Celcius Berapa Reamur ?",
      "",
      "30 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_011",
      "/celcus-reamur/011-45-derajat-celcius-berapa-reamur",
      "45 Celcius Berapa Reamur ?",
      "",
      "45 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_012",
      "/celcus-reamur/012-80-derajat-celcius-berapa-reamur",
      "80 Celcius Berapa Reamur ?",
      "",
      "80 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_013",
      "/celcus-reamur/013-60-derajat-celcius-berapa-reamur",
      "60 Celcius Berapa Reamur ?",
      "",
      "60 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_014",
      "/celcus-reamur/014-22-derajat-celcius-berapa-reamur",
      "22 Celcius Berapa Reamur ?",
      "",
      "22 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_015",
      "/celcus-reamur/015-37,5-derajat-celcius-berapa-reamur",
      "37.5 Celcius Berapa Reamur ?",
      "",
      "37,5 Celcius = ... Reamur",
      ["Celcius-Reamur"],
      "",
    ],
    [
      "suhu_016",
      "/celcus-fahrenheit/016-1-derajat-celcius-berapa-fahrenheit",
      "1 Celcius Berapa Fahrenheit ?",
      "",
      "1 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_017",
      "/celcus-fahrenheit/017-100-derajat-celcius-berapa-fahrenheit",
      "100 Celcius Berapa Fahrenheit ?",
      "",
      "100 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_018",
      "/celcus-fahrenheit/018-40-derajat-celcius-berapa-fahrenheit",
      "40 Celcius Berapa Fahrenheit ?",
      "",
      "40 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_019",
      "/celcus-fahrenheit/019-240-derajat-celcius-berapa-fahrenheit",
      "240 Celcius Berapa Fahrenheit ?",
      "",
      "240 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_020",
      "/celcus-fahrenheit/020-25-derajat-celcius-berapa-fahrenheit",
      "25 Celcius Berapa Fahrenheit ?",
      "",
      "25 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_021",
      "/celcus-fahrenheit/021-75-derajat-celcius-berapa-fahrenheit",
      "75 Celcius Berapa Fahrenheit ?",
      "",
      "75 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_022",
      "/celcus-fahrenheit/022-10-derajat-celcius-berapa-fahrenheit",
      "10 Celcius Berapa Fahrenheit ?",
      "",
      "10 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_023",
      "/celcus-fahrenheit/023-20-derajat-celcius-berapa-fahrenheit",
      "20 Celcius Berapa Fahrenheit ?",
      "",
      "20 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_024",
      "/celcus-fahrenheit/024-80-derajat-celcius-berapa-fahrenheit",
      "80 Celcius Berapa Fahrenheit ?",
      "",
      "80 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_025",
      "/celcus-fahrenheit/025-50-derajat-celcius-berapa-fahrenheit",
      "50 Celcius Berapa Fahrenheit ?",
      "",
      "50 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_026",
      "/celcus-fahrenheit/026-60-derajat-celcius-berapa-fahrenheit",
      "60 Celcius Berapa Fahrenheit ?",
      "",
      "60 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_027",
      "/celcus-fahrenheit/027-37-derajat-celcius-berapa-fahrenheit",
      "37 Celcius Berapa Fahrenheit ?",
      "",
      "37 Celcius = ... Fahrenheit",
      ["Celcius-Fahrenheit"],
      "",
    ],
    [
      "suhu_028",
      "/celcus-kelvin/028-1-derajat-celcius-berapa-kelvin",
      "1 Celcius Berapa Kelvin ?",
      "",
      "1 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_029",
      "/celcus-kelvin/029-37-derajat-celcius-berapa-kelvin",
      "37 Celcius Berapa Kelvin ?",
      "",
      "37 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_030",
      "/celcus-kelvin/030-27-derajat-celcius-berapa-kelvin",
      "27 Celcius Berapa Kelvin ?",
      "",
      "27 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_031",
      "/celcus-kelvin/031-39-derajat-celcius-berapa-kelvin",
      "39 Celcius Berapa Kelvin ?",
      "",
      "39 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_032",
      "/celcus-kelvin/032-227-derajat-celcius-berapa-kelvin",
      "227 Celcius Berapa Kelvin ?",
      "",
      "227 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_033",
      "/celcus-kelvin/033-127-derajat-celcius-berapa-kelvin",
      "127 Celcius Berapa Kelvin ?",
      "",
      "127 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_034",
      "/celcus-kelvin/034-20-derajat-celcius-berapa-kelvin",
      "20 Celcius Berapa Kelvin ?",
      "",
      "20 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_035",
      "/celcus-kelvin/035-10-derajat-celcius-berapa-kelvin",
      "10 Celcius Berapa Kelvin ?",
      "",
      "10 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_036",
      "/celcus-kelvin/036-80-derajat-celcius-berapa-kelvin",
      "80 Celcius Berapa Kelvin ?",
      "",
      "80 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_037",
      "/celcus-kelvin/037-0-derajat-celcius-berapa-kelvin",
      "0 Celcius Berapa Kelvin ?",
      "",
      "0 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_038",
      "/celcus-kelvin/038-50-derajat-celcius-berapa-kelvin",
      "50 Celcius Berapa Kelvin ?",
      "",
      "50 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_039",
      "/celcus-kelvin/039-40-derajat-celcius-berapa-kelvin",
      "40 Celcius Berapa Kelvin ?",
      "",
      "40 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_040",
      "/celcus-kelvin/040-100-derajat-celcius-berapa-kelvin",
      "100 Celcius Berapa Kelvin ?",
      "",
      "100 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_041",
      "/celcus-kelvin/041-36-derajat-celcius-berapa-kelvin",
      "36 Celcius Berapa Kelvin ?",
      "",
      "36 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_042",
      "/celcus-kelvin/042-25-derajat-celcius-berapa-kelvin",
      "25 Celcius Berapa Kelvin ?",
      "",
      "25 Celcius = ... Kelvin",
      ["Celcius-Kelvin"],
      "",
    ],
    [
      "suhu_043",
      "/reamur-celcius/043-60-derajat-reamur-berapa-celcius",
      "60 Reamur Berapa Celcius ?",
      "",
      "60 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_044",
      "/reamur-celcius/044-36-derajat-reamur-berapa-celcius",
      "36 Reamur Berapa Celcius ?",
      "",
      "36 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_045",
      "/reamur-celcius/045-80-derajat-reamur-berapa-celcius",
      "80 Reamur Berapa Celcius ?",
      "",
      "80 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_046",
      "/reamur-celcius/046-40-derajat-reamur-berapa-celcius",
      "40 Reamur Berapa Celcius ?",
      "",
      "40 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_047",
      "/reamur-celcius/047-32-derajat-reamur-berapa-celcius",
      "32 Reamur Berapa Celcius ?",
      "",
      "32 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_047",
      "/reamur-celcius/047-32-derajat-reamur-berapa-celcius",
      "32 Reamur Berapa Celcius ?",
      "",
      "32 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_048",
      "/reamur-celcius/048-20-derajat-reamur-berapa-celcius",
      "20 Reamur Berapa Celcius ?",
      "",
      "20 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_049",
      "/reamur-celcius/049-24-derajat-reamur-berapa-celcius",
      "24 Reamur Berapa Celcius ?",
      "",
      "24 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_050",
      "/reamur-celcius/050-64-derajat-reamur-berapa-celcius",
      "64 Reamur Berapa Celcius ?",
      "",
      "64 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_051",
      "/reamur-celcius/051-100-derajat-reamur-berapa-celcius",
      "100 Reamur Berapa Celcius ?",
      "",
      "100 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_052",
      "/reamur-celcius/052-200-derajat-reamur-berapa-celcius",
      "200 Reamur Berapa Celcius ?",
      "",
      "200 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_053",
      "/reamur-celcius/053-30-derajat-reamur-berapa-celcius",
      "30 Reamur Berapa Celcius ?",
      "",
      "30 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_054",
      "/reamur-celcius/054-75-derajat-reamur-berapa-celcius",
      "75 Reamur Berapa Celcius ?",
      "",
      "75 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_055",
      "/reamur-celcius/055-1-derajat-reamur-berapa-celcius",
      "1 Reamur Berapa Celcius ?",
      "",
      "1 Reamur = ... Celcius",
      ["Reamur-Celcius"],
      "",
    ],
    [
      "suhu_056",
      "/reamur-fahrenheit/056-1-derajat-reamur-berapa-fahrenheit",
      "1 Reamur Berapa Fahrenheit ?",
      "",
      "1 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_057",
      "/reamur-fahrenheit/057-45-derajat-reamur-berapa-fahrenheit",
      "45 Reamur Berapa Fahrenheit ?",
      "",
      "45 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_058",
      "/reamur-fahrenheit/058-60-derajat-reamur-berapa-fahrenheit",
      "60 Reamur Berapa Fahrenheit ?",
      "",
      "60 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_059",
      "/reamur-fahrenheit/059-40-derajat-reamur-berapa-fahrenheit",
      "40 Reamur Berapa Fahrenheit ?",
      "",
      "40 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_060",
      "/reamur-fahrenheit/060-80-derajat-reamur-berapa-fahrenheit",
      "80 Reamur Berapa Fahrenheit ?",
      "",
      "80 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_061",
      "/reamur-fahrenheit/061-36-derajat-reamur-berapa-fahrenheit",
      "36 Reamur Berapa Fahrenheit ?",
      "",
      "36 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_062",
      "/reamur-fahrenheit/062-72-derajat-reamur-berapa-fahrenheit",
      "72 Reamur Berapa Fahrenheit ?",
      "",
      "72 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_063",
      "/reamur-fahrenheit/063-50-derajat-reamur-berapa-fahrenheit",
      "50 Reamur Berapa Fahrenheit ?",
      "",
      "50 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_064",
      "/reamur-fahrenheit/064-20-derajat-reamur-berapa-fahrenheit",
      "20 Reamur Berapa Fahrenheit ?",
      "",
      "20 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_065",
      "/reamur-fahrenheit/065-32-derajat-reamur-berapa-fahrenheit",
      "32 Reamur Berapa Fahrenheit ?",
      "",
      "32 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_066",
      "/reamur-fahrenheit/066-120-derajat-reamur-berapa-fahrenheit",
      "120 Reamur Berapa Fahrenheit ?",
      "",
      "120 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_067",
      "/reamur-fahrenheit/067-28-derajat-reamur-berapa-fahrenheit",
      "28 Reamur Berapa Fahrenheit ?",
      "",
      "28 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],
    [
      "suhu_068",
      "/reamur-fahrenheit/068-158-derajat-reamur-berapa-fahrenheit",
      "158 Reamur Berapa Fahrenheit ?",
      "",
      "158 Reamur = ... Fahrenheit",
      ["Reamur-Fahrenheit"],
      "",
    ],

    [
      "suhu_069",
      "/reamur-kelvin/069-20-derajat-reamur-berapa-kelvin",
      "20 Reamur Berapa Kelvin ?",
      "",
      "20 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_070",
      "/reamur-kelvin/070-40-derajat-reamur-berapa-kelvin",
      "40 Reamur Berapa Kelvin ?",
      "",
      "40 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_071",
      "/reamur-kelvin/071-30-derajat-reamur-berapa-kelvin",
      "30 Reamur Berapa Kelvin ?",
      "",
      "30 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_072",
      "/reamur-kelvin/072-80-derajat-reamur-berapa-kelvin",
      "80 Reamur Berapa Kelvin ?",
      "",
      "80 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_073",
      "/reamur-kelvin/073-60-derajat-reamur-berapa-kelvin",
      "60 Reamur Berapa Kelvin ?",
      "",
      "60 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_074",
      "/reamur-kelvin/074-36-derajat-reamur-berapa-kelvin",
      "36 Reamur Berapa Kelvin ?",
      "",
      "36 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_075",
      "/reamur-kelvin/075-100-derajat-reamur-berapa-kelvin",
      "100 Reamur Berapa Kelvin ?",
      "",
      "100 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_076",
      "/reamur-kelvin/076-50-derajat-reamur-berapa-kelvin",
      "50 Reamur Berapa Kelvin ?",
      "",
      "50 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_077",
      "/reamur-kelvin/077-10-derajat-reamur-berapa-kelvin",
      "10 Reamur Berapa Kelvin ?",
      "",
      "10 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],
    [
      "suhu_078",
      "/reamur-kelvin/078-1-derajat-reamur-berapa-kelvin",
      "1 Reamur Berapa Kelvin ?",
      "",
      "1 Reamur = ... Kelvin",
      ["Reamur-Kelvin"],
      "",
    ],

    [
      "suhu_079",
      "/fahrenheit-celcius/079-77-derajat-fahrenheit-berapa-celcius",
      "77 Fahrenheit Berapa Celcius ?",
      "",
      "77 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_080",
      "/fahrenheit-celcius/080-60-derajat-fahrenheit-berapa-celcius",
      "60 Fahrenheit Berapa Celcius ?",
      "",
      "60 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_081",
      "/fahrenheit-celcius/081-122-derajat-fahrenheit-berapa-celcius",
      "122 Fahrenheit Berapa Celcius ?",
      "",
      "122 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_082",
      "/fahrenheit-celcius/082-50-derajat-fahrenheit-berapa-celcius",
      "50 Fahrenheit Berapa Celcius ?",
      "",
      "50 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_083",
      "/fahrenheit-celcius/083-86-derajat-fahrenheit-berapa-celcius",
      "86 Fahrenheit Berapa Celcius ?",
      "",
      "86 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_084",
      "/fahrenheit-celcius/084-68-derajat-fahrenheit-berapa-celcius",
      "68 Fahrenheit Berapa Celcius ?",
      "",
      "68 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_085",
      "/fahrenheit-celcius/085-113-derajat-fahrenheit-berapa-celcius",
      "113 Fahrenheit Berapa Celcius ?",
      "",
      "113 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_086",
      "/fahrenheit-celcius/086-90-derajat-fahrenheit-berapa-celcius",
      "90 Fahrenheit Berapa Celcius ?",
      "",
      "90 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_087",
      "/fahrenheit-celcius/087-95-derajat-fahrenheit-berapa-celcius",
      "95 Fahrenheit Berapa Celcius ?",
      "",
      "95 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_088",
      "/fahrenheit-celcius/088-54-derajat-fahrenheit-berapa-celcius",
      "54 Fahrenheit Berapa Celcius ?",
      "",
      "54 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],
    [
      "suhu_089",
      "/fahrenheit-celcius/089-1-derajat-fahrenheit-berapa-celcius",
      "1 Fahrenheit Berapa Celcius ?",
      "",
      "1 Fahrenheit = ... Celcius",
      ["Fahrenheit-Celcius"],
      "",
    ],

    [
      "suhu_090",
      "/fahrenheit-reamur/090-122-derajat-fahrenheit-berapa-reamur",
      "122 Fahrenheit Berapa Reamur ?",
      "",
      "122 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_091",
      "/fahrenheit-reamur/091-77-derajat-fahrenheit-berapa-reamur",
      "77 Fahrenheit Berapa Reamur ?",
      "",
      "77 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_092",
      "/fahrenheit-reamur/092-158-derajat-fahrenheit-berapa-reamur",
      "158 Fahrenheit Berapa Reamur ?",
      "",
      "158 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_093",
      "/fahrenheit-reamur/093-50-derajat-fahrenheit-berapa-reamur",
      "50 Fahrenheit Berapa Reamur ?",
      "",
      "50 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_094",
      "/fahrenheit-reamur/094-68-derajat-fahrenheit-berapa-reamur",
      "68 Fahrenheit Berapa Reamur ?",
      "",
      "68 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_095",
      "/fahrenheit-reamur/095-59-derajat-fahrenheit-berapa-reamur",
      "59 Fahrenheit Berapa Reamur ?",
      "",
      "59 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_096",
      "/fahrenheit-reamur/096-140-derajat-fahrenheit-berapa-reamur",
      "140 Fahrenheit Berapa Reamur ?",
      "",
      "140 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_097",
      "/fahrenheit-reamur/097-32-derajat-fahrenheit-berapa-reamur",
      "32 Fahrenheit Berapa Reamur ?",
      "",
      "32 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],
    [
      "suhu_098",
      "/fahrenheit-reamur/098-20-derajat-fahrenheit-berapa-reamur",
      "20 Fahrenheit Berapa Reamur ?",
      "",
      "20 Fahrenheit = ... Reamur",
      ["Fahrenheit-Reamur"],
      "",
    ],

    [
      "suhu_099",
      "/fahrenheit-kelvin/099-122-derajat-fahrenheit-berapa-kelvin",
      "122 Fahrenheit Berapa Kelvin ?",
      "",
      "122 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_100",
      "/fahrenheit-kelvin/100-212-derajat-fahrenheit-berapa-kelvin",
      "212 Fahrenheit Berapa Kelvin ?",
      "",
      "212 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_101",
      "/fahrenheit-kelvin/101-113-derajat-fahrenheit-berapa-kelvin",
      "113 Fahrenheit Berapa Kelvin ?",
      "",
      "113 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_102",
      "/fahrenheit-kelvin/102-50-derajat-fahrenheit-berapa-kelvin",
      "50 Fahrenheit Berapa Kelvin ?",
      "",
      "50 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_103",
      "/fahrenheit-kelvin/103-77-derajat-fahrenheit-berapa-kelvin",
      "77 Fahrenheit Berapa Kelvin ?",
      "",
      "77 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_104",
      "/fahrenheit-kelvin/104-59-derajat-fahrenheit-berapa-kelvin",
      "59 Fahrenheit Berapa Kelvin ?",
      "",
      "59 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_105",
      "/fahrenheit-kelvin/105-68-derajat-fahrenheit-berapa-kelvin",
      "68 Fahrenheit Berapa Kelvin ?",
      "",
      "68 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_106",
      "/fahrenheit-kelvin/106-45-derajat-fahrenheit-berapa-kelvin",
      "45 Fahrenheit Berapa Kelvin ?",
      "",
      "45 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],
    [
      "suhu_107",
      "/fahrenheit-kelvin/107-1-derajat-fahrenheit-berapa-kelvin",
      "1 Fahrenheit Berapa Kelvin ?",
      "",
      "1 Fahrenheit = ... Kelvin",
      ["Fahrenheit-Kelvin"],
      "",
    ],

    [
      "suhu_108",
      "/kelvin-celcius/108-1-derajat-kelvin-berapa-celcius",
      "1 Kelvin Berapa Celcius ?",
      "",
      "1 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_109",
      "/kelvin-celcius/109-225-derajat-kelvin-berapa-celcius",
      "225 Kelvin Berapa Celcius ?",
      "",
      "225 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_110",
      "/kelvin-celcius/110-500-derajat-kelvin-berapa-celcius",
      "500 Kelvin Berapa Celcius ?",
      "",
      "500 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_111",
      "/kelvin-celcius/111-0-derajat-kelvin-berapa-celcius",
      "0 Kelvin Berapa Celcius ?",
      "",
      "0 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_112",
      "/kelvin-celcius/112-373-derajat-kelvin-berapa-celcius",
      "373 Kelvin Berapa Celcius ?",
      "",
      "373 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_113",
      "/kelvin-celcius/113-333-derajat-kelvin-berapa-celcius",
      "333 Kelvin Berapa Celcius ?",
      "",
      "333 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_114",
      "/kelvin-celcius/114-303-derajat-kelvin-berapa-celcius",
      "303 Kelvin Berapa Celcius ?",
      "",
      "303 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_115",
      "/kelvin-celcius/115-20-derajat-kelvin-berapa-celcius",
      "20 Kelvin Berapa Celcius ?",
      "",
      "20 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_116",
      "/kelvin-celcius/116-30-derajat-kelvin-berapa-celcius",
      "30 Kelvin Berapa Celcius ?",
      "",
      "30 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_117",
      "/kelvin-celcius/117-200-derajat-kelvin-berapa-celcius",
      "200 Kelvin Berapa Celcius ?",
      "",
      "200 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_118",
      "/kelvin-celcius/118-365-derajat-kelvin-berapa-celcius",
      "365 Kelvin Berapa Celcius ?",
      "",
      "365 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    [
      "suhu_119",
      "/kelvin-celcius/119-100-derajat-kelvin-berapa-celcius",
      "100 Kelvin Berapa Celcius ?",
      "",
      "100 Kelvin = ... Celcius",
      ["Kelvin-Celcius"],
      "",
    ],
    
    [
      "suhu_120",
      "/kelvin-reamur/120-300-derajat-kelvin-berapa-reamur",
      "300 Kelvin Berapa Reamur ?",
      "",
      "300 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_121",
      "/kelvin-reamur/121-225-derajat-kelvin-berapa-reamur",
      "225 Kelvin Berapa Reamur ?",
      "",
      "225 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_122",
      "/kelvin-reamur/122-313-derajat-kelvin-berapa-reamur",
      "313 Kelvin Berapa Reamur ?",
      "",
      "313 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_123",
      "/kelvin-reamur/123-398-derajat-kelvin-berapa-reamur",
      "398 Kelvin Berapa Reamur ?",
      "",
      "398 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_124",
      "/kelvin-reamur/124-303-derajat-kelvin-berapa-reamur",
      "303 Kelvin Berapa Reamur ?",
      "",
      "303 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_125",
      "/kelvin-reamur/125-373-derajat-kelvin-berapa-reamur",
      "373 Kelvin Berapa Reamur ?",
      "",
      "373 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_126",
      "/kelvin-reamur/126-333-derajat-kelvin-berapa-reamur",
      "333 Kelvin Berapa Reamur ?",
      "",
      "333 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_127",
      "/kelvin-reamur/127-298-derajat-kelvin-berapa-reamur",
      "298 Kelvin Berapa Reamur ?",
      "",
      "298 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_128",
      "/kelvin-reamur/128-350-derajat-kelvin-berapa-reamur",
      "350 Kelvin Berapa Reamur ?",
      "",
      "350 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_129",
      "/kelvin-reamur/129-400-derajat-kelvin-berapa-reamur",
      "400 Kelvin Berapa Reamur ?",
      "",
      "400 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_130",
      "/kelvin-reamur/130-1-derajat-kelvin-berapa-reamur",
      "1 Kelvin Berapa Reamur ?",
      "",
      "1 Kelvin = ... Reamur",
      ["Kelvin-Reamur"],
      "",
    ],
    [
      "suhu_131",
      "/kelvin-fahrenheit/131-1-derajat-kelvin-berapa-fahrenheit",
      "1 Kelvin Berapa Fahrenheit ?",
      "",
      "1 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_132",
      "/kelvin-fahrenheit/132-333-derajat-kelvin-berapa-fahrenheit",
      "333 Kelvin Berapa Fahrenheit ?",
      "",
      "333 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_133",
      "/kelvin-fahrenheit/133-303-derajat-kelvin-berapa-fahrenheit",
      "303 Kelvin Berapa Fahrenheit ?",
      "",
      "303 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_134",
      "/kelvin-fahrenheit/134-300-derajat-kelvin-berapa-fahrenheit",
      "300 Kelvin Berapa Fahrenheit ?",
      "",
      "300 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_135",
      "/kelvin-fahrenheit/135-323-derajat-kelvin-berapa-fahrenheit",
      "323 Kelvin Berapa Fahrenheit ?",
      "",
      "323 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_136",
      "/kelvin-fahrenheit/136-313-derajat-kelvin-berapa-fahrenheit",
      "313 Kelvin Berapa Fahrenheit ?",
      "",
      "313 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_137",
      "/kelvin-fahrenheit/137-293-derajat-kelvin-berapa-fahrenheit",
      "293 Kelvin Berapa Fahrenheit ?",
      "",
      "293 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_138",
      "/kelvin-fahrenheit/138-318-derajat-kelvin-berapa-fahrenheit",
      "318 Kelvin Berapa Fahrenheit ?",
      "",
      "318 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_139",
      "/kelvin-fahrenheit/139-343-derajat-kelvin-berapa-fahrenheit",
      "343 Kelvin Berapa Fahrenheit ?",
      "",
      "343 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_140",
      "/kelvin-fahrenheit/140-100-derajat-kelvin-berapa-fahrenheit",
      "100 Kelvin Berapa Fahrenheit ?",
      "",
      "100 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
    [
      "suhu_141",
      "/kelvin-fahrenheit/141-0-derajat-kelvin-berapa-fahrenheit",
      "0 Kelvin Berapa Fahrenheit ?",
      "",
      "0 Kelvin = ... Fahrenheit",
      ["Kelvin-Fahrenheit"],
      "",
    ],
  
];