var titleCat_1 = "Pecahan";
var cat_1 = [
  ["Desimal - Pecahan Biasa", "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa", ""],
  ["Bagian", "/bagian/163-5per8-dari-240", ""],
  ["Jumlah Pecahan", "/jumlah-pecahan/163-5per8-dari-240", ""],  
];
var url_root = "https://nasrianas.website/jawab/math/pecahan";
var footerArray = [
    //June2020
    [
      "pecahan_001",
      "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa",
      "0.75 Diubah Menjadi Pecahan Biasa",
      "",
      "0.75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_002",
      "/decimal-pecahanBiasa/002-0,25-diubah-menjadi-pecahan-biasa",
      "0.25 Diubah Menjadi Pecahan Biasa",
      "",
      "0.25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_003",
      "/decimal-pecahanBiasa/003-0,72-diubah-menjadi-pecahan-biasa",
      "0.72 Diubah Menjadi Pecahan Biasa",
      "",
      "0.72 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_004",
      "/decimal-pecahanBiasa/004-0,02-diubah-menjadi-pecahan-biasa",
      "0.02 Diubah Menjadi Pecahan Biasa",
      "",
      "0.02 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_005",
      "/decimal-pecahanBiasa/005-0,30-diubah-menjadi-pecahan-biasa",
      "0.30 Diubah Menjadi Pecahan Biasa",
      "",
      "0.30 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_006",
      "/decimal-pecahanBiasa/006-0,2-diubah-menjadi-pecahan-biasa",
      "0.2 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_007",
      "/decimal-pecahanBiasa/007-0,15-diubah-menjadi-pecahan-biasa",
      "0.15 Diubah Menjadi Pecahan Biasa",
      "",
      "0.15 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_008",
      "/decimal-pecahanBiasa/008-0,125-diubah-menjadi-pecahan-biasa",
      "0.125 Diubah Menjadi Pecahan Biasa",
      "",
      "0.125 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_009",
      "/decimal-pecahanBiasa/009-0,3-diubah-menjadi-pecahan-biasa",
      "0.3 Diubah Menjadi Pecahan Biasa",
      "",
      "0.3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_010",
      "/decimal-pecahanBiasa/010-0,4-diubah-menjadi-pecahan-biasa",
      "0.4 Diubah Menjadi Pecahan Biasa",
      "",
      "0.4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_011",
      "/decimal-pecahanBiasa/011-0,50-diubah-menjadi-pecahan-biasa",
      "0.50 Diubah Menjadi Pecahan Biasa",
      "",
      "0.50 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_012",
      "/decimal-pecahanBiasa/012-0,6-diubah-menjadi-pecahan-biasa",
      "0.6 Diubah Menjadi Pecahan Biasa",
      "",
      "0.6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_013",
      "/decimal-pecahanBiasa/013-0,62-diubah-menjadi-pecahan-biasa",
      "0.62 Diubah Menjadi Pecahan Biasa",
      "",
      "0.62 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_014",
      "/decimal-pecahanBiasa/014-0,32-diubah-menjadi-pecahan-biasa",
      "0.32 Diubah Menjadi Pecahan Biasa",
      "",
      "0.32 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_015",
      "/decimal-pecahanBiasa/015-0,875-diubah-menjadi-pecahan-biasa",
      "0.875 Diubah Menjadi Pecahan Biasa",
      "",
      "0.875 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_016",
      "/decimal-pecahanBiasa/016-0,625-diubah-menjadi-pecahan-biasa",
      "0.625 Diubah Menjadi Pecahan Biasa",
      "",
      "0.625 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_017",
      "/decimal-pecahanBiasa/017-0,375-diubah-menjadi-pecahan-biasa",
      "0.375 Diubah Menjadi Pecahan Biasa",
      "",
      "0.375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_018",
      "/decimal-pecahanBiasa/018-0,8-diubah-menjadi-pecahan-biasa",
      "0.8 Diubah Menjadi Pecahan Biasa",
      "",
      "0.8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_019",
      "/decimal-pecahanBiasa/019-0,45-diubah-menjadi-pecahan-biasa",
      "0.45 Diubah Menjadi Pecahan Biasa",
      "",
      "0.45 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_020",
      "/decimal-pecahanBiasa/020-0,09-diubah-menjadi-pecahan-biasa",
      "0.09 Diubah Menjadi Pecahan Biasa",
      "",
      "0.09 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_021",
      "/decimal-pecahanBiasa/021-0,36-diubah-menjadi-pecahan-biasa",
      "0.36 Diubah Menjadi Pecahan Biasa",
      "",
      "0.36 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_022",
      "/decimal-pecahanBiasa/022-0,5-diubah-menjadi-pecahan-biasa",
      "0.5 Diubah Menjadi Pecahan Biasa",
      "",
      "0.5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_023",
      "/decimal-pecahanBiasa/023-0,65-diubah-menjadi-pecahan-biasa",
      "0.65 Diubah Menjadi Pecahan Biasa",
      "",
      "0.65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_024",
      "/decimal-pecahanBiasa/024-0,01-diubah-menjadi-pecahan-biasa",
      "0.01 Diubah Menjadi Pecahan Biasa",
      "",
      "0.01 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_025",
      "/decimal-pecahanBiasa/025-0,03-diubah-menjadi-pecahan-biasa",
      "0.03 Diubah Menjadi Pecahan Biasa",
      "",
      "0.03 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_026",
      "/decimal-pecahanBiasa/026-0,07-diubah-menjadi-pecahan-biasa",
      "0.07 Diubah Menjadi Pecahan Biasa",
      "",
      "0.07 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_027",
      "/decimal-pecahanBiasa/027-0,04-diubah-menjadi-pecahan-biasa",
      "0.04 Diubah Menjadi Pecahan Biasa",
      "",
      "0.04 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_028",
      "/decimal-pecahanBiasa/028-0,06-diubah-menjadi-pecahan-biasa",
      "0.06 Diubah Menjadi Pecahan Biasa",
      "",
      "0.06 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_029",
      "/decimal-pecahanBiasa/029-0,08-diubah-menjadi-pecahan-biasa",
      "0.08 Diubah Menjadi Pecahan Biasa",
      "",
      "0.08 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_030",
      "/decimal-pecahanBiasa/030-0,12-diubah-menjadi-pecahan-biasa",
      "0.12 Diubah Menjadi Pecahan Biasa",
      "",
      "0.12 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_031",
      "/decimal-pecahanBiasa/031-0,16-diubah-menjadi-pecahan-biasa",
      "0.16 Diubah Menjadi Pecahan Biasa",
      "",
      "0.16 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_032",
      "/decimal-pecahanBiasa/032-0,175-diubah-menjadi-pecahan-biasa",
      "0.175 Diubah Menjadi Pecahan Biasa",
      "",
      "0.175 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_033",
      "/decimal-pecahanBiasa/033-0,1025-diubah-menjadi-pecahan-biasa",
      "0.1025 Diubah Menjadi Pecahan Biasa",
      "",
      "0.1025 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_034",
      "/decimal-pecahanBiasa/034-0,24-diubah-menjadi-pecahan-biasa",
      "0.24 Diubah Menjadi Pecahan Biasa",
      "",
      "0.24 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_035",
      "/decimal-pecahanBiasa/035-0,20-diubah-menjadi-pecahan-biasa",
      "0.20 Diubah Menjadi Pecahan Biasa",
      "",
      "0.20 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_036",
      "/decimal-pecahanBiasa/036-0,2525-diubah-menjadi-pecahan-biasa",
      "0.2525 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2525 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_037",
      "/decimal-pecahanBiasa/037-0,26-diubah-menjadi-pecahan-biasa",
      "0.26 Diubah Menjadi Pecahan Biasa",
      "",
      "0.26 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_038",
      "/decimal-pecahanBiasa/038-0,225-diubah-menjadi-pecahan-biasa",
      "0.225 Diubah Menjadi Pecahan Biasa",
      "",
      "0.225 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_039",
      "/decimal-pecahanBiasa/039-0,21-diubah-menjadi-pecahan-biasa",
      "0.21 Diubah Menjadi Pecahan Biasa",
      "",
      "0.21 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_040",
      "/decimal-pecahanBiasa/040-0,23-diubah-menjadi-pecahan-biasa",
      "0.23 Diubah Menjadi Pecahan Biasa",
      "",
      "0.23 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_041",
      "/decimal-pecahanBiasa/041-0,33-diubah-menjadi-pecahan-biasa",
      "0.33 Diubah Menjadi Pecahan Biasa",
      "",
      "0.33 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_042",
      "/decimal-pecahanBiasa/042-0,333-diubah-menjadi-pecahan-biasa",
      "0.333 Diubah Menjadi Pecahan Biasa",
      "",
      "0.333 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_043",
      "/decimal-pecahanBiasa/043-0,35-diubah-menjadi-pecahan-biasa",
      "0.35 Diubah Menjadi Pecahan Biasa",
      "",
      "0.35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_044",
      "/decimal-pecahanBiasa/044-0,48-diubah-menjadi-pecahan-biasa",
      "0.48 Diubah Menjadi Pecahan Biasa",
      "",
      "0.48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_045",
      "/decimal-pecahanBiasa/045-0,40-diubah-menjadi-pecahan-biasa",
      "0.40 Diubah Menjadi Pecahan Biasa",
      "",
      "0.40 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_046",
      "/decimal-pecahanBiasa/046-0,42-diubah-menjadi-pecahan-biasa",
      "0.42 Diubah Menjadi Pecahan Biasa",
      "",
      "0.42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_047",
      "/decimal-pecahanBiasa/047-0,44-diubah-menjadi-pecahan-biasa",
      "0.44 Diubah Menjadi Pecahan Biasa",
      "",
      "0.44 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_048",
      "/decimal-pecahanBiasa/048-0,46-diubah-menjadi-pecahan-biasa",
      "0.46 Diubah Menjadi Pecahan Biasa",
      "",
      "0.46 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_049",
      "/decimal-pecahanBiasa/049-0,43-diubah-menjadi-pecahan-biasa",
      "0.43 Diubah Menjadi Pecahan Biasa",
      "",
      "0.43 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_050",
      "/decimal-pecahanBiasa/050-0,53-diubah-menjadi-pecahan-biasa",
      "0.53 Diubah Menjadi Pecahan Biasa",
      "",
      "0.53 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_051",
      "/decimal-pecahanBiasa/051-0,52-diubah-menjadi-pecahan-biasa",
      "0.52 Diubah Menjadi Pecahan Biasa",
      "",
      "0.52 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_052",
      "/decimal-pecahanBiasa/052-0,55-diubah-menjadi-pecahan-biasa",
      "0.55 Diubah Menjadi Pecahan Biasa",
      "",
      "0.55 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_053",
      "/decimal-pecahanBiasa/053-0,56-diubah-menjadi-pecahan-biasa",
      "0.56 Diubah Menjadi Pecahan Biasa",
      "",
      "0.56 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_054",
      "/decimal-pecahanBiasa/054-0,58-diubah-menjadi-pecahan-biasa",
      "0.58 Diubah Menjadi Pecahan Biasa",
      "",
      "0.58 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_055",
      "/decimal-pecahanBiasa/055-0,60-diubah-menjadi-pecahan-biasa",
      "0.60 Diubah Menjadi Pecahan Biasa",
      "",
      "0.60 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_056",
      "/decimal-pecahanBiasa/056-0,64-diubah-menjadi-pecahan-biasa",
      "0.64 Diubah Menjadi Pecahan Biasa",
      "",
      "0.64 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_057",
      "/decimal-pecahanBiasa/057-0,66-diubah-menjadi-pecahan-biasa",
      "0.66 Diubah Menjadi Pecahan Biasa",
      "",
      "0.66 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_058",
      "/decimal-pecahanBiasa/058-0,69-diubah-menjadi-pecahan-biasa",
      "0.69 Diubah Menjadi Pecahan Biasa",
      "",
      "0.69 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_059",
      "/decimal-pecahanBiasa/059-0,7-diubah-menjadi-pecahan-biasa",
      "0.7 Diubah Menjadi Pecahan Biasa",
      "",
      "0.7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_060",
      "/decimal-pecahanBiasa/060-0,79-diubah-menjadi-pecahan-biasa",
      "0.79 Diubah Menjadi Pecahan Biasa",
      "",
      "0.79 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_061",
      "/decimal-pecahanBiasa/061-0,70-diubah-menjadi-pecahan-biasa",
      "0.70 Diubah Menjadi Pecahan Biasa",
      "",
      "0.70 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_062",
      "/decimal-pecahanBiasa/062-0,74-diubah-menjadi-pecahan-biasa",
      "0.74 Diubah Menjadi Pecahan Biasa",
      "",
      "0.74 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_063",
      "/decimal-pecahanBiasa/063-0,76-diubah-menjadi-pecahan-biasa",
      "0.76 Diubah Menjadi Pecahan Biasa",
      "",
      "0.76 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_064",
      "/decimal-pecahanBiasa/064-0,725-diubah-menjadi-pecahan-biasa",
      "0.725 Diubah Menjadi Pecahan Biasa",
      "",
      "0.725 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_065",
      "/decimal-pecahanBiasa/065-0,80-diubah-menjadi-pecahan-biasa",
      "0.80 Diubah Menjadi Pecahan Biasa",
      "",
      "0.80 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_066",
      "/decimal-pecahanBiasa/066-0,82-diubah-menjadi-pecahan-biasa",
      "0.82 Diubah Menjadi Pecahan Biasa",
      "",
      "0.82 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_067",
      "/decimal-pecahanBiasa/067-0,84-diubah-menjadi-pecahan-biasa",
      "0.84 Diubah Menjadi Pecahan Biasa",
      "",
      "0.84 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_068",
      "/decimal-pecahanBiasa/068-0,85-diubah-menjadi-pecahan-biasa",
      "0.85 Diubah Menjadi Pecahan Biasa",
      "",
      "0.85 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_069",
      "/decimal-pecahanBiasa/069-0,86-diubah-menjadi-pecahan-biasa",
      "0.86 Diubah Menjadi Pecahan Biasa",
      "",
      "0.86 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_070",
      "/decimal-pecahanBiasa/070-0,88-diubah-menjadi-pecahan-biasa",
      "0.88 Diubah Menjadi Pecahan Biasa",
      "",
      "0.88 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_071",
      "/decimal-pecahanBiasa/071-0,83-diubah-menjadi-pecahan-biasa",
      "0.83 Diubah Menjadi Pecahan Biasa",
      "",
      "0.83 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_072",
      "/decimal-pecahanBiasa/072-0,9-diubah-menjadi-pecahan-biasa",
      "0.9 Diubah Menjadi Pecahan Biasa",
      "",
      "0.9 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_073",
      "/decimal-pecahanBiasa/073-0,90-diubah-menjadi-pecahan-biasa",
      "0.90 Diubah Menjadi Pecahan Biasa",
      "",
      "0.90 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_074",
      "/decimal-pecahanBiasa/074-0,95-diubah-menjadi-pecahan-biasa",
      "0.95 Diubah Menjadi Pecahan Biasa",
      "",
      "0.95 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_075",
      "/decimal-pecahanBiasa/075-0,96-diubah-menjadi-pecahan-biasa",
      "0.96 Diubah Menjadi Pecahan Biasa",
      "",
      "0.96 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_076",
      "/decimal-pecahanBiasa/076-1,15-diubah-menjadi-pecahan-biasa",
      "1.15 Diubah Menjadi Pecahan Biasa",
      "",
      "1.15 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_077",
      "/decimal-pecahanBiasa/077-1,2-diubah-menjadi-pecahan-biasa",
      "1.2 Diubah Menjadi Pecahan Biasa",
      "",
      "1.2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_078",
      "/decimal-pecahanBiasa/078-1,25-diubah-menjadi-pecahan-biasa",
      "1.25 Diubah Menjadi Pecahan Biasa",
      "",
      "1.25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_079",
      "/decimal-pecahanBiasa/079-1,24-diubah-menjadi-pecahan-biasa",
      "1.24 Diubah Menjadi Pecahan Biasa",
      "",
      "1.24 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_080",
      "/decimal-pecahanBiasa/080-1,20-diubah-menjadi-pecahan-biasa",
      "1.20 Diubah Menjadi Pecahan Biasa",
      "",
      "1.20 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_081",
      "/decimal-pecahanBiasa/081-1,29-diubah-menjadi-pecahan-biasa",
      "1.29 Diubah Menjadi Pecahan Biasa",
      "",
      "1.29 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_082",
      "/decimal-pecahanBiasa/082-1,33-diubah-menjadi-pecahan-biasa",
      "1.33 Diubah Menjadi Pecahan Biasa",
      "",
      "1.33 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_083",
      "/decimal-pecahanBiasa/083-1,32-diubah-menjadi-pecahan-biasa",
      "1.32 Diubah Menjadi Pecahan Biasa",
      "",
      "1.32 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_084",
      "/decimal-pecahanBiasa/084-1,4-diubah-menjadi-pecahan-biasa",
      "1.4 Diubah Menjadi Pecahan Biasa",
      "",
      "1.4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_085",
      "/decimal-pecahanBiasa/085-1,42-diubah-menjadi-pecahan-biasa",
      "1.42 Diubah Menjadi Pecahan Biasa",
      "",
      "1.42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_086",
      "/decimal-pecahanBiasa/086-1,5-diubah-menjadi-pecahan-biasa",
      "1.5 Diubah Menjadi Pecahan Biasa",
      "",
      "1.5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_087",
      "/decimal-pecahanBiasa/087-1,50-diubah-menjadi-pecahan-biasa",
      "1.50 Diubah Menjadi Pecahan Biasa",
      "",
      "1.50 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_088",
      "/decimal-pecahanBiasa/088-1,6-diubah-menjadi-pecahan-biasa",
      "1.6 Diubah Menjadi Pecahan Biasa",
      "",
      "1.6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_089",
      "/decimal-pecahanBiasa/089-1,65-diubah-menjadi-pecahan-biasa",
      "1.65 Diubah Menjadi Pecahan Biasa",
      "",
      "1.65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_090",
      "/decimal-pecahanBiasa/090-1,75-diubah-menjadi-pecahan-biasa",
      "1.75 Diubah Menjadi Pecahan Biasa",
      "",
      "1.75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_091",
      "/decimal-pecahanBiasa/091-1,8-diubah-menjadi-pecahan-biasa",
      "1.8 Diubah Menjadi Pecahan Biasa",
      "",
      "1.8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_092",
      "/decimal-pecahanBiasa/092-1,7-diubah-menjadi-pecahan-biasa",
      "1.7 Diubah Menjadi Pecahan Biasa",
      "",
      "1.7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_093",
      "/decimal-pecahanBiasa/093-2,3-diubah-menjadi-pecahan-biasa",
      "2,3 Diubah Menjadi Pecahan Biasa",
      "",
      "2,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_094",
      "/decimal-pecahanBiasa/094-2,7-diubah-menjadi-pecahan-biasa",
      "2,7 Diubah Menjadi Pecahan Biasa",
      "",
      "2,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_095",
      "/decimal-pecahanBiasa/095-2,71-diubah-menjadi-pecahan-biasa",
      "2,71 Diubah Menjadi Pecahan Biasa",
      "",
      "2,71 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_096",
      "/decimal-pecahanBiasa/096-2,05-diubah-menjadi-pecahan-biasa",
      "2,05 Diubah Menjadi Pecahan Biasa",
      "",
      "2,05 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_097",
      "/decimal-pecahanBiasa/097-2,2-diubah-menjadi-pecahan-biasa",
      "2,2 Diubah Menjadi Pecahan Biasa",
      "",
      "2,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_098",
      "/decimal-pecahanBiasa/098-2,25-diubah-menjadi-pecahan-biasa",
      "2,25 Diubah Menjadi Pecahan Biasa",
      "",
      "2,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_099",
      "/decimal-pecahanBiasa/099-2,4-diubah-menjadi-pecahan-biasa",
      "2,4 Diubah Menjadi Pecahan Biasa",
      "",
      "2,4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_100",
      "/decimal-pecahanBiasa/100-2,5-diubah-menjadi-pecahan-biasa",
      "2,5 Diubah Menjadi Pecahan Biasa",
      "",
      "2,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_101",
      "/decimal-pecahanBiasa/101-2,6-diubah-menjadi-pecahan-biasa",
      "2,6 Diubah Menjadi Pecahan Biasa",
      "",
      "2,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_102",
      "/decimal-pecahanBiasa/102-2,8-diubah-menjadi-pecahan-biasa",
      "2,8 Diubah Menjadi Pecahan Biasa",
      "",
      "2,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_103",
      "/decimal-pecahanBiasa/103-2,35-diubah-menjadi-pecahan-biasa",
      "2,35 Diubah Menjadi Pecahan Biasa",
      "",
      "2,35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_104",
      "/decimal-pecahanBiasa/104-2,48-diubah-menjadi-pecahan-biasa",
      "2,48 Diubah Menjadi Pecahan Biasa",
      "",
      "2,48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_105",
      "/decimal-pecahanBiasa/105-2,68-diubah-menjadi-pecahan-biasa",
      "2,68 Diubah Menjadi Pecahan Biasa",
      "",
      "2,68 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_106",
      "/decimal-pecahanBiasa/106-2,75-diubah-menjadi-pecahan-biasa",
      "2,75 Diubah Menjadi Pecahan Biasa",
      "",
      "2,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_107",
      "/decimal-pecahanBiasa/107-2,375-diubah-menjadi-pecahan-biasa",
      "2,375 Diubah Menjadi Pecahan Biasa",
      "",
      "2,375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_108",
      "/decimal-pecahanBiasa/108-3,45-diubah-menjadi-pecahan-biasa",
      "3,45 Diubah Menjadi Pecahan Biasa",
      "",
      "3,45 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_109",
      "/decimal-pecahanBiasa/109-3,5-diubah-menjadi-pecahan-biasa",
      "3,5 Diubah Menjadi Pecahan Biasa",
      "",
      "3,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_110",
      "/decimal-pecahanBiasa/110-3,4-diubah-menjadi-pecahan-biasa",
      "3,4 Diubah Menjadi Pecahan Biasa",
      "",
      "3,4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_111",
      "/decimal-pecahanBiasa/111-3,6-diubah-menjadi-pecahan-biasa",
      "3,6 Diubah Menjadi Pecahan Biasa",
      "",
      "3,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_112",
      "/decimal-pecahanBiasa/112-3,8-diubah-menjadi-pecahan-biasa",
      "3,8 Diubah Menjadi Pecahan Biasa",
      "",
      "3,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_113",
      "/decimal-pecahanBiasa/113-3,3-diubah-menjadi-pecahan-biasa",
      "3,3 Diubah Menjadi Pecahan Biasa",
      "",
      "3,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_114",
      "/decimal-pecahanBiasa/114-3,75-diubah-menjadi-pecahan-biasa",
      "3,75 Diubah Menjadi Pecahan Biasa",
      "",
      "3,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_115",
      "/decimal-pecahanBiasa/115-3,25-diubah-menjadi-pecahan-biasa",
      "3,25 Diubah Menjadi Pecahan Biasa",
      "",
      "3,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_116",
      "/decimal-pecahanBiasa/116-3,42-diubah-menjadi-pecahan-biasa",
      "3,42 Diubah Menjadi Pecahan Biasa",
      "",
      "3,42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_117",
      "/decimal-pecahanBiasa/117-3,56-diubah-menjadi-pecahan-biasa",
      "3,56 Diubah Menjadi Pecahan Biasa",
      "",
      "3,56 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_118",
      "/decimal-pecahanBiasa/118-3,48-diubah-menjadi-pecahan-biasa",
      "3,48 Diubah Menjadi Pecahan Biasa",
      "",
      "3,48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_119",
      "/decimal-pecahanBiasa/119-3,65-diubah-menjadi-pecahan-biasa",
      "3,65 Diubah Menjadi Pecahan Biasa",
      "",
      "3,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_120",
      "/decimal-pecahanBiasa/120-3,70-diubah-menjadi-pecahan-biasa",
      "3,70 Diubah Menjadi Pecahan Biasa",
      "",
      "3,70 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_121",
      "/decimal-pecahanBiasa/121-4,2-diubah-menjadi-pecahan-biasa",
      "4,2 Diubah Menjadi Pecahan Biasa",
      "",
      "4,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_122",
      "/decimal-pecahanBiasa/122-4,5-diubah-menjadi-pecahan-biasa",
      "4,5 Diubah Menjadi Pecahan Biasa",
      "",
      "4,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_123",
      "/decimal-pecahanBiasa/123-4,6-diubah-menjadi-pecahan-biasa",
      "4,6 Diubah Menjadi Pecahan Biasa",
      "",
      "4,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_124",
      "/decimal-pecahanBiasa/124-4,8-diubah-menjadi-pecahan-biasa",
      "4,8 Diubah Menjadi Pecahan Biasa",
      "",
      "4,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_125",
      "/decimal-pecahanBiasa/125-4,7-diubah-menjadi-pecahan-biasa",
      "4,7 Diubah Menjadi Pecahan Biasa",
      "",
      "4,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_126",
      "/decimal-pecahanBiasa/126-4,75-diubah-menjadi-pecahan-biasa",
      "4,75 Diubah Menjadi Pecahan Biasa",
      "",
      "4,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_127",
      "/decimal-pecahanBiasa/127-4,68-diubah-menjadi-pecahan-biasa",
      "4,68 Diubah Menjadi Pecahan Biasa",
      "",
      "4,68 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_128",
      "/decimal-pecahanBiasa/128-4,65-diubah-menjadi-pecahan-biasa",
      "4,65 Diubah Menjadi Pecahan Biasa",
      "",
      "4,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_129",
      "/decimal-pecahanBiasa/129-4,375-diubah-menjadi-pecahan-biasa",
      "4,375 Diubah Menjadi Pecahan Biasa",
      "",
      "4,375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_130",
      "/decimal-pecahanBiasa/130-5,25-diubah-menjadi-pecahan-biasa",
      "5,25 Diubah Menjadi Pecahan Biasa",
      "",
      "5,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_131",
      "/decimal-pecahanBiasa/131-5,75-diubah-menjadi-pecahan-biasa",
      "5,75 Diubah Menjadi Pecahan Biasa",
      "",
      "5,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_132",
      "/decimal-pecahanBiasa/132-5,65-diubah-menjadi-pecahan-biasa",
      "5,65 Diubah Menjadi Pecahan Biasa",
      "",
      "5,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_133",
      "/decimal-pecahanBiasa/133-5,40-diubah-menjadi-pecahan-biasa",
      "5,40 Diubah Menjadi Pecahan Biasa",
      "",
      "5,40 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_134",
      "/decimal-pecahanBiasa/134-5,60-diubah-menjadi-pecahan-biasa",
      "5,60 Diubah Menjadi Pecahan Biasa",
      "",
      "5,60 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_135",
      "/decimal-pecahanBiasa/135-5,04-diubah-menjadi-pecahan-biasa",
      "5,04 Diubah Menjadi Pecahan Biasa",
      "",
      "5,04 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_136",
      "/decimal-pecahanBiasa/136-5,28-diubah-menjadi-pecahan-biasa",
      "5,28 Diubah Menjadi Pecahan Biasa",
      "",
      "5,28 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_137",
      "/decimal-pecahanBiasa/137-5,016-diubah-menjadi-pecahan-biasa",
      "5,016 Diubah Menjadi Pecahan Biasa",
      "",
      "5,016 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_138",
      "/decimal-pecahanBiasa/138-5,87-diubah-menjadi-pecahan-biasa",
      "5,87 Diubah Menjadi Pecahan Biasa",
      "",
      "5,87 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_139",
      "/decimal-pecahanBiasa/139-6,75-diubah-menjadi-pecahan-biasa",
      "6,75 Diubah Menjadi Pecahan Biasa",
      "",
      "6,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_140",
      "/decimal-pecahanBiasa/140-6,8-diubah-menjadi-pecahan-biasa",
      "6,8 Diubah Menjadi Pecahan Biasa",
      "",
      "6,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_141",
      "/decimal-pecahanBiasa/141-6,5-diubah-menjadi-pecahan-biasa",
      "6,5 Diubah Menjadi Pecahan Biasa",
      "",
      "6,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_142",
      "/decimal-pecahanBiasa/142-6,6-diubah-menjadi-pecahan-biasa",
      "6,6 Diubah Menjadi Pecahan Biasa",
      "",
      "6,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_143",
      "/decimal-pecahanBiasa/143-6,7-diubah-menjadi-pecahan-biasa",
      "6,7 Diubah Menjadi Pecahan Biasa",
      "",
      "6,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_144",
      "/decimal-pecahanBiasa/144-7,5-diubah-menjadi-pecahan-biasa",
      "7,5 Diubah Menjadi Pecahan Biasa",
      "",
      "7,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_145",
      "/decimal-pecahanBiasa/145-7,25-diubah-menjadi-pecahan-biasa",
      "7,25 Diubah Menjadi Pecahan Biasa",
      "",
      "7,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_146",
      "/decimal-pecahanBiasa/146-7,80-diubah-menjadi-pecahan-biasa",
      "7,80 Diubah Menjadi Pecahan Biasa",
      "",
      "7,80 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_147",
      "/decimal-pecahanBiasa/147-7,2-diubah-menjadi-pecahan-biasa",
      "7,2 Diubah Menjadi Pecahan Biasa",
      "",
      "7,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_148",
      "/decimal-pecahanBiasa/148-7,8-diubah-menjadi-pecahan-biasa",
      "7,8 Diubah Menjadi Pecahan Biasa",
      "",
      "7,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_149",
      "/decimal-pecahanBiasa/149-7,125-diubah-menjadi-pecahan-biasa",
      "7,125 Diubah Menjadi Pecahan Biasa",
      "",
      "7,125 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_150",
      "/decimal-pecahanBiasa/150-7,016-diubah-menjadi-pecahan-biasa",
      "7,016 Diubah Menjadi Pecahan Biasa",
      "",
      "7,016 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_151",
      "/decimal-pecahanBiasa/151-8,5-diubah-menjadi-pecahan-biasa",
      "8,5 Diubah Menjadi Pecahan Biasa",
      "",
      "8,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_152",
      "/decimal-pecahanBiasa/152-8,2-diubah-menjadi-pecahan-biasa",
      "8,2 Diubah Menjadi Pecahan Biasa",
      "",
      "8,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_153",
      "/decimal-pecahanBiasa/153-8,8-diubah-menjadi-pecahan-biasa",
      "8,8 Diubah Menjadi Pecahan Biasa",
      "",
      "8,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_154",
      "/decimal-pecahanBiasa/154-8,12-diubah-menjadi-pecahan-biasa",
      "8,12 Diubah Menjadi Pecahan Biasa",
      "",
      "8,12 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_155",
      "/decimal-pecahanBiasa/155-8,75-diubah-menjadi-pecahan-biasa",
      "8,75 Diubah Menjadi Pecahan Biasa",
      "",
      "8,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_156",
      "/decimal-pecahanBiasa/156-8,3-diubah-menjadi-pecahan-biasa",
      "8,3 Diubah Menjadi Pecahan Biasa",
      "",
      "8,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_157",
      "/decimal-pecahanBiasa/157-8,7-diubah-menjadi-pecahan-biasa",
      "8,7 Diubah Menjadi Pecahan Biasa",
      "",
      "8,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_158",
      "/decimal-pecahanBiasa/158-9,5-diubah-menjadi-pecahan-biasa",
      "9,5 Diubah Menjadi Pecahan Biasa",
      "",
      "9,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_159",
      "/decimal-pecahanBiasa/159-9,6-diubah-menjadi-pecahan-biasa",
      "9,6 Diubah Menjadi Pecahan Biasa",
      "",
      "9,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_160",
      "/decimal-pecahanBiasa/160-9,06-diubah-menjadi-pecahan-biasa",
      "9,06 Diubah Menjadi Pecahan Biasa",
      "",
      "9,06 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_161",
      "/decimal-pecahanBiasa/161-15,35-diubah-menjadi-pecahan-biasa",
      "15,35 Diubah Menjadi Pecahan Biasa",
      "",
      "15,35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_162",
      "/decimal-pecahanBiasa/162-90,25-diubah-menjadi-pecahan-biasa",
      "90,25 Diubah Menjadi Pecahan Biasa",
      "",
      "90,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_163",
      "/bagian/163-5per8-dari-240",
      "5/8 dari 240 = ... ?",
      "",
      "5/8 dari 240 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_164",
      "/bagian/164-5per8-dari-584",
      "5/8 dari 584 = ... ?",
      "",
      "5/8 dari 584 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_165",
      "/bagian/165-5per8-dari-65",
      "5/8 dari 65 = ... ?",
      "",
      "5/8 dari 65 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_166",
      "/bagian/166-5per8-dari-50",
      "5/8 dari 50 = ... ?",
      "",
      "5/8 dari 50 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_167",
      "/bagian/167-5per8-dari-40",
      "5/8 dari 40 = ... ?",
      "",
      "5/8 dari 40 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_168",
      "/bagian/168-1per2-dari-3",
      "1/2 dari 3 = ... ?",
      "",
      "1/2 dari 3 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_169",
      "/bagian/169-1per2-dari-4",
      "1/2 dari 4 = ... ?",
      "",
      "1/2 dari 4 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_170",
      "/bagian/170-1per2-dari-6",
      "1/2 dari 6 = ... ?",
      "",
      "1/2 dari 6 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_171",
      "/bagian/171-1per2-dari-7",
      "1/2 dari 7 = ... ?",
      "",
      "1/2 dari 7 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_172",
      "/bagian/172-1per2-dari-8",
      "1/2 dari 8 = ... ?",
      "",
      "1/2 dari 8 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_173",
      "/bagian/173-1per2-dari-12",
      "1/2 dari 12 = ... ?",
      "",
      "1/2 dari 12 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_174",
      "/bagian/174-1per2-dari-14",
      "1/2 dari 14 = ... ?",
      "",
      "1/2 dari 14 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_175",
      "/bagian/175-1per2-dari-16",
      "1/2 dari 16 = ... ?",
      "",
      "1/2 dari 16 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_176",
      "/bagian/176-1per2-dari-30",
      "1/2 dari 30 = ... ?",
      "",
      "1/2 dari 30 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_177",
      "/bagian/177-1per2-dari-50",
      "1/2 dari 50 = ... ?",
      "",
      "1/2 dari 50 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_178",
      "/bagian/178-1per2-dari-64",
      "1/2 dari 64 = ... ?",
      "",
      "1/2 dari 64 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_179",
      "/bagian/179-1per3-dari-9",
      "1/3 dari 9 = ... ?",
      "",
      "1/3 dari 9 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_180",
      "/bagian/180-1per3-dari-12",
      "1/3 dari 12 = ... ?",
      "",
      "1/3 dari 12 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_181",
      "/bagian/181-1per3-dari-15",
      "1/3 dari 15 = ... ?",
      "",
      "1/3 dari 15 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_182",
      "/bagian/182-1per3-dari-27",
      "1/3 dari 27 = ... ?",
      "",
      "1/3 dari 27 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_183",
      "/bagian/183-1per3-dari-36",
      "1/3 dari 36 = ... ?",
      "",
      "1/3 dari 36 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_184",
      "/bagian/184-1per3-dari-5",
      "1/3 dari 5 = ... ?",
      "",
      "1/3 dari 5 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_185",
      "/bagian/185-1per3-dari-10",
      "1/3 dari 10 = ... ?",
      "",
      "1/3 dari 10 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_186",
      "/bagian/186-1per3-dari-100",
      "1/3 dari 100 = ... ?",
      "",
      "1/3 dari 100 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_187",
      "/bagian/187-1per3-dari-1200",
      "1/3 dari 1200 = ... ?",
      "",
      "1/3 dari 1200 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_188",
      "/bagian/188-2per3-dari-5",
      "2/3 dari 5 = ... ?",
      "",
      "2/3 dari 5 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_189",
      "/bagian/189-2per3-dari-9",
      "2/3 dari 9 = ... ?",
      "",
      "2/3 dari 9 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_190",
      "/bagian/190-2per3-dari-10",
      "2/3 dari 10 = ... ?",
      "",
      "2/3 dari 10 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_191",
      "/bagian/191-2per3-dari-12",
      "2/3 dari 12 = ... ?",
      "",
      "2/3 dari 12 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_192",
      "/bagian/192-2per3-dari-15",
      "2/3 dari 15 = ... ?",
      "",
      "2/3 dari 15 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_193",
      "/bagian/193-2per3-dari-27",
      "2/3 dari 27 = ... ?",
      "",
      "2/3 dari 27 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_194",
      "/bagian/194-2per3-dari-36",
      "2/3 dari 36 = ... ?",
      "",
      "2/3 dari 36 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_195",
      "/bagian/195-2per3-dari-100",
      "2/3 dari 100 = ... ?",
      "",
      "2/3 dari 100 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_196",
      "/bagian/196-2per3-dari-1200",
      "2/3 dari 1200 = ... ?",
      "",
      "2/3 dari 1200 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_197",
      "/bagian/197-1per4-dari-8",
      "1/4 dari 8 = ... ?",
      "",
      "1/4 dari 8 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_198",
      "/bagian/198-1per4-dari-12",
      "1/4 dari 12 = ... ?",
      "",
      "1/4 dari 12 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_199",
      "/bagian/199-1per4-dari-20",
      "1/4 dari 20 = ... ?",
      "",
      "1/4 dari 20 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_200",
      "/bagian/200-1per4-dari-24",
      "1/4 dari 24 = ... ?",
      "",
      "1/4 dari 24 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_201",
      "/bagian/201-1per4-dari-40",
      "1/4 dari 40 = ... ?",
      "",
      "1/4 dari 40 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_202",
      "/bagian/202-1per4-dari-60",
      "1/4 dari 60 = ... ?",
      "",
      "1/4 dari 60 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_203",
      "/bagian/203-1per4-dari-100",
      "1/4 dari 100 = ... ?",
      "",
      "1/4 dari 100 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_204",
      "/bagian/204-1per4-dari-280",
      "1/4 dari 280 = ... ?",
      "",
      "1/4 dari 280 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_205",
      "/bagian/205-1per4-dari-100000",
      "1/4 dari 100.000 = ... ?",
      "",
      "1/4 dari 100.000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_206",
      "/bagian/206-3per4-dari-8",
      "3/4 dari 8 = ... ?",
      "",
      "3/4 dari 8 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_207",
      "/bagian/207-3per4-dari-12",
      "3/4 dari 12 = ... ?",
      "",
      "3/4 dari 12 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_208",
      "/bagian/208-3per4-dari-20",
      "3/4 dari 20 = ... ?",
      "",
      "3/4 dari 20 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_209",
      "/bagian/209-3per4-dari-24",
      "3/4 dari 24 = ... ?",
      "",
      "3/4 dari 24 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_210",
      "/bagian/210-3per4-dari-40",
      "3/4 dari 40 = ... ?",
      "",
      "3/4 dari 40 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_211",
      "/bagian/211-3per4-dari-60",
      "3/4 dari 60 = ... ?",
      "",
      "3/4 dari 60 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_212",
      "/bagian/212-3per4-dari-100",
      "3/4 dari 100 = ... ?",
      "",
      "3/4 dari 100 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_213",
      "/bagian/213-3per4-dari-280",
      "3/4 dari 280 = ... ?",
      "",
      "3/4 dari 280 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_214",
      "/bagian/214-3per4-dari-100000",
      "3/4 dari 100000 = ... ?",
      "",
      "3/4 dari 100000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_215",
      "/bagian/215-1per5-dari-500",
      "1/5 dari 500 = ... ?",
      "",
      "1/5 dari 500 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_216",
      "/bagian/216-1per5-dari-1-juta",
      "1/5 dari 1 juta = ... ?",
      "",
      "1/5 dari 1 juta ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_217",
      "/bagian/217-2per5-dari-25",
      "2/5 dari 25 = ... ?",
      "",
      "2/5 dari 25 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_218",
      "/bagian/218-2per5-dari-80",
      "2/5 dari 80 = ... ?",
      "",
      "2/5 dari 80 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_219",
      "/bagian/219-2per5-dari-100",
      "2/5 dari 100 = ... ?",
      "",
      "2/5 dari 100 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_220",
      "/bagian/220-2per5-dari-500",
      "2/5 dari 500 = ... ?",
      "",
      "2/5 dari 500 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_221",
      "/bagian/221-3per5-dari-15",
      "3/5 dari 15 = ... ?",
      "",
      "3/5 dari 15 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_222",
      "/bagian/222-3per5-dari-500000",
      "3/5 dari 500.000 = ... ?",
      "",
      "3/5 dari 500.000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_223",
      "/bagian/223-4per5-dari-45",
      "4/5 dari 45 = ... ?",
      "",
      "4/5 dari 45 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_224",
      "/bagian/224-3per6-dari-300",
      "3/6 dari 300 = ... ?",
      "",
      "3/6 dari 300 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_225",
      "/bagian/225-5per6-dari-12000",
      "5/6 dari 12000 = ... ?",
      "",
      "5/6 dari 12000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_226",
      "/bagian/226-1per7-dari-4914",
      "1/7 dari 4914 = ... ?",
      "",
      "1/7 dari 4914 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_227",
      "/bagian/227-2per7-dari-60",
      "2/7 dari 60 = ... ?",
      "",
      "2/7 dari 60 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_228",
      "/bagian/228-2per7-dari-588000",
      "2/7 dari 588000 = ... ?",
      "",
      "2/7 dari 588000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_229",
      "/bagian/229-3per7-dari-21",
      "3/7 dari 21 = ... ?",
      "",
      "3/7 dari 21 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_230",
      "/bagian/230-3per7-dari-84",
      "3/7 dari 84 = ... ?",
      "",
      "3/7 dari 84 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_231",
      "/bagian/231-4per7-dari-28",
      "4/7 dari 28 = ... ?",
      "",
      "4/7 dari 28 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_232",
      "/bagian/232-5per7-dari-49",
      "5/7 dari 49 = ... ?",
      "",
      "5/7 dari 49 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_233",
      "/bagian/233-5per7-dari-350000",
      "5/7 dari 350000 = ... ?",
      "",
      "5/7 dari 350000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_234",
      "/bagian/234-6per7-dari-87,5",
      "6/7 dari 87,5 = ... ?",
      "",
      "6/7 dari 87,5 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_235",
      "/bagian/235-6per7-dari-105",
      "6/7 dari 105 = ... ?",
      "",
      "6/7 dari 105 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_236",
      "/bagian/236-1per8-dari-10000",
      "1/8 dari 10000 = ... ?",
      "",
      "1/8 dari 10000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_237",
      "/bagian/237-2per8-dari-160",
      "2/8 dari 160 = ... ?",
      "",
      "2/8 dari 160 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_238",
      "/bagian/238-3per8-dari-40",
      "3/8 dari 40 = ... ?",
      "",
      "3/8 dari 40 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_239",
      "/bagian/239-3per8-dari-56",
      "3/8 dari 56 = ... ?",
      "",
      "3/8 dari 56 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_240",
      "/bagian/240-3per8-dari-12000",
      "3/8 dari 12000 = ... ?",
      "",
      "3/8 dari 12000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_241",
      "/bagian/241-6per9-dari-135",
      "6/9 dari 135 = ... ?",
      "",
      "6/9 dari 135 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_242",
      "/bagian/242-1per9-dari-81",
      "1/9 dari 81 = ... ?",
      "",
      "1/9 dari 81 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_243",
      "/bagian/243-7per8-dari-64",
      "7/8 dari 64 = ... ?",
      "",
      "7/8 dari 64 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_244",
      "/bagian/244-4per9-dari-36",
      "4/9 dari 36 = ... ?",
      "",
      "4/9 dari 36 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_245",
      "/bagian/245-4per9-dari-648",
      "4/9 dari 648 = ... ?",
      "",
      "4/9 dari 648 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_246",
      "/bagian/246-4per9-dari-45",
      "4/9 dari 45 = ... ?",
      "",
      "4/9 dari 45 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_247",
      "/bagian/247-4per9-dari-108",
      "4/9 dari 108 = ... ?",
      "",
      "4/9 dari 108 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_248",
      "/bagian/248-5per9-dari-261000",
      "5/9 dari 261000 = ... ?",
      "",
      "5/9 dari 261000 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_249",
      "/bagian/249-5per9-dari-1080",
      "5/9 dari 1080 = ... ?",
      "",
      "5/9 dari 1080 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_250",
      "/bagian/250-7per9-dari-819",
      "7/9 dari 819 = ... ?",
      "",
      "7/9 dari 819 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_251",
      "/bagian/251-7per9-dari-18",
      "7/9 dari 18 = ... ?",
      "",
      "7/9 dari 18 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_252",
      "/bagian/252-7per9-dari-36",
      "7/9 dari 36 = ... ?",
      "",
      "7/9 dari 36 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_253",
      "/bagian/253-7per9-dari-54",
      "7/9 dari 54 = ... ?",
      "",
      "7/9 dari 54 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_254",
      "/bagian/254-8per9-dari-5",
      "8/9 dari 5 = ... ?",
      "",
      "8/9 dari 5 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_255",
      "/bagian/255-3per10-dari-80",
      "3/10 dari 80 = ... ?",
      "",
      "3/10 dari 80 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_256",
      "/bagian/256-5per10-dari-300",
      "5/10 dari 300 = ... ?",
      "",
      "5/10 dari 300 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_257",
      "/bagian/257-5per10-dari-220",
      "5/10 dari 220 = ... ?",
      "",
      "5/10 dari 220 ? Berikut hasil beserta penjelasannya",
      ["Bagian"],
      "",
    ],
    [
      "pecahan_258",
      "/jumlah-pecahan/258-1-per-2-tambah-1-per-4",
      "1 per 2 + 1 per 4 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_259",
      "/jumlah-pecahan/259-1-per-2-tambah-3-per-4",
      "1 per 2 + 3 per 4 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_260",
      "/jumlah-pecahan/260-1-per-2-tambah-1-per-2",
      "1 per 2 + 1 per 2 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 2 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_261",
      "/jumlah-pecahan/261-1-per-2-tambah-1-per-3",
      "1 per 2 + 1 per 3 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_262",
      "/jumlah-pecahan/262-1-per-2-tambah-2-per-3",
      "1 per 2 + 2 per 3 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_263",
      "/jumlah-pecahan/263-1-per-2-tambah-5-per-6",
      "1 per 2 + 5 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_264",
      "/jumlah-pecahan/264-3-per-2-tambah-2-per-2",
      "3 per 2 + 2 per 2 = ... ?",
      "",
      "berapa 3 per 2 + 2 per 2 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_265",
      "/jumlah-pecahan/265-1-per-3-tambah-1-per-3",
      "1 per 3 + 1 per 3 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_266",
      "/jumlah-pecahan/266-1-per-3-tambah-1-per-4",
      "1 per 3 + 1 per 4 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_267",
      "/jumlah-pecahan/267-1-per-3-tambah-2-per-3",
      "1 per 3 + 2 per 3 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_268",
      "/jumlah-pecahan/268-1-per-3-tambah-2-per-5",
      "1 per 3 + 2 per 5 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_269",
      "/jumlah-pecahan/269-1-per-3-tambah-3-per-5",
      "1 per 3 + 3 per 5 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_270",
      "/jumlah-pecahan/270-1-per-3-tambah-2-per-6",
      "1 per 3 + 2 per 6 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_271",
      "/jumlah-pecahan/271-1-per-3-tambah-6-per-8",
      "1 per 3 + 6 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 6 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_272",
      "/jumlah-pecahan/272-2-per-3-tambah-1-per-3",
      "2 per 3 + 1 per 3 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_273",
      "/jumlah-pecahan/273-2-per-3-tambah-2-per-3",
      "2 per 3 + 2 per 3 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_274",
      "/jumlah-pecahan/274-2-per-3-tambah-1-per-4",
      "2 per 3 + 1 per 4 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_275",
      "/jumlah-pecahan/275-2-per-3-tambah-2-per-4",
      "2 per 3 + 2 per 4 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_276",
      "/jumlah-pecahan/276-2-per-3-tambah-3-per-4",
      "2 per 3 + 3 per 4 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_277",
      "/jumlah-pecahan/277-1-per-2-tambah-2-per-2",
      "1 per 2 + 2 per 2 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 2 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_278",
      "/jumlah-pecahan/278-1-per-2-tambah-3-per-3",
      "1 per 2 + 3 per 3 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 3 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_279",
      "/jumlah-pecahan/279-1-per-2-tambah-2-per-4",
      "1 per 2 + 2 per 4 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_280",
      "/jumlah-pecahan/280-1-per-2-tambah-4-per-4",
      "1 per 2 + 4 per 4 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_281",
      "/jumlah-pecahan/281-1-per-2-tambah-1-per-5",
      "1 per 2 + 1 per 5 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_282",
      "/jumlah-pecahan/282-1-per-2-tambah-2-per-5",
      "1 per 2 + 2 per 5 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_283",
      "/jumlah-pecahan/283-1-per-2-tambah-3-per-5",
      "1 per 2 + 3 per 5 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_284",
      "/jumlah-pecahan/284-1-per-2-tambah-4-per-5",
      "1 per 2 + 4 per 5 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_285",
      "/jumlah-pecahan/285-1-per-2-tambah-5-per-5",
      "1 per 2 + 5 per 5 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_286",
      "/jumlah-pecahan/286-1-per-2-tambah-1-per-6",
      "1 per 2 + 1 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_287",
      "/jumlah-pecahan/287-1-per-2-tambah-2-per-6",
      "1 per 2 + 2 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_288",
      "/jumlah-pecahan/288-1-per-2-tambah-3-per-6",
      "1 per 2 + 3 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_289",
      "/jumlah-pecahan/289-1-per-2-tambah-4-per-6",
      "1 per 2 + 4 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_290",
      "/jumlah-pecahan/290-1-per-2-tambah-6-per-6",
      "1 per 2 + 6 per 6 = ... ?",
      "",
      "berapa 1 per 2 + 6 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_291",
      "/jumlah-pecahan/291-1-per-2-tambah-1-per-7",
      "1 per 2 + 1 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_292",
      "/jumlah-pecahan/292-1-per-2-tambah-2-per-7",
      "1 per 2 + 2 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_293",
      "/jumlah-pecahan/293-1-per-2-tambah-3-per-7",
      "1 per 2 + 3 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_294",
      "/jumlah-pecahan/294-1-per-2-tambah-4-per-7",
      "1 per 2 + 4 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_295",
      "/jumlah-pecahan/295-1-per-2-tambah-5-per-7",
      "1 per 2 + 5 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_296",
      "/jumlah-pecahan/296-1-per-2-tambah-6-per-7",
      "1 per 2 + 6 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 6 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_297",
      "/jumlah-pecahan/297-1-per-2-tambah-7-per-7",
      "1 per 2 + 7 per 7 = ... ?",
      "",
      "berapa 1 per 2 + 7 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_298",
      "/jumlah-pecahan/298-1-per-2-tambah-1-per-8",
      "1 per 2 + 1 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_299",
      "/jumlah-pecahan/299-1-per-2-tambah-2-per-8",
      "1 per 2 + 2 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_300",
      "/jumlah-pecahan/300-1-per-2-tambah-3-per-8",
      "1 per 2 + 3 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_301",
      "/jumlah-pecahan/301-1-per-2-tambah-4-per-8",
      "1 per 2 + 4 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_302",
      "/jumlah-pecahan/302-1-per-2-tambah-5-per-8",
      "1 per 2 + 5 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_303",
      "/jumlah-pecahan/303-1-per-2-tambah-6-per-8",
      "1 per 2 + 6 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 6 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_304",
      "/jumlah-pecahan/304-1-per-2-tambah-7-per-8",
      "1 per 2 + 7 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 7 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_305",
      "/jumlah-pecahan/305-1-per-2-tambah-8-per-8",
      "1 per 2 + 8 per 8 = ... ?",
      "",
      "berapa 1 per 2 + 8 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_306",
      "/jumlah-pecahan/306-1-per-2-tambah-1-per-9",
      "1 per 2 + 1 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_307",
      "/jumlah-pecahan/307-1-per-2-tambah-2-per-9",
      "1 per 2 + 2 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_308",
      "/jumlah-pecahan/308-1-per-2-tambah-3-per-9",
      "1 per 2 + 3 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_309",
      "/jumlah-pecahan/309-1-per-2-tambah-4-per-9",
      "1 per 2 + 4 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_310",
      "/jumlah-pecahan/310-1-per-2-tambah-5-per-9",
      "1 per 2 + 5 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_311",
      "/jumlah-pecahan/311-1-per-2-tambah-6-per-9",
      "1 per 2 + 6 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 6 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_312",
      "/jumlah-pecahan/312-1-per-2-tambah-7-per-9",
      "1 per 2 + 7 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 7 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_313",
      "/jumlah-pecahan/313-1-per-2-tambah-8-per-9",
      "1 per 2 + 8 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 8 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_314",
      "/jumlah-pecahan/314-1-per-2-tambah-9-per-9",
      "1 per 2 + 9 per 9 = ... ?",
      "",
      "berapa 1 per 2 + 9 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_315",
      "/jumlah-pecahan/315-1-per-2-tambah-1-per-10",
      "1 per 2 + 1 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 1 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_316",
      "/jumlah-pecahan/316-1-per-2-tambah-2-per-10",
      "1 per 2 + 2 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 2 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_317",
      "/jumlah-pecahan/317-1-per-2-tambah-3-per-10",
      "1 per 2 + 3 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 3 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_318",
      "/jumlah-pecahan/318-1-per-2-tambah-4-per-10",
      "1 per 2 + 4 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 4 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_319",
      "/jumlah-pecahan/319-1-per-2-tambah-5-per-10",
      "1 per 2 + 5 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 5 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_320",
      "/jumlah-pecahan/320-1-per-2-tambah-6-per-10",
      "1 per 2 + 6 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 6 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_321",
      "/jumlah-pecahan/321-1-per-2-tambah-7-per-10",
      "1 per 2 + 7 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 7 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_322",
      "/jumlah-pecahan/322-1-per-2-tambah-8-per-10",
      "1 per 2 + 8 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 8 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_323",
      "/jumlah-pecahan/323-1-per-2-tambah-9-per-10",
      "1 per 2 + 9 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 9 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_324",
      "/jumlah-pecahan/324-1-per-2-tambah-10-per-10",
      "1 per 2 + 10 per 10 = ... ?",
      "",
      "berapa 1 per 2 + 10 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_325",
      "/jumlah-pecahan/325-1-per-3-tambah-1-per-2",
      "1 per 3 + 1 per 2 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 2 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_326",
      "/jumlah-pecahan/326-1-per-3-tambah-2-per-4",
      "1 per 3 + 2 per 4 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_327",
      "/jumlah-pecahan/327-1-per-3-tambah-3-per-4",
      "1 per 3 + 3 per 4 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 4 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_328",
      "/jumlah-pecahan/328-1-per-3-tambah-1-per-5",
      "1 per 3 + 1 per 5 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_329",
      "/jumlah-pecahan/329-1-per-3-tambah-4-per-5",
      "1 per 3 + 4 per 5 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_330",
      "/jumlah-pecahan/330-1-per-3-tambah-1-per-6",
      "1 per 3 + 1 per 6 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_331",
      "/jumlah-pecahan/331-1-per-3-tambah-3-per-6",
      "1 per 3 + 3 per 6 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_332",
      "/jumlah-pecahan/332-1-per-3-tambah-4-per-6",
      "1 per 3 + 4 per 6 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_333",
      "/jumlah-pecahan/333-1-per-3-tambah-5-per-6",
      "1 per 3 + 5 per 6 = ... ?",
      "",
      "berapa 1 per 3 + 5 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_334",
      "/jumlah-pecahan/334-1-per-3-tambah-1-per-7",
      "1 per 3 + 1 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_335",
      "/jumlah-pecahan/335-1-per-3-tambah-2-per-7",
      "1 per 3 + 2 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_336",
      "/jumlah-pecahan/336-1-per-3-tambah-3-per-7",
      "1 per 3 + 3 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_337",
      "/jumlah-pecahan/337-1-per-3-tambah-4-per-7",
      "1 per 3 + 4 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_338",
      "/jumlah-pecahan/338-1-per-3-tambah-5-per-7",
      "1 per 3 + 5 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 5 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_339",
      "/jumlah-pecahan/339-1-per-3-tambah-6-per-7",
      "1 per 3 + 6 per 7 = ... ?",
      "",
      "berapa 1 per 3 + 6 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_340",
      "/jumlah-pecahan/340-1-per-3-tambah-1-per-8",
      "1 per 3 + 1 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_341",
      "/jumlah-pecahan/341-1-per-3-tambah-2-per-8",
      "1 per 3 + 2 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_342",
      "/jumlah-pecahan/342-1-per-3-tambah-3-per-8",
      "1 per 3 + 3 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_343",
      "/jumlah-pecahan/343-1-per-3-tambah-4-per-8",
      "1 per 3 + 4 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_344",
      "/jumlah-pecahan/344-1-per-3-tambah-5-per-8",
      "1 per 3 + 5 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 5 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_345",
      "/jumlah-pecahan/345-1-per-3-tambah-7-per-8",
      "1 per 3 + 7 per 8 = ... ?",
      "",
      "berapa 1 per 3 + 7 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_346",
      "/jumlah-pecahan/346-1-per-3-tambah-1-per-9",
      "1 per 3 + 1 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_347",
      "/jumlah-pecahan/347-1-per-3-tambah-2-per-9",
      "1 per 3 + 2 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_348",
      "/jumlah-pecahan/348-1-per-3-tambah-3-per-9",
      "1 per 3 + 3 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_349",
      "/jumlah-pecahan/349-1-per-3-tambah-4-per-9",
      "1 per 3 + 4 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_350",
      "/jumlah-pecahan/350-1-per-3-tambah-5-per-9",
      "1 per 3 + 5 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 5 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_351",
      "/jumlah-pecahan/351-1-per-3-tambah-6-per-9",
      "1 per 3 + 6 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 6 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_352",
      "/jumlah-pecahan/352-1-per-3-tambah-7-per-9",
      "1 per 3 + 7 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 7 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_353",
      "/jumlah-pecahan/353-1-per-3-tambah-8-per-9",
      "1 per 3 + 8 per 9 = ... ?",
      "",
      "berapa 1 per 3 + 8 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_354",
      "/jumlah-pecahan/354-1-per-3-tambah-1-per-10",
      "1 per 3 + 1 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 1 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_355",
      "/jumlah-pecahan/355-1-per-3-tambah-2-per-10",
      "1 per 3 + 2 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 2 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_356",
      "/jumlah-pecahan/356-1-per-3-tambah-3-per-10",
      "1 per 3 + 3 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 3 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_357",
      "/jumlah-pecahan/357-1-per-3-tambah-4-per-10",
      "1 per 3 + 4 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 4 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_358",
      "/jumlah-pecahan/358-1-per-3-tambah-5-per-10",
      "1 per 3 + 5 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 5 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_359",
      "/jumlah-pecahan/359-1-per-3-tambah-6-per-10",
      "1 per 3 + 6 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 6 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_360",
      "/jumlah-pecahan/360-1-per-3-tambah-7-per-10",
      "1 per 3 + 7 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 7 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_361",
      "/jumlah-pecahan/361-1-per-3-tambah-8-per-10",
      "1 per 3 + 8 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 8 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_362",
      "/jumlah-pecahan/362-1-per-3-tambah-9-per-10",
      "1 per 3 + 9 per 10 = ... ?",
      "",
      "berapa 1 per 3 + 9 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_363",
      "/jumlah-pecahan/363-2-per-3-tambah-1-per-2",
      "2 per 3 + 1 per 2 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 2 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_364",
      "/jumlah-pecahan/364-2-per-3-tambah-1-per-5",
      "2 per 3 + 1 per 5 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_365",
      "/jumlah-pecahan/365-2-per-3-tambah-2-per-5",
      "2 per 3 + 2 per 5 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_366",
      "/jumlah-pecahan/366-2-per-3-tambah-3-per-5",
      "2 per 3 + 3 per 5 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_367",
      "/jumlah-pecahan/367-2-per-3-tambah-4-per-5",
      "2 per 3 + 4 per 5 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 5 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_368",
      "/jumlah-pecahan/368-2-per-3-tambah-1-per-6",
      "2 per 3 + 1 per 6 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_369",
      "/jumlah-pecahan/369-2-per-3-tambah-2-per-6",
      "2 per 3 + 2 per 6 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_370",
      "/jumlah-pecahan/370-2-per-3-tambah-3-per-6",
      "2 per 3 + 3 per 6 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_371",
      "/jumlah-pecahan/371-2-per-3-tambah-4-per-6",
      "2 per 3 + 4 per 6 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_372",
      "/jumlah-pecahan/372-2-per-3-tambah-5-per-6",
      "2 per 3 + 5 per 6 = ... ?",
      "",
      "berapa 2 per 3 + 5 per 6 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_373",
      "/jumlah-pecahan/373-2-per-3-tambah-1-per-7",
      "2 per 3 + 1 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_374",
      "/jumlah-pecahan/374-2-per-3-tambah-2-per-7",
      "2 per 3 + 2 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_375",
      "/jumlah-pecahan/375-2-per-3-tambah-3-per-7",
      "2 per 3 + 3 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_376",
      "/jumlah-pecahan/376-2-per-3-tambah-4-per-7",
      "2 per 3 + 4 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_377",
      "/jumlah-pecahan/377-2-per-3-tambah-5-per-7",
      "2 per 3 + 5 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 5 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_378",
      "/jumlah-pecahan/378-2-per-3-tambah-6-per-7",
      "2 per 3 + 6 per 7 = ... ?",
      "",
      "berapa 2 per 3 + 6 per 7 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_379",
      "/jumlah-pecahan/379-2-per-3-tambah-1-per-8",
      "2 per 3 + 1 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_380",
      "/jumlah-pecahan/380-2-per-3-tambah-2-per-8",
      "2 per 3 + 2 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_381",
      "/jumlah-pecahan/381-2-per-3-tambah-3-per-8",
      "2 per 3 + 3 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_382",
      "/jumlah-pecahan/382-2-per-3-tambah-4-per-8",
      "2 per 3 + 4 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_383",
      "/jumlah-pecahan/383-2-per-3-tambah-5-per-8",
      "2 per 3 + 5 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 5 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_384",
      "/jumlah-pecahan/384-2-per-3-tambah-6-per-8",
      "2 per 3 + 6 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 6 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_385",
      "/jumlah-pecahan/385-2-per-3-tambah-7-per-8",
      "2 per 3 + 7 per 8 = ... ?",
      "",
      "berapa 2 per 3 + 7 per 8 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_386",
      "/jumlah-pecahan/386-2-per-3-tambah-1-per-9",
      "2 per 3 + 1 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_387",
      "/jumlah-pecahan/387-2-per-3-tambah-2-per-9",
      "2 per 3 + 2 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_388",
      "/jumlah-pecahan/388-2-per-3-tambah-3-per-9",
      "2 per 3 + 3 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_389",
      "/jumlah-pecahan/389-2-per-3-tambah-4-per-9",
      "2 per 3 + 4 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_390",
      "/jumlah-pecahan/390-2-per-3-tambah-5-per-9",
      "2 per 3 + 5 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 5 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_391",
      "/jumlah-pecahan/391-2-per-3-tambah-6-per-9",
      "2 per 3 + 6 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 6 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_392",
      "/jumlah-pecahan/392-2-per-3-tambah-7-per-9",
      "2 per 3 + 7 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 7 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_393",
      "/jumlah-pecahan/393-2-per-3-tambah-8-per-9",
      "2 per 3 + 8 per 9 = ... ?",
      "",
      "berapa 2 per 3 + 8 per 9 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_394",
      "/jumlah-pecahan/394-2-per-3-tambah-1-per-10",
      "2 per 3 + 1 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 1 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_395",
      "/jumlah-pecahan/395-2-per-3-tambah-2-per-10",
      "2 per 3 + 2 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 2 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_396",
      "/jumlah-pecahan/396-2-per-3-tambah-3-per-10",
      "2 per 3 + 3 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 3 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_397",
      "/jumlah-pecahan/397-2-per-3-tambah-4-per-10",
      "2 per 3 + 4 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 4 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_398",
      "/jumlah-pecahan/398-2-per-3-tambah-5-per-10",
      "2 per 3 + 5 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 5 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_399",
      "/jumlah-pecahan/399-2-per-3-tambah-6-per-10",
      "2 per 3 + 6 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 6 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_400",
      "/jumlah-pecahan/400-2-per-3-tambah-7-per-10",
      "2 per 3 + 7 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 7 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_401",
      "/jumlah-pecahan/401-2-per-3-tambah-8-per-10",
      "2 per 3 + 8 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 8 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
    [
      "pecahan_402",
      "/jumlah-pecahan/402-2-per-3-tambah-9-per-10",
      "2 per 3 + 9 per 10 = ... ?",
      "",
      "berapa 2 per 3 + 9 per 10 ? Berikut hasil beserta penjelasannya",
      ["Jumlah Pecahan"],
      "",
    ],
];