var titleCat_1 = "Waktu";
var cat_1 = [
  ["Detik-Menit", "/detik-menit/001-300-detik-berapa-menit", ""],
  ["Menit-Jam", "/menit-jam/003-300-menit-berapa-jam", ""],
  ["Detik-Jam", "/detik-jam/004-300-detik-berapa-jam", ""],
  ["Jam-Hari", "/jam-hari/005-300-jam-berapa-hari", ""],
  ["Menit-Detik", "/menit-detik/035-3-menit-berapa-detik", ""],
  ["Jam-Detik", "/jam-detik/069-1-per-4-jam-berapa-detik", ""],
  ["Jam-Menit", "/jam-menit/073-1-jam-berapa-menit", ""],

  
];
var url_root = "https://nasrianas.website/jawab/math/waktu";
var footerArray = [
    //June2020
    [
      "Waktu_001",
      "/detik-menit/001-300-detik-berapa-menit",
      "300 Detik Berapa Menit ?",
      "",
      "300 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_002",
      "/detik-menit/002-500-detik-berapa-menit",
      "500 Detik Berapa Menit ?",
      "",
      "500 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_003",
      "/menit-jam/003-300-menit-berapa-jam",
      "300 Menit Berapa Jam ?",
      "",
      "300 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_004",
      "/detik-jam/004-300-detik-berapa-jam",
      "300 Detik Berapa Jam",
      "",
      "300 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Math_005",
      "/jam-hari/005-300-jam-berapa-hari",
      "300 Jam Berapa Hari",
      "",
      "300 Jam = ... Hari",
      ["Jam-Hari"],
      "",
    ],
    [
      "Waktu_006",
      "/menit-jam/006-500-menit-berapa-jam",
      "500 Menit Berapa Jam ?",
      "",
      "500 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_007",
      "/menit-jam/007-100-menit-berapa-jam",
      "100 Menit Berapa Jam ?",
      "",
      "100 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_008",
      "/menit-jam/008-1000-menit-berapa-jam",
      "1000 Menit Berapa Jam ?",
      "",
      "1000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_009",
      "/menit-jam/009-90-menit-berapa-jam",
      "90 Menit Berapa Jam ?",
      "",
      "90 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_010",
      "/menit-jam/010-120-menit-berapa-jam",
      "120 Menit Berapa Jam ?",
      "",
      "120 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_011",
      "/menit-jam/011-180-menit-berapa-jam",
      "180 Menit Berapa Jam ?",
      "",
      "180 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_012",
      "/menit-jam/012-60-menit-berapa-jam",
      "60 Menit Berapa Jam ?",
      "",
      "60 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_013",
      "/menit-jam/013-45-menit-berapa-jam",
      "45 Menit Berapa Jam ?",
      "",
      "45 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_014",
      "/menit-jam/014-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_015",
      "/menit-jam/015-20-menit-berapa-jam",
      "20 Menit Berapa Jam ?",
      "",
      "20 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_016",
      "/menit-jam/016-5-menit-berapa-jam",
      "5 Menit Berapa Jam ?",
      "",
      "5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_017",
      "/menit-jam/017-40-menit-berapa-jam",
      "40 Menit Berapa Jam ?",
      "",
      "40 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_018",
      "/menit-jam/018-30-menit-berapa-jam",
      "30 Menit Berapa Jam ?",
      "",
      "30 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_019",
      "/menit-jam/019-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_020",
      "/menit-jam/020-12-menit-berapa-jam",
      "12 Menit Berapa Jam ?",
      "",
      "12 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_021",
      "/menit-jam/021-10-menit-berapa-jam",
      "10 Menit Berapa Jam ?",
      "",
      "10 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_022",
      "/menit-jam/022-17-menit-berapa-jam",
      "17 Menit Berapa Jam ?",
      "",
      "17 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_023",
      "/detik-menit/023-720-detik-berapa-menit",
      "720 Detik Berapa Menit ?",
      "",
      "720 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_024",
      "/detik-menit/024-120-detik-berapa-menit",
      "120 Detik Berapa Menit ?",
      "",
      "120 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_025",
      "/detik-menit/025-480-detik-berapa-menit",
      "480 Detik Berapa Menit ?",
      "",
      "480 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_026",
      "/detik-menit/026-7200-detik-berapa-menit",
      "7200 Detik Berapa Menit ?",
      "",
      "7200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_027",
      "/detik-menit/027-600-detik-berapa-menit",
      "600 Detik Berapa Menit ?",
      "",
      "600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_028",
      "/detik-menit/028-180-detik-berapa-menit",
      "180 Detik Berapa Menit ?",
      "",
      "180 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_029",
      "/detik-menit/029-15-detik-berapa-menit",
      "15 Detik Berapa Menit ?",
      "",
      "15 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_030",
      "/detik-menit/030-6-detik-berapa-menit",
      "6 Detik Berapa Menit ?",
      "",
      "6 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_031",
      "/detik-menit/031-10-detik-berapa-menit",
      "10 Detik Berapa Menit ?",
      "",
      "10 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_032",
      "/detik-menit/032-8-detik-berapa-menit",
      "8 Detik Berapa Menit ?",
      "",
      "8 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_033",
      "/detik-menit/033-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_034",
      "/detik-menit/034-90-detik-berapa-menit",
      "90 Detik Berapa Menit ?",
      "",
      "90 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_035",
      "/menit-detik/035-3-menit-berapa-detik",
      "3 Menit Berapa Detik ?",
      "",
      "3 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_036",
      "/menit-detik/036-25-menit-berapa-detik",
      "25 Menit Berapa Detik ?",
      "",
      "25 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_037",
      "/menit-detik/037-5-menit-berapa-detik",
      "5 Menit Berapa Detik ?",
      "",
      "5 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_038",
      "/menit-detik/038-30-menit-berapa-detik",
      "30 Menit Berapa Detik ?",
      "",
      "30 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_039",
      "/menit-detik/039-10-menit-berapa-detik",
      "10 Menit Berapa Detik ?",
      "",
      "10 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_040",
      "/menit-detik/040-60-menit-berapa-detik",
      "60 Menit Berapa Detik ?",
      "",
      "60 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_041",
      "/menit-detik/041-15-menit-berapa-detik",
      "15 Menit Berapa Detik ?",
      "",
      "15 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_042",
      "/menit-detik/042-12-menit-berapa-detik",
      "12 Menit Berapa Detik ?",
      "",
      "12 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_043",
      "/menit-detik/043-20-menit-berapa-detik",
      "20 Menit Berapa Detik ?",
      "",
      "20 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_044",
      "/menit-detik/044-7-menit-berapa-detik",
      "7 Menit Berapa Detik ?",
      "",
      "7 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_045",
      "/menit-detik/045-0,1-menit-berapa-detik",
      "0.1 Menit Berapa Detik ?",
      "",
      "0,1 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_046",
      "/detik-jam/046-500-detik-berapa-jam",
      "500 Detik Berapa Jam ?",
      "",
      "500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_047",
      "/detik-jam/047-7200-detik-berapa-jam",
      "7200 Detik Berapa Jam ?",
      "",
      "7200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_048",
      "/detik-jam/048-1-detik-berapa-jam",
      "1 Detik Berapa Jam ?",
      "",
      "1 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_049",
      "/detik-jam/049-1800-detik-berapa-jam",
      "1800 Detik Berapa Jam ?",
      "",
      "1800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_050",
      "/detik-jam/050-600-detik-berapa-jam",
      "600 Detik Berapa Jam ?",
      "",
      "600 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_051",
      "/detik-jam/051-100-detik-berapa-jam",
      "100 Detik Berapa Jam ?",
      "",
      "100 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_052",
      "/detik-jam/052-10-detik-berapa-jam",
      "10 Detik Berapa Jam ?",
      "",
      "10 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_053",
      "/detik-jam/053-15-detik-berapa-jam",
      "15 Detik Berapa Jam ?",
      "",
      "15 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_054",
      "/detik-jam/054-60-detik-berapa-jam",
      "60 Detik Berapa Jam ?",
      "",
      "60 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_055",
      "/detik-jam/055-6-detik-berapa-jam",
      "6 Detik Berapa Jam ?",
      "",
      "6 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_056",
      "/jam-detik/056-2-jam-berapa-detik",
      "2 Jam Berapa Detik ?",
      "",
      "2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_057",
      "/jam-detik/057-1-jam-berapa-detik",
      "1 Jam Berapa Detik ?",
      "",
      "1 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_058",
      "/jam-detik/058-0,45-jam-berapa-detik",
      "0.45 Jam Berapa Detik ?",
      "",
      "0,45 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_059",
      "/jam-detik/059-3-jam-berapa-detik",
      "3 Jam Berapa Detik ?",
      "",
      "3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_060",
      "/jam-detik/060-0,5-jam-berapa-detik",
      "0.5 Jam Berapa Detik ?",
      "",
      "0,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_061",
      "/jam-detik/061-1-per-6-jam-berapa-detik",
      "1/6 Jam Berapa Detik ?",
      "",
      "1/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_062",
      "/jam-detik/062-1-per-60-jam-berapa-detik",
      "1/60 Jam Berapa Detik ?",
      "",
      "1/60 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_063",
      "/jam-detik/063-1,5-jam-berapa-detik",
      "1.5 Jam Berapa Detik ?",
      "",
      "1,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_064",
      "/jam-detik/064-24-jam-berapa-detik",
      "24 Jam Berapa Detik ?",
      "",
      "24 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_065",
      "/jam-detik/065-4-jam-berapa-detik",
      "4 Jam Berapa Detik ?",
      "",
      "4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_066",
      "/jam-detik/066-7-jam-berapa-detik",
      "7 Jam Berapa Detik ?",
      "",
      "7 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_067",
      "/jam-detik/067-6-jam-berapa-detik",
      "6 Jam Berapa Detik ?",
      "",
      "6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_068",
      "/jam-detik/068-12-jam-berapa-detik",
      "12 Jam Berapa Detik ?",
      "",
      "12 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_069",
      "/jam-detik/069-1-per-4-jam-berapa-detik",
      "1/4 Jam Berapa Detik ?",
      "",
      "1/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_070",
      "/jam-detik/070-1-per-3-jam-berapa-detik",
      "1/3 Jam Berapa Detik ?",
      "",
      "1/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_071",
      "/jam-detik/071-0,25-jam-berapa-detik",
      "0.25 Jam Berapa Detik ?",
      "",
      "0.25 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_072",
      "/jam-detik/072-2,5-jam-berapa-detik",
      "2.5 Jam Berapa Detik ?",
      "",
      "2.5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_073",
      "/jam-menit/073-1-jam-berapa-menit",
      "1 Jam Berapa Menit ?",
      "",
      "1 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_074",
      "/jam-menit/074-2-jam-berapa-menit",
      "2 Jam Berapa Menit ?",
      "",
      "2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_075",
      "/jam-menit/075-3-jam-berapa-menit",
      "3 Jam Berapa Menit ?",
      "",
      "3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_076",
      "/jam-menit/076-4-jam-berapa-menit",
      "4 Jam Berapa Menit ?",
      "",
      "4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_077",
      "/jam-menit/077-5-jam-berapa-menit",
      "5 Jam Berapa Menit ?",
      "",
      "5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_078",
      "/jam-menit/078-6-jam-berapa-menit",
      "6 Jam Berapa Menit ?",
      "",
      "6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_079",
      "/jam-menit/079-7-jam-berapa-menit",
      "7 Jam Berapa Menit ?",
      "",
      "7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_080",
      "/jam-menit/080-8-jam-berapa-menit",
      "8 Jam Berapa Menit ?",
      "",
      "8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_081",
      "/jam-menit/081-9-jam-berapa-menit",
      "9 Jam Berapa Menit ?",
      "",
      "9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_082",
      "/jam-menit/082-10-jam-berapa-menit",
      "10 Jam Berapa Menit ?",
      "",
      "10 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_083",
      "/jam-menit/083-11-jam-berapa-menit",
      "11 Jam Berapa Menit ?",
      "",
      "11 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_084",
      "/jam-menit/084-12-jam-berapa-menit",
      "12 Jam Berapa Menit ?",
      "",
      "12 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_085",
      "/jam-menit/085-13-jam-berapa-menit",
      "13 Jam Berapa Menit ?",
      "",
      "13 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_086",
      "/jam-menit/086-14-jam-berapa-menit",
      "14 Jam Berapa Menit ?",
      "",
      "14 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_087",
      "/jam-menit/087-15-jam-berapa-menit",
      "15 Jam Berapa Menit ?",
      "",
      "15 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_088",
      "/jam-menit/088-16-jam-berapa-menit",
      "16 Jam Berapa Menit ?",
      "",
      "16 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_089",
      "/jam-menit/089-17-jam-berapa-menit",
      "17 Jam Berapa Menit ?",
      "",
      "17 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_090",
      "/jam-menit/090-18-jam-berapa-menit",
      "18 Jam Berapa Menit ?",
      "",
      "18 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_091",
      "/jam-menit/091-19-jam-berapa-menit",
      "19 Jam Berapa Menit ?",
      "",
      "19 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_092",
      "/jam-menit/092-20-jam-berapa-menit",
      "20 Jam Berapa Menit ?",
      "",
      "20 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_093",
      "/jam-menit/093-21-jam-berapa-menit",
      "21 Jam Berapa Menit ?",
      "",
      "21 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_094",
      "/jam-menit/094-22-jam-berapa-menit",
      "22 Jam Berapa Menit ?",
      "",
      "22 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_095",
      "/jam-menit/095-23-jam-berapa-menit",
      "23 Jam Berapa Menit ?",
      "",
      "23 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_096",
      "/jam-menit/096-24-jam-berapa-menit",
      "24 Jam Berapa Menit ?",
      "",
      "24 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_097",
      "/jam-menit/097-0,5-jam-berapa-menit",
      "0,5 Jam Berapa Menit ?",
      "",
      "0,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_098",
      "/jam-menit/098-1,5-jam-berapa-menit",
      "1,5 Jam Berapa Menit ?",
      "",
      "1,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_099",
      "/jam-menit/099-2,5-jam-berapa-menit",
      "2,5 Jam Berapa Menit ?",
      "",
      "2,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_100",
      "/jam-menit/100-1,2-jam-berapa-menit",
      "1,2 Jam Berapa Menit ?",
      "",
      "1,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_101",
      "/jam-menit/101-1,6-jam-berapa-menit",
      "1,6 Jam Berapa Menit ?",
      "",
      "1,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_102",
      "/jam-menit/102-1,25-jam-berapa-menit",
      "1,25 Jam Berapa Menit ?",
      "",
      "1,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_103",
      "/jam-menit/103-5,6-jam-berapa-menit",
      "5,6 Jam Berapa Menit ?",
      "",
      "5,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_104",
      "/jam-menit/104-1per2-jam-berapa-menit",
      "1/2 Jam Berapa Menit ?",
      "",
      "1/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_105",
      "/jam-menit/105-1per6-jam-berapa-menit",
      "1/6 Jam Berapa Menit ?",
      "",
      "1/6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_106",
      "/jam-menit/106-4000-jam-berapa-menit",
      "4000 Jam Berapa Menit ?",
      "",
      "4000 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_107",
      "/detik-menit/107-3600-detik-berapa-menit",
      "3600 Detik Berapa Menit ?",
      "",
      "3600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_108",
      "/detik-menit/108-1000-detik-berapa-menit",
      "1000 Detik Berapa Menit ?",
      "",
      "1000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_109",
      "/detik-menit/109-270-detik-berapa-menit",
      "270 Detik Berapa Menit ?",
      "",
      "270 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_110",
      "/detik-menit/110-230-detik-berapa-menit",
      "230 Detik Berapa Menit ?",
      "",
      "230 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_111",
      "/detik-menit/111-5000-detik-berapa-menit",
      "5000 Detik Berapa Menit ?",
      "",
      "5000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_112",
      "/detik-menit/112-200-detik-berapa-menit",
      "200 Detik Berapa Menit ?",
      "",
      "200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_113",
      "/detik-menit/113-1200-detik-berapa-menit",
      "1200 Detik Berapa Menit ?",
      "",
      "1200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_114",
      "/detik-menit/114-2400-detik-berapa-menit",
      "2400 Detik Berapa Menit ?",
      "",
      "2400 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_115",
      "/detik-menit/115-420-detik-berapa-menit",
      "420 Detik Berapa Menit ?",
      "",
      "420 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_116",
      "/detik-menit/116-4200-detik-berapa-menit",
      "4200 Detik Berapa Menit ?",
      "",
      "4200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_117",
      "/detik-menit/117-360-detik-berapa-menit",
      "360 Detik Berapa Menit ?",
      "",
      "360 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_118",
      "/detik-menit/118-20-detik-berapa-menit",
      "20 Detik Berapa Menit ?",
      "",
      "20 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_119",
      "/detik-menit/119-30-detik-berapa-menit",
      "30 Detik Berapa Menit ?",
      "",
      "30 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_120",
      "/detik-menit/120-5-detik-berapa-menit",
      "5 Detik Berapa Menit ?",
      "",
      "5 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_121",
      "/detik-menit/121-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_122",
      "/detik-jam/122-1,5-detik-berapa-jam",
      "1,5 Detik Berapa Jam ?",
      "",
      "1,5 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_123",
      "/detik-jam/123-1-juta-detik-berapa-jam",
      "1 juta Detik Berapa Jam ?",
      "",
      "1 juta Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_124",
      "/detik-jam/124-10800-detik-berapa-jam",
      "10.800 Detik Berapa Jam ?",
      "",
      "10.800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_125",
      "/detik-jam/125-1000-detik-berapa-jam",
      "1000 Detik Berapa Jam ?",
      "",
      "1000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_126",
      "/detik-jam/126-120-detik-berapa-jam",
      "120 Detik Berapa Jam ?",
      "",
      "120 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_127",
      "/detik-jam/127-18000-detik-berapa-jam",
      "18000 Detik Berapa Jam ?",
      "",
      "18000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_128",
      "/detik-jam/128-2-detik-berapa-jam",
      "2 Detik Berapa Jam ?",
      "",
      "2 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_129",
      "/detik-jam/129-20-detik-berapa-jam",
      "20 Detik Berapa Jam ?",
      "",
      "20 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_130",
      "/detik-jam/130-200-detik-berapa-jam",
      "200 Detik Berapa Jam ?",
      "",
      "200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_131",
      "/detik-jam/131-2000-detik-berapa-jam",
      "2000 Detik Berapa Jam ?",
      "",
      "2000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_132",
      "/detik-jam/132-2400-detik-berapa-jam",
      "2400 Detik Berapa Jam ?",
      "",
      "2400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_133",
      "/detik-jam/133-25200-detik-berapa-jam",
      "25.200 Detik Berapa Jam ?",
      "",
      "25.200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_134",
      "/detik-jam/134-2700-detik-berapa-jam",
      "2700 Detik Berapa Jam ?",
      "",
      "2700 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_135",
      "/detik-jam/135-3600-detik-berapa-jam",
      "3.600 Detik Berapa Jam ?",
      "",
      "3.600 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_136",
      "/detik-jam/136-30-detik-berapa-jam",
      "30 Detik Berapa Jam ?",
      "",
      "30 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_137",
      "/detik-jam/137-3000-detik-berapa-jam",
      "3000 Detik Berapa Jam ?",
      "",
      "3000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_138",
      "/detik-jam/138-3200-detik-berapa-jam",
      "3200 Detik Berapa Jam ?",
      "",
      "3200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_139",
      "/detik-jam/139-3500-detik-berapa-jam",
      "3500 Detik Berapa Jam ?",
      "",
      "3500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_140",
      "/detik-jam/140-360-detik-berapa-jam",
      "360 Detik Berapa Jam ?",
      "",
      "360 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_141",
      "/detik-jam/141-36000-detik-berapa-jam",
      "36000 Detik Berapa Jam ?",
      "",
      "36000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_142",
      "/detik-jam/142-40-detik-berapa-jam",
      "40 Detik Berapa Jam ?",
      "",
      "40 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_143",
      "/detik-jam/143-400-detik-berapa-jam",
      "400 Detik Berapa Jam ?",
      "",
      "400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_144",
      "/detik-jam/144-4000-detik-berapa-jam",
      "4000 Detik Berapa Jam ?",
      "",
      "4000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_145",
      "/detik-jam/145-4200-detik-berapa-jam",
      "4200 Detik Berapa Jam ?",
      "",
      "4200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_146",
      "/detik-jam/146-45-detik-berapa-jam",
      "45 Detik Berapa Jam ?",
      "",
      "45 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_147",
      "/detik-jam/147-4500-detik-berapa-jam",
      "4500 Detik Berapa Jam ?",
      "",
      "4500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_148",
      "/detik-jam/148-480-detik-berapa-jam",
      "480 Detik Berapa Jam ?",
      "",
      "480 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_149",
      "/detik-jam/149-4800-detik-berapa-jam",
      "4800 Detik Berapa Jam ?",
      "",
      "4800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_150",
      "/detik-jam/150-5-detik-berapa-jam",
      "5 Detik Berapa Jam ?",
      "",
      "5 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_151",
      "/detik-jam/151-5550-detik-berapa-jam",
      "5.550 Detik Berapa Jam ?",
      "",
      "5.550 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_152",
      "/detik-jam/152-50-detik-berapa-jam",
      "50 Detik Berapa Jam ?",
      "",
      "50 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_153",
      "/detik-jam/153-5000-detik-berapa-jam",
      "5000 Detik Berapa Jam ?",
      "",
      "5000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_154",
      "/detik-jam/154-50000-detik-berapa-jam",
      "50000 Detik Berapa Jam ?",
      "",
      "50000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_155",
      "/detik-jam/155-5400-detik-berapa-jam",
      "5400 Detik Berapa Jam ?",
      "",
      "5400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_156",
      "/detik-jam/156-5500-detik-berapa-jam",
      "5500 Detik Berapa Jam ?",
      "",
      "5500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_157",
      "/detik-jam/157-6000-detik-berapa-jam",
      "6000 Detik Berapa Jam ?",
      "",
      "6000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_158",
      "/detik-jam/158-60000-detik-berapa-jam",
      "60000 Detik Berapa Jam ?",
      "",
      "60000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_159",
      "/detik-jam/159-7200-detik-berapa-jam",
      "7.200 Detik Berapa Jam ?",
      "",
      "7.200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_160",
      "/detik-jam/160-700-detik-berapa-jam",
      "700 Detik Berapa Jam ?",
      "",
      "700 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_161",
      "/detik-jam/161-7000-detik-berapa-jam",
      "7000 Detik Berapa Jam ?",
      "",
      "7000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_162",
      "/detik-jam/162-72-detik-berapa-jam",
      "72 Detik Berapa Jam ?",
      "",
      "72 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_163",
      "/detik-jam/163-720-detik-berapa-jam",
      "720 Detik Berapa Jam ?",
      "",
      "720 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_164",
      "/detik-jam/164-72000-detik-berapa-jam",
      "72000 Detik Berapa Jam ?",
      "",
      "72000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_165",
      "/detik-jam/165-7220-detik-berapa-jam",
      "7220 Detik Berapa Jam ?",
      "",
      "7220 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_166",
      "/detik-jam/166-7260-detik-berapa-jam",
      "7260 Detik Berapa Jam ?",
      "",
      "7260 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_167",
      "/detik-jam/167-7500-detik-berapa-jam",
      "7500 Detik Berapa Jam ?",
      "",
      "7500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_168",
      "/detik-jam/168-8100-detik-berapa-jam",
      "8.100 Detik Berapa Jam ?",
      "",
      "8.100 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_169",
      "/detik-jam/169-800-detik-berapa-jam",
      "800 Detik Berapa Jam ?",
      "",
      "800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_170",
      "/detik-jam/170-8000-detik-berapa-jam",
      "8000 Detik Berapa Jam ?",
      "",
      "8000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_171",
      "/detik-jam/171-8400-detik-berapa-jam",
      "8400 Detik Berapa Jam ?",
      "",
      "8400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_172",
      "/detik-jam/172-86400-detik-berapa-jam",
      "86400 Detik Berapa Jam ?",
      "",
      "86400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_173",
      "/detik-jam/173-9325-detik-berapa-jam",
      "9.325 Detik Berapa Jam ?",
      "",
      "9.325 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_174",
      "/detik-jam/174-90-detik-berapa-jam",
      "90 Detik Berapa Jam ?",
      "",
      "90 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_175",
      "/detik-jam/175-90000-detik-berapa-jam",
      "90.000 Detik Berapa Jam ?",
      "",
      "90.000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_176",
      "/detik-jam/176-900-detik-berapa-jam",
      "900 Detik Berapa Jam ?",
      "",
      "900 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_177",
      "/detik-jam/177-9000-detik-berapa-jam",
      "9000 Detik Berapa Jam ?",
      "",
      "9000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_178",
      "/detik-jam/178-9300-detik-berapa-jam",
      "9300 Detik Berapa Jam ?",
      "",
      "9300 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_179",
      "/detik-jam/179-999-detik-berapa-jam",
      "999 Detik Berapa Jam ?",
      "",
      "999 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_180",
      "/jam-detik/180-0,2-jam-berapa-detik",
      "0,2 Jam Berapa Detik ?",
      "",
      "0,2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_181",
      "/jam-detik/181-0,4-jam-berapa-detik",
      "0,4 Jam Berapa Detik ?",
      "",
      "0,4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_182",
      "/jam-detik/182-0,3-jam-berapa-detik",
      "0,3 Jam Berapa Detik ?",
      "",
      "0,3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_183",
      "/jam-detik/183-0,5-jam-berapa-detik",
      "0,5 Jam Berapa Detik ?",
      "",
      "0,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_184",
      "/jam-detik/184-0,7-jam-berapa-detik",
      "0,7 Jam Berapa Detik ?",
      "",
      "0,7 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_185",
      "/jam-detik/185-0,75-jam-berapa-detik",
      "0,75 Jam Berapa Detik ?",
      "",
      "0,75 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_186",
      "/jam-detik/186-1,25-jam-berapa-detik",
      "1,25 Jam Berapa Detik ?",
      "",
      "1,25 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_187",
      "/jam-detik/187-1,75-jam-berapa-detik",
      "1,75 Jam Berapa Detik ?",
      "",
      "1,75 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_188",
      "/jam-detik/188-1,8-jam-berapa-detik",
      "1,8 Jam Berapa Detik ?",
      "",
      "1,8 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_189",
      "/jam-detik/189-10-jam-berapa-detik",
      "10 Jam Berapa Detik ?",
      "",
      "10 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_190",
      "/jam-detik/190-11-jam-berapa-detik",
      "11 Jam Berapa Detik ?",
      "",
      "11 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_191",
      "/jam-detik/191-13-jam-berapa-detik",
      "13 Jam Berapa Detik ?",
      "",
      "13 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_192",
      "/jam-detik/192-2,4-jam-berapa-detik",
      "2,4 Jam Berapa Detik ?",
      "",
      "2,4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_193",
      "/jam-detik/193-2-setengah-jam-berapa-detik",
      "2 setengah Jam Berapa Detik ?",
      "",
      "2 setengah Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_194",
      "/jam-detik/194-20-jam-berapa-detik",
      "20 Jam Berapa Detik ?",
      "",
      "20 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_195",
      "/jam-detik/195-3,5-jam-berapa-detik",
      "3,5 Jam Berapa Detik ?",
      "",
      "3,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_196",
      "/jam-detik/196-3,6-jam-berapa-detik",
      "3,6 Jam Berapa Detik ?",
      "",
      "3,6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_197",
      "/jam-detik/197-30-jam-berapa-detik",
      "30 Jam Berapa Detik ?",
      "",
      "30 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_198",
      "/jam-detik/198-36-jam-berapa-detik",
      "36 Jam Berapa Detik ?",
      "",
      "36 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_199",
      "/jam-detik/199-4,5-jam-berapa-detik",
      "4,5 Jam Berapa Detik ?",
      "",
      "4,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_200",
      "/jam-detik/200-40-jam-berapa-detik",
      "40 Jam Berapa Detik ?",
      "",
      "40 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_201",
      "/jam-detik/201-4000-jam-berapa-detik",
      "4000 Jam Berapa Detik ?",
      "",
      "4000 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_202",
      "/jam-detik/202-48-jam-berapa-detik",
      "48 Jam Berapa Detik ?",
      "",
      "48 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_203",
      "/jam-detik/203-5-jam-berapa-detik",
      "5 Jam Berapa Detik ?",
      "",
      "5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_204",
      "/jam-detik/204-72-jam-berapa-detik",
      "72 Jam Berapa Detik ?",
      "",
      "72 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_205",
      "/jam-detik/205-8,5-jam-berapa-detik",
      "8,5 Jam Berapa Detik ?",
      "",
      "8,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_206",
      "/jam-detik/206-8-jam-berapa-detik",
      "8 Jam Berapa Detik ?",
      "",
      "8 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_207",
      "/jam-detik/207-9-jam-berapa-detik",
      "9 Jam Berapa Detik ?",
      "",
      "9 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_208",
      "/jam-detik/208-1per2-jam-berapa-detik",
      "1/2 Jam Berapa Detik ?",
      "",
      "1/2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_209",
      "/jam-detik/209-1per3-jam-berapa-detik",
      "1/3 Jam Berapa Detik ?",
      "",
      "1/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_210",
      "/jam-detik/210-1per4-jam-berapa-detik",
      "1/4 Jam Berapa Detik ?",
      "",
      "1/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_211",
      "/jam-detik/211-1per6-jam-berapa-detik",
      "1/6 Jam Berapa Detik ?",
      "",
      "1/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_212",
      "/jam-detik/212-2per5-jam-berapa-detik",
      "2/5 Jam Berapa Detik ?",
      "",
      "2/5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_213",
      "/jam-detik/213-2per3-jam-berapa-detik",
      "2/3 Jam Berapa Detik ?",
      "",
      "2/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_214",
      "/jam-detik/214-3per4-jam-berapa-detik",
      "3/4 Jam Berapa Detik ?",
      "",
      "3/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_215",
      "/jam-detik/215-5per6-jam-berapa-detik",
      "5/6 Jam Berapa Detik ?",
      "",
      "5/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_216",
      "/jam-detik/216-2per5-jam-berapa-detik",
      "2 per 5 Jam Berapa Detik ?",
      "",
      "2 per 5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_217",
      "/jam-detik/217-3per4-jam-berapa-detik",
      "3 per 4 Jam Berapa Detik ?",
      "",
      "3 per 4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_218",
      "/jam-menit/218-0,1-jam-berapa-menit",
      "0,1 Jam Berapa Menit ?",
      "",
      "0,1 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_219",
      "/jam-menit/219-0,2-jam-berapa-menit",
      "0,2 Jam Berapa Menit ?",
      "",
      "0,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_220",
      "/jam-menit/220-0,25-jam-berapa-menit",
      "0,25 Jam Berapa Menit ?",
      "",
      "0,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_221",
      "/jam-menit/221-0,3-jam-berapa-menit",
      "0,3 Jam Berapa Menit ?",
      "",
      "0,3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_222",
      "/jam-menit/222-0,4-jam-berapa-menit",
      "0,4 Jam Berapa Menit ?",
      "",
      "0,4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_223",
      "/jam-menit/223-0,6-jam-berapa-menit",
      "0,6 Jam Berapa Menit ?",
      "",
      "0,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_224",
      "/jam-menit/224-0,7-jam-berapa-menit",
      "0,7 Jam Berapa Menit ?",
      "",
      "0,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_225",
      "/jam-menit/225-0,75-jam-berapa-menit",
      "0,75 Jam Berapa Menit ?",
      "",
      "0,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_226",
      "/jam-menit/226-0,8-jam-berapa-menit",
      "0,8 Jam Berapa Menit ?",
      "",
      "0,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_227",
      "/jam-menit/227-0,9-jam-berapa-menit",
      "0,9 Jam Berapa Menit ?",
      "",
      "0,9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_228",
      "/jam-menit/228-1,7-jam-berapa-menit",
      "1,7 Jam Berapa Menit ?",
      "",
      "1,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_229",
      "/jam-menit/229-1,75-jam-berapa-menit",
      "1,75 Jam Berapa Menit ?",
      "",
      "1,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_230",
      "/jam-menit/230-1000-jam-berapa-menit",
      "1000 Jam Berapa Menit ?",
      "",
      "1000 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_231",
      "/jam-menit/231-2,4-jam-berapa-menit",
      "2,4 Jam Berapa Menit ?",
      "",
      "2,4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_232",
      "/jam-menit/232-2,6-jam-berapa-menit",
      "2,6 Jam Berapa Menit ?",
      "",
      "2,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_233",
      "/jam-menit/233-2,7-jam-berapa-menit",
      "2,7 Jam Berapa Menit ?",
      "",
      "2,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_234",
      "/jam-menit/234-2,8-jam-berapa-menit",
      "2,8 Jam Berapa Menit ?",
      "",
      "2,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_235",
      "/jam-menit/235-3,5-jam-berapa-menit",
      "3,5 Jam Berapa Menit ?",
      "",
      "3,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_236",
      "/jam-menit/236-3,6-jam-berapa-menit",
      "3,6 Jam Berapa Menit ?",
      "",
      "3,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_237",
      "/jam-menit/237-3,2-jam-berapa-menit",
      "3,2 Jam Berapa Menit ?",
      "",
      "3,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_238",
      "/jam-menit/238-3,75-jam-berapa-menit",
      "3,75 Jam Berapa Menit ?",
      "",
      "3,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_239",
      "/jam-menit/239-4,5-jam-berapa-menit",
      "4,5 Jam Berapa Menit ?",
      "",
      "4,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_240",
      "/jam-menit/240-4,6-jam-berapa-menit",
      "4,6 Jam Berapa Menit ?",
      "",
      "4,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_241",
      "/jam-menit/241-4,8-jam-berapa-menit",
      "4,8 Jam Berapa Menit ?",
      "",
      "4,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_242",
      "/jam-menit/242-5,25-jam-berapa-menit",
      "5,25 Jam Berapa Menit ?",
      "",
      "5,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_243",
      "/jam-menit/243-5,5-jam-berapa-menit",
      "5,5 Jam Berapa Menit ?",
      "",
      "5,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_244",
      "/jam-menit/244-6,25-jam-berapa-menit",
      "6,25 Jam Berapa Menit ?",
      "",
      "6,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_245",
      "/jam-menit/245-7,5-jam-berapa-menit",
      "7,5 Jam Berapa Menit ?",
      "",
      "7,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_246",
      "/jam-menit/246-8,5-jam-berapa-menit",
      "8,5 Jam Berapa Menit ?",
      "",
      "8,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_247",
      "/jam-menit/247-30-jam-berapa-menit",
      "30 Jam Berapa Menit ?",
      "",
      "30 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_248",
      "/jam-menit/248-360-jam-berapa-menit",
      "360 Jam Berapa Menit ?",
      "",
      "360 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_249",
      "/jam-menit/249-40-jam-berapa-menit",
      "40 Jam Berapa Menit ?",
      "",
      "40 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_250",
      "/jam-menit/250-400-jam-berapa-menit",
      "400 Jam Berapa Menit ?",
      "",
      "400 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_251",
      "/jam-menit/251-48-jam-berapa-menit",
      "48 Jam Berapa Menit ?",
      "",
      "48 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_252",
      "/jam-menit/252-4-ribu-jam-berapa-menit",
      "4 ribu Jam Berapa Menit ?",
      "",
      "4 ribu Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_253",
      "/jam-menit/253-50-jam-berapa-menit",
      "50 Jam Berapa Menit ?",
      "",
      "50 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_254",
      "/jam-menit/254-500-jam-berapa-menit",
      "500 Jam Berapa Menit ?",
      "",
      "500 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_255",
      "/jam-menit/255-60-jam-berapa-menit",
      "60 Jam Berapa Menit ?",
      "",
      "60 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_256",
      "/jam-menit/256-600-jam-berapa-menit",
      "600 Jam Berapa Menit ?",
      "",
      "600 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_257",
      "/jam-menit/257-72-jam-berapa-menit",
      "72 Jam Berapa Menit ?",
      "",
      "72 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_258",
      "/jam-menit/258-720-jam-berapa-menit",
      "720 Jam Berapa Menit ?",
      "",
      "720 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_259",
      "/jam-menit/259-90-jam-berapa-menit",
      "90 Jam Berapa Menit ?",
      "",
      "90 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_260",
      "/jam-menit/260-96-jam-berapa-menit",
      "96 Jam Berapa Menit ?",
      "",
      "96 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_261",
      "/jam-menit/261-empat-jam-berapa-menit",
      "Empat Jam Berapa Menit ?",
      "",
      "Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_262",
      "/jam-menit/262-empat-setengah-jam-berapa-menit",
      "Empat Setengah Jam Berapa Menit ?",
      "",
      "Empat Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_263",
      "/jam-menit/263-lima-jam-berapa-menit",
      "Lima Jam Berapa Menit ?",
      "",
      "Lima Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_264",
      "/jam-menit/264-satu-jam-berapa-menit",
      "Satu Jam Berapa Menit ?",
      "",
      "Satu Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_265",
      "/jam-menit/265-satu-per-empat-jam-berapa-menit",
      "Satu per Empat Jam Berapa Menit ?",
      "",
      "Satu per Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_266",
      "/jam-menit/266-satu-per-enam-jam-berapa-menit",
      "Satu per Enam Jam Berapa Menit ?",
      "",
      "Satu per Enam Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_267",
      "/jam-menit/267-satu-setengah-jam-berapa-menit",
      "Satu Setengah Jam Berapa Menit ?",
      "",
      "Satu Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_268",
      "/jam-menit/268-seperdua-jam-berapa-menit",
      "Seperdua Jam Berapa Menit ?",
      "",
      "Seperdua Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_269",
      "/jam-menit/269-seperempat-jam-berapa-menit",
      "Seperempat Jam Berapa Menit ?",
      "",
      "Seperempat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_270",
      "/jam-menit/270-seperenam-jam-berapa-menit",
      "Seperenam Jam Berapa Menit ?",
      "",
      "Seperenam Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_271",
      "/jam-menit/271-seperlima-jam-berapa-menit",
      "Seperlima Jam Berapa Menit ?",
      "",
      "Seperlima Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_272",
      "/jam-menit/272-sepertiga-jam-berapa-menit",
      "Sepertiga Jam Berapa Menit ?",
      "",
      "Sepertiga Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_273",
      "/jam-menit/273-setengah-jam-berapa-menit",
      "Setengah Jam Berapa Menit ?",
      "",
      "Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_274",
      "/jam-menit/274-tiga-jam-berapa-menit",
      "Tiga Jam Berapa Menit ?",
      "",
      "Tiga Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_275",
      "/jam-menit/275-tiga-perempat-jam-berapa-menit",
      "Tiga Perempat Jam Berapa Menit ?",
      "",
      "Tiga Perempat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_276",
      "/jam-menit/276-tiga-per-empat-jam-berapa-menit",
      "Tiga Per Empat Jam Berapa Menit ?",
      "",
      "Tiga Per Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_277",
      "/jam-menit/277-tiga-setengah-jam-berapa-menit",
      "Tiga Setengah Jam Berapa Menit ?",
      "",
      "Tiga Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_278",
      "/jam-menit/278-satu-per-empat-jam-berapa-menit",
      "1/4 Jam Berapa Menit ?",
      "",
      "1/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_279",
      "/jam-menit/279-dua-seperdua-jam-berapa-menit",
      "2 1/2 Jam Berapa Menit ?",
      "",
      "2 1/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_280",
      "/jam-menit/280-2-per-3-jam-berapa-menit",
      "2/3 Jam Berapa Menit ?",
      "",
      "2/3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_281",
      "/jam-menit/281-21-per-2-jam-berapa-menit",
      "21/2 Jam Berapa Menit ?",
      "",
      "21/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_282",
      "/jam-menit/282-3-per-4-jam-berapa-menit",
      "3/4 Jam Berapa Menit ?",
      "",
      "3/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_283",
      "/jam-menit/283-3-per-8-jam-berapa-menit",
      "3/8 Jam Berapa Menit ?",
      "",
      "3/8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_284",
      "/jam-menit/284-31-per-4-jam-berapa-menit",
      "31/4 Jam Berapa Menit ?",
      "",
      "31/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_285",
      "/jam-menit/285-5-per-6-jam-berapa-menit",
      "5/6 Jam Berapa Menit ?",
      "",
      "5/6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_286",
      "/jam-menit/286-7-per-12-jam-berapa-menit",
      "7/12 Jam Berapa Menit ?",
      "",
      "7/12 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_287",
      "/jam-menit/287-7-per-4-jam-berapa-menit",
      "7/4 Jam Berapa Menit ?",
      "",
      "7/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_288",
      "/jam-menit/288-9-per-4-jam-berapa-menit",
      "9/4 Jam Berapa Menit ?",
      "",
      "9/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_289",
      "/jam-menit/289-8-per-9-jam-berapa-menit",
      "8/9 Jam Berapa Menit ?",
      "",
      "8/9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
];