var titleCat_1 = "Pecahan";
var cat_1 = [
  ["Desimal - Pecahan Biasa", "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa", ""],
];
var url_root = "https://nasrianas.website/jawab/math/pecahan";
var footerArray = [
    //June2020
    [
      "pecahan_001",
      "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa",
      "0.75 Diubah Menjadi Pecahan Biasa",
      "",
      "0.75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_002",
      "/decimal-pecahanBiasa/002-0,25-diubah-menjadi-pecahan-biasa",
      "0.25 Diubah Menjadi Pecahan Biasa",
      "",
      "0.25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_003",
      "/decimal-pecahanBiasa/003-0,72-diubah-menjadi-pecahan-biasa",
      "0.72 Diubah Menjadi Pecahan Biasa",
      "",
      "0.72 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_004",
      "/decimal-pecahanBiasa/004-0,02-diubah-menjadi-pecahan-biasa",
      "0.02 Diubah Menjadi Pecahan Biasa",
      "",
      "0.02 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_005",
      "/decimal-pecahanBiasa/005-0,30-diubah-menjadi-pecahan-biasa",
      "0.30 Diubah Menjadi Pecahan Biasa",
      "",
      "0.30 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_006",
      "/decimal-pecahanBiasa/006-0,2-diubah-menjadi-pecahan-biasa",
      "0.2 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_007",
      "/decimal-pecahanBiasa/007-0,15-diubah-menjadi-pecahan-biasa",
      "0.15 Diubah Menjadi Pecahan Biasa",
      "",
      "0.15 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_008",
      "/decimal-pecahanBiasa/008-0,125-diubah-menjadi-pecahan-biasa",
      "0.125 Diubah Menjadi Pecahan Biasa",
      "",
      "0.125 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_009",
      "/decimal-pecahanBiasa/009-0,3-diubah-menjadi-pecahan-biasa",
      "0.3 Diubah Menjadi Pecahan Biasa",
      "",
      "0.3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_010",
      "/decimal-pecahanBiasa/010-0,4-diubah-menjadi-pecahan-biasa",
      "0.4 Diubah Menjadi Pecahan Biasa",
      "",
      "0.4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_011",
      "/decimal-pecahanBiasa/011-0,50-diubah-menjadi-pecahan-biasa",
      "0.50 Diubah Menjadi Pecahan Biasa",
      "",
      "0.50 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_012",
      "/decimal-pecahanBiasa/012-0,6-diubah-menjadi-pecahan-biasa",
      "0.6 Diubah Menjadi Pecahan Biasa",
      "",
      "0.6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_013",
      "/decimal-pecahanBiasa/013-0,62-diubah-menjadi-pecahan-biasa",
      "0.62 Diubah Menjadi Pecahan Biasa",
      "",
      "0.62 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_014",
      "/decimal-pecahanBiasa/014-0,32-diubah-menjadi-pecahan-biasa",
      "0.32 Diubah Menjadi Pecahan Biasa",
      "",
      "0.32 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_015",
      "/decimal-pecahanBiasa/015-0,875-diubah-menjadi-pecahan-biasa",
      "0.875 Diubah Menjadi Pecahan Biasa",
      "",
      "0.875 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_016",
      "/decimal-pecahanBiasa/016-0,625-diubah-menjadi-pecahan-biasa",
      "0.625 Diubah Menjadi Pecahan Biasa",
      "",
      "0.625 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_017",
      "/decimal-pecahanBiasa/017-0,375-diubah-menjadi-pecahan-biasa",
      "0.375 Diubah Menjadi Pecahan Biasa",
      "",
      "0.375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_018",
      "/decimal-pecahanBiasa/018-0,8-diubah-menjadi-pecahan-biasa",
      "0.8 Diubah Menjadi Pecahan Biasa",
      "",
      "0.8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_019",
      "/decimal-pecahanBiasa/019-0,45-diubah-menjadi-pecahan-biasa",
      "0.45 Diubah Menjadi Pecahan Biasa",
      "",
      "0.45 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_020",
      "/decimal-pecahanBiasa/020-0,09-diubah-menjadi-pecahan-biasa",
      "0.09 Diubah Menjadi Pecahan Biasa",
      "",
      "0.09 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_021",
      "/decimal-pecahanBiasa/021-0,36-diubah-menjadi-pecahan-biasa",
      "0.36 Diubah Menjadi Pecahan Biasa",
      "",
      "0.36 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_022",
      "/decimal-pecahanBiasa/022-0,5-diubah-menjadi-pecahan-biasa",
      "0.5 Diubah Menjadi Pecahan Biasa",
      "",
      "0.5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_023",
      "/decimal-pecahanBiasa/023-0,65-diubah-menjadi-pecahan-biasa",
      "0.65 Diubah Menjadi Pecahan Biasa",
      "",
      "0.65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_024",
      "/decimal-pecahanBiasa/024-0,01-diubah-menjadi-pecahan-biasa",
      "0.01 Diubah Menjadi Pecahan Biasa",
      "",
      "0.01 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_025",
      "/decimal-pecahanBiasa/025-0,03-diubah-menjadi-pecahan-biasa",
      "0.03 Diubah Menjadi Pecahan Biasa",
      "",
      "0.03 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_026",
      "/decimal-pecahanBiasa/026-0,07-diubah-menjadi-pecahan-biasa",
      "0.07 Diubah Menjadi Pecahan Biasa",
      "",
      "0.07 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_027",
      "/decimal-pecahanBiasa/027-0,04-diubah-menjadi-pecahan-biasa",
      "0.04 Diubah Menjadi Pecahan Biasa",
      "",
      "0.04 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_028",
      "/decimal-pecahanBiasa/028-0,06-diubah-menjadi-pecahan-biasa",
      "0.06 Diubah Menjadi Pecahan Biasa",
      "",
      "0.06 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_029",
      "/decimal-pecahanBiasa/029-0,08-diubah-menjadi-pecahan-biasa",
      "0.08 Diubah Menjadi Pecahan Biasa",
      "",
      "0.08 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_030",
      "/decimal-pecahanBiasa/030-0,12-diubah-menjadi-pecahan-biasa",
      "0.12 Diubah Menjadi Pecahan Biasa",
      "",
      "0.12 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_031",
      "/decimal-pecahanBiasa/031-0,16-diubah-menjadi-pecahan-biasa",
      "0.16 Diubah Menjadi Pecahan Biasa",
      "",
      "0.16 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_032",
      "/decimal-pecahanBiasa/032-0,175-diubah-menjadi-pecahan-biasa",
      "0.175 Diubah Menjadi Pecahan Biasa",
      "",
      "0.175 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_033",
      "/decimal-pecahanBiasa/033-0,1025-diubah-menjadi-pecahan-biasa",
      "0.1025 Diubah Menjadi Pecahan Biasa",
      "",
      "0.1025 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_034",
      "/decimal-pecahanBiasa/034-0,24-diubah-menjadi-pecahan-biasa",
      "0.24 Diubah Menjadi Pecahan Biasa",
      "",
      "0.24 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_035",
      "/decimal-pecahanBiasa/035-0,20-diubah-menjadi-pecahan-biasa",
      "0.20 Diubah Menjadi Pecahan Biasa",
      "",
      "0.20 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_036",
      "/decimal-pecahanBiasa/036-0,2525-diubah-menjadi-pecahan-biasa",
      "0.2525 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2525 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_037",
      "/decimal-pecahanBiasa/037-0,26-diubah-menjadi-pecahan-biasa",
      "0.26 Diubah Menjadi Pecahan Biasa",
      "",
      "0.26 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_038",
      "/decimal-pecahanBiasa/038-0,225-diubah-menjadi-pecahan-biasa",
      "0.225 Diubah Menjadi Pecahan Biasa",
      "",
      "0.225 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_039",
      "/decimal-pecahanBiasa/039-0,21-diubah-menjadi-pecahan-biasa",
      "0.21 Diubah Menjadi Pecahan Biasa",
      "",
      "0.21 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_040",
      "/decimal-pecahanBiasa/040-0,23-diubah-menjadi-pecahan-biasa",
      "0.23 Diubah Menjadi Pecahan Biasa",
      "",
      "0.23 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_041",
      "/decimal-pecahanBiasa/041-0,33-diubah-menjadi-pecahan-biasa",
      "0.33 Diubah Menjadi Pecahan Biasa",
      "",
      "0.33 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_042",
      "/decimal-pecahanBiasa/042-0,333-diubah-menjadi-pecahan-biasa",
      "0.333 Diubah Menjadi Pecahan Biasa",
      "",
      "0.333 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_043",
      "/decimal-pecahanBiasa/043-0,35-diubah-menjadi-pecahan-biasa",
      "0.35 Diubah Menjadi Pecahan Biasa",
      "",
      "0.35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_044",
      "/decimal-pecahanBiasa/044-0,48-diubah-menjadi-pecahan-biasa",
      "0.48 Diubah Menjadi Pecahan Biasa",
      "",
      "0.48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_045",
      "/decimal-pecahanBiasa/045-0,40-diubah-menjadi-pecahan-biasa",
      "0.40 Diubah Menjadi Pecahan Biasa",
      "",
      "0.40 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_046",
      "/decimal-pecahanBiasa/046-0,42-diubah-menjadi-pecahan-biasa",
      "0.42 Diubah Menjadi Pecahan Biasa",
      "",
      "0.42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_047",
      "/decimal-pecahanBiasa/047-0,44-diubah-menjadi-pecahan-biasa",
      "0.44 Diubah Menjadi Pecahan Biasa",
      "",
      "0.44 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_048",
      "/decimal-pecahanBiasa/048-0,46-diubah-menjadi-pecahan-biasa",
      "0.46 Diubah Menjadi Pecahan Biasa",
      "",
      "0.46 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_049",
      "/decimal-pecahanBiasa/049-0,43-diubah-menjadi-pecahan-biasa",
      "0.43 Diubah Menjadi Pecahan Biasa",
      "",
      "0.43 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_050",
      "/decimal-pecahanBiasa/050-0,53-diubah-menjadi-pecahan-biasa",
      "0.53 Diubah Menjadi Pecahan Biasa",
      "",
      "0.53 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_051",
      "/decimal-pecahanBiasa/051-0,52-diubah-menjadi-pecahan-biasa",
      "0.52 Diubah Menjadi Pecahan Biasa",
      "",
      "0.52 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_052",
      "/decimal-pecahanBiasa/052-0,55-diubah-menjadi-pecahan-biasa",
      "0.55 Diubah Menjadi Pecahan Biasa",
      "",
      "0.55 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_053",
      "/decimal-pecahanBiasa/053-0,56-diubah-menjadi-pecahan-biasa",
      "0.56 Diubah Menjadi Pecahan Biasa",
      "",
      "0.56 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_054",
      "/decimal-pecahanBiasa/054-0,58-diubah-menjadi-pecahan-biasa",
      "0.58 Diubah Menjadi Pecahan Biasa",
      "",
      "0.58 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_055",
      "/decimal-pecahanBiasa/055-0,60-diubah-menjadi-pecahan-biasa",
      "0.60 Diubah Menjadi Pecahan Biasa",
      "",
      "0.60 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_056",
      "/decimal-pecahanBiasa/056-0,64-diubah-menjadi-pecahan-biasa",
      "0.64 Diubah Menjadi Pecahan Biasa",
      "",
      "0.64 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_057",
      "/decimal-pecahanBiasa/057-0,66-diubah-menjadi-pecahan-biasa",
      "0.66 Diubah Menjadi Pecahan Biasa",
      "",
      "0.66 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_058",
      "/decimal-pecahanBiasa/058-0,69-diubah-menjadi-pecahan-biasa",
      "0.69 Diubah Menjadi Pecahan Biasa",
      "",
      "0.69 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_059",
      "/decimal-pecahanBiasa/059-0,7-diubah-menjadi-pecahan-biasa",
      "0.7 Diubah Menjadi Pecahan Biasa",
      "",
      "0.7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_060",
      "/decimal-pecahanBiasa/060-0,79-diubah-menjadi-pecahan-biasa",
      "0.79 Diubah Menjadi Pecahan Biasa",
      "",
      "0.79 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_061",
      "/decimal-pecahanBiasa/061-0,70-diubah-menjadi-pecahan-biasa",
      "0.70 Diubah Menjadi Pecahan Biasa",
      "",
      "0.70 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_062",
      "/decimal-pecahanBiasa/062-0,74-diubah-menjadi-pecahan-biasa",
      "0.74 Diubah Menjadi Pecahan Biasa",
      "",
      "0.74 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_063",
      "/decimal-pecahanBiasa/063-0,76-diubah-menjadi-pecahan-biasa",
      "0.76 Diubah Menjadi Pecahan Biasa",
      "",
      "0.76 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_064",
      "/decimal-pecahanBiasa/064-0,725-diubah-menjadi-pecahan-biasa",
      "0.725 Diubah Menjadi Pecahan Biasa",
      "",
      "0.725 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_065",
      "/decimal-pecahanBiasa/065-0,80-diubah-menjadi-pecahan-biasa",
      "0.80 Diubah Menjadi Pecahan Biasa",
      "",
      "0.80 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_066",
      "/decimal-pecahanBiasa/066-0,82-diubah-menjadi-pecahan-biasa",
      "0.82 Diubah Menjadi Pecahan Biasa",
      "",
      "0.82 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_067",
      "/decimal-pecahanBiasa/067-0,84-diubah-menjadi-pecahan-biasa",
      "0.84 Diubah Menjadi Pecahan Biasa",
      "",
      "0.84 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_068",
      "/decimal-pecahanBiasa/068-0,85-diubah-menjadi-pecahan-biasa",
      "0.85 Diubah Menjadi Pecahan Biasa",
      "",
      "0.85 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_069",
      "/decimal-pecahanBiasa/069-0,86-diubah-menjadi-pecahan-biasa",
      "0.86 Diubah Menjadi Pecahan Biasa",
      "",
      "0.86 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_070",
      "/decimal-pecahanBiasa/070-0,88-diubah-menjadi-pecahan-biasa",
      "0.88 Diubah Menjadi Pecahan Biasa",
      "",
      "0.88 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_071",
      "/decimal-pecahanBiasa/071-0,83-diubah-menjadi-pecahan-biasa",
      "0.83 Diubah Menjadi Pecahan Biasa",
      "",
      "0.83 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_072",
      "/decimal-pecahanBiasa/072-0,9-diubah-menjadi-pecahan-biasa",
      "0.9 Diubah Menjadi Pecahan Biasa",
      "",
      "0.9 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_073",
      "/decimal-pecahanBiasa/073-0,90-diubah-menjadi-pecahan-biasa",
      "0.90 Diubah Menjadi Pecahan Biasa",
      "",
      "0.90 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_074",
      "/decimal-pecahanBiasa/074-0,95-diubah-menjadi-pecahan-biasa",
      "0.95 Diubah Menjadi Pecahan Biasa",
      "",
      "0.95 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_075",
      "/decimal-pecahanBiasa/075-0,96-diubah-menjadi-pecahan-biasa",
      "0.96 Diubah Menjadi Pecahan Biasa",
      "",
      "0.96 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    
    
  
];