var titleCat_1 = "Waktu";
var cat_1 = [
  ["Detik-Menit", "/detik-menit/001-300-detik-berapa-menit", ""],
  ["Menit-Jam", "/menit-jam/003-300-menit-berapa-jam", ""],
  ["Detik-Jam", "/detik-jam/004-300-detik-berapa-jam", ""],
  ["Jam-Hari", "/jam-hari/005-300-jam-berapa-hari", ""],
  ["Menit-Detik", "/menit-detik/035-3-menit-berapa-detik", ""],
  ["Jam-Detik", "/jam-detik/069-1-per-4-jam-berapa-detik", ""],
  ["Jam-Menit", "/jam-menit/073-1-jam-berapa-menit", ""],

  
];
var url_root = "https://nasrianas.website/jawab/math/waktu";
var footerArray = [
    //June2020
    [
      "Waktu_001",
      "/detik-menit/001-300-detik-berapa-menit",
      "300 Detik Berapa Menit ?",
      "",
      "300 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_002",
      "/detik-menit/002-500-detik-berapa-menit",
      "500 Detik Berapa Menit ?",
      "",
      "500 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_003",
      "/menit-jam/003-300-menit-berapa-jam",
      "300 Menit Berapa Jam ?",
      "",
      "300 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_004",
      "/detik-jam/004-300-detik-berapa-jam",
      "300 Detik Berapa Jam",
      "",
      "300 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Math_005",
      "/jam-hari/005-300-jam-berapa-hari",
      "300 Jam Berapa Hari",
      "",
      "300 Jam = ... Hari",
      ["Jam-Hari"],
      "",
    ],
    [
      "Waktu_006",
      "/menit-jam/006-500-menit-berapa-jam",
      "500 Menit Berapa Jam ?",
      "",
      "500 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_007",
      "/menit-jam/007-100-menit-berapa-jam",
      "100 Menit Berapa Jam ?",
      "",
      "100 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_008",
      "/menit-jam/008-1000-menit-berapa-jam",
      "1000 Menit Berapa Jam ?",
      "",
      "1000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_009",
      "/menit-jam/009-90-menit-berapa-jam",
      "90 Menit Berapa Jam ?",
      "",
      "90 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_010",
      "/menit-jam/010-120-menit-berapa-jam",
      "120 Menit Berapa Jam ?",
      "",
      "120 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_011",
      "/menit-jam/011-180-menit-berapa-jam",
      "180 Menit Berapa Jam ?",
      "",
      "180 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_012",
      "/menit-jam/012-60-menit-berapa-jam",
      "60 Menit Berapa Jam ?",
      "",
      "60 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_013",
      "/menit-jam/013-45-menit-berapa-jam",
      "45 Menit Berapa Jam ?",
      "",
      "45 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_014",
      "/menit-jam/014-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_015",
      "/menit-jam/015-20-menit-berapa-jam",
      "20 Menit Berapa Jam ?",
      "",
      "20 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_016",
      "/menit-jam/016-5-menit-berapa-jam",
      "5 Menit Berapa Jam ?",
      "",
      "5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_017",
      "/menit-jam/017-40-menit-berapa-jam",
      "40 Menit Berapa Jam ?",
      "",
      "40 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_018",
      "/menit-jam/018-30-menit-berapa-jam",
      "30 Menit Berapa Jam ?",
      "",
      "30 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_019",
      "/menit-jam/019-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_020",
      "/menit-jam/020-12-menit-berapa-jam",
      "12 Menit Berapa Jam ?",
      "",
      "12 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_021",
      "/menit-jam/021-10-menit-berapa-jam",
      "10 Menit Berapa Jam ?",
      "",
      "10 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_022",
      "/menit-jam/022-17-menit-berapa-jam",
      "17 Menit Berapa Jam ?",
      "",
      "17 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_023",
      "/detik-menit/023-720-detik-berapa-menit",
      "720 Detik Berapa Menit ?",
      "",
      "720 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_024",
      "/detik-menit/024-120-detik-berapa-menit",
      "120 Detik Berapa Menit ?",
      "",
      "120 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_025",
      "/detik-menit/025-480-detik-berapa-menit",
      "480 Detik Berapa Menit ?",
      "",
      "480 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_026",
      "/detik-menit/026-7200-detik-berapa-menit",
      "7200 Detik Berapa Menit ?",
      "",
      "7200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_027",
      "/detik-menit/027-600-detik-berapa-menit",
      "600 Detik Berapa Menit ?",
      "",
      "600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_028",
      "/detik-menit/028-180-detik-berapa-menit",
      "180 Detik Berapa Menit ?",
      "",
      "180 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_029",
      "/detik-menit/029-15-detik-berapa-menit",
      "15 Detik Berapa Menit ?",
      "",
      "15 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_030",
      "/detik-menit/030-6-detik-berapa-menit",
      "6 Detik Berapa Menit ?",
      "",
      "6 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_031",
      "/detik-menit/031-10-detik-berapa-menit",
      "10 Detik Berapa Menit ?",
      "",
      "10 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_032",
      "/detik-menit/032-8-detik-berapa-menit",
      "8 Detik Berapa Menit ?",
      "",
      "8 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_033",
      "/detik-menit/033-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_034",
      "/detik-menit/034-90-detik-berapa-menit",
      "90 Detik Berapa Menit ?",
      "",
      "90 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_035",
      "/menit-detik/035-3-menit-berapa-detik",
      "3 Menit Berapa Detik ?",
      "",
      "3 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_035",
      "/menit-detik/035-3-menit-berapa-detik",
      "3 Menit Berapa Detik ?",
      "",
      "3 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_036",
      "/menit-detik/036-25-menit-berapa-detik",
      "25 Menit Berapa Detik ?",
      "",
      "25 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_037",
      "/menit-detik/037-5-menit-berapa-detik",
      "5 Menit Berapa Detik ?",
      "",
      "5 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_038",
      "/menit-detik/038-30-menit-berapa-detik",
      "30 Menit Berapa Detik ?",
      "",
      "30 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_039",
      "/menit-detik/039-10-menit-berapa-detik",
      "10 Menit Berapa Detik ?",
      "",
      "10 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_040",
      "/menit-detik/040-60-menit-berapa-detik",
      "60 Menit Berapa Detik ?",
      "",
      "60 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_041",
      "/menit-detik/041-15-menit-berapa-detik",
      "15 Menit Berapa Detik ?",
      "",
      "15 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_042",
      "/menit-detik/042-12-menit-berapa-detik",
      "12 Menit Berapa Detik ?",
      "",
      "12 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_043",
      "/menit-detik/043-20-menit-berapa-detik",
      "20 Menit Berapa Detik ?",
      "",
      "20 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_044",
      "/menit-detik/044-7-menit-berapa-detik",
      "7 Menit Berapa Detik ?",
      "",
      "7 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_045",
      "/menit-detik/045-0,1-menit-berapa-detik",
      "0.1 Menit Berapa Detik ?",
      "",
      "0,1 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_046",
      "/detik-jam/046-500-detik-berapa-jam",
      "500 Detik Berapa Jam ?",
      "",
      "500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_047",
      "/detik-jam/047-7200-detik-berapa-jam",
      "7200 Detik Berapa Jam ?",
      "",
      "7200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_048",
      "/detik-jam/048-1-detik-berapa-jam",
      "1 Detik Berapa Jam ?",
      "",
      "1 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_049",
      "/detik-jam/049-1800-detik-berapa-jam",
      "1800 Detik Berapa Jam ?",
      "",
      "1800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_050",
      "/detik-jam/050-600-detik-berapa-jam",
      "600 Detik Berapa Jam ?",
      "",
      "600 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_051",
      "/detik-jam/051-100-detik-berapa-jam",
      "100 Detik Berapa Jam ?",
      "",
      "100 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_052",
      "/detik-jam/052-10-detik-berapa-jam",
      "10 Detik Berapa Jam ?",
      "",
      "10 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_053",
      "/detik-jam/053-15-detik-berapa-jam",
      "15 Detik Berapa Jam ?",
      "",
      "15 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_054",
      "/detik-jam/054-60-detik-berapa-jam",
      "60 Detik Berapa Jam ?",
      "",
      "60 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_055",
      "/detik-jam/055-6-detik-berapa-jam",
      "6 Detik Berapa Jam ?",
      "",
      "6 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_056",
      "/jam-detik/056-2-jam-berapa-detik",
      "2 Jam Berapa Detik ?",
      "",
      "2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_057",
      "/jam-detik/057-1-jam-berapa-detik",
      "1 Jam Berapa Detik ?",
      "",
      "1 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_058",
      "/jam-detik/058-0,45-jam-berapa-detik",
      "0.45 Jam Berapa Detik ?",
      "",
      "0,45 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_059",
      "/jam-detik/059-3-jam-berapa-detik",
      "3 Jam Berapa Detik ?",
      "",
      "3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_060",
      "/jam-detik/060-0,5-jam-berapa-detik",
      "0.5 Jam Berapa Detik ?",
      "",
      "0,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_061",
      "/jam-detik/061-1-per-6-jam-berapa-detik",
      "1/6 Jam Berapa Detik ?",
      "",
      "1/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_062",
      "/jam-detik/062-1-per-60-jam-berapa-detik",
      "1/60 Jam Berapa Detik ?",
      "",
      "1/60 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_063",
      "/jam-detik/063-1,5-jam-berapa-detik",
      "1.5 Jam Berapa Detik ?",
      "",
      "1,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_064",
      "/jam-detik/064-24-jam-berapa-detik",
      "24 Jam Berapa Detik ?",
      "",
      "24 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_065",
      "/jam-detik/065-4-jam-berapa-detik",
      "4 Jam Berapa Detik ?",
      "",
      "4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_066",
      "/jam-detik/066-7-jam-berapa-detik",
      "7 Jam Berapa Detik ?",
      "",
      "7 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_067",
      "/jam-detik/067-6-jam-berapa-detik",
      "6 Jam Berapa Detik ?",
      "",
      "6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_068",
      "/jam-detik/068-12-jam-berapa-detik",
      "12 Jam Berapa Detik ?",
      "",
      "12 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_069",
      "/jam-detik/069-1-per-4-jam-berapa-detik",
      "1/4 Jam Berapa Detik ?",
      "",
      "1/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_070",
      "/jam-detik/070-1-per-3-jam-berapa-detik",
      "1/3 Jam Berapa Detik ?",
      "",
      "1/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_071",
      "/jam-detik/071-0,25-jam-berapa-detik",
      "0.25 Jam Berapa Detik ?",
      "",
      "0.25 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_072",
      "/jam-detik/072-2,5-jam-berapa-detik",
      "2.5 Jam Berapa Detik ?",
      "",
      "2.5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_073",
      "/jam-menit/073-1-jam-berapa-menit",
      "1 Jam Berapa Menit ?",
      "",
      "1 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_074",
      "/jam-menit/074-2-jam-berapa-menit",
      "2 Jam Berapa Menit ?",
      "",
      "2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_075",
      "/jam-menit/075-3-jam-berapa-menit",
      "3 Jam Berapa Menit ?",
      "",
      "3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_076",
      "/jam-menit/076-4-jam-berapa-menit",
      "4 Jam Berapa Menit ?",
      "",
      "4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_077",
      "/jam-menit/077-5-jam-berapa-menit",
      "5 Jam Berapa Menit ?",
      "",
      "5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_078",
      "/jam-menit/078-6-jam-berapa-menit",
      "6 Jam Berapa Menit ?",
      "",
      "6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_079",
      "/jam-menit/079-7-jam-berapa-menit",
      "7 Jam Berapa Menit ?",
      "",
      "7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_080",
      "/jam-menit/080-8-jam-berapa-menit",
      "8 Jam Berapa Menit ?",
      "",
      "8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_081",
      "/jam-menit/081-9-jam-berapa-menit",
      "9 Jam Berapa Menit ?",
      "",
      "9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_082",
      "/jam-menit/082-10-jam-berapa-menit",
      "10 Jam Berapa Menit ?",
      "",
      "10 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_083",
      "/jam-menit/083-11-jam-berapa-menit",
      "11 Jam Berapa Menit ?",
      "",
      "11 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_084",
      "/jam-menit/084-12-jam-berapa-menit",
      "12 Jam Berapa Menit ?",
      "",
      "12 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_085",
      "/jam-menit/085-13-jam-berapa-menit",
      "13 Jam Berapa Menit ?",
      "",
      "13 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_086",
      "/jam-menit/086-14-jam-berapa-menit",
      "14 Jam Berapa Menit ?",
      "",
      "14 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_087",
      "/jam-menit/087-15-jam-berapa-menit",
      "15 Jam Berapa Menit ?",
      "",
      "15 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_088",
      "/jam-menit/088-16-jam-berapa-menit",
      "16 Jam Berapa Menit ?",
      "",
      "16 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_089",
      "/jam-menit/089-17-jam-berapa-menit",
      "17 Jam Berapa Menit ?",
      "",
      "17 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_090",
      "/jam-menit/090-18-jam-berapa-menit",
      "18 Jam Berapa Menit ?",
      "",
      "18 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_091",
      "/jam-menit/091-19-jam-berapa-menit",
      "19 Jam Berapa Menit ?",
      "",
      "19 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_092",
      "/jam-menit/092-20-jam-berapa-menit",
      "20 Jam Berapa Menit ?",
      "",
      "20 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_093",
      "/jam-menit/093-21-jam-berapa-menit",
      "21 Jam Berapa Menit ?",
      "",
      "21 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_094",
      "/jam-menit/094-22-jam-berapa-menit",
      "22 Jam Berapa Menit ?",
      "",
      "22 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_095",
      "/jam-menit/095-23-jam-berapa-menit",
      "23 Jam Berapa Menit ?",
      "",
      "23 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_096",
      "/jam-menit/096-24-jam-berapa-menit",
      "24 Jam Berapa Menit ?",
      "",
      "24 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_097",
      "/jam-menit/097-0,5-jam-berapa-menit",
      "0,5 Jam Berapa Menit ?",
      "",
      "0,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_098",
      "/jam-menit/098-1,5-jam-berapa-menit",
      "1,5 Jam Berapa Menit ?",
      "",
      "1,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_099",
      "/jam-menit/099-2,5-jam-berapa-menit",
      "2,5 Jam Berapa Menit ?",
      "",
      "2,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_100",
      "/jam-menit/100-1,2-jam-berapa-menit",
      "1,2 Jam Berapa Menit ?",
      "",
      "1,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_101",
      "/jam-menit/101-1,6-jam-berapa-menit",
      "1,6 Jam Berapa Menit ?",
      "",
      "1,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_102",
      "/jam-menit/102-1,25-jam-berapa-menit",
      "1,25 Jam Berapa Menit ?",
      "",
      "1,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_103",
      "/jam-menit/103-5,6-jam-berapa-menit",
      "5,6 Jam Berapa Menit ?",
      "",
      "5,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_104",
      "/jam-menit/104-1per2-jam-berapa-menit",
      "1/2 Jam Berapa Menit ?",
      "",
      "1/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_105",
      "/jam-menit/105-1per6-jam-berapa-menit",
      "1/6 Jam Berapa Menit ?",
      "",
      "1/6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_106",
      "/jam-menit/106-4000-jam-berapa-menit",
      "4000 Jam Berapa Menit ?",
      "",
      "4000 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],

    [
      "Waktu_107",
      "/detik-menit/107-3600-detik-berapa-menit",
      "3600 Detik Berapa Menit ?",
      "",
      "3600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_108",
      "/detik-menit/108-1000-detik-berapa-menit",
      "1000 Detik Berapa Menit ?",
      "",
      "1000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_109",
      "/detik-menit/109-270-detik-berapa-menit",
      "270 Detik Berapa Menit ?",
      "",
      "270 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_110",
      "/detik-menit/110-230-detik-berapa-menit",
      "230 Detik Berapa Menit ?",
      "",
      "230 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_111",
      "/detik-menit/111-5000-detik-berapa-menit",
      "5000 Detik Berapa Menit ?",
      "",
      "5000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_112",
      "/detik-menit/112-200-detik-berapa-menit",
      "200 Detik Berapa Menit ?",
      "",
      "200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_113",
      "/detik-menit/113-1200-detik-berapa-menit",
      "1200 Detik Berapa Menit ?",
      "",
      "1200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_114",
      "/detik-menit/114-2400-detik-berapa-menit",
      "2400 Detik Berapa Menit ?",
      "",
      "2400 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_115",
      "/detik-menit/115-420-detik-berapa-menit",
      "420 Detik Berapa Menit ?",
      "",
      "420 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_116",
      "/detik-menit/116-4200-detik-berapa-menit",
      "4200 Detik Berapa Menit ?",
      "",
      "4200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_117",
      "/detik-menit/117-360-detik-berapa-menit",
      "360 Detik Berapa Menit ?",
      "",
      "360 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_118",
      "/detik-menit/118-20-detik-berapa-menit",
      "20 Detik Berapa Menit ?",
      "",
      "20 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_119",
      "/detik-menit/119-30-detik-berapa-menit",
      "30 Detik Berapa Menit ?",
      "",
      "30 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_120",
      "/detik-menit/120-5-detik-berapa-menit",
      "5 Detik Berapa Menit ?",
      "",
      "5 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_121",
      "/detik-menit/121-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],

];