var titleCat_1 = "Persen";
var cat_1 = [
  ["1 Persen", "/1persen/001-1-persen-dari-1-juta", ""],
  ["2 Persen", "/2persen/005-2-persen-dari-1-juta", ""],
  ["3 Persen", "/3persen/008-3-persen-dari-1-juta", ""],
  ["2.5 Persen", "/2,5persen/011-2,5-persen-dari-1-juta", ""],
  ["5 Persen", "/5persen/019-5-persen-dari-1-juta", ""],
  ["10 Persen", "/10persen/023-10-persen-dari-100", ""],
  ["15 Persen", "/15persen/031-15-persen-dari-60", ""],
  ["20 Persen", "/20persen/032-20-persen-dari-100", ""],
  ["25 Persen", "/25persen/034-25-persen-dari-100", ""],
  ["30 Persen", "/30persen/036-30-persen-dari-100", ""],
  ["33 Persen", "/33persen/039-33-persen-dari-163-ribu", ""],
  ["150 Persen", "/150persen/050-9-adalah-150-persen-dari", ""],
  ["Berapa Persen dari", "/berapa-persen-dari/042-3-berapa-persen-dari-20", ""],
  ["Pecahan - Persen", "/pecahan-persen/051-persen-dari-4per5", ""],
];
var url_root = "https://nasrianas.website/jawab/math/persen";
var footerArray = [
    //June2020
    [
      "persen_001",
      "/1persen/001-1-persen-dari-1-juta",
      "Berapa 1 Persen dari 1 Juta ?",
      "",
      "1 % dari 1 juta = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_002",
      "/1persen/002-1-persen-dari-10-juta",
      "Berapa 1 Persen dari 10 Juta ?",
      "",
      "1 % dari 10 juta = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_003",
      "/1persen/003-1-persen-dari-50-juta",
      "Berapa 1 Persen dari 50 Juta ?",
      "",
      "1 % dari 50 juta = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_004",
      "/1persen/004-1-persen-dari-1-milyar",
      "Berapa 1 Persen dari 1 Milyar ?",
      "",
      "1 % dari 1 Milyar = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_005",
      "/2persen/005-2-persen-dari-1-juta",
      "Berapa 2 Persen dari 1 Juta ?",
      "",
      "2 % dari 1 juta = ...",
      ["2 Persen"],
      "",
    ],
    [
      "persen_006",
      "/2persen/006-2-persen-dari-5-juta",
      "Berapa 2 Persen dari 5 Juta ?",
      "",
      "2 % dari 5 juta = ...",
      ["2 Persen"],
      "",
    ],
    [
      "persen_007",
      "/2persen/007-2-persen-dari-1-milyar",
      "Berapa 2 Persen dari 1 Milyar ?",
      "",
      "2 % dari 1 Milyar = ...",
      ["2 Persen"],
      "",
    ],
    [
      "persen_008",
      "/3persen/008-3-persen-dari-1-juta",
      "Berapa 3 Persen dari 1 Juta ?",
      "",
      "3 % dari 1 Juta = ...",
      ["3 Persen"],
      "",
    ],
    [
      "persen_009",
      "/3persen/009-3-persen-dari-10-juta",
      "Berapa 3 Persen dari 10 Juta ?",
      "",
      "3 % dari 10 Juta = ...",
      ["3 Persen"],
      "",
    ],
    [
      "persen_010",
      "/3persen/010-3-persen-dari-1-milyar",
      "Berapa 3 Persen dari 1 Milyar ?",
      "",
      "3 % dari 1 Milyar = ...",
      ["3 Persen"],
      "",
    ],
    [
      "persen_011",
      "/2,5persen/011-2,5-persen-dari-1-juta",
      "Berapa 2.5 Persen dari 1 Juta ?",
      "",
      "2.5 % dari 1 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_012",
      "/2,5persen/012-2,5-persen-dari-2-juta",
      "Berapa 2.5 Persen dari 2 Juta ?",
      "",
      "2.5 % dari 2 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_013",
      "/2,5persen/013-2,5-persen-dari-3-juta",
      "Berapa 2.5 Persen dari 3 Juta ?",
      "",
      "2.5 % dari 3 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_014",
      "/2,5persen/014-2,5-persen-dari-4-juta",
      "Berapa 2.5 Persen dari 4 Juta ?",
      "",
      "2.5 % dari 4 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_015",
      "/2,5persen/015-2,5-persen-dari-5-juta",
      "Berapa 2.5 Persen dari 5 Juta ?",
      "",
      "2.5 % dari 5 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_016",
      "/2,5persen/016-2,5-persen-dari-100-juta",
      "Berapa 2.5 Persen dari 100 Juta ?",
      "",
      "2.5 % dari 100 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_017",
      "/2,5persen/017-2,5-persen-dari-500-ribu",
      "Berapa 2.5 Persen dari 500 ribu ?",
      "",
      "2.5 % dari 500 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_018",
      "/2,5persen/018-2,5-persen-dari-1-milyar",
      "Berapa 2.5 Persen dari 1 Milyar ?",
      "",
      "2.5 % dari 1 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_019",
      "/5persen/019-5-persen-dari-1-juta",
      "Berapa 5 Persen dari 1 Juta ?",
      "",
      "5 % dari 1 Juta = ...",
      ["5 Persen"],
      "",
    ],
    [
      "persen_020",
      "/5persen/020-5-persen-dari-3-juta",
      "Berapa 5 Persen dari 3 Juta ?",
      "",
      "5 % dari 3 Juta = ...",
      ["5 Persen"],
      "",
    ],
    [
      "persen_021",
      "/5persen/021-5-persen-dari-100-juta",
      "Berapa 5 Persen dari 100 Juta ?",
      "",
      "5 % dari 100 Juta = ...",
      ["5 Persen"],
      "",
    ],
    [
      "persen_022",
      "/5persen/022-5-persen-dari-1-milyar",
      "Berapa 5 Persen dari 1 Milyar ?",
      "",
      "5 % dari 1 Milyar = ...",
      ["5 Persen"],
      "",
    ],
    [
      "persen_023",
      "/10persen/023-10-persen-dari-100",
      "Berapa 10 Persen dari 100 ?",
      "",
      "10 % dari 100 = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_024",
      "/10persen/024-10-persen-dari-150",
      "Berapa 10 Persen dari 150 ?",
      "",
      "10 % dari 150 = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_025",
      "/10persen/025-10-persen-dari-500",
      "Berapa 10 Persen dari 500 ?",
      "",
      "10 % dari 500 = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_026",
      "/10persen/026-10-persen-dari-300-ribu",
      "Berapa 10 Persen dari 300 ribu ?",
      "",
      "10 % dari 300 ribu = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_027",
      "/10persen/027-10-persen-dari-1-juta",
      "Berapa 10 Persen dari 1 juta ?",
      "",
      "10 % dari 1 juta = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_028",
      "/10persen/028-10-persen-dari-2-juta",
      "Berapa 10 Persen dari 2 juta ?",
      "",
      "10 % dari 2 juta = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_029",
      "/10persen/029-10-persen-dari-5-juta",
      "Berapa 10 Persen dari 5 juta ?",
      "",
      "10 % dari 5 juta = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_030",
      "/10persen/030-10-persen-dari-1-milyar",
      "Berapa 10 Persen dari 1 Milyar ?",
      "",
      "10 % dari 1 Milyar = ...",
      ["10 Persen"],
      "",
    ],
    [
      "persen_031",
      "/15persen/031-15-persen-dari-60",
      "Berapa 15 Persen dari 60 ?",
      "",
      "15 % dari 60 = ...",
      ["15 Persen"],
      "",
    ],
    [
      "persen_032",
      "/20persen/032-20-persen-dari-100",
      "Berapa 20 Persen dari 100 ?",
      "",
      "20 % dari 100 = ...",
      ["20 Persen"],
      "",
    ],
    [
      "persen_033",
      "/20persen/033-20-persen-dari-300-ribu",
      "Berapa 20 Persen dari 300 ribu ?",
      "",
      "20 % dari 300 ribu = ...",
      ["20 Persen"],
      "",
    ],
    [
      "persen_034",
      "/25persen/034-25-persen-dari-100",
      "Berapa 25 Persen dari 100?",
      "",
      "25 % dari 100 = ...",
      ["25 Persen"],
      "",
    ],
    [
      "persen_035",
      "/25persen/035-25-persen-dari-200",
      "Berapa 25 Persen dari 200?",
      "",
      "25 % dari 200 = ...",
      ["25 Persen"],
      "",
    ],
    [
      "persen_036",
      "/30persen/036-30-persen-dari-100",
      "Berapa 30 Persen dari 100?",
      "",
      "30 % dari 100 = ...",
      ["30 Persen"],
      "",
    ],
    [
      "persen_037",
      "/30persen/037-30-persen-dari-300-ribu",
      "Berapa 30 Persen dari 300 ribu?",
      "",
      "30 % dari 300 ribu = ...",
      ["30 Persen"],
      "",
    ],
    [
      "persen_038",
      "/30persen/038-30-persen-dari-500-ribu",
      "Berapa 30 Persen dari 500 ribu?",
      "",
      "30 % dari 500 ribu = ...",
      ["30 Persen"],
      "",
    ],
    [
      "persen_039",
      "/33persen/039-33-persen-dari-163",
      "Berapa 33 Persen dari 163?",
      "",
      "33 % dari 163 = ...",
      ["33 Persen"],
      "",
    ],
    [
      "persen_040",
      "/33persen/040-33-persen-dari-60",
      "Berapa 33 Persen dari 60?",
      "",
      "33 % dari 60 = ...",
      ["33 Persen"],
      "",
    ],
    [
      "persen_041",
      "/40persen/041-40-persen-dari-100",
      "Berapa 40 Persen dari 100?",
      "",
      "40 % dari 100 = ...",
      ["40 Persen"],
      "",
    ],

    [
      "persen_042",
      "/berapa-persen-dari/042-3-berapa-persen-dari-20",
      "3 Berapa Persen dari 20?",
      "",
      "3 Berapa Persen dari 20 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_043",
      "/berapa-persen-dari/043-28-berapa-persen-dari-70",
      "28 Berapa Persen dari 70?",
      "",
      "28 Berapa Persen dari 70 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_044",
      "/berapa-persen-dari/044-7-berapa-persen-dari-50",
      "7 Berapa Persen dari 50?",
      "",
      "7 Berapa Persen dari 50 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_045",
      "/berapa-persen-dari/045-9-berapa-persen-dari-20",
      "9 Berapa Persen dari 20?",
      "",
      "9 Berapa Persen dari 20 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_046",
      "/berapa-persen-dari/046-42-berapa-persen-dari-70",
      "42 Berapa Persen dari 70?",
      "",
      "42 Berapa Persen dari 70 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_047",
      "/berapa-persen-dari/047-48-berapa-persen-dari-64",
      "48 Berapa Persen dari 64?",
      "",
      "48 Berapa Persen dari 64 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_048",
      "/berapa-persen-dari/048-25-berapa-persen-dari-60",
      "25 Berapa Persen dari 60?",
      "",
      "25 Berapa Persen dari 60 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_049",
      "/berapa-persen-dari/049-700-berapa-persen-dari-150",
      "700 Berapa Persen dari 150?",
      "",
      "700 Berapa Persen dari 150 = ...",
      ["Berapa Persen dari"],
      "",
    ],
    [
      "persen_050",
      "/150persen/050-9-adalah-150-persen-dari",
      "9 adalah 150 Persen dari 150?",
      "",
      "150 % dari ... = 9",
      ["150 Persen"],
      "",
    ],

    [
      "persen_051",
      "/pecahan-persen/051-persen-dari-4per5",
      "4/5 = ... %",
      "",
      "persen dari 4/5",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_053",
      "/pecahan-persen/052-persen-dari-3per8",
      "3/8 = ... %",
      "",
      "persen dari 3/8",
      ["Pecahan - Persen"],
      "",
    ],    
    [
      "persen_053",
      "/pecahan-persen/053-persen-dari-1per5",
      "1/5 = ... %",
      "",
      "persen dari 1/5",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_054",
      "/pecahan-persen/054-persen-dari-2per5",
      "2/5 = ... %",
      "",
      "persen dari 2/5",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_055",
      "/pecahan-persen/055-persen-dari-3per5",
      "3/5 = ... %",
      "",
      "persen dari 3/5",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_056",
      "/pecahan-persen/056-persen-dari-1per2",
      "1/2 = ... %",
      "",
      "persen dari 1/2",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_057",
      "/pecahan-persen/057-persen-dari-1per3",
      "1/3 = ... %",
      "",
      "persen dari 1/3",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_058",
      "/pecahan-persen/058-persen-dari-2per3",
      "2/3 = ... %",
      "",
      "persen dari 2/3",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_059",
      "/pecahan-persen/059-persen-dari-1per4",
      "1/4 = ... %",
      "",
      "persen dari 1/4",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_060",
      "/pecahan-persen/060-persen-dari-2per4",
      "2/4 = ... %",
      "",
      "persen dari 2/4",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_061",
      "/pecahan-persen/061-persen-dari-3per4",
      "3/4 = ... %",
      "",
      "persen dari 3/4",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_062",
      "/pecahan-persen/062-persen-dari-1per6",
      "1/6 = ... %",
      "",
      "persen dari 1/6",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_063",
      "/pecahan-persen/063-persen-dari-2per6",
      "2/6 = ... %",
      "",
      "persen dari 2/6",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_064",
      "/pecahan-persen/064-persen-dari-3per6",
      "3/6 = ... %",
      "",
      "persen dari 3/6",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_065",
      "/pecahan-persen/065-persen-dari-4per6",
      "4/6 = ... %",
      "",
      "persen dari 4/6",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_066",
      "/pecahan-persen/066-persen-dari-5per6",
      "5/6 = ... %",
      "",
      "persen dari 5/6",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_067",
      "/pecahan-persen/067-persen-dari-1per7",
      "1/7 = ... %",
      "",
      "persen dari 1/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_068",
      "/pecahan-persen/068-persen-dari-2per7",
      "2/7 = ... %",
      "",
      "persen dari 2/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_069",
      "/pecahan-persen/069-persen-dari-3per7",
      "3/7 = ... %",
      "",
      "persen dari 3/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_070",
      "/pecahan-persen/070-persen-dari-4per7",
      "4/7 = ... %",
      "",
      "persen dari 4/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_071",
      "/pecahan-persen/071-persen-dari-5per7",
      "5/7 = ... %",
      "",
      "persen dari 5/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_072",
      "/pecahan-persen/072-persen-dari-6per7",
      "6/7 = ... %",
      "",
      "persen dari 6/7",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_073",
      "/pecahan-persen/073-persen-dari-1per8",
      "1/8 = ... %",
      "",
      "persen dari 1/8",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_074",
      "/pecahan-persen/074-persen-dari-2per8",
      "2/8 = ... %",
      "",
      "persen dari 2/8",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_075",
      "/pecahan-persen/075-persen-dari-4per8",
      "4/8 = ... %",
      "",
      "persen dari 4/8",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_076",
      "/pecahan-persen/076-persen-dari-5per8",
      "5/8 = ... %",
      "",
      "persen dari 5/8",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_077",
      "/pecahan-persen/077-persen-dari-6per8",
      "6/8 = ... %",
      "",
      "persen dari 6/8",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_078",
      "/pecahan-persen/078-persen-dari-7per8",
      "7/8 = ... %",
      "",
      "persen dari 7/8",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_079",
      "/pecahan-persen/079-persen-dari-1per9",
      "1/9 = ... %",
      "",
      "persen dari 1/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_080",
      "/pecahan-persen/080-persen-dari-2per9",
      "2/9 = ... %",
      "",
      "persen dari 2/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_081",
      "/pecahan-persen/081-persen-dari-3per9",
      "3/9 = ... %",
      "",
      "persen dari 3/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_082",
      "/pecahan-persen/082-persen-dari-4per9",
      "4/9 = ... %",
      "",
      "persen dari 4/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_083",
      "/pecahan-persen/083-persen-dari-5per9",
      "5/9 = ... %",
      "",
      "persen dari 5/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_084",
      "/pecahan-persen/084-persen-dari-6per9",
      "6/9 = ... %",
      "",
      "persen dari 6/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_085",
      "/pecahan-persen/085-persen-dari-7per9",
      "7/9 = ... %",
      "",
      "persen dari 7/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_086",
      "/pecahan-persen/086-persen-dari-8per9",
      "8/9 = ... %",
      "",
      "persen dari 8/9",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_087",
      "/pecahan-persen/087-persen-dari-1per10",
      "1/10 = ... %",
      "",
      "persen dari 1/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_088",
      "/pecahan-persen/088-persen-dari-2per10",
      "2/10 = ... %",
      "",
      "persen dari 2/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_089",
      "/pecahan-persen/089-persen-dari-3per10",
      "3/10 = ... %",
      "",
      "persen dari 3/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_090",
      "/pecahan-persen/090-persen-dari-4per10",
      "4/10 = ... %",
      "",
      "persen dari 4/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_091",
      "/pecahan-persen/091-persen-dari-5per10",
      "5/10 = ... %",
      "",
      "persen dari 5/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_092",
      "/pecahan-persen/092-persen-dari-6per10",
      "6/10 = ... %",
      "",
      "persen dari 6/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_093",
      "/pecahan-persen/093-persen-dari-7per10",
      "7/10 = ... %",
      "",
      "persen dari 7/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_094",
      "/pecahan-persen/094-persen-dari-8per10",
      "8/10 = ... %",
      "",
      "persen dari 8/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_095",
      "/pecahan-persen/095-persen-dari-9per10",
      "9/10 = ... %",
      "",
      "persen dari 9/10",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_096",
      "/pecahan-persen/096-persen-dari-1per12",
      "1/12 = ... %",
      "",
      "persen dari 1/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_097",
      "/pecahan-persen/097-persen-dari-2per12",
      "2/12 = ... %",
      "",
      "persen dari 2/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_098",
      "/pecahan-persen/098-persen-dari-3per12",
      "3/12 = ... %",
      "",
      "persen dari 3/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_099",
      "/pecahan-persen/099-persen-dari-4per12",
      "4/12 = ... %",
      "",
      "persen dari 4/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_100",
      "/pecahan-persen/100-persen-dari-5per12",
      "5/12 = ... %",
      "",
      "persen dari 5/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_101",
      "/pecahan-persen/101-persen-dari-6per12",
      "6/12 = ... %",
      "",
      "persen dari 6/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_102",
      "/pecahan-persen/102-persen-dari-7per12",
      "7/12 = ... %",
      "",
      "persen dari 7/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_103",
      "/pecahan-persen/103-persen-dari-8per12",
      "8/12 = ... %",
      "",
      "persen dari 8/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_104",
      "/pecahan-persen/104-persen-dari-9per12",
      "9/12 = ... %",
      "",
      "persen dari 9/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_105",
      "/pecahan-persen/105-persen-dari-10per12",
      "10/12 = ... %",
      "",
      "persen dari 10/12",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_106",
      "/pecahan-persen/106-persen-dari-11per12",
      "11/12 = ... %",
      "",
      "persen dari 11/12",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_107",
      "/pecahan-persen/107-persen-dari-1per15",
      "1/15 = ... %",
      "",
      "persen dari 1/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_108",
      "/pecahan-persen/108-persen-dari-2per15",
      "2/15 = ... %",
      "",
      "persen dari 2/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_109",
      "/pecahan-persen/109-persen-dari-3per15",
      "3/15 = ... %",
      "",
      "persen dari 3/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_110",
      "/pecahan-persen/110-persen-dari-4per15",
      "4/15 = ... %",
      "",
      "persen dari 4/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_111",
      "/pecahan-persen/111-persen-dari-5per15",
      "5/15 = ... %",
      "",
      "persen dari 5/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_112",
      "/pecahan-persen/112-persen-dari-6per15",
      "6/15 = ... %",
      "",
      "persen dari 6/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_113",
      "/pecahan-persen/113-persen-dari-7per15",
      "7/15 = ... %",
      "",
      "persen dari 7/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_114",
      "/pecahan-persen/114-persen-dari-8per15",
      "8/15 = ... %",
      "",
      "persen dari 8/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_115",
      "/pecahan-persen/115-persen-dari-9per15",
      "9/15 = ... %",
      "",
      "persen dari 9/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_116",
      "/pecahan-persen/116-persen-dari-10per15",
      "10/15 = ... %",
      "",
      "persen dari 10/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_117",
      "/pecahan-persen/117-persen-dari-11per15",
      "11/15 = ... %",
      "",
      "persen dari 11/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_118",
      "/pecahan-persen/118-persen-dari-12per15",
      "12/15 = ... %",
      "",
      "persen dari 12/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_119",
      "/pecahan-persen/119-persen-dari-13per15",
      "13/15 = ... %",
      "",
      "persen dari 13/15",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_120",
      "/pecahan-persen/120-persen-dari-14per15",
      "14/15 = ... %",
      "",
      "persen dari 14/15",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_121",
      "/pecahan-persen/121-persen-dari-1per16",
      "1/16 = ... %",
      "",
      "persen dari 1/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_122",
      "/pecahan-persen/122-persen-dari-2per16",
      "2/16 = ... %",
      "",
      "persen dari 2/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_123",
      "/pecahan-persen/123-persen-dari-3per16",
      "3/16 = ... %",
      "",
      "persen dari 3/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_124",
      "/pecahan-persen/124-persen-dari-4per16",
      "4/16 = ... %",
      "",
      "persen dari 4/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_125",
      "/pecahan-persen/125-persen-dari-5per16",
      "5/16 = ... %",
      "",
      "persen dari 5/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_126",
      "/pecahan-persen/126-persen-dari-6per16",
      "6/16 = ... %",
      "",
      "persen dari 6/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_127",
      "/pecahan-persen/127-persen-dari-7per16",
      "7/16 = ... %",
      "",
      "persen dari 7/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_128",
      "/pecahan-persen/128-persen-dari-8per16",
      "8/16 = ... %",
      "",
      "persen dari 8/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_129",
      "/pecahan-persen/129-persen-dari-9per16",
      "9/16 = ... %",
      "",
      "persen dari 9/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_130",
      "/pecahan-persen/130-persen-dari-10per16",
      "10/16 = ... %",
      "",
      "persen dari 10/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_131",
      "/pecahan-persen/131-persen-dari-11per16",
      "11/16 = ... %",
      "",
      "persen dari 11/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_132",
      "/pecahan-persen/132-persen-dari-12per16",
      "12/16 = ... %",
      "",
      "persen dari 12/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_133",
      "/pecahan-persen/133-persen-dari-13per16",
      "13/16 = ... %",
      "",
      "persen dari 13/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_134",
      "/pecahan-persen/134-persen-dari-14per16",
      "14/16 = ... %",
      "",
      "persen dari 14/16",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_135",
      "/pecahan-persen/135-persen-dari-15per16",
      "15/16 = ... %",
      "",
      "persen dari 15/16",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_136",
      "/pecahan-persen/136-persen-dari-1per20",
      "1/20 = ... %",
      "",
      "persen dari 1/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_137",
      "/pecahan-persen/137-persen-dari-2per20",
      "2/20 = ... %",
      "",
      "persen dari 2/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_138",
      "/pecahan-persen/138-persen-dari-3per20",
      "3/20 = ... %",
      "",
      "persen dari 3/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_139",
      "/pecahan-persen/139-persen-dari-4per20",
      "4/20 = ... %",
      "",
      "persen dari 4/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_140",
      "/pecahan-persen/140-persen-dari-5per20",
      "5/20 = ... %",
      "",
      "persen dari 5/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_141",
      "/pecahan-persen/141-persen-dari-6per20",
      "6/20 = ... %",
      "",
      "persen dari 6/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_142",
      "/pecahan-persen/142-persen-dari-7per20",
      "7/20 = ... %",
      "",
      "persen dari 7/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_143",
      "/pecahan-persen/143-persen-dari-8per20",
      "8/20 = ... %",
      "",
      "persen dari 8/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_144",
      "/pecahan-persen/144-persen-dari-9per20",
      "9/20 = ... %",
      "",
      "persen dari 9/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_145",
      "/pecahan-persen/145-persen-dari-10per20",
      "10/20 = ... %",
      "",
      "persen dari 10/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_146",
      "/pecahan-persen/146-persen-dari-11per20",
      "11/20 = ... %",
      "",
      "persen dari 11/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_147",
      "/pecahan-persen/147-persen-dari-12per20",
      "12/20 = ... %",
      "",
      "persen dari 12/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_148",
      "/pecahan-persen/148-persen-dari-13per20",
      "13/20 = ... %",
      "",
      "persen dari 13/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_149",
      "/pecahan-persen/149-persen-dari-14per20",
      "14/20 = ... %",
      "",
      "persen dari 14/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_150",
      "/pecahan-persen/150-persen-dari-15per20",
      "15/20 = ... %",
      "",
      "persen dari 15/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_151",
      "/pecahan-persen/151-persen-dari-16per20",
      "16/20 = ... %",
      "",
      "persen dari 16/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_152",
      "/pecahan-persen/152-persen-dari-17per20",
      "17/20 = ... %",
      "",
      "persen dari 17/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_153",
      "/pecahan-persen/153-persen-dari-18per20",
      "18/20 = ... %",
      "",
      "persen dari 18/20",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_154",
      "/pecahan-persen/154-persen-dari-19per20",
      "19/20 = ... %",
      "",
      "persen dari 19/20",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_155",
      "/pecahan-persen/155-persen-dari-1per25",
      "1/25 = ... %",
      "",
      "persen dari 1/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_156",
      "/pecahan-persen/156-persen-dari-2per25",
      "2/25 = ... %",
      "",
      "persen dari 2/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_157",
      "/pecahan-persen/157-persen-dari-3per25",
      "3/25 = ... %",
      "",
      "persen dari 3/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_158",
      "/pecahan-persen/158-persen-dari-4per25",
      "4/25 = ... %",
      "",
      "persen dari 4/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_159",
      "/pecahan-persen/159-persen-dari-5per25",
      "5/25 = ... %",
      "",
      "persen dari 5/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_160",
      "/pecahan-persen/160-persen-dari-6per25",
      "6/25 = ... %",
      "",
      "persen dari 6/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_161",
      "/pecahan-persen/161-persen-dari-7per25",
      "7/25 = ... %",
      "",
      "persen dari 7/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_162",
      "/pecahan-persen/162-persen-dari-8per25",
      "8/25 = ... %",
      "",
      "persen dari 8/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_163",
      "/pecahan-persen/163-persen-dari-9per25",
      "9/25 = ... %",
      "",
      "persen dari 9/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_164",
      "/pecahan-persen/164-persen-dari-10per25",
      "10/25 = ... %",
      "",
      "persen dari 10/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_165",
      "/pecahan-persen/165-persen-dari-11per25",
      "11/25 = ... %",
      "",
      "persen dari 11/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_166",
      "/pecahan-persen/166-persen-dari-12per25",
      "12/25 = ... %",
      "",
      "persen dari 12/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_167",
      "/pecahan-persen/167-persen-dari-13per25",
      "13/25 = ... %",
      "",
      "persen dari 13/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_168",
      "/pecahan-persen/168-persen-dari-14per25",
      "14/25 = ... %",
      "",
      "persen dari 14/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_169",
      "/pecahan-persen/169-persen-dari-15per25",
      "15/25 = ... %",
      "",
      "persen dari 15/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_170",
      "/pecahan-persen/170-persen-dari-16per25",
      "16/25 = ... %",
      "",
      "persen dari 16/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_171",
      "/pecahan-persen/171-persen-dari-17per25",
      "17/25 = ... %",
      "",
      "persen dari 17/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_172",
      "/pecahan-persen/172-persen-dari-18per25",
      "18/25 = ... %",
      "",
      "persen dari 18/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_173",
      "/pecahan-persen/173-persen-dari-19per25",
      "19/25 = ... %",
      "",
      "persen dari 19/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_174",
      "/pecahan-persen/174-persen-dari-20per25",
      "20/25 = ... %",
      "",
      "persen dari 20/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_175",
      "/pecahan-persen/175-persen-dari-21per25",
      "21/25 = ... %",
      "",
      "persen dari 21/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_176",
      "/pecahan-persen/176-persen-dari-22per25",
      "22/25 = ... %",
      "",
      "persen dari 22/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_177",
      "/pecahan-persen/177-persen-dari-23per25",
      "23/25 = ... %",
      "",
      "persen dari 23/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_178",
      "/pecahan-persen/178-persen-dari-24per25",
      "24/25 = ... %",
      "",
      "persen dari 24/25",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_179",
      "/pecahan-persen/179-persen-dari-1per40",
      "1/40 = ... %",
      "",
      "persen dari 1/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_180",
      "/pecahan-persen/180-persen-dari-2per40",
      "2/40 = ... %",
      "",
      "persen dari 2/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_181",
      "/pecahan-persen/181-persen-dari-3per40",
      "3/40 = ... %",
      "",
      "persen dari 3/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_182",
      "/pecahan-persen/182-persen-dari-4per40",
      "4/40 = ... %",
      "",
      "persen dari 4/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_183",
      "/pecahan-persen/183-persen-dari-5per40",
      "5/40 = ... %",
      "",
      "persen dari 5/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_184",
      "/pecahan-persen/184-persen-dari-6per40",
      "6/40 = ... %",
      "",
      "persen dari 6/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_185",
      "/pecahan-persen/185-persen-dari-7per40",
      "7/40 = ... %",
      "",
      "persen dari 7/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_186",
      "/pecahan-persen/186-persen-dari-8per40",
      "8/40 = ... %",
      "",
      "persen dari 8/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_187",
      "/pecahan-persen/187-persen-dari-9per40",
      "9/40 = ... %",
      "",
      "persen dari 9/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_188",
      "/pecahan-persen/188-persen-dari-10per40",
      "10/40 = ... %",
      "",
      "persen dari 10/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_189",
      "/pecahan-persen/189-persen-dari-11per40",
      "11/40 = ... %",
      "",
      "persen dari 11/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_190",
      "/pecahan-persen/190-persen-dari-12per40",
      "12/40 = ... %",
      "",
      "persen dari 12/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_191",
      "/pecahan-persen/191-persen-dari-13per40",
      "13/40 = ... %",
      "",
      "persen dari 13/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_192",
      "/pecahan-persen/192-persen-dari-14per40",
      "14/40 = ... %",
      "",
      "persen dari 14/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_193",
      "/pecahan-persen/193-persen-dari-15per40",
      "15/40 = ... %",
      "",
      "persen dari 15/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_194",
      "/pecahan-persen/194-persen-dari-16per40",
      "16/40 = ... %",
      "",
      "persen dari 16/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_195",
      "/pecahan-persen/195-persen-dari-17per40",
      "17/40 = ... %",
      "",
      "persen dari 17/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_196",
      "/pecahan-persen/196-persen-dari-18per40",
      "18/40 = ... %",
      "",
      "persen dari 18/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_197",
      "/pecahan-persen/197-persen-dari-19per40",
      "19/40 = ... %",
      "",
      "persen dari 19/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_198",
      "/pecahan-persen/198-persen-dari-20per40",
      "20/40 = ... %",
      "",
      "persen dari 20/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_199",
      "/pecahan-persen/199-persen-dari-21per40",
      "21/40 = ... %",
      "",
      "persen dari 21/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_200",
      "/pecahan-persen/200-persen-dari-22per40",
      "22/40 = ... %",
      "",
      "persen dari 22/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_201",
      "/pecahan-persen/201-persen-dari-23per40",
      "23/40 = ... %",
      "",
      "persen dari 23/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_202",
      "/pecahan-persen/202-persen-dari-24per40",
      "24/40 = ... %",
      "",
      "persen dari 24/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_203",
      "/pecahan-persen/203-persen-dari-25per40",
      "25/40 = ... %",
      "",
      "persen dari 25/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_204",
      "/pecahan-persen/204-persen-dari-26per40",
      "26/40 = ... %",
      "",
      "persen dari 26/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_205",
      "/pecahan-persen/205-persen-dari-27per40",
      "27/40 = ... %",
      "",
      "persen dari 27/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_206",
      "/pecahan-persen/206-persen-dari-28per40",
      "28/40 = ... %",
      "",
      "persen dari 28/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_207",
      "/pecahan-persen/207-persen-dari-29per40",
      "29/40 = ... %",
      "",
      "persen dari 29/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_208",
      "/pecahan-persen/208-persen-dari-30per40",
      "30/40 = ... %",
      "",
      "persen dari 30/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_209",
      "/pecahan-persen/209-persen-dari-31per40",
      "31/40 = ... %",
      "",
      "persen dari 31/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_210",
      "/pecahan-persen/210-persen-dari-32per40",
      "32/40 = ... %",
      "",
      "persen dari 32/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_211",
      "/pecahan-persen/211-persen-dari-33per40",
      "33/40 = ... %",
      "",
      "persen dari 33/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_212",
      "/pecahan-persen/212-persen-dari-34per40",
      "34/40 = ... %",
      "",
      "persen dari 34/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_213",
      "/pecahan-persen/213-persen-dari-35per40",
      "35/40 = ... %",
      "",
      "persen dari 35/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_214",
      "/pecahan-persen/214-persen-dari-36per40",
      "36/40 = ... %",
      "",
      "persen dari 36/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_215",
      "/pecahan-persen/215-persen-dari-37per40",
      "37/40 = ... %",
      "",
      "persen dari 37/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_216",
      "/pecahan-persen/216-persen-dari-38per40",
      "38/40 = ... %",
      "",
      "persen dari 38/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_217",
      "/pecahan-persen/217-persen-dari-39per40",
      "39/40 = ... %",
      "",
      "persen dari 39/40",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_218",
      "/pecahan-persen/218-persen-dari-1per50",
      "1/50 = ... %",
      "",
      "persen dari 1/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_219",
      "/pecahan-persen/219-persen-dari-2per50",
      "2/50 = ... %",
      "",
      "persen dari 2/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_220",
      "/pecahan-persen/220-persen-dari-3per50",
      "3/50 = ... %",
      "",
      "persen dari 3/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_221",
      "/pecahan-persen/221-persen-dari-4per50",
      "4/50 = ... %",
      "",
      "persen dari 4/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_222",
      "/pecahan-persen/222-persen-dari-5per50",
      "5/50 = ... %",
      "",
      "persen dari 5/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_223",
      "/pecahan-persen/223-persen-dari-6per50",
      "6/50 = ... %",
      "",
      "persen dari 6/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_224",
      "/pecahan-persen/224-persen-dari-7per50",
      "7/50 = ... %",
      "",
      "persen dari 7/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_225",
      "/pecahan-persen/225-persen-dari-8per50",
      "8/50 = ... %",
      "",
      "persen dari 8/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_226",
      "/pecahan-persen/226-persen-dari-9per50",
      "9/50 = ... %",
      "",
      "persen dari 9/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_227",
      "/pecahan-persen/227-persen-dari-10per50",
      "10/50 = ... %",
      "",
      "persen dari 10/50",
      ["Pecahan - Persen"],
      "",
    ],

    [
      "persen_228",
      "/pecahan-persen/228-persen-dari-11per50",
      "11/50 = ... %",
      "",
      "persen dari 11/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_229",
      "/pecahan-persen/229-persen-dari-12per50",
      "12/50 = ... %",
      "",
      "persen dari 12/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_230",
      "/pecahan-persen/230-persen-dari-13per50",
      "13/50 = ... %",
      "",
      "persen dari 13/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_231",
      "/pecahan-persen/231-persen-dari-14per50",
      "14/50 = ... %",
      "",
      "persen dari 14/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_232",
      "/pecahan-persen/232-persen-dari-15per50",
      "15/50 = ... %",
      "",
      "persen dari 15/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_233",
      "/pecahan-persen/233-persen-dari-16per50",
      "16/50 = ... %",
      "",
      "persen dari 16/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_234",
      "/pecahan-persen/234-persen-dari-17per50",
      "17/50 = ... %",
      "",
      "persen dari 17/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_235",
      "/pecahan-persen/235-persen-dari-18per50",
      "18/50 = ... %",
      "",
      "persen dari 18/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_236",
      "/pecahan-persen/236-persen-dari-19per50",
      "19/50 = ... %",
      "",
      "persen dari 19/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_237",
      "/pecahan-persen/237-persen-dari-20per50",
      "20/50 = ... %",
      "",
      "persen dari 20/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_238",
      "/pecahan-persen/238-persen-dari-21per50",
      "21/50 = ... %",
      "",
      "persen dari 21/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_239",
      "/pecahan-persen/239-persen-dari-22per50",
      "22/50 = ... %",
      "",
      "persen dari 22/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_240",
      "/pecahan-persen/240-persen-dari-23per50",
      "23/50 = ... %",
      "",
      "persen dari 23/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_241",
      "/pecahan-persen/241-persen-dari-24per50",
      "24/50 = ... %",
      "",
      "persen dari 24/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_242",
      "/pecahan-persen/242-persen-dari-25per50",
      "25/50 = ... %",
      "",
      "persen dari 25/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_243",
      "/pecahan-persen/243-persen-dari-26per50",
      "26/50 = ... %",
      "",
      "persen dari 26/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_244",
      "/pecahan-persen/244-persen-dari-27per50",
      "27/50 = ... %",
      "",
      "persen dari 27/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_245",
      "/pecahan-persen/245-persen-dari-28per50",
      "28/50 = ... %",
      "",
      "persen dari 28/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_246",
      "/pecahan-persen/246-persen-dari-29per50",
      "29/50 = ... %",
      "",
      "persen dari 29/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_247",
      "/pecahan-persen/247-persen-dari-30per50",
      "30/50 = ... %",
      "",
      "persen dari 30/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_247",
      "/pecahan-persen/247-persen-dari-30per50",
      "30/50 = ... %",
      "",
      "persen dari 30/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_248",
      "/pecahan-persen/248-persen-dari-31per50",
      "31/50 = ... %",
      "",
      "persen dari 31/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_249",
      "/pecahan-persen/249-persen-dari-32per50",
      "32/50 = ... %",
      "",
      "persen dari 32/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_250",
      "/pecahan-persen/250-persen-dari-33per50",
      "33/50 = ... %",
      "",
      "persen dari 33/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_251",
      "/pecahan-persen/251-persen-dari-34per50",
      "34/50 = ... %",
      "",
      "persen dari 34/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_252",
      "/pecahan-persen/252-persen-dari-35per50",
      "35/50 = ... %",
      "",
      "persen dari 35/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_253",
      "/pecahan-persen/253-persen-dari-36per50",
      "36/50 = ... %",
      "",
      "persen dari 36/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_254",
      "/pecahan-persen/254-persen-dari-37per50",
      "37/50 = ... %",
      "",
      "persen dari 37/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_255",
      "/pecahan-persen/255-persen-dari-38per50",
      "38/50 = ... %",
      "",
      "persen dari 38/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_256",
      "/pecahan-persen/256-persen-dari-39per50",
      "39/50 = ... %",
      "",
      "persen dari 39/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_257",
      "/pecahan-persen/257-persen-dari-40per50",
      "40/50 = ... %",
      "",
      "persen dari 40/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_258",
      "/pecahan-persen/258-persen-dari-41per50",
      "41/50 = ... %",
      "",
      "persen dari 41/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_259",
      "/pecahan-persen/259-persen-dari-42per50",
      "42/50 = ... %",
      "",
      "persen dari 42/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_260",
      "/pecahan-persen/260-persen-dari-43per50",
      "43/50 = ... %",
      "",
      "persen dari 43/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_261",
      "/pecahan-persen/261-persen-dari-44per50",
      "44/50 = ... %",
      "",
      "persen dari 44/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_262",
      "/pecahan-persen/262-persen-dari-45per50",
      "44/50 = ... %",
      "",
      "persen dari 45/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_263",
      "/pecahan-persen/263-persen-dari-46per50",
      "46/50 = ... %",
      "",
      "persen dari 46/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_264",
      "/pecahan-persen/264-persen-dari-47per50",
      "47/50 = ... %",
      "",
      "persen dari 47/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_265",
      "/pecahan-persen/265-persen-dari-48per50",
      "48/50 = ... %",
      "",
      "persen dari 48/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_266",
      "/pecahan-persen/266-persen-dari-49per50",
      "49/50 = ... %",
      "",
      "persen dari 49/50",
      ["Pecahan - Persen"],
      "",
    ],
    [
      "persen_267",
      "/2,5persen/267-2,5-persen-dari-2-milyar",
      "Berapa 2.5 Persen dari 2 Milyar ?",
      "",
      "2.5 % dari 2 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_268",
      "/2,5persen/268-2,5-persen-dari-3-milyar",
      "Berapa 2.5 Persen dari 3 Milyar ?",
      "",
      "2.5 % dari 3 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_269",
      "/2,5persen/269-2,5-persen-dari-4-milyar",
      "Berapa 2.5 Persen dari 4 Milyar ?",
      "",
      "2.5 % dari 4 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_270",
      "/2,5persen/270-2,5-persen-dari-5-milyar",
      "Berapa 2.5 Persen dari 5 Milyar ?",
      "",
      "2.5 % dari 5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_271",
      "/2,5persen/271-2,5-persen-dari-6-milyar",
      "Berapa 2.5 Persen dari 6 Milyar ?",
      "",
      "2.5 % dari 6 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_272",
      "/2,5persen/272-2,5-persen-dari-7-milyar",
      "Berapa 2.5 Persen dari 7 Milyar ?",
      "",
      "2.5 % dari 7 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_273",
      "/2,5persen/273-2,5-persen-dari-8-milyar",
      "Berapa 2.5 Persen dari 8 Milyar ?",
      "",
      "2.5 % dari 8 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_274",
      "/2,5persen/274-2,5-persen-dari-9-milyar",
      "Berapa 2.5 Persen dari 9 Milyar ?",
      "",
      "2.5 % dari 9 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_275",
      "/2,5persen/275-2,5-persen-dari-10-milyar",
      "Berapa 2.5 Persen dari 10 Milyar ?",
      "",
      "2.5 % dari 10 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_276",
      "/2,5persen/276-2,5-persen-dari-20-milyar",
      "Berapa 2.5 Persen dari 20 Milyar ?",
      "",
      "2.5 % dari 20 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_277",
      "/2,5persen/277-2,5-persen-dari-1,5-milyar",
      "Berapa 2.5 Persen dari 1.5 Milyar ?",
      "",
      "2.5 % dari 1.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_278",
      "/2,5persen/278-2,5-persen-dari-2,5-milyar",
      "Berapa 2.5 Persen dari 2.5 Milyar ?",
      "",
      "2.5 % dari 2.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_279",
      "/2,5persen/279-2,5-persen-dari-3,5-milyar",
      "Berapa 2.5 Persen dari 3.5 Milyar ?",
      "",
      "2.5 % dari 3.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_280",
      "/2,5persen/280-2,5-persen-dari-4,5-milyar",
      "Berapa 2.5 Persen dari 4.5 Milyar ?",
      "",
      "2.5 % dari 4.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_281",
      "/2,5persen/281-2,5-persen-dari-5,5-milyar",
      "Berapa 2.5 Persen dari 5.5 Milyar ?",
      "",
      "2.5 % dari 5.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_282",
      "/2,5persen/282-2,5-persen-dari-6,5-milyar",
      "Berapa 2.5 Persen dari 6.5 Milyar ?",
      "",
      "2.5 % dari 6.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_283",
      "/2,5persen/283-2,5-persen-dari-7,5-milyar",
      "Berapa 2.5 Persen dari 7.5 Milyar ?",
      "",
      "2.5 % dari 7.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_284",
      "/2,5persen/284-2,5-persen-dari-8,5-milyar",
      "Berapa 2.5 Persen dari 8.5 Milyar ?",
      "",
      "2.5 % dari 8.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_285",
      "/2,5persen/285-2,5-persen-dari-9,5-milyar",
      "Berapa 2.5 Persen dari 9.5 Milyar ?",
      "",
      "2.5 % dari 9.5 Milyar = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_286",
      "/2,5persen/286-2,5-persen-dari-6-juta",
      "Berapa 2.5 Persen dari 6 Juta ?",
      "",
      "2.5 % dari 6 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_287",
      "/2,5persen/287-2,5-persen-dari-7-juta",
      "Berapa 2.5 Persen dari 7 Juta ?",
      "",
      "2.5 % dari 7 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_288",
      "/2,5persen/288-2,5-persen-dari-8-juta",
      "Berapa 2.5 Persen dari 8 Juta ?",
      "",
      "2.5 % dari 8 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_289",
      "/2,5persen/289-2,5-persen-dari-9-juta",
      "Berapa 2.5 Persen dari 9 Juta ?",
      "",
      "2.5 % dari 9 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_290",
      "/2,5persen/290-2,5-persen-dari-10-juta",
      "Berapa 2.5 Persen dari 10 Juta ?",
      "",
      "2.5 % dari 10 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_291",
      "/2,5persen/291-2,5-persen-dari-100-ribu",
      "Berapa 2.5 Persen dari 100 ribu ?",
      "",
      "2.5 % dari 100 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_292",
      "/2,5persen/292-2,5-persen-dari-200-ribu",
      "Berapa 2.5 Persen dari 200 ribu ?",
      "",
      "2.5 % dari 200 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_293",
      "/2,5persen/293-2,5-persen-dari-300-ribu",
      "Berapa 2.5 Persen dari 300 ribu ?",
      "",
      "2.5 % dari 300 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_294",
      "/2,5persen/294-2,5-persen-dari-400-ribu",
      "Berapa 2.5 Persen dari 400 ribu ?",
      "",
      "2.5 % dari 400 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_295",
      "/2,5persen/295-2,5-persen-dari-600-ribu",
      "Berapa 2.5 Persen dari 600 ribu ?",
      "",
      "2.5 % dari 600 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_296",
      "/2,5persen/296-2,5-persen-dari-700-ribu",
      "Berapa 2.5 Persen dari 700 ribu ?",
      "",
      "2.5 % dari 700 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_297",
      "/2,5persen/297-2,5-persen-dari-800-ribu",
      "Berapa 2.5 Persen dari 800 ribu ?",
      "",
      "2.5 % dari 800 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_298",
      "/2,5persen/298-2,5-persen-dari-900-ribu",
      "Berapa 2.5 Persen dari 900 ribu ?",
      "",
      "2.5 % dari 900 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_299",
      "/2,5persen/299-2,5-persen-dari-20-juta",
      "Berapa 2.5 Persen dari 20 Juta ?",
      "",
      "2.5 % dari 20 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_300",
      "/2,5persen/300-2,5-persen-dari-30-juta",
      "Berapa 2.5 Persen dari 30 Juta ?",
      "",
      "2.5 % dari 30 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_301",
      "/2,5persen/301-2,5-persen-dari-40-juta",
      "Berapa 2.5 Persen dari 40 Juta ?",
      "",
      "2.5 % dari 40 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_302",
      "/2,5persen/302-2,5-persen-dari-50-juta",
      "Berapa 2.5 Persen dari 50 Juta ?",
      "",
      "2.5 % dari 50 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_303",
      "/2,5persen/303-2,5-persen-dari-60-juta",
      "Berapa 2.5 Persen dari 60 Juta ?",
      "",
      "2.5 % dari 60 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_304",
      "/2,5persen/304-2,5-persen-dari-70-juta",
      "Berapa 2.5 Persen dari 70 Juta ?",
      "",
      "2.5 % dari 70 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_305",
      "/2,5persen/305-2,5-persen-dari-80-juta",
      "Berapa 2.5 Persen dari 80 Juta ?",
      "",
      "2.5 % dari 80 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_306",
      "/2,5persen/306-2,5-persen-dari-90-juta",
      "Berapa 2.5 Persen dari 90 Juta ?",
      "",
      "2.5 % dari 90 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_307",
      "/2,5persen/307-2,5-persen-dari-200-juta",
      "Berapa 2.5 Persen dari 200 Juta ?",
      "",
      "2.5 % dari 200 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_308",
      "/2,5persen/308-2,5-persen-dari-300-juta",
      "Berapa 2.5 Persen dari 300 Juta ?",
      "",
      "2.5 % dari 300 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_309",
      "/2,5persen/309-2,5-persen-dari-400-juta",
      "Berapa 2.5 Persen dari 400 Juta ?",
      "",
      "2.5 % dari 400 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_310",
      "/2,5persen/310-2,5-persen-dari-500-juta",
      "Berapa 2.5 Persen dari 500 Juta ?",
      "",
      "2.5 % dari 500 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_311",
      "/2,5persen/311-2,5-persen-dari-600-juta",
      "Berapa 2.5 Persen dari 600 Juta ?",
      "",
      "2.5 % dari 600 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_312",
      "/2,5persen/312-2,5-persen-dari-700-juta",
      "Berapa 2.5 Persen dari 700 Juta ?",
      "",
      "2.5 % dari 700 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_313",
      "/2,5persen/313-2,5-persen-dari-800-juta",
      "Berapa 2.5 Persen dari 800 Juta ?",
      "",
      "2.5 % dari 800 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_314",
      "/2,5persen/314-2,5-persen-dari-900-juta",
      "Berapa 2.5 Persen dari 900 Juta ?",
      "",
      "2.5 % dari 900 Juta = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_315",
      "/2,5persen/315-2,5-persen-dari-10-ribu",
      "Berapa 2.5 Persen dari 10 ribu ?",
      "",
      "2.5 % dari 10 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_316",
      "/2,5persen/316-2,5-persen-dari-20-ribu",
      "Berapa 2.5 Persen dari 20 ribu ?",
      "",
      "2.5 % dari 20 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_317",
      "/2,5persen/317-2,5-persen-dari-30-ribu",
      "Berapa 2.5 Persen dari 30 ribu ?",
      "",
      "2.5 % dari 30 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_318",
      "/2,5persen/318-2,5-persen-dari-40-ribu",
      "Berapa 2.5 Persen dari 40 ribu ?",
      "",
      "2.5 % dari 40 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_319",
      "/2,5persen/319-2,5-persen-dari-50-ribu",
      "Berapa 2.5 Persen dari 50 ribu ?",
      "",
      "2.5 % dari 50 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_320",
      "/2,5persen/320-2,5-persen-dari-60-ribu",
      "Berapa 2.5 Persen dari 60 ribu ?",
      "",
      "2.5 % dari 60 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_321",
      "/2,5persen/321-2,5-persen-dari-70-ribu",
      "Berapa 2.5 Persen dari 70 ribu ?",
      "",
      "2.5 % dari 70 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_322",
      "/2,5persen/322-2,5-persen-dari-80-ribu",
      "Berapa 2.5 Persen dari 80 ribu ?",
      "",
      "2.5 % dari 80 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_323",
      "/2,5persen/323-2,5-persen-dari-90-ribu",
      "Berapa 2.5 Persen dari 90 ribu ?",
      "",
      "2.5 % dari 90 ribu = ...",
      ["2.5 Persen"],
      "",
    ],
    [
      "persen_324",
      "/1persen/324-1-persen-dari-1",
      "Berapa 1 Persen dari 1?",
      "",
      "1 % dari 1 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_325",
      "/1persen/325-1-persen-dari-2",
      "Berapa 1 Persen dari 2?",
      "",
      "1 % dari 2 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_326",
      "/1persen/326-1-persen-dari-3",
      "Berapa 1 Persen dari 3?",
      "",
      "1 % dari 3 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_327",
      "/1persen/327-1-persen-dari-4",
      "Berapa 1 Persen dari 4?",
      "",
      "1 % dari 4 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_328",
      "/1persen/328-1-persen-dari-5",
      "Berapa 1 Persen dari 5?",
      "",
      "1 % dari 5 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_329",
      "/1persen/329-1-persen-dari-6",
      "Berapa 1 Persen dari 6?",
      "",
      "1 % dari 6 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_330",
      "/1persen/330-1-persen-dari-7",
      "Berapa 1 Persen dari 7?",
      "",
      "1 % dari 7 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_331",
      "/1persen/331-1-persen-dari-8",
      "Berapa 1 Persen dari 8?",
      "",
      "1 % dari 8 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_332",
      "/1persen/332-1-persen-dari-9",
      "Berapa 1 Persen dari 9?",
      "",
      "1 % dari 9 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_333",
      "/1persen/333-1-persen-dari-10",
      "Berapa 1 Persen dari 10?",
      "",
      "1 % dari 10 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_334",
      "/1persen/334-1-persen-dari-20",
      "Berapa 1 Persen dari 20?",
      "",
      "1 % dari 20 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_335",
      "/1persen/335-1-persen-dari-30",
      "Berapa 1 Persen dari 30?",
      "",
      "1 % dari 30 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_336",
      "/1persen/336-1-persen-dari-40",
      "Berapa 1 Persen dari 40?",
      "",
      "1 % dari 40 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_337",
      "/1persen/337-1-persen-dari-50",
      "Berapa 1 Persen dari 50?",
      "",
      "1 % dari 50 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_338",
      "/1persen/338-1-persen-dari-60",
      "Berapa 1 Persen dari 60?",
      "",
      "1 % dari 60 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_339",
      "/1persen/339-1-persen-dari-70",
      "Berapa 1 Persen dari 70?",
      "",
      "1 % dari 70 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_340",
      "/1persen/340-1-persen-dari-80",
      "Berapa 1 Persen dari 80?",
      "",
      "1 % dari 80 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_341",
      "/1persen/341-1-persen-dari-90",
      "Berapa 1 Persen dari 90?",
      "",
      "1 % dari 90 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_342",
      "/1persen/342-1-persen-dari-100",
      "Berapa 1 Persen dari 100?",
      "",
      "1 % dari 100 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_343",
      "/1persen/343-1-persen-dari-200",
      "Berapa 1 Persen dari 200?",
      "",
      "1 % dari 200 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_344",
      "/1persen/344-1-persen-dari-300",
      "Berapa 1 Persen dari 300?",
      "",
      "1 % dari 300 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_345",
      "/1persen/345-1-persen-dari-400",
      "Berapa 1 Persen dari 400?",
      "",
      "1 % dari 400 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_346",
      "/1persen/346-1-persen-dari-500",
      "Berapa 1 Persen dari 500?",
      "",
      "1 % dari 500 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_347",
      "/1persen/347-1-persen-dari-600",
      "Berapa 1 Persen dari 600?",
      "",
      "1 % dari 600 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_348",
      "/1persen/348-1-persen-dari-700",
      "Berapa 1 Persen dari 700?",
      "",
      "1 % dari 700 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_349",
      "/1persen/349-1-persen-dari-800",
      "Berapa 1 Persen dari 800?",
      "",
      "1 % dari 800 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_350",
      "/1persen/350-1-persen-dari-900",
      "Berapa 1 Persen dari 900?",
      "",
      "1 % dari 900 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_351",
      "/1persen/351-1-persen-dari-1000",
      "Berapa 1 Persen dari 1000?",
      "",
      "1 % dari 1000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_352",
      "/1persen/352-1-persen-dari-2000",
      "Berapa 1 Persen dari 2000?",
      "",
      "1 % dari 2000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_353",
      "/1persen/353-1-persen-dari-3000",
      "Berapa 1 Persen dari 3000?",
      "",
      "1 % dari 3000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_354",
      "/1persen/354-1-persen-dari-4000",
      "Berapa 1 Persen dari 4000?",
      "",
      "1 % dari 4000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_355",
      "/1persen/355-1-persen-dari-5000",
      "Berapa 1 Persen dari 5000?",
      "",
      "1 % dari 5000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_356",
      "/1persen/356-1-persen-dari-6000",
      "Berapa 1 Persen dari 6000?",
      "",
      "1 % dari 6000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_357",
      "/1persen/357-1-persen-dari-7000",
      "Berapa 1 Persen dari 7000?",
      "",
      "1 % dari 7000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_358",
      "/1persen/358-1-persen-dari-8000",
      "Berapa 1 Persen dari 8000?",
      "",
      "1 % dari 8000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_359",
      "/1persen/359-1-persen-dari-9000",
      "Berapa 1 Persen dari 9000?",
      "",
      "1 % dari 9000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_360",
      "/1persen/360-1-persen-dari-10000",
      "Berapa 1 Persen dari 10 ribu?",
      "",
      "1 % dari 10000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_361",
      "/1persen/361-1-persen-dari-20000",
      "Berapa 1 Persen dari 20 ribu?",
      "",
      "1 % dari 20000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_362",
      "/1persen/362-1-persen-dari-30000",
      "Berapa 1 Persen dari 30 ribu?",
      "",
      "1 % dari 30000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_363",
      "/1persen/363-1-persen-dari-40000",
      "Berapa 1 Persen dari 40 ribu?",
      "",
      "1 % dari 40000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_364",
      "/1persen/364-1-persen-dari-50000",
      "Berapa 1 Persen dari 50 ribu?",
      "",
      "1 % dari 50000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_365",
      "/1persen/365-1-persen-dari-60000",
      "Berapa 1 Persen dari 60 ribu?",
      "",
      "1 % dari 60000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_366",
      "/1persen/366-1-persen-dari-70000",
      "Berapa 1 Persen dari 70 ribu?",
      "",
      "1 % dari 70000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_367",
      "/1persen/367-1-persen-dari-80000",
      "Berapa 1 Persen dari 80 ribu?",
      "",
      "1 % dari 80000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_368",
      "/1persen/368-1-persen-dari-90000",
      "Berapa 1 Persen dari 90 ribu?",
      "",
      "1 % dari 90000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_369",
      "/1persen/369-1-persen-dari-100000",
      "Berapa 1 Persen dari 100 ribu?",
      "",
      "1 % dari 100000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_370",
      "/1persen/370-1-persen-dari-200000",
      "Berapa 1 Persen dari 200 ribu?",
      "",
      "1 % dari 200000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_371",
      "/1persen/371-1-persen-dari-300000",
      "Berapa 1 Persen dari 300 ribu?",
      "",
      "1 % dari 300000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_372",
      "/1persen/372-1-persen-dari-400000",
      "Berapa 1 Persen dari 400 ribu?",
      "",
      "1 % dari 400000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_373",
      "/1persen/373-1-persen-dari-500000",
      "Berapa 1 Persen dari 500 ribu?",
      "",
      "1 % dari 500000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_374",
      "/1persen/374-1-persen-dari-600000",
      "Berapa 1 Persen dari 600 ribu?",
      "",
      "1 % dari 600000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_375",
      "/1persen/375-1-persen-dari-700000",
      "Berapa 1 Persen dari 700 ribu?",
      "",
      "1 % dari 700000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_376",
      "/1persen/376-1-persen-dari-800000",
      "Berapa 1 Persen dari 800 ribu?",
      "",
      "1 % dari 800000 = ...",
      ["1 Persen"],
      "",
    ],
    [
      "persen_377",
      "/1persen/377-1-persen-dari-900000",
      "Berapa 1 Persen dari 900 ribu?",
      "",
      "1 % dari 900000 = ...",
      ["1 Persen"],
      "",
    ],
  
];