var titleCat_1 = "Pecahan";
var cat_1 = [
  ["Desimal - Pecahan Biasa", "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa", ""],
];
var url_root = "https://nasrianas.website/jawab/math/pecahan";
var footerArray = [
    //June2020
    [
      "pecahan_001",
      "/decimal-pecahanBiasa/001-0,75-diubah-menjadi-pecahan-biasa",
      "0.75 Diubah Menjadi Pecahan Biasa",
      "",
      "0.75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_002",
      "/decimal-pecahanBiasa/002-0,25-diubah-menjadi-pecahan-biasa",
      "0.25 Diubah Menjadi Pecahan Biasa",
      "",
      "0.25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_003",
      "/decimal-pecahanBiasa/003-0,72-diubah-menjadi-pecahan-biasa",
      "0.72 Diubah Menjadi Pecahan Biasa",
      "",
      "0.72 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_004",
      "/decimal-pecahanBiasa/004-0,02-diubah-menjadi-pecahan-biasa",
      "0.02 Diubah Menjadi Pecahan Biasa",
      "",
      "0.02 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_005",
      "/decimal-pecahanBiasa/005-0,30-diubah-menjadi-pecahan-biasa",
      "0.30 Diubah Menjadi Pecahan Biasa",
      "",
      "0.30 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_006",
      "/decimal-pecahanBiasa/006-0,2-diubah-menjadi-pecahan-biasa",
      "0.2 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_007",
      "/decimal-pecahanBiasa/007-0,15-diubah-menjadi-pecahan-biasa",
      "0.15 Diubah Menjadi Pecahan Biasa",
      "",
      "0.15 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_008",
      "/decimal-pecahanBiasa/008-0,125-diubah-menjadi-pecahan-biasa",
      "0.125 Diubah Menjadi Pecahan Biasa",
      "",
      "0.125 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_009",
      "/decimal-pecahanBiasa/009-0,3-diubah-menjadi-pecahan-biasa",
      "0.3 Diubah Menjadi Pecahan Biasa",
      "",
      "0.3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_010",
      "/decimal-pecahanBiasa/010-0,4-diubah-menjadi-pecahan-biasa",
      "0.4 Diubah Menjadi Pecahan Biasa",
      "",
      "0.4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_011",
      "/decimal-pecahanBiasa/011-0,50-diubah-menjadi-pecahan-biasa",
      "0.50 Diubah Menjadi Pecahan Biasa",
      "",
      "0.50 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_012",
      "/decimal-pecahanBiasa/012-0,6-diubah-menjadi-pecahan-biasa",
      "0.6 Diubah Menjadi Pecahan Biasa",
      "",
      "0.6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_013",
      "/decimal-pecahanBiasa/013-0,62-diubah-menjadi-pecahan-biasa",
      "0.62 Diubah Menjadi Pecahan Biasa",
      "",
      "0.62 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_014",
      "/decimal-pecahanBiasa/014-0,32-diubah-menjadi-pecahan-biasa",
      "0.32 Diubah Menjadi Pecahan Biasa",
      "",
      "0.32 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_015",
      "/decimal-pecahanBiasa/015-0,875-diubah-menjadi-pecahan-biasa",
      "0.875 Diubah Menjadi Pecahan Biasa",
      "",
      "0.875 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_016",
      "/decimal-pecahanBiasa/016-0,625-diubah-menjadi-pecahan-biasa",
      "0.625 Diubah Menjadi Pecahan Biasa",
      "",
      "0.625 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_017",
      "/decimal-pecahanBiasa/017-0,375-diubah-menjadi-pecahan-biasa",
      "0.375 Diubah Menjadi Pecahan Biasa",
      "",
      "0.375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_018",
      "/decimal-pecahanBiasa/018-0,8-diubah-menjadi-pecahan-biasa",
      "0.8 Diubah Menjadi Pecahan Biasa",
      "",
      "0.8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_019",
      "/decimal-pecahanBiasa/019-0,45-diubah-menjadi-pecahan-biasa",
      "0.45 Diubah Menjadi Pecahan Biasa",
      "",
      "0.45 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_020",
      "/decimal-pecahanBiasa/020-0,09-diubah-menjadi-pecahan-biasa",
      "0.09 Diubah Menjadi Pecahan Biasa",
      "",
      "0.09 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_021",
      "/decimal-pecahanBiasa/021-0,36-diubah-menjadi-pecahan-biasa",
      "0.36 Diubah Menjadi Pecahan Biasa",
      "",
      "0.36 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_022",
      "/decimal-pecahanBiasa/022-0,5-diubah-menjadi-pecahan-biasa",
      "0.5 Diubah Menjadi Pecahan Biasa",
      "",
      "0.5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_023",
      "/decimal-pecahanBiasa/023-0,65-diubah-menjadi-pecahan-biasa",
      "0.65 Diubah Menjadi Pecahan Biasa",
      "",
      "0.65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_024",
      "/decimal-pecahanBiasa/024-0,01-diubah-menjadi-pecahan-biasa",
      "0.01 Diubah Menjadi Pecahan Biasa",
      "",
      "0.01 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_025",
      "/decimal-pecahanBiasa/025-0,03-diubah-menjadi-pecahan-biasa",
      "0.03 Diubah Menjadi Pecahan Biasa",
      "",
      "0.03 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_026",
      "/decimal-pecahanBiasa/026-0,07-diubah-menjadi-pecahan-biasa",
      "0.07 Diubah Menjadi Pecahan Biasa",
      "",
      "0.07 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_027",
      "/decimal-pecahanBiasa/027-0,04-diubah-menjadi-pecahan-biasa",
      "0.04 Diubah Menjadi Pecahan Biasa",
      "",
      "0.04 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_028",
      "/decimal-pecahanBiasa/028-0,06-diubah-menjadi-pecahan-biasa",
      "0.06 Diubah Menjadi Pecahan Biasa",
      "",
      "0.06 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_029",
      "/decimal-pecahanBiasa/029-0,08-diubah-menjadi-pecahan-biasa",
      "0.08 Diubah Menjadi Pecahan Biasa",
      "",
      "0.08 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_030",
      "/decimal-pecahanBiasa/030-0,12-diubah-menjadi-pecahan-biasa",
      "0.12 Diubah Menjadi Pecahan Biasa",
      "",
      "0.12 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_031",
      "/decimal-pecahanBiasa/031-0,16-diubah-menjadi-pecahan-biasa",
      "0.16 Diubah Menjadi Pecahan Biasa",
      "",
      "0.16 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_032",
      "/decimal-pecahanBiasa/032-0,175-diubah-menjadi-pecahan-biasa",
      "0.175 Diubah Menjadi Pecahan Biasa",
      "",
      "0.175 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_033",
      "/decimal-pecahanBiasa/033-0,1025-diubah-menjadi-pecahan-biasa",
      "0.1025 Diubah Menjadi Pecahan Biasa",
      "",
      "0.1025 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_034",
      "/decimal-pecahanBiasa/034-0,24-diubah-menjadi-pecahan-biasa",
      "0.24 Diubah Menjadi Pecahan Biasa",
      "",
      "0.24 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_035",
      "/decimal-pecahanBiasa/035-0,20-diubah-menjadi-pecahan-biasa",
      "0.20 Diubah Menjadi Pecahan Biasa",
      "",
      "0.20 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_036",
      "/decimal-pecahanBiasa/036-0,2525-diubah-menjadi-pecahan-biasa",
      "0.2525 Diubah Menjadi Pecahan Biasa",
      "",
      "0.2525 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_037",
      "/decimal-pecahanBiasa/037-0,26-diubah-menjadi-pecahan-biasa",
      "0.26 Diubah Menjadi Pecahan Biasa",
      "",
      "0.26 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_038",
      "/decimal-pecahanBiasa/038-0,225-diubah-menjadi-pecahan-biasa",
      "0.225 Diubah Menjadi Pecahan Biasa",
      "",
      "0.225 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_039",
      "/decimal-pecahanBiasa/039-0,21-diubah-menjadi-pecahan-biasa",
      "0.21 Diubah Menjadi Pecahan Biasa",
      "",
      "0.21 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_040",
      "/decimal-pecahanBiasa/040-0,23-diubah-menjadi-pecahan-biasa",
      "0.23 Diubah Menjadi Pecahan Biasa",
      "",
      "0.23 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_041",
      "/decimal-pecahanBiasa/041-0,33-diubah-menjadi-pecahan-biasa",
      "0.33 Diubah Menjadi Pecahan Biasa",
      "",
      "0.33 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_042",
      "/decimal-pecahanBiasa/042-0,333-diubah-menjadi-pecahan-biasa",
      "0.333 Diubah Menjadi Pecahan Biasa",
      "",
      "0.333 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_043",
      "/decimal-pecahanBiasa/043-0,35-diubah-menjadi-pecahan-biasa",
      "0.35 Diubah Menjadi Pecahan Biasa",
      "",
      "0.35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_044",
      "/decimal-pecahanBiasa/044-0,48-diubah-menjadi-pecahan-biasa",
      "0.48 Diubah Menjadi Pecahan Biasa",
      "",
      "0.48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_045",
      "/decimal-pecahanBiasa/045-0,40-diubah-menjadi-pecahan-biasa",
      "0.40 Diubah Menjadi Pecahan Biasa",
      "",
      "0.40 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_046",
      "/decimal-pecahanBiasa/046-0,42-diubah-menjadi-pecahan-biasa",
      "0.42 Diubah Menjadi Pecahan Biasa",
      "",
      "0.42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_047",
      "/decimal-pecahanBiasa/047-0,44-diubah-menjadi-pecahan-biasa",
      "0.44 Diubah Menjadi Pecahan Biasa",
      "",
      "0.44 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_048",
      "/decimal-pecahanBiasa/048-0,46-diubah-menjadi-pecahan-biasa",
      "0.46 Diubah Menjadi Pecahan Biasa",
      "",
      "0.46 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_049",
      "/decimal-pecahanBiasa/049-0,43-diubah-menjadi-pecahan-biasa",
      "0.43 Diubah Menjadi Pecahan Biasa",
      "",
      "0.43 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_050",
      "/decimal-pecahanBiasa/050-0,53-diubah-menjadi-pecahan-biasa",
      "0.53 Diubah Menjadi Pecahan Biasa",
      "",
      "0.53 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_051",
      "/decimal-pecahanBiasa/051-0,52-diubah-menjadi-pecahan-biasa",
      "0.52 Diubah Menjadi Pecahan Biasa",
      "",
      "0.52 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_052",
      "/decimal-pecahanBiasa/052-0,55-diubah-menjadi-pecahan-biasa",
      "0.55 Diubah Menjadi Pecahan Biasa",
      "",
      "0.55 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_053",
      "/decimal-pecahanBiasa/053-0,56-diubah-menjadi-pecahan-biasa",
      "0.56 Diubah Menjadi Pecahan Biasa",
      "",
      "0.56 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_054",
      "/decimal-pecahanBiasa/054-0,58-diubah-menjadi-pecahan-biasa",
      "0.58 Diubah Menjadi Pecahan Biasa",
      "",
      "0.58 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_055",
      "/decimal-pecahanBiasa/055-0,60-diubah-menjadi-pecahan-biasa",
      "0.60 Diubah Menjadi Pecahan Biasa",
      "",
      "0.60 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_056",
      "/decimal-pecahanBiasa/056-0,64-diubah-menjadi-pecahan-biasa",
      "0.64 Diubah Menjadi Pecahan Biasa",
      "",
      "0.64 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_057",
      "/decimal-pecahanBiasa/057-0,66-diubah-menjadi-pecahan-biasa",
      "0.66 Diubah Menjadi Pecahan Biasa",
      "",
      "0.66 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_058",
      "/decimal-pecahanBiasa/058-0,69-diubah-menjadi-pecahan-biasa",
      "0.69 Diubah Menjadi Pecahan Biasa",
      "",
      "0.69 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_059",
      "/decimal-pecahanBiasa/059-0,7-diubah-menjadi-pecahan-biasa",
      "0.7 Diubah Menjadi Pecahan Biasa",
      "",
      "0.7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_060",
      "/decimal-pecahanBiasa/060-0,79-diubah-menjadi-pecahan-biasa",
      "0.79 Diubah Menjadi Pecahan Biasa",
      "",
      "0.79 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_061",
      "/decimal-pecahanBiasa/061-0,70-diubah-menjadi-pecahan-biasa",
      "0.70 Diubah Menjadi Pecahan Biasa",
      "",
      "0.70 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_062",
      "/decimal-pecahanBiasa/062-0,74-diubah-menjadi-pecahan-biasa",
      "0.74 Diubah Menjadi Pecahan Biasa",
      "",
      "0.74 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_063",
      "/decimal-pecahanBiasa/063-0,76-diubah-menjadi-pecahan-biasa",
      "0.76 Diubah Menjadi Pecahan Biasa",
      "",
      "0.76 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_064",
      "/decimal-pecahanBiasa/064-0,725-diubah-menjadi-pecahan-biasa",
      "0.725 Diubah Menjadi Pecahan Biasa",
      "",
      "0.725 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_065",
      "/decimal-pecahanBiasa/065-0,80-diubah-menjadi-pecahan-biasa",
      "0.80 Diubah Menjadi Pecahan Biasa",
      "",
      "0.80 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_066",
      "/decimal-pecahanBiasa/066-0,82-diubah-menjadi-pecahan-biasa",
      "0.82 Diubah Menjadi Pecahan Biasa",
      "",
      "0.82 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_067",
      "/decimal-pecahanBiasa/067-0,84-diubah-menjadi-pecahan-biasa",
      "0.84 Diubah Menjadi Pecahan Biasa",
      "",
      "0.84 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_068",
      "/decimal-pecahanBiasa/068-0,85-diubah-menjadi-pecahan-biasa",
      "0.85 Diubah Menjadi Pecahan Biasa",
      "",
      "0.85 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_069",
      "/decimal-pecahanBiasa/069-0,86-diubah-menjadi-pecahan-biasa",
      "0.86 Diubah Menjadi Pecahan Biasa",
      "",
      "0.86 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_070",
      "/decimal-pecahanBiasa/070-0,88-diubah-menjadi-pecahan-biasa",
      "0.88 Diubah Menjadi Pecahan Biasa",
      "",
      "0.88 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_071",
      "/decimal-pecahanBiasa/071-0,83-diubah-menjadi-pecahan-biasa",
      "0.83 Diubah Menjadi Pecahan Biasa",
      "",
      "0.83 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_072",
      "/decimal-pecahanBiasa/072-0,9-diubah-menjadi-pecahan-biasa",
      "0.9 Diubah Menjadi Pecahan Biasa",
      "",
      "0.9 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_073",
      "/decimal-pecahanBiasa/073-0,90-diubah-menjadi-pecahan-biasa",
      "0.90 Diubah Menjadi Pecahan Biasa",
      "",
      "0.90 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_074",
      "/decimal-pecahanBiasa/074-0,95-diubah-menjadi-pecahan-biasa",
      "0.95 Diubah Menjadi Pecahan Biasa",
      "",
      "0.95 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_075",
      "/decimal-pecahanBiasa/075-0,96-diubah-menjadi-pecahan-biasa",
      "0.96 Diubah Menjadi Pecahan Biasa",
      "",
      "0.96 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_076",
      "/decimal-pecahanBiasa/076-1,15-diubah-menjadi-pecahan-biasa",
      "1.15 Diubah Menjadi Pecahan Biasa",
      "",
      "1.15 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_077",
      "/decimal-pecahanBiasa/077-1,2-diubah-menjadi-pecahan-biasa",
      "1.2 Diubah Menjadi Pecahan Biasa",
      "",
      "1.2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_078",
      "/decimal-pecahanBiasa/078-1,25-diubah-menjadi-pecahan-biasa",
      "1.25 Diubah Menjadi Pecahan Biasa",
      "",
      "1.25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_079",
      "/decimal-pecahanBiasa/079-1,24-diubah-menjadi-pecahan-biasa",
      "1.24 Diubah Menjadi Pecahan Biasa",
      "",
      "1.24 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_080",
      "/decimal-pecahanBiasa/080-1,20-diubah-menjadi-pecahan-biasa",
      "1.20 Diubah Menjadi Pecahan Biasa",
      "",
      "1.20 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_081",
      "/decimal-pecahanBiasa/081-1,29-diubah-menjadi-pecahan-biasa",
      "1.29 Diubah Menjadi Pecahan Biasa",
      "",
      "1.29 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_082",
      "/decimal-pecahanBiasa/082-1,33-diubah-menjadi-pecahan-biasa",
      "1.33 Diubah Menjadi Pecahan Biasa",
      "",
      "1.33 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_083",
      "/decimal-pecahanBiasa/083-1,32-diubah-menjadi-pecahan-biasa",
      "1.32 Diubah Menjadi Pecahan Biasa",
      "",
      "1.32 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_084",
      "/decimal-pecahanBiasa/084-1,4-diubah-menjadi-pecahan-biasa",
      "1.4 Diubah Menjadi Pecahan Biasa",
      "",
      "1.4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_085",
      "/decimal-pecahanBiasa/085-1,42-diubah-menjadi-pecahan-biasa",
      "1.42 Diubah Menjadi Pecahan Biasa",
      "",
      "1.42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_086",
      "/decimal-pecahanBiasa/086-1,5-diubah-menjadi-pecahan-biasa",
      "1.5 Diubah Menjadi Pecahan Biasa",
      "",
      "1.5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_087",
      "/decimal-pecahanBiasa/087-1,50-diubah-menjadi-pecahan-biasa",
      "1.50 Diubah Menjadi Pecahan Biasa",
      "",
      "1.50 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_088",
      "/decimal-pecahanBiasa/088-1,6-diubah-menjadi-pecahan-biasa",
      "1.6 Diubah Menjadi Pecahan Biasa",
      "",
      "1.6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_089",
      "/decimal-pecahanBiasa/089-1,65-diubah-menjadi-pecahan-biasa",
      "1.65 Diubah Menjadi Pecahan Biasa",
      "",
      "1.65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_090",
      "/decimal-pecahanBiasa/090-1,75-diubah-menjadi-pecahan-biasa",
      "1.75 Diubah Menjadi Pecahan Biasa",
      "",
      "1.75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_091",
      "/decimal-pecahanBiasa/091-1,8-diubah-menjadi-pecahan-biasa",
      "1.8 Diubah Menjadi Pecahan Biasa",
      "",
      "1.8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_092",
      "/decimal-pecahanBiasa/092-1,7-diubah-menjadi-pecahan-biasa",
      "1.7 Diubah Menjadi Pecahan Biasa",
      "",
      "1.7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_093",
      "/decimal-pecahanBiasa/093-2,3-diubah-menjadi-pecahan-biasa",
      "2,3 Diubah Menjadi Pecahan Biasa",
      "",
      "2,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_094",
      "/decimal-pecahanBiasa/094-2,7-diubah-menjadi-pecahan-biasa",
      "2,7 Diubah Menjadi Pecahan Biasa",
      "",
      "2,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_095",
      "/decimal-pecahanBiasa/095-2,71-diubah-menjadi-pecahan-biasa",
      "2,71 Diubah Menjadi Pecahan Biasa",
      "",
      "2,71 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_096",
      "/decimal-pecahanBiasa/096-2,05-diubah-menjadi-pecahan-biasa",
      "2,05 Diubah Menjadi Pecahan Biasa",
      "",
      "2,05 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_097",
      "/decimal-pecahanBiasa/097-2,2-diubah-menjadi-pecahan-biasa",
      "2,2 Diubah Menjadi Pecahan Biasa",
      "",
      "2,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_098",
      "/decimal-pecahanBiasa/098-2,25-diubah-menjadi-pecahan-biasa",
      "2,25 Diubah Menjadi Pecahan Biasa",
      "",
      "2,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_099",
      "/decimal-pecahanBiasa/099-2,4-diubah-menjadi-pecahan-biasa",
      "2,4 Diubah Menjadi Pecahan Biasa",
      "",
      "2,4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_100",
      "/decimal-pecahanBiasa/100-2,5-diubah-menjadi-pecahan-biasa",
      "2,5 Diubah Menjadi Pecahan Biasa",
      "",
      "2,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_101",
      "/decimal-pecahanBiasa/101-2,6-diubah-menjadi-pecahan-biasa",
      "2,6 Diubah Menjadi Pecahan Biasa",
      "",
      "2,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_102",
      "/decimal-pecahanBiasa/102-2,8-diubah-menjadi-pecahan-biasa",
      "2,8 Diubah Menjadi Pecahan Biasa",
      "",
      "2,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_103",
      "/decimal-pecahanBiasa/103-2,35-diubah-menjadi-pecahan-biasa",
      "2,35 Diubah Menjadi Pecahan Biasa",
      "",
      "2,35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_104",
      "/decimal-pecahanBiasa/104-2,48-diubah-menjadi-pecahan-biasa",
      "2,48 Diubah Menjadi Pecahan Biasa",
      "",
      "2,48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_105",
      "/decimal-pecahanBiasa/105-2,68-diubah-menjadi-pecahan-biasa",
      "2,68 Diubah Menjadi Pecahan Biasa",
      "",
      "2,68 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_106",
      "/decimal-pecahanBiasa/106-2,75-diubah-menjadi-pecahan-biasa",
      "2,75 Diubah Menjadi Pecahan Biasa",
      "",
      "2,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_107",
      "/decimal-pecahanBiasa/107-2,375-diubah-menjadi-pecahan-biasa",
      "2,375 Diubah Menjadi Pecahan Biasa",
      "",
      "2,375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_108",
      "/decimal-pecahanBiasa/108-3,45-diubah-menjadi-pecahan-biasa",
      "3,45 Diubah Menjadi Pecahan Biasa",
      "",
      "3,45 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_109",
      "/decimal-pecahanBiasa/109-3,5-diubah-menjadi-pecahan-biasa",
      "3,5 Diubah Menjadi Pecahan Biasa",
      "",
      "3,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_110",
      "/decimal-pecahanBiasa/110-3,4-diubah-menjadi-pecahan-biasa",
      "3,4 Diubah Menjadi Pecahan Biasa",
      "",
      "3,4 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_111",
      "/decimal-pecahanBiasa/111-3,6-diubah-menjadi-pecahan-biasa",
      "3,6 Diubah Menjadi Pecahan Biasa",
      "",
      "3,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_112",
      "/decimal-pecahanBiasa/112-3,8-diubah-menjadi-pecahan-biasa",
      "3,8 Diubah Menjadi Pecahan Biasa",
      "",
      "3,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_113",
      "/decimal-pecahanBiasa/113-3,3-diubah-menjadi-pecahan-biasa",
      "3,3 Diubah Menjadi Pecahan Biasa",
      "",
      "3,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_114",
      "/decimal-pecahanBiasa/114-3,75-diubah-menjadi-pecahan-biasa",
      "3,75 Diubah Menjadi Pecahan Biasa",
      "",
      "3,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_115",
      "/decimal-pecahanBiasa/115-3,25-diubah-menjadi-pecahan-biasa",
      "3,25 Diubah Menjadi Pecahan Biasa",
      "",
      "3,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_116",
      "/decimal-pecahanBiasa/116-3,42-diubah-menjadi-pecahan-biasa",
      "3,42 Diubah Menjadi Pecahan Biasa",
      "",
      "3,42 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_117",
      "/decimal-pecahanBiasa/117-3,56-diubah-menjadi-pecahan-biasa",
      "3,56 Diubah Menjadi Pecahan Biasa",
      "",
      "3,56 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_118",
      "/decimal-pecahanBiasa/118-3,48-diubah-menjadi-pecahan-biasa",
      "3,48 Diubah Menjadi Pecahan Biasa",
      "",
      "3,48 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_119",
      "/decimal-pecahanBiasa/119-3,65-diubah-menjadi-pecahan-biasa",
      "3,65 Diubah Menjadi Pecahan Biasa",
      "",
      "3,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_120",
      "/decimal-pecahanBiasa/120-3,70-diubah-menjadi-pecahan-biasa",
      "3,70 Diubah Menjadi Pecahan Biasa",
      "",
      "3,70 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_121",
      "/decimal-pecahanBiasa/121-4,2-diubah-menjadi-pecahan-biasa",
      "4,2 Diubah Menjadi Pecahan Biasa",
      "",
      "4,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_122",
      "/decimal-pecahanBiasa/122-4,5-diubah-menjadi-pecahan-biasa",
      "4,5 Diubah Menjadi Pecahan Biasa",
      "",
      "4,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_123",
      "/decimal-pecahanBiasa/123-4,6-diubah-menjadi-pecahan-biasa",
      "4,6 Diubah Menjadi Pecahan Biasa",
      "",
      "4,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_124",
      "/decimal-pecahanBiasa/124-4,8-diubah-menjadi-pecahan-biasa",
      "4,8 Diubah Menjadi Pecahan Biasa",
      "",
      "4,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_125",
      "/decimal-pecahanBiasa/125-4,7-diubah-menjadi-pecahan-biasa",
      "4,7 Diubah Menjadi Pecahan Biasa",
      "",
      "4,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_126",
      "/decimal-pecahanBiasa/126-4,75-diubah-menjadi-pecahan-biasa",
      "4,75 Diubah Menjadi Pecahan Biasa",
      "",
      "4,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_127",
      "/decimal-pecahanBiasa/127-4,68-diubah-menjadi-pecahan-biasa",
      "4,68 Diubah Menjadi Pecahan Biasa",
      "",
      "4,68 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_128",
      "/decimal-pecahanBiasa/128-4,65-diubah-menjadi-pecahan-biasa",
      "4,65 Diubah Menjadi Pecahan Biasa",
      "",
      "4,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_129",
      "/decimal-pecahanBiasa/129-4,375-diubah-menjadi-pecahan-biasa",
      "4,375 Diubah Menjadi Pecahan Biasa",
      "",
      "4,375 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_130",
      "/decimal-pecahanBiasa/130-5,25-diubah-menjadi-pecahan-biasa",
      "5,25 Diubah Menjadi Pecahan Biasa",
      "",
      "5,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_131",
      "/decimal-pecahanBiasa/131-5,75-diubah-menjadi-pecahan-biasa",
      "5,75 Diubah Menjadi Pecahan Biasa",
      "",
      "5,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_132",
      "/decimal-pecahanBiasa/132-5,65-diubah-menjadi-pecahan-biasa",
      "5,65 Diubah Menjadi Pecahan Biasa",
      "",
      "5,65 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_133",
      "/decimal-pecahanBiasa/133-5,40-diubah-menjadi-pecahan-biasa",
      "5,40 Diubah Menjadi Pecahan Biasa",
      "",
      "5,40 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_134",
      "/decimal-pecahanBiasa/134-5,60-diubah-menjadi-pecahan-biasa",
      "5,60 Diubah Menjadi Pecahan Biasa",
      "",
      "5,60 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_135",
      "/decimal-pecahanBiasa/135-5,04-diubah-menjadi-pecahan-biasa",
      "5,04 Diubah Menjadi Pecahan Biasa",
      "",
      "5,04 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_136",
      "/decimal-pecahanBiasa/136-5,28-diubah-menjadi-pecahan-biasa",
      "5,28 Diubah Menjadi Pecahan Biasa",
      "",
      "5,28 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_137",
      "/decimal-pecahanBiasa/137-5,016-diubah-menjadi-pecahan-biasa",
      "5,016 Diubah Menjadi Pecahan Biasa",
      "",
      "5,016 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_138",
      "/decimal-pecahanBiasa/138-5,87-diubah-menjadi-pecahan-biasa",
      "5,87 Diubah Menjadi Pecahan Biasa",
      "",
      "5,87 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_139",
      "/decimal-pecahanBiasa/139-6,75-diubah-menjadi-pecahan-biasa",
      "6,75 Diubah Menjadi Pecahan Biasa",
      "",
      "6,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_140",
      "/decimal-pecahanBiasa/140-6,8-diubah-menjadi-pecahan-biasa",
      "6,8 Diubah Menjadi Pecahan Biasa",
      "",
      "6,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_141",
      "/decimal-pecahanBiasa/141-6,5-diubah-menjadi-pecahan-biasa",
      "6,5 Diubah Menjadi Pecahan Biasa",
      "",
      "6,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_142",
      "/decimal-pecahanBiasa/142-6,6-diubah-menjadi-pecahan-biasa",
      "6,6 Diubah Menjadi Pecahan Biasa",
      "",
      "6,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_143",
      "/decimal-pecahanBiasa/143-6,7-diubah-menjadi-pecahan-biasa",
      "6,7 Diubah Menjadi Pecahan Biasa",
      "",
      "6,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_144",
      "/decimal-pecahanBiasa/144-7,5-diubah-menjadi-pecahan-biasa",
      "7,5 Diubah Menjadi Pecahan Biasa",
      "",
      "7,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_145",
      "/decimal-pecahanBiasa/145-7,25-diubah-menjadi-pecahan-biasa",
      "7,25 Diubah Menjadi Pecahan Biasa",
      "",
      "7,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_146",
      "/decimal-pecahanBiasa/146-7,80-diubah-menjadi-pecahan-biasa",
      "7,80 Diubah Menjadi Pecahan Biasa",
      "",
      "7,80 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_147",
      "/decimal-pecahanBiasa/147-7,2-diubah-menjadi-pecahan-biasa",
      "7,2 Diubah Menjadi Pecahan Biasa",
      "",
      "7,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_148",
      "/decimal-pecahanBiasa/148-7,8-diubah-menjadi-pecahan-biasa",
      "7,8 Diubah Menjadi Pecahan Biasa",
      "",
      "7,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_149",
      "/decimal-pecahanBiasa/149-7,125-diubah-menjadi-pecahan-biasa",
      "7,125 Diubah Menjadi Pecahan Biasa",
      "",
      "7,125 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_150",
      "/decimal-pecahanBiasa/150-7,016-diubah-menjadi-pecahan-biasa",
      "7,016 Diubah Menjadi Pecahan Biasa",
      "",
      "7,016 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_151",
      "/decimal-pecahanBiasa/151-8,5-diubah-menjadi-pecahan-biasa",
      "8,5 Diubah Menjadi Pecahan Biasa",
      "",
      "8,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_152",
      "/decimal-pecahanBiasa/152-8,2-diubah-menjadi-pecahan-biasa",
      "8,2 Diubah Menjadi Pecahan Biasa",
      "",
      "8,2 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_153",
      "/decimal-pecahanBiasa/153-8,8-diubah-menjadi-pecahan-biasa",
      "8,8 Diubah Menjadi Pecahan Biasa",
      "",
      "8,8 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_154",
      "/decimal-pecahanBiasa/154-8,12-diubah-menjadi-pecahan-biasa",
      "8,12 Diubah Menjadi Pecahan Biasa",
      "",
      "8,12 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_155",
      "/decimal-pecahanBiasa/155-8,75-diubah-menjadi-pecahan-biasa",
      "8,75 Diubah Menjadi Pecahan Biasa",
      "",
      "8,75 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_156",
      "/decimal-pecahanBiasa/156-8,3-diubah-menjadi-pecahan-biasa",
      "8,3 Diubah Menjadi Pecahan Biasa",
      "",
      "8,3 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_157",
      "/decimal-pecahanBiasa/157-8,7-diubah-menjadi-pecahan-biasa",
      "8,7 Diubah Menjadi Pecahan Biasa",
      "",
      "8,7 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_158",
      "/decimal-pecahanBiasa/158-9,5-diubah-menjadi-pecahan-biasa",
      "9,5 Diubah Menjadi Pecahan Biasa",
      "",
      "9,5 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_159",
      "/decimal-pecahanBiasa/159-9,6-diubah-menjadi-pecahan-biasa",
      "9,6 Diubah Menjadi Pecahan Biasa",
      "",
      "9,6 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_160",
      "/decimal-pecahanBiasa/160-9,06-diubah-menjadi-pecahan-biasa",
      "9,06 Diubah Menjadi Pecahan Biasa",
      "",
      "9,06 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_161",
      "/decimal-pecahanBiasa/161-15,35-diubah-menjadi-pecahan-biasa",
      "15,35 Diubah Menjadi Pecahan Biasa",
      "",
      "15,35 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    [
      "pecahan_162",
      "/decimal-pecahanBiasa/162-90,25-diubah-menjadi-pecahan-biasa",
      "90,25 Diubah Menjadi Pecahan Biasa",
      "",
      "90,25 diubah menjadi pecahan biasa",
      ["Desimal - Pecahan Biasa"],
      "",
    ],
    
    
  
];