var titleCat_1 = "Waktu";
var cat_1 = [
  ["Detik-Menit", "/detik-menit/001-300-detik-berapa-menit", ""],
  ["Menit-Jam", "/menit-jam/003-300-menit-berapa-jam", ""],
  ["Detik-Jam", "/detik-jam/004-300-detik-berapa-jam", ""],
  ["Jam-Hari", "/jam-hari/005-300-jam-berapa-hari", ""],
  ["Menit-Detik", "/menit-detik/035-3-menit-berapa-detik", ""],
  ["Jam-Detik", "/jam-detik/069-1-per-4-jam-berapa-detik", ""],
  ["Jam-Menit", "/jam-menit/073-1-jam-berapa-menit", ""],
  ["Jam Berapa", "/jam-berapa/372-jam-13-jam-berapa", ""],

];
var url_root = "https://nasrianas.website/jawab/math/waktu";
var footerArray = [
    //June2020
    [
      "Waktu_001",
      "/detik-menit/001-300-detik-berapa-menit",
      "300 Detik Berapa Menit ?",
      "",
      "300 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_002",
      "/detik-menit/002-500-detik-berapa-menit",
      "500 Detik Berapa Menit ?",
      "",
      "500 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_003",
      "/menit-jam/003-300-menit-berapa-jam",
      "300 Menit Berapa Jam ?",
      "",
      "300 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_004",
      "/detik-jam/004-300-detik-berapa-jam",
      "300 Detik Berapa Jam",
      "",
      "300 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Math_005",
      "/jam-hari/005-300-jam-berapa-hari",
      "300 Jam Berapa Hari",
      "",
      "300 Jam = ... Hari",
      ["Jam-Hari"],
      "",
    ],
    [
      "Waktu_006",
      "/menit-jam/006-500-menit-berapa-jam",
      "500 Menit Berapa Jam ?",
      "",
      "500 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_007",
      "/menit-jam/007-100-menit-berapa-jam",
      "100 Menit Berapa Jam ?",
      "",
      "100 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_008",
      "/menit-jam/008-1000-menit-berapa-jam",
      "1000 Menit Berapa Jam ?",
      "",
      "1000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_009",
      "/menit-jam/009-90-menit-berapa-jam",
      "90 Menit Berapa Jam ?",
      "",
      "90 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_010",
      "/menit-jam/010-120-menit-berapa-jam",
      "120 Menit Berapa Jam ?",
      "",
      "120 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_011",
      "/menit-jam/011-180-menit-berapa-jam",
      "180 Menit Berapa Jam ?",
      "",
      "180 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_012",
      "/menit-jam/012-60-menit-berapa-jam",
      "60 Menit Berapa Jam ?",
      "",
      "60 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_013",
      "/menit-jam/013-45-menit-berapa-jam",
      "45 Menit Berapa Jam ?",
      "",
      "45 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_014",
      "/menit-jam/014-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_015",
      "/menit-jam/015-20-menit-berapa-jam",
      "20 Menit Berapa Jam ?",
      "",
      "20 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_016",
      "/menit-jam/016-5-menit-berapa-jam",
      "5 Menit Berapa Jam ?",
      "",
      "5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_017",
      "/menit-jam/017-40-menit-berapa-jam",
      "40 Menit Berapa Jam ?",
      "",
      "40 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_018",
      "/menit-jam/018-30-menit-berapa-jam",
      "30 Menit Berapa Jam ?",
      "",
      "30 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_019",
      "/menit-jam/019-15-menit-berapa-jam",
      "15 Menit Berapa Jam ?",
      "",
      "15 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_020",
      "/menit-jam/020-12-menit-berapa-jam",
      "12 Menit Berapa Jam ?",
      "",
      "12 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_021",
      "/menit-jam/021-10-menit-berapa-jam",
      "10 Menit Berapa Jam ?",
      "",
      "10 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_022",
      "/menit-jam/022-17-menit-berapa-jam",
      "17 Menit Berapa Jam ?",
      "",
      "17 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_023",
      "/detik-menit/023-720-detik-berapa-menit",
      "720 Detik Berapa Menit ?",
      "",
      "720 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_024",
      "/detik-menit/024-120-detik-berapa-menit",
      "120 Detik Berapa Menit ?",
      "",
      "120 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_025",
      "/detik-menit/025-480-detik-berapa-menit",
      "480 Detik Berapa Menit ?",
      "",
      "480 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_026",
      "/detik-menit/026-7200-detik-berapa-menit",
      "7200 Detik Berapa Menit ?",
      "",
      "7200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_027",
      "/detik-menit/027-600-detik-berapa-menit",
      "600 Detik Berapa Menit ?",
      "",
      "600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_028",
      "/detik-menit/028-180-detik-berapa-menit",
      "180 Detik Berapa Menit ?",
      "",
      "180 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_029",
      "/detik-menit/029-15-detik-berapa-menit",
      "15 Detik Berapa Menit ?",
      "",
      "15 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_030",
      "/detik-menit/030-6-detik-berapa-menit",
      "6 Detik Berapa Menit ?",
      "",
      "6 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_031",
      "/detik-menit/031-10-detik-berapa-menit",
      "10 Detik Berapa Menit ?",
      "",
      "10 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_032",
      "/detik-menit/032-8-detik-berapa-menit",
      "8 Detik Berapa Menit ?",
      "",
      "8 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_033",
      "/detik-menit/033-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_034",
      "/detik-menit/034-90-detik-berapa-menit",
      "90 Detik Berapa Menit ?",
      "",
      "90 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_035",
      "/menit-detik/035-3-menit-berapa-detik",
      "3 Menit Berapa Detik ?",
      "",
      "3 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_036",
      "/menit-detik/036-25-menit-berapa-detik",
      "25 Menit Berapa Detik ?",
      "",
      "25 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_037",
      "/menit-detik/037-5-menit-berapa-detik",
      "5 Menit Berapa Detik ?",
      "",
      "5 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_038",
      "/menit-detik/038-30-menit-berapa-detik",
      "30 Menit Berapa Detik ?",
      "",
      "30 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_039",
      "/menit-detik/039-10-menit-berapa-detik",
      "10 Menit Berapa Detik ?",
      "",
      "10 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_040",
      "/menit-detik/040-60-menit-berapa-detik",
      "60 Menit Berapa Detik ?",
      "",
      "60 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_041",
      "/menit-detik/041-15-menit-berapa-detik",
      "15 Menit Berapa Detik ?",
      "",
      "15 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_042",
      "/menit-detik/042-12-menit-berapa-detik",
      "12 Menit Berapa Detik ?",
      "",
      "12 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_043",
      "/menit-detik/043-20-menit-berapa-detik",
      "20 Menit Berapa Detik ?",
      "",
      "20 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_044",
      "/menit-detik/044-7-menit-berapa-detik",
      "7 Menit Berapa Detik ?",
      "",
      "7 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_045",
      "/menit-detik/045-0,1-menit-berapa-detik",
      "0.1 Menit Berapa Detik ?",
      "",
      "0,1 Menit = ... Detik",
      ["Menit-Detik"],
      "",
    ],
    [
      "Waktu_046",
      "/detik-jam/046-500-detik-berapa-jam",
      "500 Detik Berapa Jam ?",
      "",
      "500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_047",
      "/detik-jam/047-7200-detik-berapa-jam",
      "7200 Detik Berapa Jam ?",
      "",
      "7200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_048",
      "/detik-jam/048-1-detik-berapa-jam",
      "1 Detik Berapa Jam ?",
      "",
      "1 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_049",
      "/detik-jam/049-1800-detik-berapa-jam",
      "1800 Detik Berapa Jam ?",
      "",
      "1800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_050",
      "/detik-jam/050-600-detik-berapa-jam",
      "600 Detik Berapa Jam ?",
      "",
      "600 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_051",
      "/detik-jam/051-100-detik-berapa-jam",
      "100 Detik Berapa Jam ?",
      "",
      "100 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_052",
      "/detik-jam/052-10-detik-berapa-jam",
      "10 Detik Berapa Jam ?",
      "",
      "10 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_053",
      "/detik-jam/053-15-detik-berapa-jam",
      "15 Detik Berapa Jam ?",
      "",
      "15 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_054",
      "/detik-jam/054-60-detik-berapa-jam",
      "60 Detik Berapa Jam ?",
      "",
      "60 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_055",
      "/detik-jam/055-6-detik-berapa-jam",
      "6 Detik Berapa Jam ?",
      "",
      "6 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_056",
      "/jam-detik/056-2-jam-berapa-detik",
      "2 Jam Berapa Detik ?",
      "",
      "2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_057",
      "/jam-detik/057-1-jam-berapa-detik",
      "1 Jam Berapa Detik ?",
      "",
      "1 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_058",
      "/jam-detik/058-0,45-jam-berapa-detik",
      "0.45 Jam Berapa Detik ?",
      "",
      "0,45 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_059",
      "/jam-detik/059-3-jam-berapa-detik",
      "3 Jam Berapa Detik ?",
      "",
      "3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_060",
      "/jam-detik/060-0,5-jam-berapa-detik",
      "0.5 Jam Berapa Detik ?",
      "",
      "0,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_061",
      "/jam-detik/061-1-per-6-jam-berapa-detik",
      "1/6 Jam Berapa Detik ?",
      "",
      "1/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_062",
      "/jam-detik/062-1-per-60-jam-berapa-detik",
      "1/60 Jam Berapa Detik ?",
      "",
      "1/60 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_063",
      "/jam-detik/063-1,5-jam-berapa-detik",
      "1.5 Jam Berapa Detik ?",
      "",
      "1,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_064",
      "/jam-detik/064-24-jam-berapa-detik",
      "24 Jam Berapa Detik ?",
      "",
      "24 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_065",
      "/jam-detik/065-4-jam-berapa-detik",
      "4 Jam Berapa Detik ?",
      "",
      "4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_066",
      "/jam-detik/066-7-jam-berapa-detik",
      "7 Jam Berapa Detik ?",
      "",
      "7 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_067",
      "/jam-detik/067-6-jam-berapa-detik",
      "6 Jam Berapa Detik ?",
      "",
      "6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_068",
      "/jam-detik/068-12-jam-berapa-detik",
      "12 Jam Berapa Detik ?",
      "",
      "12 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_069",
      "/jam-detik/069-1-per-4-jam-berapa-detik",
      "1/4 Jam Berapa Detik ?",
      "",
      "1/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_070",
      "/jam-detik/070-1-per-3-jam-berapa-detik",
      "1/3 Jam Berapa Detik ?",
      "",
      "1/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_071",
      "/jam-detik/071-0,25-jam-berapa-detik",
      "0.25 Jam Berapa Detik ?",
      "",
      "0.25 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_072",
      "/jam-detik/072-2,5-jam-berapa-detik",
      "2.5 Jam Berapa Detik ?",
      "",
      "2.5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_073",
      "/jam-menit/073-1-jam-berapa-menit",
      "1 Jam Berapa Menit ?",
      "",
      "1 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_074",
      "/jam-menit/074-2-jam-berapa-menit",
      "2 Jam Berapa Menit ?",
      "",
      "2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_075",
      "/jam-menit/075-3-jam-berapa-menit",
      "3 Jam Berapa Menit ?",
      "",
      "3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_076",
      "/jam-menit/076-4-jam-berapa-menit",
      "4 Jam Berapa Menit ?",
      "",
      "4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_077",
      "/jam-menit/077-5-jam-berapa-menit",
      "5 Jam Berapa Menit ?",
      "",
      "5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_078",
      "/jam-menit/078-6-jam-berapa-menit",
      "6 Jam Berapa Menit ?",
      "",
      "6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_079",
      "/jam-menit/079-7-jam-berapa-menit",
      "7 Jam Berapa Menit ?",
      "",
      "7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_080",
      "/jam-menit/080-8-jam-berapa-menit",
      "8 Jam Berapa Menit ?",
      "",
      "8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_081",
      "/jam-menit/081-9-jam-berapa-menit",
      "9 Jam Berapa Menit ?",
      "",
      "9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_082",
      "/jam-menit/082-10-jam-berapa-menit",
      "10 Jam Berapa Menit ?",
      "",
      "10 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_083",
      "/jam-menit/083-11-jam-berapa-menit",
      "11 Jam Berapa Menit ?",
      "",
      "11 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_084",
      "/jam-menit/084-12-jam-berapa-menit",
      "12 Jam Berapa Menit ?",
      "",
      "12 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_085",
      "/jam-menit/085-13-jam-berapa-menit",
      "13 Jam Berapa Menit ?",
      "",
      "13 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_086",
      "/jam-menit/086-14-jam-berapa-menit",
      "14 Jam Berapa Menit ?",
      "",
      "14 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_087",
      "/jam-menit/087-15-jam-berapa-menit",
      "15 Jam Berapa Menit ?",
      "",
      "15 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_088",
      "/jam-menit/088-16-jam-berapa-menit",
      "16 Jam Berapa Menit ?",
      "",
      "16 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_089",
      "/jam-menit/089-17-jam-berapa-menit",
      "17 Jam Berapa Menit ?",
      "",
      "17 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_090",
      "/jam-menit/090-18-jam-berapa-menit",
      "18 Jam Berapa Menit ?",
      "",
      "18 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_091",
      "/jam-menit/091-19-jam-berapa-menit",
      "19 Jam Berapa Menit ?",
      "",
      "19 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_092",
      "/jam-menit/092-20-jam-berapa-menit",
      "20 Jam Berapa Menit ?",
      "",
      "20 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_093",
      "/jam-menit/093-21-jam-berapa-menit",
      "21 Jam Berapa Menit ?",
      "",
      "21 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_094",
      "/jam-menit/094-22-jam-berapa-menit",
      "22 Jam Berapa Menit ?",
      "",
      "22 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_095",
      "/jam-menit/095-23-jam-berapa-menit",
      "23 Jam Berapa Menit ?",
      "",
      "23 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_096",
      "/jam-menit/096-24-jam-berapa-menit",
      "24 Jam Berapa Menit ?",
      "",
      "24 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_097",
      "/jam-menit/097-0,5-jam-berapa-menit",
      "0,5 Jam Berapa Menit ?",
      "",
      "0,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_098",
      "/jam-menit/098-1,5-jam-berapa-menit",
      "1,5 Jam Berapa Menit ?",
      "",
      "1,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_099",
      "/jam-menit/099-2,5-jam-berapa-menit",
      "2,5 Jam Berapa Menit ?",
      "",
      "2,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_100",
      "/jam-menit/100-1,2-jam-berapa-menit",
      "1,2 Jam Berapa Menit ?",
      "",
      "1,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_101",
      "/jam-menit/101-1,6-jam-berapa-menit",
      "1,6 Jam Berapa Menit ?",
      "",
      "1,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_102",
      "/jam-menit/102-1,25-jam-berapa-menit",
      "1,25 Jam Berapa Menit ?",
      "",
      "1,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_103",
      "/jam-menit/103-5,6-jam-berapa-menit",
      "5,6 Jam Berapa Menit ?",
      "",
      "5,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_104",
      "/jam-menit/104-1per2-jam-berapa-menit",
      "1/2 Jam Berapa Menit ?",
      "",
      "1/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_105",
      "/jam-menit/105-1per6-jam-berapa-menit",
      "1/6 Jam Berapa Menit ?",
      "",
      "1/6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_106",
      "/jam-menit/106-4000-jam-berapa-menit",
      "4000 Jam Berapa Menit ?",
      "",
      "4000 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_107",
      "/detik-menit/107-3600-detik-berapa-menit",
      "3600 Detik Berapa Menit ?",
      "",
      "3600 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_108",
      "/detik-menit/108-1000-detik-berapa-menit",
      "1000 Detik Berapa Menit ?",
      "",
      "1000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_109",
      "/detik-menit/109-270-detik-berapa-menit",
      "270 Detik Berapa Menit ?",
      "",
      "270 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_110",
      "/detik-menit/110-230-detik-berapa-menit",
      "230 Detik Berapa Menit ?",
      "",
      "230 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_111",
      "/detik-menit/111-5000-detik-berapa-menit",
      "5000 Detik Berapa Menit ?",
      "",
      "5000 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_112",
      "/detik-menit/112-200-detik-berapa-menit",
      "200 Detik Berapa Menit ?",
      "",
      "200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_113",
      "/detik-menit/113-1200-detik-berapa-menit",
      "1200 Detik Berapa Menit ?",
      "",
      "1200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_114",
      "/detik-menit/114-2400-detik-berapa-menit",
      "2400 Detik Berapa Menit ?",
      "",
      "2400 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_115",
      "/detik-menit/115-420-detik-berapa-menit",
      "420 Detik Berapa Menit ?",
      "",
      "420 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_116",
      "/detik-menit/116-4200-detik-berapa-menit",
      "4200 Detik Berapa Menit ?",
      "",
      "4200 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_117",
      "/detik-menit/117-360-detik-berapa-menit",
      "360 Detik Berapa Menit ?",
      "",
      "360 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_118",
      "/detik-menit/118-20-detik-berapa-menit",
      "20 Detik Berapa Menit ?",
      "",
      "20 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_119",
      "/detik-menit/119-30-detik-berapa-menit",
      "30 Detik Berapa Menit ?",
      "",
      "30 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_120",
      "/detik-menit/120-5-detik-berapa-menit",
      "5 Detik Berapa Menit ?",
      "",
      "5 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_121",
      "/detik-menit/121-1-detik-berapa-menit",
      "1 Detik Berapa Menit ?",
      "",
      "1 Detik = ... Menit",
      ["Detik-Menit"],
      "",
    ],
    [
      "Waktu_122",
      "/detik-jam/122-1,5-detik-berapa-jam",
      "1,5 Detik Berapa Jam ?",
      "",
      "1,5 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_123",
      "/detik-jam/123-1-juta-detik-berapa-jam",
      "1 juta Detik Berapa Jam ?",
      "",
      "1 juta Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_124",
      "/detik-jam/124-10800-detik-berapa-jam",
      "10.800 Detik Berapa Jam ?",
      "",
      "10.800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_125",
      "/detik-jam/125-1000-detik-berapa-jam",
      "1000 Detik Berapa Jam ?",
      "",
      "1000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_126",
      "/detik-jam/126-120-detik-berapa-jam",
      "120 Detik Berapa Jam ?",
      "",
      "120 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_127",
      "/detik-jam/127-18000-detik-berapa-jam",
      "18000 Detik Berapa Jam ?",
      "",
      "18000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_128",
      "/detik-jam/128-2-detik-berapa-jam",
      "2 Detik Berapa Jam ?",
      "",
      "2 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_129",
      "/detik-jam/129-20-detik-berapa-jam",
      "20 Detik Berapa Jam ?",
      "",
      "20 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_130",
      "/detik-jam/130-200-detik-berapa-jam",
      "200 Detik Berapa Jam ?",
      "",
      "200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_131",
      "/detik-jam/131-2000-detik-berapa-jam",
      "2000 Detik Berapa Jam ?",
      "",
      "2000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_132",
      "/detik-jam/132-2400-detik-berapa-jam",
      "2400 Detik Berapa Jam ?",
      "",
      "2400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_133",
      "/detik-jam/133-25200-detik-berapa-jam",
      "25.200 Detik Berapa Jam ?",
      "",
      "25.200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_134",
      "/detik-jam/134-2700-detik-berapa-jam",
      "2700 Detik Berapa Jam ?",
      "",
      "2700 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_135",
      "/detik-jam/135-3600-detik-berapa-jam",
      "3.600 Detik Berapa Jam ?",
      "",
      "3.600 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_136",
      "/detik-jam/136-30-detik-berapa-jam",
      "30 Detik Berapa Jam ?",
      "",
      "30 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_137",
      "/detik-jam/137-3000-detik-berapa-jam",
      "3000 Detik Berapa Jam ?",
      "",
      "3000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_138",
      "/detik-jam/138-3200-detik-berapa-jam",
      "3200 Detik Berapa Jam ?",
      "",
      "3200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_139",
      "/detik-jam/139-3500-detik-berapa-jam",
      "3500 Detik Berapa Jam ?",
      "",
      "3500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_140",
      "/detik-jam/140-360-detik-berapa-jam",
      "360 Detik Berapa Jam ?",
      "",
      "360 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_141",
      "/detik-jam/141-36000-detik-berapa-jam",
      "36000 Detik Berapa Jam ?",
      "",
      "36000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_142",
      "/detik-jam/142-40-detik-berapa-jam",
      "40 Detik Berapa Jam ?",
      "",
      "40 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_143",
      "/detik-jam/143-400-detik-berapa-jam",
      "400 Detik Berapa Jam ?",
      "",
      "400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_144",
      "/detik-jam/144-4000-detik-berapa-jam",
      "4000 Detik Berapa Jam ?",
      "",
      "4000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_145",
      "/detik-jam/145-4200-detik-berapa-jam",
      "4200 Detik Berapa Jam ?",
      "",
      "4200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_146",
      "/detik-jam/146-45-detik-berapa-jam",
      "45 Detik Berapa Jam ?",
      "",
      "45 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_147",
      "/detik-jam/147-4500-detik-berapa-jam",
      "4500 Detik Berapa Jam ?",
      "",
      "4500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_148",
      "/detik-jam/148-480-detik-berapa-jam",
      "480 Detik Berapa Jam ?",
      "",
      "480 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_149",
      "/detik-jam/149-4800-detik-berapa-jam",
      "4800 Detik Berapa Jam ?",
      "",
      "4800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_150",
      "/detik-jam/150-5-detik-berapa-jam",
      "5 Detik Berapa Jam ?",
      "",
      "5 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_151",
      "/detik-jam/151-5550-detik-berapa-jam",
      "5.550 Detik Berapa Jam ?",
      "",
      "5.550 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_152",
      "/detik-jam/152-50-detik-berapa-jam",
      "50 Detik Berapa Jam ?",
      "",
      "50 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_153",
      "/detik-jam/153-5000-detik-berapa-jam",
      "5000 Detik Berapa Jam ?",
      "",
      "5000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_154",
      "/detik-jam/154-50000-detik-berapa-jam",
      "50000 Detik Berapa Jam ?",
      "",
      "50000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_155",
      "/detik-jam/155-5400-detik-berapa-jam",
      "5400 Detik Berapa Jam ?",
      "",
      "5400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_156",
      "/detik-jam/156-5500-detik-berapa-jam",
      "5500 Detik Berapa Jam ?",
      "",
      "5500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_157",
      "/detik-jam/157-6000-detik-berapa-jam",
      "6000 Detik Berapa Jam ?",
      "",
      "6000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_158",
      "/detik-jam/158-60000-detik-berapa-jam",
      "60000 Detik Berapa Jam ?",
      "",
      "60000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_159",
      "/detik-jam/159-7200-detik-berapa-jam",
      "7.200 Detik Berapa Jam ?",
      "",
      "7.200 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_160",
      "/detik-jam/160-700-detik-berapa-jam",
      "700 Detik Berapa Jam ?",
      "",
      "700 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_161",
      "/detik-jam/161-7000-detik-berapa-jam",
      "7000 Detik Berapa Jam ?",
      "",
      "7000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_162",
      "/detik-jam/162-72-detik-berapa-jam",
      "72 Detik Berapa Jam ?",
      "",
      "72 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_163",
      "/detik-jam/163-720-detik-berapa-jam",
      "720 Detik Berapa Jam ?",
      "",
      "720 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_164",
      "/detik-jam/164-72000-detik-berapa-jam",
      "72000 Detik Berapa Jam ?",
      "",
      "72000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_165",
      "/detik-jam/165-7220-detik-berapa-jam",
      "7220 Detik Berapa Jam ?",
      "",
      "7220 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_166",
      "/detik-jam/166-7260-detik-berapa-jam",
      "7260 Detik Berapa Jam ?",
      "",
      "7260 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_167",
      "/detik-jam/167-7500-detik-berapa-jam",
      "7500 Detik Berapa Jam ?",
      "",
      "7500 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_168",
      "/detik-jam/168-8100-detik-berapa-jam",
      "8.100 Detik Berapa Jam ?",
      "",
      "8.100 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_169",
      "/detik-jam/169-800-detik-berapa-jam",
      "800 Detik Berapa Jam ?",
      "",
      "800 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_170",
      "/detik-jam/170-8000-detik-berapa-jam",
      "8000 Detik Berapa Jam ?",
      "",
      "8000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_171",
      "/detik-jam/171-8400-detik-berapa-jam",
      "8400 Detik Berapa Jam ?",
      "",
      "8400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_172",
      "/detik-jam/172-86400-detik-berapa-jam",
      "86400 Detik Berapa Jam ?",
      "",
      "86400 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_173",
      "/detik-jam/173-9325-detik-berapa-jam",
      "9.325 Detik Berapa Jam ?",
      "",
      "9.325 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_174",
      "/detik-jam/174-90-detik-berapa-jam",
      "90 Detik Berapa Jam ?",
      "",
      "90 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_175",
      "/detik-jam/175-90000-detik-berapa-jam",
      "90.000 Detik Berapa Jam ?",
      "",
      "90.000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_176",
      "/detik-jam/176-900-detik-berapa-jam",
      "900 Detik Berapa Jam ?",
      "",
      "900 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_177",
      "/detik-jam/177-9000-detik-berapa-jam",
      "9000 Detik Berapa Jam ?",
      "",
      "9000 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_178",
      "/detik-jam/178-9300-detik-berapa-jam",
      "9300 Detik Berapa Jam ?",
      "",
      "9300 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_179",
      "/detik-jam/179-999-detik-berapa-jam",
      "999 Detik Berapa Jam ?",
      "",
      "999 Detik = ... Jam",
      ["Detik-Jam"],
      "",
    ],
    [
      "Waktu_180",
      "/jam-detik/180-0,2-jam-berapa-detik",
      "0,2 Jam Berapa Detik ?",
      "",
      "0,2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_181",
      "/jam-detik/181-0,4-jam-berapa-detik",
      "0,4 Jam Berapa Detik ?",
      "",
      "0,4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_182",
      "/jam-detik/182-0,3-jam-berapa-detik",
      "0,3 Jam Berapa Detik ?",
      "",
      "0,3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_183",
      "/jam-detik/183-0,5-jam-berapa-detik",
      "0,5 Jam Berapa Detik ?",
      "",
      "0,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_184",
      "/jam-detik/184-0,7-jam-berapa-detik",
      "0,7 Jam Berapa Detik ?",
      "",
      "0,7 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_185",
      "/jam-detik/185-0,75-jam-berapa-detik",
      "0,75 Jam Berapa Detik ?",
      "",
      "0,75 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_186",
      "/jam-detik/186-1,25-jam-berapa-detik",
      "1,25 Jam Berapa Detik ?",
      "",
      "1,25 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_187",
      "/jam-detik/187-1,75-jam-berapa-detik",
      "1,75 Jam Berapa Detik ?",
      "",
      "1,75 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_188",
      "/jam-detik/188-1,8-jam-berapa-detik",
      "1,8 Jam Berapa Detik ?",
      "",
      "1,8 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_189",
      "/jam-detik/189-10-jam-berapa-detik",
      "10 Jam Berapa Detik ?",
      "",
      "10 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_190",
      "/jam-detik/190-11-jam-berapa-detik",
      "11 Jam Berapa Detik ?",
      "",
      "11 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_191",
      "/jam-detik/191-13-jam-berapa-detik",
      "13 Jam Berapa Detik ?",
      "",
      "13 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_192",
      "/jam-detik/192-2,4-jam-berapa-detik",
      "2,4 Jam Berapa Detik ?",
      "",
      "2,4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_193",
      "/jam-detik/193-2-setengah-jam-berapa-detik",
      "2 setengah Jam Berapa Detik ?",
      "",
      "2 setengah Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_194",
      "/jam-detik/194-20-jam-berapa-detik",
      "20 Jam Berapa Detik ?",
      "",
      "20 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_195",
      "/jam-detik/195-3,5-jam-berapa-detik",
      "3,5 Jam Berapa Detik ?",
      "",
      "3,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_196",
      "/jam-detik/196-3,6-jam-berapa-detik",
      "3,6 Jam Berapa Detik ?",
      "",
      "3,6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_197",
      "/jam-detik/197-30-jam-berapa-detik",
      "30 Jam Berapa Detik ?",
      "",
      "30 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_198",
      "/jam-detik/198-36-jam-berapa-detik",
      "36 Jam Berapa Detik ?",
      "",
      "36 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_199",
      "/jam-detik/199-4,5-jam-berapa-detik",
      "4,5 Jam Berapa Detik ?",
      "",
      "4,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_200",
      "/jam-detik/200-40-jam-berapa-detik",
      "40 Jam Berapa Detik ?",
      "",
      "40 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_201",
      "/jam-detik/201-4000-jam-berapa-detik",
      "4000 Jam Berapa Detik ?",
      "",
      "4000 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_202",
      "/jam-detik/202-48-jam-berapa-detik",
      "48 Jam Berapa Detik ?",
      "",
      "48 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_203",
      "/jam-detik/203-5-jam-berapa-detik",
      "5 Jam Berapa Detik ?",
      "",
      "5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_204",
      "/jam-detik/204-72-jam-berapa-detik",
      "72 Jam Berapa Detik ?",
      "",
      "72 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_205",
      "/jam-detik/205-8,5-jam-berapa-detik",
      "8,5 Jam Berapa Detik ?",
      "",
      "8,5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_206",
      "/jam-detik/206-8-jam-berapa-detik",
      "8 Jam Berapa Detik ?",
      "",
      "8 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_207",
      "/jam-detik/207-9-jam-berapa-detik",
      "9 Jam Berapa Detik ?",
      "",
      "9 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_208",
      "/jam-detik/208-1per2-jam-berapa-detik",
      "1/2 Jam Berapa Detik ?",
      "",
      "1/2 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_209",
      "/jam-detik/209-1per3-jam-berapa-detik",
      "1/3 Jam Berapa Detik ?",
      "",
      "1/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_210",
      "/jam-detik/210-1per4-jam-berapa-detik",
      "1/4 Jam Berapa Detik ?",
      "",
      "1/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_211",
      "/jam-detik/211-1per6-jam-berapa-detik",
      "1/6 Jam Berapa Detik ?",
      "",
      "1/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_212",
      "/jam-detik/212-2per5-jam-berapa-detik",
      "2/5 Jam Berapa Detik ?",
      "",
      "2/5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_213",
      "/jam-detik/213-2per3-jam-berapa-detik",
      "2/3 Jam Berapa Detik ?",
      "",
      "2/3 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_214",
      "/jam-detik/214-3per4-jam-berapa-detik",
      "3/4 Jam Berapa Detik ?",
      "",
      "3/4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_215",
      "/jam-detik/215-5per6-jam-berapa-detik",
      "5/6 Jam Berapa Detik ?",
      "",
      "5/6 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_216",
      "/jam-detik/216-2per5-jam-berapa-detik",
      "2 per 5 Jam Berapa Detik ?",
      "",
      "2 per 5 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_217",
      "/jam-detik/217-3per4-jam-berapa-detik",
      "3 per 4 Jam Berapa Detik ?",
      "",
      "3 per 4 Jam = ... Detik",
      ["Jam-Detik"],
      "",
    ],
    [
      "Waktu_218",
      "/jam-menit/218-0,1-jam-berapa-menit",
      "0,1 Jam Berapa Menit ?",
      "",
      "0,1 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_219",
      "/jam-menit/219-0,2-jam-berapa-menit",
      "0,2 Jam Berapa Menit ?",
      "",
      "0,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_220",
      "/jam-menit/220-0,25-jam-berapa-menit",
      "0,25 Jam Berapa Menit ?",
      "",
      "0,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_221",
      "/jam-menit/221-0,3-jam-berapa-menit",
      "0,3 Jam Berapa Menit ?",
      "",
      "0,3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_222",
      "/jam-menit/222-0,4-jam-berapa-menit",
      "0,4 Jam Berapa Menit ?",
      "",
      "0,4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_223",
      "/jam-menit/223-0,6-jam-berapa-menit",
      "0,6 Jam Berapa Menit ?",
      "",
      "0,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_224",
      "/jam-menit/224-0,7-jam-berapa-menit",
      "0,7 Jam Berapa Menit ?",
      "",
      "0,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_225",
      "/jam-menit/225-0,75-jam-berapa-menit",
      "0,75 Jam Berapa Menit ?",
      "",
      "0,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_226",
      "/jam-menit/226-0,8-jam-berapa-menit",
      "0,8 Jam Berapa Menit ?",
      "",
      "0,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_227",
      "/jam-menit/227-0,9-jam-berapa-menit",
      "0,9 Jam Berapa Menit ?",
      "",
      "0,9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_228",
      "/jam-menit/228-1,7-jam-berapa-menit",
      "1,7 Jam Berapa Menit ?",
      "",
      "1,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_229",
      "/jam-menit/229-1,75-jam-berapa-menit",
      "1,75 Jam Berapa Menit ?",
      "",
      "1,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_230",
      "/jam-menit/230-1000-jam-berapa-menit",
      "1000 Jam Berapa Menit ?",
      "",
      "1000 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_231",
      "/jam-menit/231-2,4-jam-berapa-menit",
      "2,4 Jam Berapa Menit ?",
      "",
      "2,4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_232",
      "/jam-menit/232-2,6-jam-berapa-menit",
      "2,6 Jam Berapa Menit ?",
      "",
      "2,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_233",
      "/jam-menit/233-2,7-jam-berapa-menit",
      "2,7 Jam Berapa Menit ?",
      "",
      "2,7 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_234",
      "/jam-menit/234-2,8-jam-berapa-menit",
      "2,8 Jam Berapa Menit ?",
      "",
      "2,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_235",
      "/jam-menit/235-3,5-jam-berapa-menit",
      "3,5 Jam Berapa Menit ?",
      "",
      "3,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_236",
      "/jam-menit/236-3,6-jam-berapa-menit",
      "3,6 Jam Berapa Menit ?",
      "",
      "3,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_237",
      "/jam-menit/237-3,2-jam-berapa-menit",
      "3,2 Jam Berapa Menit ?",
      "",
      "3,2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_238",
      "/jam-menit/238-3,75-jam-berapa-menit",
      "3,75 Jam Berapa Menit ?",
      "",
      "3,75 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_239",
      "/jam-menit/239-4,5-jam-berapa-menit",
      "4,5 Jam Berapa Menit ?",
      "",
      "4,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_240",
      "/jam-menit/240-4,6-jam-berapa-menit",
      "4,6 Jam Berapa Menit ?",
      "",
      "4,6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_241",
      "/jam-menit/241-4,8-jam-berapa-menit",
      "4,8 Jam Berapa Menit ?",
      "",
      "4,8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_242",
      "/jam-menit/242-5,25-jam-berapa-menit",
      "5,25 Jam Berapa Menit ?",
      "",
      "5,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_243",
      "/jam-menit/243-5,5-jam-berapa-menit",
      "5,5 Jam Berapa Menit ?",
      "",
      "5,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_244",
      "/jam-menit/244-6,25-jam-berapa-menit",
      "6,25 Jam Berapa Menit ?",
      "",
      "6,25 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_245",
      "/jam-menit/245-7,5-jam-berapa-menit",
      "7,5 Jam Berapa Menit ?",
      "",
      "7,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_246",
      "/jam-menit/246-8,5-jam-berapa-menit",
      "8,5 Jam Berapa Menit ?",
      "",
      "8,5 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_247",
      "/jam-menit/247-30-jam-berapa-menit",
      "30 Jam Berapa Menit ?",
      "",
      "30 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_248",
      "/jam-menit/248-360-jam-berapa-menit",
      "360 Jam Berapa Menit ?",
      "",
      "360 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_249",
      "/jam-menit/249-40-jam-berapa-menit",
      "40 Jam Berapa Menit ?",
      "",
      "40 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_250",
      "/jam-menit/250-400-jam-berapa-menit",
      "400 Jam Berapa Menit ?",
      "",
      "400 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_251",
      "/jam-menit/251-48-jam-berapa-menit",
      "48 Jam Berapa Menit ?",
      "",
      "48 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_252",
      "/jam-menit/252-4-ribu-jam-berapa-menit",
      "4 ribu Jam Berapa Menit ?",
      "",
      "4 ribu Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_253",
      "/jam-menit/253-50-jam-berapa-menit",
      "50 Jam Berapa Menit ?",
      "",
      "50 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_254",
      "/jam-menit/254-500-jam-berapa-menit",
      "500 Jam Berapa Menit ?",
      "",
      "500 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_255",
      "/jam-menit/255-60-jam-berapa-menit",
      "60 Jam Berapa Menit ?",
      "",
      "60 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_256",
      "/jam-menit/256-600-jam-berapa-menit",
      "600 Jam Berapa Menit ?",
      "",
      "600 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_257",
      "/jam-menit/257-72-jam-berapa-menit",
      "72 Jam Berapa Menit ?",
      "",
      "72 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_258",
      "/jam-menit/258-720-jam-berapa-menit",
      "720 Jam Berapa Menit ?",
      "",
      "720 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_259",
      "/jam-menit/259-90-jam-berapa-menit",
      "90 Jam Berapa Menit ?",
      "",
      "90 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_260",
      "/jam-menit/260-96-jam-berapa-menit",
      "96 Jam Berapa Menit ?",
      "",
      "96 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_261",
      "/jam-menit/261-empat-jam-berapa-menit",
      "Empat Jam Berapa Menit ?",
      "",
      "Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_262",
      "/jam-menit/262-empat-setengah-jam-berapa-menit",
      "Empat Setengah Jam Berapa Menit ?",
      "",
      "Empat Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_263",
      "/jam-menit/263-lima-jam-berapa-menit",
      "Lima Jam Berapa Menit ?",
      "",
      "Lima Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_264",
      "/jam-menit/264-satu-jam-berapa-menit",
      "Satu Jam Berapa Menit ?",
      "",
      "Satu Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_265",
      "/jam-menit/265-satu-per-empat-jam-berapa-menit",
      "Satu per Empat Jam Berapa Menit ?",
      "",
      "Satu per Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_266",
      "/jam-menit/266-satu-per-enam-jam-berapa-menit",
      "Satu per Enam Jam Berapa Menit ?",
      "",
      "Satu per Enam Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_267",
      "/jam-menit/267-satu-setengah-jam-berapa-menit",
      "Satu Setengah Jam Berapa Menit ?",
      "",
      "Satu Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_268",
      "/jam-menit/268-seperdua-jam-berapa-menit",
      "Seperdua Jam Berapa Menit ?",
      "",
      "Seperdua Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_269",
      "/jam-menit/269-seperempat-jam-berapa-menit",
      "Seperempat Jam Berapa Menit ?",
      "",
      "Seperempat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_270",
      "/jam-menit/270-seperenam-jam-berapa-menit",
      "Seperenam Jam Berapa Menit ?",
      "",
      "Seperenam Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_271",
      "/jam-menit/271-seperlima-jam-berapa-menit",
      "Seperlima Jam Berapa Menit ?",
      "",
      "Seperlima Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_272",
      "/jam-menit/272-sepertiga-jam-berapa-menit",
      "Sepertiga Jam Berapa Menit ?",
      "",
      "Sepertiga Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_273",
      "/jam-menit/273-setengah-jam-berapa-menit",
      "Setengah Jam Berapa Menit ?",
      "",
      "Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_274",
      "/jam-menit/274-tiga-jam-berapa-menit",
      "Tiga Jam Berapa Menit ?",
      "",
      "Tiga Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_275",
      "/jam-menit/275-tiga-perempat-jam-berapa-menit",
      "Tiga Perempat Jam Berapa Menit ?",
      "",
      "Tiga Perempat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_276",
      "/jam-menit/276-tiga-per-empat-jam-berapa-menit",
      "Tiga Per Empat Jam Berapa Menit ?",
      "",
      "Tiga Per Empat Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_277",
      "/jam-menit/277-tiga-setengah-jam-berapa-menit",
      "Tiga Setengah Jam Berapa Menit ?",
      "",
      "Tiga Setengah Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_278",
      "/jam-menit/278-satu-per-empat-jam-berapa-menit",
      "1/4 Jam Berapa Menit ?",
      "",
      "1/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_279",
      "/jam-menit/279-dua-seperdua-jam-berapa-menit",
      "2 1/2 Jam Berapa Menit ?",
      "",
      "2 1/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_280",
      "/jam-menit/280-2-per-3-jam-berapa-menit",
      "2/3 Jam Berapa Menit ?",
      "",
      "2/3 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_281",
      "/jam-menit/281-21-per-2-jam-berapa-menit",
      "21/2 Jam Berapa Menit ?",
      "",
      "21/2 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_282",
      "/jam-menit/282-3-per-4-jam-berapa-menit",
      "3/4 Jam Berapa Menit ?",
      "",
      "3/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_283",
      "/jam-menit/283-3-per-8-jam-berapa-menit",
      "3/8 Jam Berapa Menit ?",
      "",
      "3/8 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_284",
      "/jam-menit/284-31-per-4-jam-berapa-menit",
      "31/4 Jam Berapa Menit ?",
      "",
      "31/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_285",
      "/jam-menit/285-5-per-6-jam-berapa-menit",
      "5/6 Jam Berapa Menit ?",
      "",
      "5/6 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_286",
      "/jam-menit/286-7-per-12-jam-berapa-menit",
      "7/12 Jam Berapa Menit ?",
      "",
      "7/12 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_287",
      "/jam-menit/287-7-per-4-jam-berapa-menit",
      "7/4 Jam Berapa Menit ?",
      "",
      "7/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_288",
      "/jam-menit/288-9-per-4-jam-berapa-menit",
      "9/4 Jam Berapa Menit ?",
      "",
      "9/4 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_289",
      "/jam-menit/289-8-per-9-jam-berapa-menit",
      "8/9 Jam Berapa Menit ?",
      "",
      "8/9 Jam = ... Menit",
      ["Jam-Menit"],
      "",
    ],
    [
      "Waktu_290",
      "/menit-jam/290-0,2-menit-berapa-jam",
      "0,2 Menit Berapa Jam ?",
      "",
      "0,2 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_291",
      "/menit-jam/291-0,25-menit-berapa-jam",
      "0,25 Menit Berapa Jam ?",
      "",
      "0,25 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_292",
      "/menit-jam/292-0,4-menit-berapa-jam",
      "0,4 Menit Berapa Jam ?",
      "",
      "0,4 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_293",
      "/menit-jam/293-0,5-menit-berapa-jam",
      "0,5 Menit Berapa Jam ?",
      "",
      "0,5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_294",
      "/menit-jam/294-1,5-menit-berapa-jam",
      "1,5 Menit Berapa Jam ?",
      "",
      "1,5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_295",
      "/menit-jam/295-1-menit-berapa-jam",
      "1 Menit Berapa Jam ?",
      "",
      "1 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_296",
      "/menit-jam/296-1-juta-menit-berapa-jam",
      "1 juta Menit Berapa Jam ?",
      "",
      "1 juta Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_297",
      "/menit-jam/297-11-ribu-menit-berapa-jam",
      "11 ribu Menit Berapa Jam ?",
      "",
      "11 ribu Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_298",
      "/menit-jam/298-135-menit-berapa-jam",
      "135 Menit Berapa Jam ?",
      "",
      "135 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_299",
      "/menit-jam/299-150-menit-berapa-jam",
      "150 Menit Berapa Jam ?",
      "",
      "150 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_300",
      "/menit-jam/300-1600-menit-berapa-jam",
      "1600 Menit Berapa Jam ?",
      "",
      "1600 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_301",
      "/menit-jam/301-160-menit-berapa-jam",
      "160 Menit Berapa Jam ?",
      "",
      "160 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_302",
      "/menit-jam/302-1800-menit-berapa-jam",
      "1800 Menit Berapa Jam ?",
      "",
      "1800 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_303",
      "/menit-jam/303-185-menit-berapa-jam",
      "185 Menit Berapa Jam ?",
      "",
      "185 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_304",
      "/menit-jam/304-20-ribu-menit-berapa-jam",
      "20 ribu Menit Berapa Jam ?",
      "",
      "20 ribu Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_305",
      "/menit-jam/305-200-menit-berapa-jam",
      "200 Menit Berapa Jam ?",
      "",
      "200 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_306",
      "/menit-jam/306-2000-menit-berapa-jam",
      "2000 Menit Berapa Jam ?",
      "",
      "2000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_307",
      "/menit-jam/307-212-menit-berapa-jam",
      "212 Menit Berapa Jam ?",
      "",
      "212 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_308",
      "/menit-jam/308-214-menit-berapa-jam",
      "214 Menit Berapa Jam ?",
      "",
      "214 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_309",
      "/menit-jam/309-240-menit-berapa-jam",
      "240 Menit Berapa Jam ?",
      "",
      "240 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_310",
      "/menit-jam/310-360-menit-berapa-jam",
      "360 Menit Berapa Jam ?",
      "",
      "360 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_311",
      "/menit-jam/311-3000-menit-berapa-jam",
      "3000 Menit Berapa Jam ?",
      "",
      "3000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_312",
      "/menit-jam/312-420-menit-berapa-jam",
      "420 Menit Berapa Jam ?",
      "",
      "420 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_313",
      "/menit-jam/313-480-menit-berapa-jam",
      "480 Menit Berapa Jam ?",
      "",
      "480 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_314",
      "/menit-jam/314-4680-menit-berapa-jam",
      "4680 Menit Berapa Jam ?",
      "",
      "4680 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_315",
      "/menit-jam/315-540-menit-berapa-jam",
      "540 Menit Berapa Jam ?",
      "",
      "540 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_316",
      "/menit-jam/316-600-menit-berapa-jam",
      "600 Menit Berapa Jam ?",
      "",
      "600 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_317",
      "/menit-jam/317-6000-menit-berapa-jam",
      "6000 Menit Berapa Jam ?",
      "",
      "6000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_318",
      "/menit-jam/318-60000-menit-berapa-jam",
      "60000 Menit Berapa Jam ?",
      "",
      "60000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_319",
      "/menit-jam/319-660-menit-berapa-jam",
      "660 Menit Berapa Jam ?",
      "",
      "660 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_320",
      "/menit-jam/320-720-menit-berapa-jam",
      "720 Menit Berapa Jam ?",
      "",
      "720 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_321",
      "/menit-jam/321-7200-menit-berapa-jam",
      "7200 Menit Berapa Jam ?",
      "",
      "7200 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_322",
      "/menit-jam/322-86400-menit-berapa-jam",
      "86400 Menit Berapa Jam ?",
      "",
      "86400 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_323",
      "/menit-jam/323-900-menit-berapa-jam",
      "900 Menit Berapa Jam ?",
      "",
      "900 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_324",
      "/menit-jam/324-9000-menit-berapa-jam",
      "9000 Menit Berapa Jam ?",
      "",
      "9000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_325",
      "/menit-jam/325-2-menit-berapa-jam",
      "2 Menit Berapa Jam ?",
      "",
      "2 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_326",
      "/menit-jam/326-25-menit-berapa-jam",
      "25 Menit Berapa Jam ?",
      "",
      "25 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_327",
      "/menit-jam/327-2,5-menit-berapa-jam",
      "2,5 Menit Berapa Jam ?",
      "",
      "2,5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_328",
      "/menit-jam/328-3-menit-berapa-jam",
      "3 Menit Berapa Jam ?",
      "",
      "3 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_329",
      "/menit-jam/329-35-menit-berapa-jam",
      "35 Menit Berapa Jam ?",
      "",
      "35 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_330",
      "/menit-jam/330-4,5-menit-berapa-jam",
      "4,5 Menit Berapa Jam ?",
      "",
      "4,5 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_331",
      "/menit-jam/331-4-menit-berapa-jam",
      "4 Menit Berapa Jam ?",
      "",
      "4 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_332",
      "/menit-jam/332-50-menit-berapa-jam",
      "50 Menit Berapa Jam ?",
      "",
      "50 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_333",
      "/menit-jam/333-54-menit-berapa-jam",
      "54 Menit Berapa Jam ?",
      "",
      "54 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_334",
      "/menit-jam/334-55-menit-berapa-jam",
      "55 Menit Berapa Jam ?",
      "",
      "55 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_335",
      "/menit-jam/335-6-menit-berapa-jam",
      "6 Menit Berapa Jam ?",
      "",
      "6 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_336",
      "/menit-jam/336-7-menit-berapa-jam",
      "7 Menit Berapa Jam ?",
      "",
      "7 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_337",
      "/menit-jam/337-8-menit-berapa-jam",
      "8 Menit Berapa Jam ?",
      "",
      "8 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_338",
      "/menit-jam/338-9-menit-berapa-jam",
      "9 Menit Berapa Jam ?",
      "",
      "9 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_339",
      "/menit-jam/339-56-menit-berapa-jam",
      "56 Menit Berapa Jam ?",
      "",
      "56 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_340",
      "/menit-jam/340-330-menit-berapa-jam",
      "330 Menit Berapa Jam ?",
      "",
      "330 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_341",
      "/menit-jam/341-350-menit-berapa-jam",
      "350 Menit Berapa Jam ?",
      "",
      "350 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_342",
      "/menit-jam/342-400-menit-berapa-jam",
      "400 Menit Berapa Jam ?",
      "",
      "400 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_343",
      "/menit-jam/343-5000-menit-berapa-jam",
      "5000 Menit Berapa Jam ?",
      "",
      "5000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_344",
      "/menit-jam/344-630-menit-berapa-jam",
      "630 Menit Berapa Jam ?",
      "",
      "630 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_345",
      "/menit-jam/345-65-menit-berapa-jam",
      "65 Menit Berapa Jam ?",
      "",
      "65 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_346",
      "/menit-jam/346-70-menit-berapa-jam",
      "70 Menit Berapa Jam ?",
      "",
      "70 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_347",
      "/menit-jam/347-700-menit-berapa-jam",
      "700 Menit Berapa Jam ?",
      "",
      "700 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_348",
      "/menit-jam/348-7000-menit-berapa-jam",
      "7000 Menit Berapa Jam ?",
      "",
      "7000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_349",
      "/menit-jam/349-72-menit-berapa-jam",
      "72 Menit Berapa Jam ?",
      "",
      "72 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_350",
      "/menit-jam/350-75-menit-berapa-jam",
      "75 Menit Berapa Jam ?",
      "",
      "75 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_351",
      "/menit-jam/351-80-menit-berapa-jam",
      "80 Menit Berapa Jam ?",
      "",
      "80 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_352",
      "/menit-jam/352-800-menit-berapa-jam",
      "800 Menit Berapa Jam ?",
      "",
      "800 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_353",
      "/menit-jam/353-8000-menit-berapa-jam",
      "8000 Menit Berapa Jam ?",
      "",
      "8000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_354",
      "/menit-jam/354-84-menit-berapa-jam",
      "84 Menit Berapa Jam ?",
      "",
      "84 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_355",
      "/menit-jam/355-85-menit-berapa-jam",
      "85 Menit Berapa Jam ?",
      "",
      "85 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_356",
      "/menit-jam/356-86-menit-berapa-jam",
      "86 Menit Berapa Jam ?",
      "",
      "86 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_357",
      "/menit-jam/357-95-menit-berapa-jam",
      "95 Menit Berapa Jam ?",
      "",
      "95 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_358",
      "/menit-jam/358-96-menit-berapa-jam",
      "96 Menit Berapa Jam ?",
      "",
      "96 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_359",
      "/menit-jam/359-98-menit-berapa-jam",
      "98 Menit Berapa Jam ?",
      "",
      "98 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_360",
      "/menit-jam/360-99-menit-berapa-jam",
      "99 Menit Berapa Jam ?",
      "",
      "99 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_361",
      "/menit-jam/361-empat-puluh-lima-menit-berapa-jam",
      "Empat Puluh Lima Menit Berapa Jam ?",
      "",
      "45 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_362",
      "/menit-jam/362-satu-menit-berapa-jam",
      "Satu Menit Berapa Jam ?",
      "",
      "1 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_363",
      "/menit-jam/363-tiga-menit-berapa-jam",
      "Tiga Menit Berapa Jam ?",
      "",
      "3 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_364",
      "/menit-jam/364-sepuluh-menit-berapa-jam",
      "Sepuluh Menit Berapa Jam ?",
      "",
      "10 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_365",
      "/menit-jam/365-seratus-menit-berapa-jam",
      "Seratus Menit Berapa Jam ?",
      "",
      "100 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_366",
      "/menit-jam/366-seribu-menit-berapa-jam",
      "Seribu Menit Berapa Jam ?",
      "",
      "1000 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_367",
      "/menit-jam/367-setengah-menit-berapa-jam",
      "Setengah Menit Berapa Jam ?",
      "",
      "1/2 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_368",
      "/menit-jam/368-satu-per-empat-menit-berapa-jam",
      "Satu per Empat Menit Berapa Jam ?",
      "",
      "1/4 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_369",
      "/menit-jam/369-1-per-2-menit-berapa-jam",
      "1/2 per Empat Menit Berapa Jam ?",
      "",
      "1/2 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_370",
      "/menit-jam/370-1-per-4-menit-berapa-jam",
      "1/4 per Empat Menit Berapa Jam ?",
      "",
      "1/4 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],
    [
      "Waktu_371",
      "/menit-jam/371-3-per-4-menit-berapa-jam",
      "3/4 per Empat Menit Berapa Jam ?",
      "",
      "3/4 Menit = ... Jam",
      ["Menit-Jam"],
      "",
    ],

["waktu_372", "/jam-berapa/372-jam-13-jam-berapa", "Jam 13 Jam Berapa ?", "", "Jam 13 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_373", "/jam-berapa/373-jam-14-jam-berapa", "Jam 14 Jam Berapa ?", "", "Jam 14 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_374", "/jam-berapa/374-jam-15-jam-berapa", "Jam 15 Jam Berapa ?", "", "Jam 15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_375", "/jam-berapa/375-jam-16-jam-berapa", "Jam 16 Jam Berapa ?", "", "Jam 16 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_376", "/jam-berapa/376-jam-17-jam-berapa", "Jam 17 Jam Berapa ?", "", "Jam 17 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_377", "/jam-berapa/377-jam-18-jam-berapa", "Jam 18 Jam Berapa ?", "", "Jam 18 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_378", "/jam-berapa/378-jam-19-jam-berapa", "Jam 19 Jam Berapa ?", "", "Jam 19 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_379", "/jam-berapa/379-jam-20-jam-berapa", "Jam 20 Jam Berapa ?", "", "Jam 20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_380", "/jam-berapa/380-jam-21-jam-berapa", "Jam 21 Jam Berapa ?", "", "Jam 21 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_381", "/jam-berapa/381-jam-22-jam-berapa", "Jam 22 Jam Berapa ?", "", "Jam 22 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_382", "/jam-berapa/382-jam-23-jam-berapa", "Jam 23 Jam Berapa ?", "", "Jam 23 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_383", "/jam-berapa/383-jam-24-jam-berapa", "Jam 24 Jam Berapa ?", "", "Jam 24 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_384", "/jam-berapa/384-jam-13-00-jam-berapa", "Jam 13:00 Jam Berapa ?", "", "Jam 13:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_385", "/jam-berapa/385-jam-14-00-jam-berapa", "Jam 14:00 Jam Berapa ?", "", "Jam 14:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_386", "/jam-berapa/386-jam-15-00-jam-berapa", "Jam 15:00 Jam Berapa ?", "", "Jam 15:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_387", "/jam-berapa/387-jam-16-00-jam-berapa", "Jam 16:00 Jam Berapa ?", "", "Jam 16:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_388", "/jam-berapa/388-jam-17-00-jam-berapa", "Jam 17:00 Jam Berapa ?", "", "Jam 17:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_389", "/jam-berapa/389-jam-18-00-jam-berapa", "Jam 18:00 Jam Berapa ?", "", "Jam 18:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_390", "/jam-berapa/390-jam-19-00-jam-berapa", "Jam 19:00 Jam Berapa ?", "", "Jam 19:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_391", "/jam-berapa/391-jam-20-00-jam-berapa", "Jam 20:00 Jam Berapa ?", "", "Jam 20:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_392", "/jam-berapa/392-jam-21-00-jam-berapa", "Jam 21:00 Jam Berapa ?", "", "Jam 21:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_393", "/jam-berapa/393-jam-22-00-jam-berapa", "Jam 22:00 Jam Berapa ?", "", "Jam 22:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_394", "/jam-berapa/394-jam-23-00-jam-berapa", "Jam 23:00 Jam Berapa ?", "", "Jam 23:00 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_395", "/jam-berapa/395-jam-13-05-jam-berapa", "Jam 13:05 Jam Berapa ?", "", "Jam 13:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_396", "/jam-berapa/396-jam-14-05-jam-berapa", "Jam 14:05 Jam Berapa ?", "", "Jam 14:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_397", "/jam-berapa/397-jam-15-05-jam-berapa", "Jam 15:05 Jam Berapa ?", "", "Jam 15:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_398", "/jam-berapa/398-jam-16-05-jam-berapa", "Jam 16:05 Jam Berapa ?", "", "Jam 16:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_399", "/jam-berapa/399-jam-17-05-jam-berapa", "Jam 17:05 Jam Berapa ?", "", "Jam 17:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_400", "/jam-berapa/400-jam-18-05-jam-berapa", "Jam 18:05 Jam Berapa ?", "", "Jam 18:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_401", "/jam-berapa/401-jam-19-05-jam-berapa", "Jam 19:05 Jam Berapa ?", "", "Jam 19:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_402", "/jam-berapa/402-jam-20-05-jam-berapa", "Jam 20:05 Jam Berapa ?", "", "Jam 20:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_403", "/jam-berapa/403-jam-21-05-jam-berapa", "Jam 21:05 Jam Berapa ?", "", "Jam 21:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_404", "/jam-berapa/404-jam-22-05-jam-berapa", "Jam 22:05 Jam Berapa ?", "", "Jam 22:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_405", "/jam-berapa/405-jam-23-05-jam-berapa", "Jam 23:05 Jam Berapa ?", "", "Jam 23:05 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_406", "/jam-berapa/406-jam-13-10-jam-berapa", "Jam 13:10 Jam Berapa ?", "", "Jam 13:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_407", "/jam-berapa/407-jam-14-10-jam-berapa", "Jam 14:10 Jam Berapa ?", "", "Jam 14:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_408", "/jam-berapa/408-jam-15-10-jam-berapa", "Jam 15:10 Jam Berapa ?", "", "Jam 15:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_409", "/jam-berapa/409-jam-16-10-jam-berapa", "Jam 16:10 Jam Berapa ?", "", "Jam 16:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_410", "/jam-berapa/410-jam-17-10-jam-berapa", "Jam 17:10 Jam Berapa ?", "", "Jam 17:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_411", "/jam-berapa/411-jam-18-10-jam-berapa", "Jam 18:10 Jam Berapa ?", "", "Jam 18:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_412", "/jam-berapa/412-jam-19-10-jam-berapa", "Jam 19:10 Jam Berapa ?", "", "Jam 19:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_413", "/jam-berapa/413-jam-20-10-jam-berapa", "Jam 20:10 Jam Berapa ?", "", "Jam 20:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_414", "/jam-berapa/414-jam-21-10-jam-berapa", "Jam 21:10 Jam Berapa ?", "", "Jam 21:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_415", "/jam-berapa/415-jam-22-10-jam-berapa", "Jam 22:10 Jam Berapa ?", "", "Jam 22:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_416", "/jam-berapa/416-jam-23-10-jam-berapa", "Jam 23:10 Jam Berapa ?", "", "Jam 23:10 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_417", "/jam-berapa/417-jam-13-15-jam-berapa", "Jam 13:15 Jam Berapa ?", "", "Jam 13:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_418", "/jam-berapa/418-jam-14-15-jam-berapa", "Jam 14:15 Jam Berapa ?", "", "Jam 14:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_419", "/jam-berapa/419-jam-15-15-jam-berapa", "Jam 15:15 Jam Berapa ?", "", "Jam 15:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_420", "/jam-berapa/420-jam-16-15-jam-berapa", "Jam 16:15 Jam Berapa ?", "", "Jam 16:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_421", "/jam-berapa/421-jam-17-15-jam-berapa", "Jam 17:15 Jam Berapa ?", "", "Jam 17:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_422", "/jam-berapa/422-jam-18-15-jam-berapa", "Jam 18:15 Jam Berapa ?", "", "Jam 18:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_423", "/jam-berapa/423-jam-19-15-jam-berapa", "Jam 19:15 Jam Berapa ?", "", "Jam 19:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_424", "/jam-berapa/424-jam-20-15-jam-berapa", "Jam 20:15 Jam Berapa ?", "", "Jam 20:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_425", "/jam-berapa/425-jam-21-15-jam-berapa", "Jam 21:15 Jam Berapa ?", "", "Jam 21:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_426", "/jam-berapa/426-jam-22-15-jam-berapa", "Jam 22:15 Jam Berapa ?", "", "Jam 22:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_427", "/jam-berapa/427-jam-23-15-jam-berapa", "Jam 23:15 Jam Berapa ?", "", "Jam 23:15 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_428", "/jam-berapa/428-jam-13-20-jam-berapa", "Jam 13:20 Jam Berapa ?", "", "Jam 13:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_429", "/jam-berapa/429-jam-14-20-jam-berapa", "Jam 14:20 Jam Berapa ?", "", "Jam 14:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_430", "/jam-berapa/430-jam-15-20-jam-berapa", "Jam 15:20 Jam Berapa ?", "", "Jam 15:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_431", "/jam-berapa/431-jam-16-20-jam-berapa", "Jam 16:20 Jam Berapa ?", "", "Jam 16:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_432", "/jam-berapa/432-jam-17-20-jam-berapa", "Jam 17:20 Jam Berapa ?", "", "Jam 17:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_433", "/jam-berapa/433-jam-18-20-jam-berapa", "Jam 18:20 Jam Berapa ?", "", "Jam 18:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_434", "/jam-berapa/434-jam-19-20-jam-berapa", "Jam 19:20 Jam Berapa ?", "", "Jam 19:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_435", "/jam-berapa/435-jam-20-20-jam-berapa", "Jam 20:20 Jam Berapa ?", "", "Jam 20:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_436", "/jam-berapa/436-jam-21-20-jam-berapa", "Jam 21:20 Jam Berapa ?", "", "Jam 21:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_437", "/jam-berapa/437-jam-22-20-jam-berapa", "Jam 22:20 Jam Berapa ?", "", "Jam 22:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_438", "/jam-berapa/438-jam-23-20-jam-berapa", "Jam 23:20 Jam Berapa ?", "", "Jam 23:20 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_439", "/jam-berapa/439-jam-13-25-jam-berapa", "Jam 13:25 Jam Berapa ?", "", "Jam 13:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_440", "/jam-berapa/440-jam-14-25-jam-berapa", "Jam 14:25 Jam Berapa ?", "", "Jam 14:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_441", "/jam-berapa/441-jam-15-25-jam-berapa", "Jam 15:25 Jam Berapa ?", "", "Jam 15:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_442", "/jam-berapa/442-jam-16-25-jam-berapa", "Jam 16:25 Jam Berapa ?", "", "Jam 16:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_443", "/jam-berapa/443-jam-17-25-jam-berapa", "Jam 17:25 Jam Berapa ?", "", "Jam 17:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_444", "/jam-berapa/444-jam-18-25-jam-berapa", "Jam 18:25 Jam Berapa ?", "", "Jam 18:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_445", "/jam-berapa/445-jam-19-25-jam-berapa", "Jam 19:25 Jam Berapa ?", "", "Jam 19:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_446", "/jam-berapa/446-jam-20-25-jam-berapa", "Jam 20:25 Jam Berapa ?", "", "Jam 20:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_447", "/jam-berapa/447-jam-21-25-jam-berapa", "Jam 21:25 Jam Berapa ?", "", "Jam 21:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_448", "/jam-berapa/448-jam-22-25-jam-berapa", "Jam 22:25 Jam Berapa ?", "", "Jam 22:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_449", "/jam-berapa/449-jam-23-25-jam-berapa", "Jam 23:25 Jam Berapa ?", "", "Jam 23:25 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_450", "/jam-berapa/450-jam-13-30-jam-berapa", "Jam 13:30 Jam Berapa ?", "", "Jam 13:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_451", "/jam-berapa/451-jam-14-30-jam-berapa", "Jam 14:30 Jam Berapa ?", "", "Jam 14:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_452", "/jam-berapa/452-jam-15-30-jam-berapa", "Jam 15:30 Jam Berapa ?", "", "Jam 15:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_453", "/jam-berapa/453-jam-16-30-jam-berapa", "Jam 16:30 Jam Berapa ?", "", "Jam 16:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_454", "/jam-berapa/454-jam-17-30-jam-berapa", "Jam 17:30 Jam Berapa ?", "", "Jam 17:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_455", "/jam-berapa/455-jam-18-30-jam-berapa", "Jam 18:30 Jam Berapa ?", "", "Jam 18:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_456", "/jam-berapa/456-jam-19-30-jam-berapa", "Jam 19:30 Jam Berapa ?", "", "Jam 19:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_457", "/jam-berapa/457-jam-20-30-jam-berapa", "Jam 20:30 Jam Berapa ?", "", "Jam 20:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_458", "/jam-berapa/458-jam-21-30-jam-berapa", "Jam 21:30 Jam Berapa ?", "", "Jam 21:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_459", "/jam-berapa/459-jam-22-30-jam-berapa", "Jam 22:30 Jam Berapa ?", "", "Jam 22:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_460", "/jam-berapa/460-jam-23-30-jam-berapa", "Jam 23:30 Jam Berapa ?", "", "Jam 23:30 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_461", "/jam-berapa/461-jam-13-35-jam-berapa", "Jam 13:35 Jam Berapa ?", "", "Jam 13:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_462", "/jam-berapa/462-jam-14-35-jam-berapa", "Jam 14:35 Jam Berapa ?", "", "Jam 14:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_463", "/jam-berapa/463-jam-15-35-jam-berapa", "Jam 15:35 Jam Berapa ?", "", "Jam 15:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_464", "/jam-berapa/464-jam-16-35-jam-berapa", "Jam 16:35 Jam Berapa ?", "", "Jam 16:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_465", "/jam-berapa/465-jam-17-35-jam-berapa", "Jam 17:35 Jam Berapa ?", "", "Jam 17:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_466", "/jam-berapa/466-jam-18-35-jam-berapa", "Jam 18:35 Jam Berapa ?", "", "Jam 18:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_467", "/jam-berapa/467-jam-19-35-jam-berapa", "Jam 19:35 Jam Berapa ?", "", "Jam 19:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_468", "/jam-berapa/468-jam-20-35-jam-berapa", "Jam 20:35 Jam Berapa ?", "", "Jam 20:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_469", "/jam-berapa/469-jam-21-35-jam-berapa", "Jam 21:35 Jam Berapa ?", "", "Jam 21:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_470", "/jam-berapa/470-jam-22-35-jam-berapa", "Jam 22:35 Jam Berapa ?", "", "Jam 22:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_471", "/jam-berapa/471-jam-23-35-jam-berapa", "Jam 23:35 Jam Berapa ?", "", "Jam 23:35 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_472", "/jam-berapa/472-jam-13-40-jam-berapa", "Jam 13:40 Jam Berapa ?", "", "Jam 13:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_473", "/jam-berapa/473-jam-14-40-jam-berapa", "Jam 14:40 Jam Berapa ?", "", "Jam 14:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_474", "/jam-berapa/474-jam-15-40-jam-berapa", "Jam 15:40 Jam Berapa ?", "", "Jam 15:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_475", "/jam-berapa/475-jam-16-40-jam-berapa", "Jam 16:40 Jam Berapa ?", "", "Jam 16:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_476", "/jam-berapa/476-jam-17-40-jam-berapa", "Jam 17:40 Jam Berapa ?", "", "Jam 17:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_477", "/jam-berapa/477-jam-18-40-jam-berapa", "Jam 18:40 Jam Berapa ?", "", "Jam 18:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_478", "/jam-berapa/478-jam-19-40-jam-berapa", "Jam 19:40 Jam Berapa ?", "", "Jam 19:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_479", "/jam-berapa/479-jam-20-40-jam-berapa", "Jam 20:40 Jam Berapa ?", "", "Jam 20:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_480", "/jam-berapa/480-jam-21-40-jam-berapa", "Jam 21:40 Jam Berapa ?", "", "Jam 21:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_481", "/jam-berapa/481-jam-22-40-jam-berapa", "Jam 22:40 Jam Berapa ?", "", "Jam 22:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_482", "/jam-berapa/482-jam-23-40-jam-berapa", "Jam 23:40 Jam Berapa ?", "", "Jam 23:40 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_483", "/jam-berapa/483-jam-13-45-jam-berapa", "Jam 13:45 Jam Berapa ?", "", "Jam 13:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_484", "/jam-berapa/484-jam-14-45-jam-berapa", "Jam 14:45 Jam Berapa ?", "", "Jam 14:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_485", "/jam-berapa/485-jam-15-45-jam-berapa", "Jam 15:45 Jam Berapa ?", "", "Jam 15:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_486", "/jam-berapa/486-jam-16-45-jam-berapa", "Jam 16:45 Jam Berapa ?", "", "Jam 16:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_487", "/jam-berapa/487-jam-17-45-jam-berapa", "Jam 17:45 Jam Berapa ?", "", "Jam 17:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_488", "/jam-berapa/488-jam-18-45-jam-berapa", "Jam 18:45 Jam Berapa ?", "", "Jam 18:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_489", "/jam-berapa/489-jam-19-45-jam-berapa", "Jam 19:45 Jam Berapa ?", "", "Jam 19:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_490", "/jam-berapa/490-jam-20-45-jam-berapa", "Jam 20:45 Jam Berapa ?", "", "Jam 20:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_491", "/jam-berapa/491-jam-21-45-jam-berapa", "Jam 21:45 Jam Berapa ?", "", "Jam 21:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_492", "/jam-berapa/492-jam-22-45-jam-berapa", "Jam 22:45 Jam Berapa ?", "", "Jam 22:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_493", "/jam-berapa/493-jam-23-45-jam-berapa", "Jam 23:45 Jam Berapa ?", "", "Jam 23:45 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_494", "/jam-berapa/494-jam-13-50-jam-berapa", "Jam 13:50 Jam Berapa ?", "", "Jam 13:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_495", "/jam-berapa/495-jam-14-50-jam-berapa", "Jam 14:50 Jam Berapa ?", "", "Jam 14:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_496", "/jam-berapa/496-jam-15-50-jam-berapa", "Jam 15:50 Jam Berapa ?", "", "Jam 15:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_497", "/jam-berapa/497-jam-16-50-jam-berapa", "Jam 16:50 Jam Berapa ?", "", "Jam 16:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_498", "/jam-berapa/498-jam-17-50-jam-berapa", "Jam 17:50 Jam Berapa ?", "", "Jam 17:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_499", "/jam-berapa/499-jam-18-50-jam-berapa", "Jam 18:50 Jam Berapa ?", "", "Jam 18:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_500", "/jam-berapa/500-jam-19-50-jam-berapa", "Jam 19:50 Jam Berapa ?", "", "Jam 19:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_501", "/jam-berapa/501-jam-20-50-jam-berapa", "Jam 20:50 Jam Berapa ?", "", "Jam 20:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_502", "/jam-berapa/502-jam-21-50-jam-berapa", "Jam 21:50 Jam Berapa ?", "", "Jam 21:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_503", "/jam-berapa/503-jam-22-50-jam-berapa", "Jam 22:50 Jam Berapa ?", "", "Jam 22:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_504", "/jam-berapa/504-jam-23-50-jam-berapa", "Jam 23:50 Jam Berapa ?", "", "Jam 23:50 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_505", "/jam-berapa/505-jam-13-55-jam-berapa", "Jam 13:55 Jam Berapa ?", "", "Jam 13:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_506", "/jam-berapa/506-jam-14-55-jam-berapa", "Jam 14:55 Jam Berapa ?", "", "Jam 14:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_507", "/jam-berapa/507-jam-15-55-jam-berapa", "Jam 15:55 Jam Berapa ?", "", "Jam 15:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_508", "/jam-berapa/508-jam-16-55-jam-berapa", "Jam 16:55 Jam Berapa ?", "", "Jam 16:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_509", "/jam-berapa/509-jam-17-55-jam-berapa", "Jam 17:55 Jam Berapa ?", "", "Jam 17:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_510", "/jam-berapa/510-jam-18-55-jam-berapa", "Jam 18:55 Jam Berapa ?", "", "Jam 18:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_511", "/jam-berapa/511-jam-19-55-jam-berapa", "Jam 19:55 Jam Berapa ?", "", "Jam 19:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_512", "/jam-berapa/512-jam-20-55-jam-berapa", "Jam 20:55 Jam Berapa ?", "", "Jam 20:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_513", "/jam-berapa/513-jam-21-55-jam-berapa", "Jam 21:55 Jam Berapa ?", "", "Jam 21:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_514", "/jam-berapa/514-jam-22-55-jam-berapa", "Jam 22:55 Jam Berapa ?", "", "Jam 22:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 
["waktu_515", "/jam-berapa/515-jam-23-55-jam-berapa", "Jam 23:55 Jam Berapa ?", "", "Jam 23:55 Jam Berapa ? jawaban beserta penjelasannya ", ["Jam Berapa"], "", ], 

];