var titleCat_1 = "Berat";
var cat_1 = [
  ["ton = ... kg", "/ton-kg/001-0,06-ton-berapa-kg", ""],
  ["kg = ... ton", "/kg-ton/100-1-kg-berapa-ton", ""],
  ["kuintal = ... ton", "/kuintal-ton/177-1-kuintal-berapa-ton", ""],
  ["ton = ... kuintal", "/ton-kuintal/224-0,08-ton-berapa-kuintal", ""],
];

var url_root = "https://nasrianas.website/jawab/math/berat";
var footerArray = [
    //June2020
    [
      "berat_001",
      "/ton-kg/001-0,06-ton-berapa-kg",
      "0,06 ton berapa kg ?",
      "",
      "0,06 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_002",
      "/ton-kg/002-0,2-ton-berapa-kg",
      "0,2 ton berapa kg ?",
      "",
      "0,2 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_003",
      "/ton-kg/003-0,25-ton-berapa-kg",
      "0,25 ton berapa kg ?",
      "",
      "0,25 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_004",
      "/ton-kg/004-0,3-ton-berapa-kg",
      "0,3 ton berapa kg ?",
      "",
      "0,3 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_005",
      "/ton-kg/005-0,35-ton-berapa-kg",
      "0,35 ton berapa kg ?",
      "",
      "0,35 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_006",
      "/ton-kg/006-0,4-ton-berapa-kg",
      "0,4 ton berapa kg ?",
      "",
      "0,4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_007",
      "/ton-kg/007-0,5-ton-berapa-kg",
      "0,5 ton berapa kg ?",
      "",
      "0,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_008",
      "/ton-kg/008-0,6-ton-berapa-kg",
      "0,6 ton berapa kg ?",
      "",
      "0,6 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_009",
      "/ton-kg/009-0,625-ton-berapa-kg",
      "0,625 ton berapa kg ?",
      "",
      "0,625 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_010",
      "/ton-kg/010-0,7-ton-berapa-kg",
      "0,7 ton berapa kg ?",
      "",
      "0,7 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_011",
      "/ton-kg/011-0,75-ton-berapa-kg",
      "0,75 ton berapa kg ?",
      "",
      "0,75 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_012",
      "/ton-kg/012-0,8-ton-berapa-kg",
      "0,8 ton berapa kg ?",
      "",
      "0,8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_013",
      "/ton-kg/013-1-ton-berapa-kg",
      "1 ton berapa kg ?",
      "",
      "1 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_014",
      "/ton-kg/014-1,2-ton-berapa-kg",
      "1,2 ton berapa kg ?",
      "",
      "1,2 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_015",
      "/ton-kg/015-1,3-ton-berapa-kg",
      "1,3 ton berapa kg ?",
      "",
      "1,3 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_016",
      "/ton-kg/016-1,5-ton-berapa-kg",
      "1,5 ton berapa kg ?",
      "",
      "1,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_017",
      "/ton-kg/017-1,7-ton-berapa-kg",
      "1,7 ton berapa kg ?",
      "",
      "1,7 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_018",
      "/ton-kg/018-1,8-ton-berapa-kg",
      "1,8 ton berapa kg ?",
      "",
      "1,8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_019",
      "/ton-kg/019-1,98-ton-berapa-kg",
      "1,98 ton berapa kg ?",
      "",
      "1,98 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_020",
      "/ton-kg/020-2-ton-berapa-kg",
      "2 ton berapa kg ?",
      "",
      "2 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_021",
      "/ton-kg/021-2,25-ton-berapa-kg",
      "2,25 ton berapa kg ?",
      "",
      "2,25 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_022",
      "/ton-kg/022-2,3-ton-berapa-kg",
      "2,3 ton berapa kg ?",
      "",
      "2,3 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_023",
      "/ton-kg/023-2,4-ton-berapa-kg",
      "2,4 ton berapa kg ?",
      "",
      "2,4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_024",
      "/ton-kg/024-2,5-ton-berapa-kg",
      "2,5 ton berapa kg ?",
      "",
      "2,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_025",
      "/ton-kg/025-2,55-ton-berapa-kg",
      "2,55 ton berapa kg ?",
      "",
      "2,55 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_026",
      "/ton-kg/026-2,7-ton-berapa-kg",
      "2,7 ton berapa kg ?",
      "",
      "2,7 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_027",
      "/ton-kg/027-2,8-ton-berapa-kg",
      "2,8 ton berapa kg ?",
      "",
      "2,8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_028",
      "/ton-kg/028-3-ton-berapa-kg",
      "3 ton berapa kg ?",
      "",
      "3 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_029",
      "/ton-kg/029-3,5-ton-berapa-kg",
      "3,5 ton berapa kg ?",
      "",
      "3,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_030",
      "/ton-kg/030-3,56-ton-berapa-kg",
      "3,56 ton berapa kg ?",
      "",
      "3,56 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_031",
      "/ton-kg/031-3,6-ton-berapa-kg",
      "3,6 ton berapa kg ?",
      "",
      "3,6 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_032",
      "/ton-kg/032-3,75-ton-berapa-kg",
      "3,75 ton berapa kg ?",
      "",
      "3,75 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_033",
      "/ton-kg/033-3,8-ton-berapa-kg",
      "3,8 ton berapa kg ?",
      "",
      "3,8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_034",
      "/ton-kg/034-4-ton-berapa-kg",
      "4 ton berapa kg ?",
      "",
      "4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_035",
      "/ton-kg/035-4,5-ton-berapa-kg",
      "4,5 ton berapa kg ?",
      "",
      "4,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_036",
      "/ton-kg/036-4,7-ton-berapa-kg",
      "4,7 ton berapa kg ?",
      "",
      "4,7 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_037",
      "/ton-kg/037-4,8-ton-berapa-kg",
      "4,8 ton berapa kg ?",
      "",
      "4,8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_038",
      "/ton-kg/038-5-ton-berapa-kg",
      "5 ton berapa kg ?",
      "",
      "5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_039",
      "/ton-kg/039-6-ton-berapa-kg",
      "6 ton berapa kg ?",
      "",
      "6 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_040",
      "/ton-kg/040-6,2-ton-berapa-kg",
      "6,2 ton berapa kg ?",
      "",
      "6,2 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_041",
      "/ton-kg/041-6,4-ton-berapa-kg",
      "6,4 ton berapa kg ?",
      "",
      "6,4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_042",
      "/ton-kg/042-6,5-ton-berapa-kg",
      "6,5 ton berapa kg ?",
      "",
      "6,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_043",
      "/ton-kg/043-6,75-ton-berapa-kg",
      "6,75 ton berapa kg ?",
      "",
      "6,75 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_044",
      "/ton-kg/044-7-ton-berapa-kg",
      "7 ton berapa kg ?",
      "",
      "7 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_045",
      "/ton-kg/045-7,5-ton-berapa-kg",
      "7,5 ton berapa kg ?",
      "",
      "7,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_046",
      "/ton-kg/046-8-ton-berapa-kg",
      "8 ton berapa kg ?",
      "",
      "8 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_047",
      "/ton-kg/047-9-ton-berapa-kg",
      "9 ton berapa kg ?",
      "",
      "9 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_048",
      "/ton-kg/048-9,75-ton-berapa-kg",
      "9,75 ton berapa kg ?",
      "",
      "9,75 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_049",
      "/ton-kg/049-10-ton-berapa-kg",
      "10 ton berapa kg ?",
      "",
      "10 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_050",
      "/ton-kg/050-12-ton-berapa-kg",
      "12 ton berapa kg ?",
      "",
      "12 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_051",
      "/ton-kg/051-12,5-ton-berapa-kg",
      "12,5 ton berapa kg ?",
      "",
      "12,5 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_052",
      "/ton-kg/052-15-ton-berapa-kg",
      "15 ton berapa kg ?",
      "",
      "15 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_053",
      "/ton-kg/053-20-ton-berapa-kg",
      "20 ton berapa kg ?",
      "",
      "20 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_054",
      "/ton-kg/054-21-ton-berapa-kg",
      "21 ton berapa kg ?",
      "",
      "21 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_055",
      "/ton-kg/055-22-ton-berapa-kg",
      "22 ton berapa kg ?",
      "",
      "22 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_056",
      "/ton-kg/056-25-ton-berapa-kg",
      "25 ton berapa kg ?",
      "",
      "25 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_057",
      "/ton-kg/057-30-ton-berapa-kg",
      "30 ton berapa kg ?",
      "",
      "30 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_058",
      "/ton-kg/058-32-ton-berapa-kg",
      "32 ton berapa kg ?",
      "",
      "32 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_059",
      "/ton-kg/059-37-ton-berapa-kg",
      "37 ton berapa kg ?",
      "",
      "37 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_060",
      "/ton-kg/060-38-ton-berapa-kg",
      "38 ton berapa kg ?",
      "",
      "38 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_061",
      "/ton-kg/061-40-ton-berapa-kg",
      "40 ton berapa kg ?",
      "",
      "40 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_062",
      "/ton-kg/062-42-ton-berapa-kg",
      "42 ton berapa kg ?",
      "",
      "42 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_063",
      "/ton-kg/063-44-ton-berapa-kg",
      "44 ton berapa kg ?",
      "",
      "44 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_064",
      "/ton-kg/064-50-ton-berapa-kg",
      "50 ton berapa kg ?",
      "",
      "50 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_065",
      "/ton-kg/065-65-ton-berapa-kg",
      "65 ton berapa kg ?",
      "",
      "65 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_066",
      "/ton-kg/066-66-ton-berapa-kg",
      "66 ton berapa kg ?",
      "",
      "66 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_067",
      "/ton-kg/067-68-ton-berapa-kg",
      "68 ton berapa kg ?",
      "",
      "68 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_068",
      "/ton-kg/068-70-ton-berapa-kg",
      "70 ton berapa kg ?",
      "",
      "70 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_069",
      "/ton-kg/069-76-ton-berapa-kg",
      "76 ton berapa kg ?",
      "",
      "76 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_070",
      "/ton-kg/070-78-ton-berapa-kg",
      "78 ton berapa kg ?",
      "",
      "78 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_071",
      "/ton-kg/071-82-ton-berapa-kg",
      "82 ton berapa kg ?",
      "",
      "82 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_072",
      "/ton-kg/072-84-ton-berapa-kg",
      "84 ton berapa kg ?",
      "",
      "84 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_073",
      "/ton-kg/073-85-ton-berapa-kg",
      "85 ton berapa kg ?",
      "",
      "85 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_074",
      "/ton-kg/074-86-ton-berapa-kg",
      "86 ton berapa kg ?",
      "",
      "86 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_075",
      "/ton-kg/075-88-ton-berapa-kg",
      "88 ton berapa kg ?",
      "",
      "88 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_076",
      "/ton-kg/076-90-ton-berapa-kg",
      "90 ton berapa kg ?",
      "",
      "90 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_077",
      "/ton-kg/077-150-ton-berapa-kg",
      "150 ton berapa kg ?",
      "",
      "150 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_078",
      "/ton-kg/078-200-ton-berapa-kg",
      "200 ton berapa kg ?",
      "",
      "200 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_079",
      "/ton-kg/079-250-ton-berapa-kg",
      "250 ton berapa kg ?",
      "",
      "250 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_080",
      "/ton-kg/080-350-ton-berapa-kg",
      "350 ton berapa kg ?",
      "",
      "350 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_081",
      "/ton-kg/081-400-ton-berapa-kg",
      "400 ton berapa kg ?",
      "",
      "400 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_082",
      "/ton-kg/082-430-ton-berapa-kg",
      "430 ton berapa kg ?",
      "",
      "430 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_083",
      "/ton-kg/083-500-ton-berapa-kg",
      "500 ton berapa kg ?",
      "",
      "500 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_084",
      "/ton-kg/084-600-ton-berapa-kg",
      "600 ton berapa kg ?",
      "",
      "600 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_085",
      "/ton-kg/085-650-ton-berapa-kg",
      "650 ton berapa kg ?",
      "",
      "650 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_086",
      "/ton-kg/086-700-ton-berapa-kg",
      "700 ton berapa kg ?",
      "",
      "700 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_087",
      "/ton-kg/087-750-ton-berapa-kg",
      "750 ton berapa kg ?",
      "",
      "750 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_088",
      "/ton-kg/088-850-ton-berapa-kg",
      "850 ton berapa kg ?",
      "",
      "850 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_089",
      "/ton-kg/089-900-ton-berapa-kg",
      "900 ton berapa kg ?",
      "",
      "900 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_090",
      "/ton-kg/090-1000-ton-berapa-kg",
      "1000 ton berapa kg ?",
      "",
      "1000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_091",
      "/ton-kg/091-2000-ton-berapa-kg",
      "2000 ton berapa kg ?",
      "",
      "2000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_092",
      "/ton-kg/092-3000-ton-berapa-kg",
      "3000 ton berapa kg ?",
      "",
      "3000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_093",
      "/ton-kg/093-4000-ton-berapa-kg",
      "4000 ton berapa kg ?",
      "",
      "4000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_094",
      "/ton-kg/094-7500-ton-berapa-kg",
      "7500 ton berapa kg ?",
      "",
      "7500 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_095",
      "/ton-kg/095-8500-ton-berapa-kg",
      "8500 ton berapa kg ?",
      "",
      "8500 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_096",
      "/ton-kg/096-9000-ton-berapa-kg",
      "9000 ton berapa kg ?",
      "",
      "9000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_097",
      "/ton-kg/097-10000-ton-berapa-kg",
      "10000 ton berapa kg ?",
      "",
      "10000 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_098",
      "/ton-kg/098-1per4-ton-berapa-kg",
      "1/4 ton berapa kg ?",
      "",
      "1/4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_099",
      "/ton-kg/099-3per4-ton-berapa-kg",
      "3/4 ton berapa kg ?",
      "",
      "3/4 ton berapa kg beserta penjelasannya",
      ["ton = ... kg"],
      "",
    ],
    [
      "berat_100",
      "/kg-ton/100-1-kg-berapa-ton",
      "1 kg berapa ton ?",
      "",
      "1 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_101",
      "/kg-ton/101-1,5-kg-berapa-ton",
      "1,5 kg berapa ton ?",
      "",
      "1,5 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_102",
      "/kg-ton/102-2-kg-berapa-ton",
      "2 kg berapa ton ?",
      "",
      "2 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_103",
      "/kg-ton/103-2,5-kg-berapa-ton",
      "2,5 kg berapa ton ?",
      "",
      "2,5 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_104",
      "/kg-ton/104-5-kg-berapa-ton",
      "5 kg berapa ton ?",
      "",
      "5 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_105",
      "/kg-ton/105-7-kg-berapa-ton",
      "7 kg berapa ton ?",
      "",
      "7 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_106",
      "/kg-ton/106-8-kg-berapa-ton",
      "8 kg berapa ton ?",
      "",
      "8 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_107",
      "/kg-ton/107-10-kg-berapa-ton",
      "10 kg berapa ton ?",
      "",
      "10 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_108",
      "/kg-ton/108-20-kg-berapa-ton",
      "20 kg berapa ton ?",
      "",
      "20 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_109",
      "/kg-ton/109-25-kg-berapa-ton",
      "25 kg berapa ton ?",
      "",
      "25 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_110",
      "/kg-ton/110-40-kg-berapa-ton",
      "40 kg berapa ton ?",
      "",
      "40 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_111",
      "/kg-ton/111-50-kg-berapa-ton",
      "50 kg berapa ton ?",
      "",
      "50 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_112",
      "/kg-ton/112-60-kg-berapa-ton",
      "60 kg berapa ton ?",
      "",
      "60 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_113",
      "/kg-ton/113-63-kg-berapa-ton",
      "63 kg berapa ton ?",
      "",
      "63 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_114",
      "/kg-ton/114-78-kg-berapa-ton",
      "78 kg berapa ton ?",
      "",
      "78 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_115",
      "/kg-ton/115-85-kg-berapa-ton",
      "85 kg berapa ton ?",
      "",
      "85 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_116",
      "/kg-ton/116-95-kg-berapa-ton",
      "95 kg berapa ton ?",
      "",
      "95 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_117",
      "/kg-ton/117-109-kg-berapa-ton",
      "109 kg berapa ton ?",
      "",
      "109 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_118",
      "/kg-ton/118-150-kg-berapa-ton",
      "150 kg berapa ton ?",
      "",
      "150 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_119",
      "/kg-ton/119-200-kg-berapa-ton",
      "200 kg berapa ton ?",
      "",
      "200 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_120",
      "/kg-ton/120-250-kg-berapa-ton",
      "250 kg berapa ton ?",
      "",
      "250 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_121",
      "/kg-ton/121-300-kg-berapa-ton",
      "300 kg berapa ton ?",
      "",
      "300 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_122",
      "/kg-ton/122-350-kg-berapa-ton",
      "350 kg berapa ton ?",
      "",
      "350 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_123",
      "/kg-ton/123-360-kg-berapa-ton",
      "360 kg berapa ton ?",
      "",
      "360 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_124",
      "/kg-ton/124-400-kg-berapa-ton",
      "400 kg berapa ton ?",
      "",
      "400 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_125",
      "/kg-ton/125-450-kg-berapa-ton",
      "450 kg berapa ton ?",
      "",
      "450 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_126",
      "/kg-ton/126-480-kg-berapa-ton",
      "480 kg berapa ton ?",
      "",
      "480 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_127",
      "/kg-ton/127-500-kg-berapa-ton",
      "500 kg berapa ton ?",
      "",
      "500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_128",
      "/kg-ton/128-600-kg-berapa-ton",
      "600 kg berapa ton ?",
      "",
      "600 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_129",
      "/kg-ton/129-625-kg-berapa-ton",
      "625 kg berapa ton ?",
      "",
      "625 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_130",
      "/kg-ton/130-640-kg-berapa-ton",
      "640 kg berapa ton ?",
      "",
      "640 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_131",
      "/kg-ton/131-675-kg-berapa-ton",
      "675 kg berapa ton ?",
      "",
      "675 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_132",
      "/kg-ton/132-680-kg-berapa-ton",
      "680 kg berapa ton ?",
      "",
      "680 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_133",
      "/kg-ton/133-700-kg-berapa-ton",
      "700 kg berapa ton ?",
      "",
      "700 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_134",
      "/kg-ton/134-730-kg-berapa-ton",
      "730 kg berapa ton ?",
      "",
      "730 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_135",
      "/kg-ton/135-750-kg-berapa-ton",
      "750 kg berapa ton ?",
      "",
      "750 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_136",
      "/kg-ton/136-800-kg-berapa-ton",
      "800 kg berapa ton ?",
      "",
      "800 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_137",
      "/kg-ton/137-820-kg-berapa-ton",
      "820 kg berapa ton ?",
      "",
      "820 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_138",
      "/kg-ton/138-850-kg-berapa-ton",
      "850 kg berapa ton ?",
      "",
      "850 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_139",
      "/kg-ton/139-900-kg-berapa-ton",
      "900 kg berapa ton ?",
      "",
      "900 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_140",
      "/kg-ton/140-923,56-kg-berapa-ton",
      "923,56 kg berapa ton ?",
      "",
      "923,56 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_141",
      "/kg-ton/141-950-kg-berapa-ton",
      "950 kg berapa ton ?",
      "",
      "950 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_142",
      "/kg-ton/142-960-kg-berapa-ton",
      "960 kg berapa ton ?",
      "",
      "960 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_143",
      "/kg-ton/143-1000-kg-berapa-ton",
      "1000 kg berapa ton ?",
      "",
      "1000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_144",
      "/kg-ton/144-1200-kg-berapa-ton",
      "1200 kg berapa ton ?",
      "",
      "1200 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_145",
      "/kg-ton/145-1500-kg-berapa-ton",
      "1500 kg berapa ton ?",
      "",
      "1500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_146",
      "/kg-ton/146-2000-kg-berapa-ton",
      "2000 kg berapa ton ?",
      "",
      "2000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_147",
      "/kg-ton/147-2500-kg-berapa-ton",
      "2500 kg berapa ton ?",
      "",
      "2500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_148",
      "/kg-ton/148-3000-kg-berapa-ton",
      "3000 kg berapa ton ?",
      "",
      "3000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_149",
      "/kg-ton/149-3500-kg-berapa-ton",
      "3500 kg berapa ton ?",
      "",
      "3500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_150",
      "/kg-ton/150-3600-kg-berapa-ton",
      "3600 kg berapa ton ?",
      "",
      "3600 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_151",
      "/kg-ton/151-4000-kg-berapa-ton",
      "4000 kg berapa ton ?",
      "",
      "4000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_152",
      "/kg-ton/152-4250-kg-berapa-ton",
      "4250 kg berapa ton ?",
      "",
      "4250 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_153",
      "/kg-ton/153-4300-kg-berapa-ton",
      "4300 kg berapa ton ?",
      "",
      "4300 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_154",
      "/kg-ton/154-4400-kg-berapa-ton",
      "4400 kg berapa ton ?",
      "",
      "4400 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_155",
      "/kg-ton/155-5000-kg-berapa-ton",
      "5000 kg berapa ton ?",
      "",
      "5000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_156",
      "/kg-ton/156-5250-kg-berapa-ton",
      "5250 kg berapa ton ?",
      "",
      "5250 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_157",
      "/kg-ton/157-5500-kg-berapa-ton",
      "5500 kg berapa ton ?",
      "",
      "5500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_158",
      "/kg-ton/158-5700-kg-berapa-ton",
      "5700 kg berapa ton ?",
      "",
      "5700 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_159",
      "/kg-ton/159-5800-kg-berapa-ton",
      "5800 kg berapa ton ?",
      "",
      "5800 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_160",
      "/kg-ton/160-6000-kg-berapa-ton",
      "6000 kg berapa ton ?",
      "",
      "6000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_161",
      "/kg-ton/161-7000-kg-berapa-ton",
      "7000 kg berapa ton ?",
      "",
      "7000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_162",
      "/kg-ton/162-7500-kg-berapa-ton",
      "7500 kg berapa ton ?",
      "",
      "7500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_163",
      "/kg-ton/163-8000-kg-berapa-ton",
      "8000 kg berapa ton ?",
      "",
      "8000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_164",
      "/kg-ton/164-8500-kg-berapa-ton",
      "8500 kg berapa ton ?",
      "",
      "8500 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_165",
      "/kg-ton/165-8700-kg-berapa-ton",
      "8700 kg berapa ton ?",
      "",
      "8700 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_166",
      "/kg-ton/166-9000-kg-berapa-ton",
      "9000 kg berapa ton ?",
      "",
      "9000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_167",
      "/kg-ton/167-9600-kg-berapa-ton",
      "9600 kg berapa ton ?",
      "",
      "9600 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_168",
      "/kg-ton/168-9800-kg-berapa-ton",
      "9800 kg berapa ton ?",
      "",
      "9800 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_169",
      "/kg-ton/169-10000-kg-berapa-ton",
      "10000 kg berapa ton ?",
      "",
      "10000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_170",
      "/kg-ton/170-24000-kg-berapa-ton",
      "24000 kg berapa ton ?",
      "",
      "24000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_171",
      "/kg-ton/171-30000-kg-berapa-ton",
      "30000 kg berapa ton ?",
      "",
      "30000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_172",
      "/kg-ton/172-38000-kg-berapa-ton",
      "38000 kg berapa ton ?",
      "",
      "38000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_173",
      "/kg-ton/173-45000-kg-berapa-ton",
      "45000 kg berapa ton ?",
      "",
      "45000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_174",
      "/kg-ton/174-70000-kg-berapa-ton",
      "70000 kg berapa ton ?",
      "",
      "70000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_175",
      "/kg-ton/175-75000-kg-berapa-ton",
      "75000 kg berapa ton ?",
      "",
      "75000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_176",
      "/kg-ton/176-80000-kg-berapa-ton",
      "80000 kg berapa ton ?",
      "",
      "80000 kg berapa ton beserta penjelasannya",
      ["kg = ... ton"],
      "",
    ],
    [
      "berat_177",
      "/kuintal-ton/177-1-kuintal-berapa-ton",
      "1 kuintal berapa ton ?",
      "",
      "1 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_178",
      "/kuintal-ton/178-2-kuintal-berapa-ton",
      "2 kuintal berapa ton ?",
      "",
      "2 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_179",
      "/kuintal-ton/179-2,5-kuintal-berapa-ton",
      "2,5 kuintal berapa ton ?",
      "",
      "2,5 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_180",
      "/kuintal-ton/180-3-kuintal-berapa-ton",
      "3 kuintal berapa ton ?",
      "",
      "3 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_181",
      "/kuintal-ton/181-3,2-kuintal-berapa-ton",
      "3,2 kuintal berapa ton ?",
      "",
      "3,2 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_182",
      "/kuintal-ton/182-3,5-kuintal-berapa-ton",
      "3,5 kuintal berapa ton ?",
      "",
      "3,5 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_183",
      "/kuintal-ton/183-4-kuintal-berapa-ton",
      "4 kuintal berapa ton ?",
      "",
      "4 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_184",
      "/kuintal-ton/184-5-kuintal-berapa-ton",
      "5 kuintal berapa ton ?",
      "",
      "5 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_185",
      "/kuintal-ton/185-5,25-kuintal-berapa-ton",
      "5,25 kuintal berapa ton ?",
      "",
      "5,25 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_186",
      "/kuintal-ton/186-6-kuintal-berapa-ton",
      "6 kuintal berapa ton ?",
      "",
      "6 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_187",
      "/kuintal-ton/187-7-kuintal-berapa-ton",
      "7 kuintal berapa ton ?",
      "",
      "7 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_188",
      "/kuintal-ton/188-8-kuintal-berapa-ton",
      "8 kuintal berapa ton ?",
      "",
      "8 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_189",
      "/kuintal-ton/189-9-kuintal-berapa-ton",
      "9 kuintal berapa ton ?",
      "",
      "9 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_190",
      "/kuintal-ton/190-10-kuintal-berapa-ton",
      "10 kuintal berapa ton ?",
      "",
      "10 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_191",
      "/kuintal-ton/191-12-kuintal-berapa-ton",
      "12 kuintal berapa ton ?",
      "",
      "12 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_192",
      "/kuintal-ton/192-15-kuintal-berapa-ton",
      "15 kuintal berapa ton ?",
      "",
      "15 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_193",
      "/kuintal-ton/193-17,5-kuintal-berapa-ton",
      "17,5 kuintal berapa ton ?",
      "",
      "17,5 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_194",
      "/kuintal-ton/194-18-kuintal-berapa-ton",
      "18 kuintal berapa ton ?",
      "",
      "18 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_195",
      "/kuintal-ton/195-20-kuintal-berapa-ton",
      "20 kuintal berapa ton ?",
      "",
      "20 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_196",
      "/kuintal-ton/196-25-kuintal-berapa-ton",
      "25 kuintal berapa ton ?",
      "",
      "25 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_197",
      "/kuintal-ton/197-30-kuintal-berapa-ton",
      "30 kuintal berapa ton ?",
      "",
      "30 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_198",
      "/kuintal-ton/198-36-kuintal-berapa-ton",
      "36 kuintal berapa ton ?",
      "",
      "36 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_199",
      "/kuintal-ton/199-40-kuintal-berapa-ton",
      "40 kuintal berapa ton ?",
      "",
      "40 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_200",
      "/kuintal-ton/200-45-kuintal-berapa-ton",
      "45 kuintal berapa ton ?",
      "",
      "45 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_201",
      "/kuintal-ton/201-48-kuintal-berapa-ton",
      "48 kuintal berapa ton ?",
      "",
      "48 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_202",
      "/kuintal-ton/202-49-kuintal-berapa-ton",
      "49 kuintal berapa ton ?",
      "",
      "49 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_203",
      "/kuintal-ton/203-50-kuintal-berapa-ton",
      "50 kuintal berapa ton ?",
      "",
      "50 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_204",
      "/kuintal-ton/204-60-kuintal-berapa-ton",
      "60 kuintal berapa ton ?",
      "",
      "60 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_205",
      "/kuintal-ton/205-70-kuintal-berapa-ton",
      "70 kuintal berapa ton ?",
      "",
      "70 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_206",
      "/kuintal-ton/206-75-kuintal-berapa-ton",
      "75 kuintal berapa ton ?",
      "",
      "75 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_207",
      "/kuintal-ton/207-80-kuintal-berapa-ton",
      "80 kuintal berapa ton ?",
      "",
      "80 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_208",
      "/kuintal-ton/208-100-kuintal-berapa-ton",
      "100 kuintal berapa ton ?",
      "",
      "100 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_209",
      "/kuintal-ton/209-120-kuintal-berapa-ton",
      "120 kuintal berapa ton ?",
      "",
      "120 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_210",
      "/kuintal-ton/210-200-kuintal-berapa-ton",
      "200 kuintal berapa ton ?",
      "",
      "200 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_211",
      "/kuintal-ton/211-247-kuintal-berapa-ton",
      "247 kuintal berapa ton ?",
      "",
      "247 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_212",
      "/kuintal-ton/212-250-kuintal-berapa-ton",
      "250 kuintal berapa ton ?",
      "",
      "250 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_213",
      "/kuintal-ton/213-300-kuintal-berapa-ton",
      "300 kuintal berapa ton ?",
      "",
      "300 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_214",
      "/kuintal-ton/214-350-kuintal-berapa-ton",
      "350 kuintal berapa ton ?",
      "",
      "350 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_215",
      "/kuintal-ton/215-450-kuintal-berapa-ton",
      "450 kuintal berapa ton ?",
      "",
      "450 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_216",
      "/kuintal-ton/216-500-kuintal-berapa-ton",
      "500 kuintal berapa ton ?",
      "",
      "500 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_217",
      "/kuintal-ton/217-600-kuintal-berapa-ton",
      "600 kuintal berapa ton ?",
      "",
      "600 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_218",
      "/kuintal-ton/218-700-kuintal-berapa-ton",
      "700 kuintal berapa ton ?",
      "",
      "700 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_219",
      "/kuintal-ton/219-800-kuintal-berapa-ton",
      "800 kuintal berapa ton ?",
      "",
      "800 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_220",
      "/kuintal-ton/220-1000-kuintal-berapa-ton",
      "1000 kuintal berapa ton ?",
      "",
      "1000 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_221",
      "/kuintal-ton/221-2000-kuintal-berapa-ton",
      "2000 kuintal berapa ton ?",
      "",
      "2000 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_222",
      "/kuintal-ton/222-5000-kuintal-berapa-ton",
      "5000 kuintal berapa ton ?",
      "",
      "5000 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_223",
      "/kuintal-ton/223-6000-kuintal-berapa-ton",
      "6000 kuintal berapa ton ?",
      "",
      "6000 kuintal berapa ton beserta penjelasannya",
      ["kuintal = ... ton"],
      "",
    ],
    [
      "berat_224",
      "/ton-kuintal/224-0,08-ton-berapa-kuintal",
      "0,08 ton berapa kuintal ?",
      "",
      "0,08 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_225",
      "/ton-kuintal/225-0,2-ton-berapa-kuintal",
      "0,2 ton berapa kuintal ?",
      "",
      "0,2 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_226",
      "/ton-kuintal/226-0,5-ton-berapa-kuintal",
      "0,5 ton berapa kuintal ?",
      "",
      "0,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_227",
      "/ton-kuintal/227-0,75-ton-berapa-kuintal",
      "0,75 ton berapa kuintal ?",
      "",
      "0,75 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_228",
      "/ton-kuintal/228-0,8-ton-berapa-kuintal",
      "0,8 ton berapa kuintal ?",
      "",
      "0,8 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_229",
      "/ton-kuintal/229-1-ton-berapa-kuintal",
      "1 ton berapa kuintal ?",
      "",
      "1 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_230",
      "/ton-kuintal/230-1,2-ton-berapa-kuintal",
      "1,2 ton berapa kuintal ?",
      "",
      "1,2 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_231",
      "/ton-kuintal/231-1,5-ton-berapa-kuintal",
      "1,5 ton berapa kuintal ?",
      "",
      "1,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_232",
      "/ton-kuintal/232-2-ton-berapa-kuintal",
      "2 ton berapa kuintal ?",
      "",
      "2 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_233",
      "/ton-kuintal/233-2,4-ton-berapa-kuintal",
      "2,4 ton berapa kuintal ?",
      "",
      "2,4 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_234",
      "/ton-kuintal/234-2,5-ton-berapa-kuintal",
      "2,5 ton berapa kuintal ?",
      "",
      "2,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_235",
      "/ton-kuintal/235-3-ton-berapa-kuintal",
      "3 ton berapa kuintal ?",
      "",
      "3 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_236",
      "/ton-kuintal/236-3,2-ton-berapa-kuintal",
      "3,2 ton berapa kuintal ?",
      "",
      "3,2 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_237",
      "/ton-kuintal/237-3,5-ton-berapa-kuintal",
      "3,5 ton berapa kuintal ?",
      "",
      "3,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_238",
      "/ton-kuintal/238-3,6-ton-berapa-kuintal",
      "3,6 ton berapa kuintal ?",
      "",
      "3,6 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_239",
      "/ton-kuintal/239-3,75-ton-berapa-kuintal",
      "3,75 ton berapa kuintal ?",
      "",
      "3,75 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_240",
      "/ton-kuintal/240-4-ton-berapa-kuintal",
      "4 ton berapa kuintal ?",
      "",
      "4 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_241",
      "/ton-kuintal/241-4,5-ton-berapa-kuintal",
      "4,5 ton berapa kuintal ?",
      "",
      "4,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_242",
      "/ton-kuintal/242-4,75-ton-berapa-kuintal",
      "4,75 ton berapa kuintal ?",
      "",
      "4,75 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_243",
      "/ton-kuintal/243-5-ton-berapa-kuintal",
      "5 ton berapa kuintal ?",
      "",
      "5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_244",
      "/ton-kuintal/244-6-ton-berapa-kuintal",
      "6 ton berapa kuintal ?",
      "",
      "6 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_245",
      "/ton-kuintal/245-6,15-ton-berapa-kuintal",
      "6,15 ton berapa kuintal ?",
      "",
      "6,15 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_246",
      "/ton-kuintal/246-6,35-ton-berapa-kuintal",
      "6,35 ton berapa kuintal ?",
      "",
      "6,35 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_247",
      "/ton-kuintal/247-6,5-ton-berapa-kuintal",
      "6,5 ton berapa kuintal ?",
      "",
      "6,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_248",
      "/ton-kuintal/248-7-ton-berapa-kuintal",
      "7 ton berapa kuintal ?",
      "",
      "7 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_249",
      "/ton-kuintal/249-7,5-ton-berapa-kuintal",
      "7,5 ton berapa kuintal ?",
      "",
      "7,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_250",
      "/ton-kuintal/250-8-ton-berapa-kuintal",
      "8 ton berapa kuintal ?",
      "",
      "8 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_251",
      "/ton-kuintal/251-9-ton-berapa-kuintal",
      "9 ton berapa kuintal ?",
      "",
      "9 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_252",
      "/ton-kuintal/252-10-ton-berapa-kuintal",
      "10 ton berapa kuintal ?",
      "",
      "10 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_253",
      "/ton-kuintal/253-12-ton-berapa-kuintal",
      "12 ton berapa kuintal ?",
      "",
      "12 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_254",
      "/ton-kuintal/254-12,5-ton-berapa-kuintal",
      "12,5 ton berapa kuintal ?",
      "",
      "12,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_255",
      "/ton-kuintal/255-15-ton-berapa-kuintal",
      "15 ton berapa kuintal ?",
      "",
      "15 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_256",
      "/ton-kuintal/256-20-ton-berapa-kuintal",
      "20 ton berapa kuintal ?",
      "",
      "20 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_257",
      "/ton-kuintal/257-21,5-ton-berapa-kuintal",
      "21,5 ton berapa kuintal ?",
      "",
      "21,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_258",
      "/ton-kuintal/258-30-ton-berapa-kuintal",
      "30 ton berapa kuintal ?",
      "",
      "30 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_259",
      "/ton-kuintal/259-32-ton-berapa-kuintal",
      "32 ton berapa kuintal ?",
      "",
      "32 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_260",
      "/ton-kuintal/260-40-ton-berapa-kuintal",
      "40 ton berapa kuintal ?",
      "",
      "40 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_261",
      "/ton-kuintal/261-45-ton-berapa-kuintal",
      "45 ton berapa kuintal ?",
      "",
      "45 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_262",
      "/ton-kuintal/262-50-ton-berapa-kuintal",
      "50 ton berapa kuintal ?",
      "",
      "50 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_263",
      "/ton-kuintal/263-60-ton-berapa-kuintal",
      "60 ton berapa kuintal ?",
      "",
      "60 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_264",
      "/ton-kuintal/264-80-ton-berapa-kuintal",
      "80 ton berapa kuintal ?",
      "",
      "80 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_265",
      "/ton-kuintal/265-87,5-ton-berapa-kuintal",
      "87,5 ton berapa kuintal ?",
      "",
      "87,5 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_266",
      "/ton-kuintal/266-100-ton-berapa-kuintal",
      "100 ton berapa kuintal ?",
      "",
      "100 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_267",
      "/ton-kuintal/267-250-ton-berapa-kuintal",
      "250 ton berapa kuintal ?",
      "",
      "250 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_268",
      "/ton-kuintal/268-600-ton-berapa-kuintal",
      "600 ton berapa kuintal ?",
      "",
      "600 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_269",
      "/ton-kuintal/269-700-ton-berapa-kuintal",
      "700 ton berapa kuintal ?",
      "",
      "700 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_270",
      "/ton-kuintal/270-800-ton-berapa-kuintal",
      "800 ton berapa kuintal ?",
      "",
      "800 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_271",
      "/ton-kuintal/271-6000-ton-berapa-kuintal",
      "6000 ton berapa kuintal ?",
      "",
      "6000 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
    [
      "berat_272",
      "/ton-kuintal/272-4-2per3-ton-berapa-kuintal",
      "4 2/3 ton berapa kuintal ?",
      "",
      "4 2/3 ton berapa kuintal beserta penjelasannya",
      ["ton = ... kuintal"],
      "",
    ],
];