// var id_post = PostList[i][0];
// var url_post = url_root + PostList[i][1];
// var name_post = PostList[i][2];
// var date_post = PostList[i][3];
// var description_post = PostList[i][4];
// var post_category = PostList[i][5];
// var post_preview_src = PostList[i][6];

var footerArray = [
  //June2020
  [
    "June20-ProK_01",
    "/kalkulator-persen",
    "Kalkulator Persen",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_02",
    "/menghitung-persentase",
    "Menghitung Persentase",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_03",
    "/kalkulator-diskon",
    "Kalkulator Diskon",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_04",
    "/diskon-berapa-persen",
    "Diskon Berapa Persen?",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_05",
    "/menghitung-akar-pangkat",
    "Kalkulator Akar Pangkat",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_06",
    "/menghitung-berat-badan-ideal",
    "Kalkulator Berat Badan Ideal",
    "",
    "",
    [""],
    "",
  ],
  ["June20-ProK_07", "/kalkulator-sinus", "Kalkulator Sinus", "", "", [""], ""],
  [
    "June20-ProK_08",
    "/kalkulator-cosinus",
    "Kalkulator Cosinus",
    "",
    "",
    [""],
    "",
  ],
  [
    "June20-ProK_09",
    "/kalkulator-tangen",
    "Kalkulator Tangen",
    "",
    "",
    [""],
    "",
  ],
  //July 2020
  ["July20-ProK_01", "/kalkulator-jam", "Kalkulator Jam", "", "", [""], ""],
  [
    "July20-ProK_02",
    "/kalkulator-pecahan",
    "Kalkulator Pecahan",
    "",
    "",
    [""],
    "",
  ],
  //August 2020
  [
    "Aug20-ProK_01",
    "/suhu/konversi-kelvin-ke-celcius",
    "Konversi Kelvin ke Celcius",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_02",
    "/suhu/konversi-celcius-ke-kelvin",
    "Konversi Celcius ke Kelvin",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_03",
    "/suhu/konversi-celcius-ke-fahrenheit",
    "Konversi Celcius ke Fahrenheit",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_04",
    "/suhu/konversi-celcius-ke-reamur",
    "Konversi Celcius ke Reamur",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_05",
    "/suhu/konversi-kelvin-ke-reamur",
    "Konversi Kelvin ke Reamur",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_06",
    "/suhu/konversi-kelvin-ke-fahrenheit",
    "Konversi Kelvin ke Fahrenheit",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_07",
    "/suhu/konversi-reamur-ke-celcius",
    "Konversi Reamur ke Celcius",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_08",
    "/suhu/konversi-reamur-ke-fahrenheit",
    "Konversi Reamur ke Fahrenheit",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_09",
    "/suhu/konversi-reamur-ke-kelvin",
    "Konversi Reamur ke Kelvin",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_10",
    "/suhu/konversi-fahrenheit-ke-celcius",
    "Konversi Fahrenheit ke Celcius",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_11",
    "/suhu/konversi-fahrenheit-ke-reamur",
    "Konversi Fahrenheit ke Reamur",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_12",
    "/suhu/konversi-fahrenheit-ke-kelvin",
    "Konversi Fahrenheit ke Kelvin",
    "",
    "",
    ["Suhu"],
    "",
  ],
  [
    "Aug20-ProK_13",
    "/bilangan/konversi-desimal-ke-biner",
    "Konversi Desimal ke Biner",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_14",
    "/bilangan/konversi-desimal-ke-oktal",
    "Konversi Desimal ke Oktal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_15",
    "/bilangan/konversi-desimal-ke-heksadesimal",
    "Konversi Desimal ke Heksadesimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_16",
    "/bilangan/konversi-biner-ke-desimal",
    "Konversi Biner ke Desimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_17",
    "/bilangan/konversi-biner-ke-oktal",
    "Konversi Biner ke Oktal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_18",
    "/bilangan/konversi-biner-ke-heksadesimal",
    "Konversi Biner ke Heksadesimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_19",
    "/bilangan/konversi-heksadesimal-ke-desimal",
    "Konversi Heksadesimal ke Desimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_20",
    "/bilangan/konversi-heksadesimal-ke-biner",
    "Konversi Heksadesimal ke Biner",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_21",
    "/bilangan/konversi-heksadesimal-ke-oktal",
    "Konversi Heksadesimal ke Oktal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_22",
    "/bilangan/konversi-oktal-ke-biner",
    "Konversi Oktal ke Biner",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_23",
    "/bilangan/konversi-oktal-ke-desimal",
    "Konversi Oktal ke Desimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_24",
    "/bilangan/konversi-oktal-ke-heksadesimal",
    "Konversi Oktal ke Heksadesimal",
    "",
    "",
    ["Bilangan"],
    "",
  ],
  [
    "Aug20-ProK_25",
    "/kecepatan/konversi-kmperjam-ke-meterperdetik",
    "Konversi Km/jam ke m/s",
    "",
    "",
    ["Kecepatan"],
    "",
  ],
  [
    "Aug20-ProK_26",
    "/kecepatan/konversi-meterperdetik-ke-kmperjam",
    "Konversi m/s ke Km/jam",
    "",
    "",
    ["Kecepatan"],
    "",
  ],
  [
    "Aug20-ProK_27",
    "/waktu/konversi-detik-ke-hari",
    "Konversi Detik ke Hari",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_28",
    "/waktu/konversi-detik-ke-jam",
    "Konversi Detik ke Jam",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_29",
    "/waktu/konversi-detik-ke-menit",
    "Konversi Detik ke Menit",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_30",
    "/waktu/konversi-detik-ke-minggu",
    "Konversi Detik ke Minggu",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_31",
    "/waktu/konversi-hari-ke-detik",
    "Konversi Hari ke Detik",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_32",
    "/waktu/konversi-hari-ke-jam",
    "Konversi Hari ke Jam",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_33",
    "/waktu/konversi-hari-ke-menit",
    "Konversi Hari ke Menit",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_34",
    "/waktu/konversi-hari-ke-minggu",
    "Konversi Hari ke Minggu",
    "",
    "",
    ["Waktu"],
    "",
  ],

  [
    "Aug20-ProK_35",
    "/waktu/konversi-jam-ke-detik",
    "Konversi Jam ke Detik",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_36",
    "/waktu/konversi-jam-ke-hari",
    "Konversi Jam ke Hari",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_37",
    "/waktu/konversi-jam-ke-menit",
    "Konversi Jam ke Menit",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_38",
    "/waktu/konversi-jam-ke-minggu",
    "Konversi Jam ke Minggu",
    "",
    "",
    ["Waktu"],
    "",
  ],

  [
    "Aug20-ProK_39",
    "/waktu/konversi-menit-ke-detik",
    "Konversi Menit ke Detik",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_40",
    "/waktu/konversi-menit-ke-hari",
    "Konversi Menit ke Hari",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_41",
    "/waktu/konversi-menit-ke-jam",
    "Konversi Menit ke Jam",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_42",
    "/waktu/konversi-menit-ke-minggu",
    "Konversi Menit ke Minggu",
    "",
    "",
    ["Waktu"],
    "",
  ],

  [
    "Aug20-ProK_43",
    "/waktu/konversi-minggu-ke-detik",
    "Konversi Minggu ke Detik",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_44",
    "/waktu/konversi-minggu-ke-hari",
    "Konversi Minggu ke Hari",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_45",
    "/waktu/konversi-minggu-ke-jam",
    "Konversi Minggu ke Jam",
    "",
    "",
    ["Waktu"],
    "",
  ],
  [
    "Aug20-ProK_46",
    "/waktu/konversi-minggu-ke-menit",
    "Konversi Minggu ke Menit",
    "",
    "",
    ["Waktu"],
    "",
  ],
];
